@interface _AXSpringBoardServerInstance : NSObject
{
	id _server;
	id _client;
	id _delegate;
	id _gestureBlockIntents;
	id _actionHandlers;
}

+ _initServer
+ _initializeHandlers
+ _performValidation
+ _startHearingAidServer:
+ springBoardActionOccurred:withPayload:
+ _removeActionHandler:
+ _getApplicationOrientation:
+ _getPid:
+ _showAlert:
+ _hideAlert:
+ _isMakingEmergencyCall:
+ _topEventPidOverride:
+ _gestureOverrideIntent:
+ _takeScreenshot:
+ _openAppSwitcher:
+ _openSiri:
+ _toggleNotificationCenter:
+ _isNotificationCenterVisible:
+ _openVoiceControl:
+ _getActiveInterfaceOrientation:
+ _actionHandling:
+ _isVoiceControlRunning:
+ _isSiriListening:
+ _isSystemSleeping:
+ _volumeLevel:
+ _isOrientationLocked:
+ _isSideSwitchUsedForOrientation:
+ _isRingerMuted:
+ _openCustomGestureCreationForAST:
+ _openCustomGestureCreationForSCAT:
+ _cancelGestureActivation:
+ _toggleHearingControl:
+ _isPointInAXInspector:
+ _isMediaPlaying:
+ _resetDimTimer:
+ _setSystemGesturedEnabled:
+ _showControlCenter:
+ _isControlCenterVisible:
+ _copyStringToPasteboard:
+ _isSiriVisible:
+ _isGuidedAccessActive:
+ _isAppSwitcherVisible:
+ _isSpringboardFrontmost:
+ _isSyncingRestoringResettingOrUpdating:
+ springBoardActionOccurred:
+ shouldBlockGestureActivation:
+ shouldCancelSiriTouchActivationBlock
+ dealloc
+ setDelegate:
+ init
+ delegate
+ isMakingEmergencyCall
+ isSystemSleeping
+ isGuidedAccessActive
+ _screenLocked:
+ _setVolume:
- _initServer
- _initializeHandlers
- _performValidation
- _startHearingAidServer:
- springBoardActionOccurred:withPayload:
- _removeActionHandler:
- _getApplicationOrientation:
- _getPid:
- _showAlert:
- _hideAlert:
- _isMakingEmergencyCall:
- _topEventPidOverride:
- _gestureOverrideIntent:
- _takeScreenshot:
- _openAppSwitcher:
- _openSiri:
- _toggleNotificationCenter:
- _isNotificationCenterVisible:
- _openVoiceControl:
- _getActiveInterfaceOrientation:
- _actionHandling:
- _isVoiceControlRunning:
- _isSiriListening:
- _isSystemSleeping:
- _volumeLevel:
- _isOrientationLocked:
- _isSideSwitchUsedForOrientation:
- _isRingerMuted:
- _openCustomGestureCreationForAST:
- _openCustomGestureCreationForSCAT:
- _cancelGestureActivation:
- _toggleHearingControl:
- _isPointInAXInspector:
- _isMediaPlaying:
- _resetDimTimer:
- _setSystemGesturedEnabled:
- _showControlCenter:
- _isControlCenterVisible:
- _copyStringToPasteboard:
- _isSiriVisible:
- _isGuidedAccessActive:
- _isAppSwitcherVisible:
- _isSpringboardFrontmost:
- _isSyncingRestoringResettingOrUpdating:
- springBoardActionOccurred:
- shouldBlockGestureActivation:
- shouldCancelSiriTouchActivationBlock
- dealloc
- setDelegate:
- init
- delegate
- isMakingEmergencyCall
- isSystemSleeping
- isGuidedAccessActive
- _screenLocked:
- _setVolume:
@end
