@interface _UICascadingTextStorage : NSConcreteTextStorage
{
	id _defaultAttributes;
}

+ setLineBreakMode:
+ setShadowColor:
+ setShadowOffset:
+ setFont:
+ font
+ shadowOffset
+ shadowColor
+ setTextColor:
+ setTextAlignment:
+ textColor
+ textAlignment
+ _ui_resolvedTextAlignment
+ _shadow
+ lineBreakMode
+ _setShadow:
+ setShadowBlur:
+ shadowBlur
+ dealloc
+ setDefaultAttributes:
+ defaultAttributes
+ attribute:atIndex:effectiveRange:
+ _defaultAttributes
+ attribute:atIndex:longestEffectiveRange:inRange:
+ attributesAtIndex:effectiveRange:
+ attributesAtIndex:longestEffectiveRange:inRange:
+ _shouldSetOriginalFontAttribute
+ _restoreOriginalFontAttribute
- setLineBreakMode:
- setShadowColor:
- setShadowOffset:
- setFont:
- font
- shadowOffset
- shadowColor
- setTextColor:
- setTextAlignment:
- textColor
- textAlignment
- _ui_resolvedTextAlignment
- _shadow
- lineBreakMode
- _setShadow:
- setShadowBlur:
- shadowBlur
- dealloc
- setDefaultAttributes:
- defaultAttributes
- attribute:atIndex:effectiveRange:
- _defaultAttributes
- attribute:atIndex:longestEffectiveRange:inRange:
- attributesAtIndex:effectiveRange:
- attributesAtIndex:longestEffectiveRange:inRange:
- _shouldSetOriginalFontAttribute
- _restoreOriginalFontAttribute
@end
