@interface _UIPopoverViewArtworkLoader : NSObject
{
	long long _backgroundStyle;
	id _backgroundSelector;
}

+ dealloc
+ arrowHeight
+ initWithBackgroundStyle:
+ topArrowLeftEndCapView
+ topArrowPinnedView
+ topArrowView
+ topArrowRightEndCapView
+ bottomArrowLeftEndCapView
+ bottomArrowPinnedView
+ bottomArrowView
+ bottomArrowRightEndCapView
+ shortRightArrowView
+ rightArrowPinnedTopView
+ rightArrowBottomEndCapView
+ rightArrowPinnedBottomView
+ rightArrowTopEndCapView
+ rightArrowView
+ arrowBase
+ templateImageForDirection:shortArtwork:
+ modern
+ topArrowStart
+ contentRectForRect:inImageOfSize:
+ arrowTopGradientEnd
+ capCornerRadius
+ contentsCenterForRect:inImageOfSize:
+ viewWithContentsImage:rect:center:antialiasingMask:directionSelector:
+ clampArrowBase
+ sideArrowStart
+ noArrowTopGradientEnd
+ bottomEndCapHeight
+ shortArtArrowTopGradientEnd
+ shortTopArrowLeftEndCapView
+ shortArtRightArrowBase
+ shortArtNoArrowTopGradientEnd
+ shortBottomArrowLeftEndCapView
+ shortTopArrowView
+ shortTopArrowPinnedView
+ shortTopArrowRightEndCapView
+ shortBottomArrowView
+ shortBottomArrowPinnedView
+ shortBottomArrowRightEndCapView
- dealloc
- arrowHeight
- initWithBackgroundStyle:
- topArrowLeftEndCapView
- topArrowPinnedView
- topArrowView
- topArrowRightEndCapView
- bottomArrowLeftEndCapView
- bottomArrowPinnedView
- bottomArrowView
- bottomArrowRightEndCapView
- shortRightArrowView
- rightArrowPinnedTopView
- rightArrowBottomEndCapView
- rightArrowPinnedBottomView
- rightArrowTopEndCapView
- rightArrowView
- arrowBase
- templateImageForDirection:shortArtwork:
- modern
- topArrowStart
- contentRectForRect:inImageOfSize:
- arrowTopGradientEnd
- capCornerRadius
- contentsCenterForRect:inImageOfSize:
- viewWithContentsImage:rect:center:antialiasingMask:directionSelector:
- clampArrowBase
- sideArrowStart
- noArrowTopGradientEnd
- bottomEndCapHeight
- shortArtArrowTopGradientEnd
- shortTopArrowLeftEndCapView
- shortArtRightArrowBase
- shortArtNoArrowTopGradientEnd
- shortBottomArrowLeftEndCapView
- shortTopArrowView
- shortTopArrowPinnedView
- shortTopArrowRightEndCapView
- shortBottomArrowView
- shortBottomArrowPinnedView
- shortBottomArrowRightEndCapView
@end
