@interface _UIScreenEdgePanRecognizerDwellSettings : _UISettings
{
	double _longPressFlatPermittedHorizontalMovement;
	double _longPressFlatPermittedVerticalMovement;
	double _longPressTipPermittedHorizontalMovement;
	double _longPressTipPermittedVerticalMovement;
	double _longPressPermittedHorizontalMovement;
	double _longPressPermittedVerticalMovement;
	double _longPressRequiredDuration;
}

+ setDefaultValues
+ setLongPressPermittedHorizontalMovement:
+ setLongPressPermittedVerticalMovement:
+ setLongPressFlatPermittedHorizontalMovement:
+ setLongPressFlatPermittedVerticalMovement:
+ setLongPressTipPermittedHorizontalMovement:
+ setLongPressTipPermittedVerticalMovement:
+ setLongPressRequiredDuration:
+ longPressFlatPermittedHorizontalMovement
+ longPressFlatPermittedVerticalMovement
+ longPressTipPermittedHorizontalMovement
+ longPressTipPermittedVerticalMovement
+ longPressPermittedHorizontalMovement
+ longPressPermittedVerticalMovement
+ longPressRequiredDuration
- setDefaultValues
- setLongPressPermittedHorizontalMovement:
- setLongPressPermittedVerticalMovement:
- setLongPressFlatPermittedHorizontalMovement:
- setLongPressFlatPermittedVerticalMovement:
- setLongPressTipPermittedHorizontalMovement:
- setLongPressTipPermittedVerticalMovement:
- setLongPressRequiredDuration:
- longPressFlatPermittedHorizontalMovement
- longPressFlatPermittedVerticalMovement
- longPressTipPermittedHorizontalMovement
- longPressTipPermittedVerticalMovement
- longPressPermittedHorizontalMovement
- longPressPermittedVerticalMovement
- longPressRequiredDuration
@end
