@interface AAAccount : NSObject
{
	id _account;
	id _fmipToken;
	id _appleIDAliases;
	id _protocolVersion;
}

+ password
+ setPassword:
+ authToken
+ setAuthToken:
+ protocolVersion
+ initWithAccountIdentifier:
+ init
+ identifier
+ displayName
+ authenticateWithHandler:
+ fmipToken
+ appleIDAliases
+ primaryEmail
+ primaryEmailVerified
+ _mailChildAccount
+ _childAccounts
+ presentQuotaDepletionAlertForDataclass:withHandler:
+ presentQuotaDepletionAlertForDataclassIfNecessary:withHandler:
+ accountServiceType
+ accountFooterText
+ accountFooterButton
+ accountFirstDisplayAlert
+ updateAccountWithProvisioningResponse:
+ serviceUnavailable
+ serviceUnavailableInfo
+ needsRegistration
+ useCellularForDataclass:
+ setUseCellular:forDataclass:
+ needsEmailConfiguration
+ mobileMeAccountStatus
+ liverpoolAccount
+ notifyUserOfQuotaDepletion
+ presentQuotaDepletionAlertForDataclass:
+ presentQuotaDepletionAlertForDataclassIfNecessary:
+ saveTokensInKeychain
+ savePasswordInKeychain
+ saveFMIPTokenInKeychain
+ removeTokensFromKeychain
+ removePasswordFromKeychain
+ flushCachedTokens
+ flushCachedPassword
+ updateAccountPropertiesWithHandler:
+ setupChildMailAccountAndEnable:withEmail:
+ signInWithHandler:
+ renewCredentialsForAppleIDWithHandler:
+ lookupEmailAddresses:withHandler:
+ needsToVerifyTerms
+ setNeedsToVerifyTerms:
+ setFmipToken:
+ dataclassProperties
+ provisionedDataclasses
+ propertiesForDataclass:
+ account
+ setEnabled:forDataclass:
+ accountPropertyForKey:
+ setAccountProperty:forKey:
+ accountDescription
+ setUsername:
+ setAccountDescription:
+ enabledDataclasses
+ supportedDataclasses
+ syncStoreIdentifier
+ initWithAccount:
+ personID
+ isEnabledForDataclass:
+ isProvisionedForDataclass:
+ username
+ firstName
+ lastName
+ .cxx_destruct
+ primaryAccount
+ setPrimaryAccount:
- password
- setPassword:
- authToken
- setAuthToken:
- protocolVersion
- initWithAccountIdentifier:
- init
- identifier
- displayName
- authenticateWithHandler:
- fmipToken
- appleIDAliases
- primaryEmail
- primaryEmailVerified
- _mailChildAccount
- _childAccounts
- presentQuotaDepletionAlertForDataclass:withHandler:
- presentQuotaDepletionAlertForDataclassIfNecessary:withHandler:
- accountServiceType
- accountFooterText
- accountFooterButton
- accountFirstDisplayAlert
- updateAccountWithProvisioningResponse:
- serviceUnavailable
- serviceUnavailableInfo
- needsRegistration
- useCellularForDataclass:
- setUseCellular:forDataclass:
- needsEmailConfiguration
- mobileMeAccountStatus
- liverpoolAccount
- notifyUserOfQuotaDepletion
- presentQuotaDepletionAlertForDataclass:
- presentQuotaDepletionAlertForDataclassIfNecessary:
- saveTokensInKeychain
- savePasswordInKeychain
- saveFMIPTokenInKeychain
- removeTokensFromKeychain
- removePasswordFromKeychain
- flushCachedTokens
- flushCachedPassword
- updateAccountPropertiesWithHandler:
- setupChildMailAccountAndEnable:withEmail:
- signInWithHandler:
- renewCredentialsForAppleIDWithHandler:
- lookupEmailAddresses:withHandler:
- needsToVerifyTerms
- setNeedsToVerifyTerms:
- setFmipToken:
- dataclassProperties
- provisionedDataclasses
- propertiesForDataclass:
- account
- setEnabled:forDataclass:
- accountPropertyForKey:
- setAccountProperty:forKey:
- accountDescription
- setUsername:
- setAccountDescription:
- enabledDataclasses
- supportedDataclasses
- syncStoreIdentifier
- initWithAccount:
- personID
- isEnabledForDataclass:
- isProvisionedForDataclass:
- username
- firstName
- lastName
- .cxx_destruct
- primaryAccount
- setPrimaryAccount:
@end
