@interface ABStyleProvider : NSObject
{

}

+ newCardActionButton
+ groupsTableBackgroundColor
+ cardCellDividerColorVertical:
+ groupCellBackgroundColor
+ groupCellTextColor
+ groupHeaderBackgroudColor
+ groupAccountNameColor
+ labelPickerUsesOpaqueBackground
+ personValueFont
+ personLabelColor
+ abCellStyleForCardTableWhenEditing:
+ memberNameSelectedColor
+ cardCellBackgroundColor
+ shadowColorForCellStyle:
+ newBackgroundViewForCellStyle:selected:
+ cardClippingImageLabelColor
+ cardClippingImageLabelBevelColor
+ cardPhotoFrameBorderSize
+ cardValueTextColor
+ memberPhotoMaskImage
+ memberPlaceholderPersonImage
+ memberPhotoOverlayImage
+ memberPlaceholderCompanyImage
+ abCellStyleForMembersTable
+ separatorStyleForCellStyle:
+ separatorColorForCellStyle:
+ shouldUsePeoplePickerBarStyle
+ peoplePickerBarStyle
+ peoplePickerBarStyleIsTranslucent
+ searchIsAlwaysActive
+ membersIndexTextColor
+ membersIndexTrackingBackgroundColor
+ memberSectionListHeaderImage
+ setIndicatesFaceTimeHistory:onActionButton:
+ unknownModalPresentationStyle
+ shouldUseCardContentProviderWhenAvailable
+ customCardCellClass
+ customCardActionCellClass
+ newCustomCardTableScrollingBackgroundView
+ cardTableViewSectionHeaderHeightWhenEditing:
+ cardTableViewSectionFooterHeightWhenEditing:
+ shouldPropagateStylesToPickers
+ shouldPropagateStylesThroughUnknownPersonActions
+ customSetEmphasized:onCell:
+ membersHeaderBackgroundColor
+ memberNameTextColor
+ cardCellSelectionStyle
+ memberNameShadowColor
+ cardLabelTextColor
+ personValueEmphasizedHighlightColor
+ personValueEmphasizedColor
+ personHeaderShadowOffset
+ newCardDividerViewVertical:
+ personViewHeaderImageWidth
+ personViewHeaderImageHeight
+ abCellStyleForGroupsTableGrouped
+ abCellStyleForGroupsTablePlain
+ abCellStyleForCardTableLinkingUI
+ newAccessoryDisclosureIndicatorForCellStyle:
+ newTableFooterViewForCellStyle:
+ membersHeaderContentViewBackgroundColor
+ memberHeaderBackgroundView
+ membersBackgroundColor
+ memberNameSelectedShadowColor
+ memberNameMeCardTextColor
+ memberSearchFieldBackgroundColor
+ membersSelectionStyle
+ membersIndexMaximumHeight
+ membersSearchBarIsInTableHeader
+ cardTableShouldRemoveBackgroundView
+ cardHeadlineTextColor
+ cardTaglineTextColor
+ personHeaderShadowColor
+ cardTableCellBorderColor
+ cardHeaderDefaultLabelTextColor
+ cardValueHighlightedTextColor
+ cardValueClearButtonImage
+ cardValueHighlightsWhenTouched
+ cardLabelSelectedBackgroundColor
+ editorViewColor
+ cardLabelHighlightedTextColor
+ cardLabelEmphasizedHighlightedTextColor
+ personValueImportantColor
+ personValueImportantHighlightColor
+ personLabelHighlightedColor
+ personLabelShadowColor
+ personActionFont
+ personActionColor
+ personActionHighlightedColor
+ personActionShadowColor
+ personActionShadowOffset
+ personHeaderPasteboardColor
+ cardActionButtonType
+ cardActionButtonBackgroundNormal
+ cardActionButtonBackgroundHighlighted
+ cardActionConferenceIcon
+ cardActionConferenceIconPressed
+ cardActionsAllowVoiceFavorites
+ cardActionsAllowFaceTimeFavorites
+ cardCellDividerShadowColorVertical:
+ cardDeleteButtonImage
+ cardDeleteButtonImagePressed
+ cardTableUsesRowFadeAnimation
+ cardShouldUseSeparateSectionsForUnknownCardActions
+ cardSectionAlwaysWantsHeader
+ cardSectionDrawsDefaultTopShadow
+ personViewGetFavoritesBadge
+ personViewGetFavoritesBadgeHighlighted
+ cardPhotoBackgroundImage
+ cardPhotoOffset
+ cardPhotoMaskImage
+ cardPhotoOverlayImage
+ cardPhotoFacebookAttributionImage
+ cardPhotoEditOverlayImage
+ cardPhotoShouldApplyOverlayImageWhenLabelPresent
+ cardPhotoShadowImage
+ cardPhotoShadowOffset
+ cardPlaceholderPersonImage
+ cardPlaceholderCompanyImage
+ cardPlaceholderImageShouldApplyMaskAndOverlay
+ cardPhotoEditPlaceholderImage
+ datePickerHasNavigationTitle
+ pickerTransitionStyle
+ shouldDefinePickerTransitionStyle
+ dialogStyleForDeleteConfirmation
+ presentDatePickerInPopover
+ presentNewContactsControllersInPopover
+ presentModalViewInPopover
+ groupsTableShouldRemoveBackgroundView
+ groupCellHighlightedTextColor
+ groupCellShadowColor
+ groupCellSelectionStyle
+ groupAccountNameShadowColor
+ refreshTinyActionCell
+ reloadCallAction
+ linkedPhotoLabelStringsDescribeSourceOnly
+ linkedPhotoPickerIncludesCurrentPhoto
+ labelPickerShouldPushCustomLabelCreator
+ memberNameInsets
+ memberNameDisabledTextColor
+ memberNameShadowOffset
+ membersCountToShowIndex
+ memberNameBoldFontForSectionHeader
+ cardLabelShadowOffset
+ cardLabelImportantHighlightedTextColor
+ cardLabelBackgroundColor
+ cardValueTextFont
+ personValueFontMinSize
+ cardValueShadowOffset
+ cardValueBackgroundColor
+ cardLabelEditingTextColor
+ cardLabelDisabledTextColor
+ cardValueDisabledTextColor
+ cardValueTappableColor
+ cardLabelEditingTextFont
+ cardLabelTextFont
+ personViewRowHeightWhenEditing:
+ cardValueInsetsWhenEditing:
+ memberNameRegularFont
+ memberNameBoldFont
+ memberNamePlaceholderFont
+ cardMaxHeightForSwellTextViewWhenEditing:
+ cardLabelInsets
+ cardNotesMinimumHeightWhenEditing:
+ cardActionButtonsInsets
+ accessoryButtonForRelatedNames
+ personLabelFontMinSize
+ cardLabelWidth
+ cardCellBadgePaddingLeft
+ cardCellBackgroundInsetsWhenEditing:
+ cardPhotoMaskMultipleImage
+ cardPhotoEditMultiplePhotoBackdropImage
+ cardPhotoEditMultipleOverlayImage
+ cardPhotoPasteboardMaskImage
+ shouldShowCardPhotoPlaceholder
+ cardHeadlineTextFont
+ cardNameNumberOfLines
+ cardTaglineTextFont
+ cardTagNumberOfLines
+ cardHeadlineShadowColor
+ cardTaglineShadowColor
+ personValueHighlightColor
+ cardDeleteButtonInsets
+ cardDeleteButtonHeight
+ personViewHorizontalCellInset
+ cardHeaderEditingImageLeftMargin
+ cardHeaderDisplayImageLeftMargin
+ cardHeaderEditingImageTopMargin
+ cardHeaderDisplayImageTopMargin
+ cardHeaderImageNameSpacing
+ cardHeaderImageNameEditorSpacing
+ personViewHeaderRightMargin
+ personViewVerticalSpacing
+ cardHeaderNameViewAlignOnBottom
+ separatorTopShadowColorForCellStyle:
+ separatorBottomShadowColorForCellStyle:
+ groupSectionDrawsDefaultTopShadow
+ cardHeaderViewLeftMargin
+ cardHeaderSpacingFromCardBodyWhenEditing:
+ personViewHeaderMinimumHeight
+ cardActionButtonHeight
+ cardActionButtonTitleSingleLineInsets
+ cardActionButtonImageInsets
+ cardActionButtonTitleDoubleLineInsets
+ cardTableViewLinkingHeaderTopPaddingWhenEditing:
+ cardTableViewLinkingHeaderBottomPaddingWhenEditing:
+ cardSectionHeaderHorizontalPadding
+ cardSectionHeaderFont
+ cardSectionHeaderTextColor
+ cardSectionHeaderShadowColor
+ cardSectionHeaderShadowOffset
+ personNoValueLabelFont
+ personNoValueLabelTextColor
+ personNoValueLabelShadowColor
+ personNoValueLabelShadowOffset
+ personTableHeaderViewScrollsWhenEditing:
+ selectWholePartForCell:
+ cardNotesHeaderView
+ cardAlwaysShowsNotes
+ selectLabelPartForCell:
+ selectValuePartForCell:
+ selectCustomPartWithFrame:occupiedCorners:forCell:
+ unselectAllCellParts:
+ personLabelFont
+ personLabelShadowOffset
+ accessoryViewForMailVIPBadge
+ accessoryViewForVideoBadge
+ accessoryViewForFavoritesBadge
+ cardCellAccessoryTypeRingtone
+ cardCellAccessoryTypeEditRingtone
+ cardCellAccessoryType
+ cardCellAccessoryTypeEdit
+ cardTableShouldAdjustForKeyboard
+ cardTableView:prepareCell:forRowAtIndexPath:
+ cardNotesLabelIncludesSource
+ cardActionButtonSpacing
+ cardCellDisabledBackgroundColor
+ cardTableView:wantsHeaderForProperty:inSection:whenEditing:
+ cardNotesHeaderViewHeight
+ cardSectionHeaderHeightForBottomActions
+ cardSectionHeaderHeightForFirstCardActions
+ cardSectionHeaderHeightForFollowingCardActions
+ linkedCardsShouldAllowDeletion
+ composeModalPresentationStyle
+ cardTableBackgroundColor
+ editorViewSmallFont
+ editorViewLargeFont
+ personEditorFieldVerticalInset
+ cardCellFacebookBadge
+ copyLocalizedLabel:
+ copyLocalizedPropertyName:lowercase:
+ membersCountToShowSections
+ memberNameFontSize
+ memberNameMeCardImage
+ memberNameMeCardSelectedImage
+ memberNameMeCardDisabledImage
+ memberShowContactPhoto
+ serverSearchNavigationBarHidingEnabled
+ searchControllerForceKeyboardDisplayEnabled
+ personValueColor
+ _fontForTextStyle:
+ cardHeaderViewTopMargin
+ cardValueEditingInsets
+ cardValueInsets
+ groupSectionHeaderHorizontalPadding
+ groupAccountNameFont
+ groupAccountNameShadowOffset
+ personViewGetNameViewAccessoryImage
+ personViewGetNameViewAccessoryImageSelected
+ personViewHeaderNameViewTextHorizontalInset
+ personViewHeaderNameViewTextVerticalInset
+ cardPhotoShouldApplyOverlayImageWhenPersonImagePresent
+ shouldApplyMaskImage
+ cardHeaderBackgroundColor
+ cardLabelShadowColor
+ cardLabelHighlightedShadowColor
+ cardValueShadowColor
+ cardValueHighlightedShadowColor
+ cardCellVerticalSpacingBetweenAlertsOfSimilarType
+ cardContentOccluderDefaultTopFadingHeight
+ cardContentOccluderDefaultBottomFadingHeight
+ cardLinkingHeaderLabelHeight
+ memberNameRegularFontForSectionHeader
+ memberNameInterComponentSpacing
+ memberNameMeCardShadowColor
+ memberScrollBarInset
+ memberSelectedBackgroundColor
+ groupSectionHeaderHeight
+ groupCellShadowOffset
+ newBackgroundViewsForChameleonCell
+ cardNameDividerColor
+ usesPhoneCardMetrics
+ personViewDefaultRowHeight
+ personViewVerticalCellInset
+ personValueBackgroundColor
+ shouldAdjustTableView:forKeyboardOrdering:
+ shouldAutorotateToInterfaceOrientation:
+ letterpressStyle
- newCardActionButton
- groupsTableBackgroundColor
- cardCellDividerColorVertical:
- groupCellBackgroundColor
- groupCellTextColor
- groupHeaderBackgroudColor
- groupAccountNameColor
- labelPickerUsesOpaqueBackground
- personValueFont
- personLabelColor
- abCellStyleForCardTableWhenEditing:
- memberNameSelectedColor
- cardCellBackgroundColor
- shadowColorForCellStyle:
- newBackgroundViewForCellStyle:selected:
- cardClippingImageLabelColor
- cardClippingImageLabelBevelColor
- cardPhotoFrameBorderSize
- cardValueTextColor
- memberPhotoMaskImage
- memberPlaceholderPersonImage
- memberPhotoOverlayImage
- memberPlaceholderCompanyImage
- abCellStyleForMembersTable
- separatorStyleForCellStyle:
- separatorColorForCellStyle:
- shouldUsePeoplePickerBarStyle
- peoplePickerBarStyle
- peoplePickerBarStyleIsTranslucent
- searchIsAlwaysActive
- membersIndexTextColor
- membersIndexTrackingBackgroundColor
- memberSectionListHeaderImage
- setIndicatesFaceTimeHistory:onActionButton:
- unknownModalPresentationStyle
- shouldUseCardContentProviderWhenAvailable
- customCardCellClass
- customCardActionCellClass
- newCustomCardTableScrollingBackgroundView
- cardTableViewSectionHeaderHeightWhenEditing:
- cardTableViewSectionFooterHeightWhenEditing:
- shouldPropagateStylesToPickers
- shouldPropagateStylesThroughUnknownPersonActions
- customSetEmphasized:onCell:
- membersHeaderBackgroundColor
- memberNameTextColor
- cardCellSelectionStyle
- memberNameShadowColor
- cardLabelTextColor
- personValueEmphasizedHighlightColor
- personValueEmphasizedColor
- personHeaderShadowOffset
- newCardDividerViewVertical:
- personViewHeaderImageWidth
- personViewHeaderImageHeight
- abCellStyleForGroupsTableGrouped
- abCellStyleForGroupsTablePlain
- abCellStyleForCardTableLinkingUI
- newAccessoryDisclosureIndicatorForCellStyle:
- newTableFooterViewForCellStyle:
- membersHeaderContentViewBackgroundColor
- memberHeaderBackgroundView
- membersBackgroundColor
- memberNameSelectedShadowColor
- memberNameMeCardTextColor
- memberSearchFieldBackgroundColor
- membersSelectionStyle
- membersIndexMaximumHeight
- membersSearchBarIsInTableHeader
- cardTableShouldRemoveBackgroundView
- cardHeadlineTextColor
- cardTaglineTextColor
- personHeaderShadowColor
- cardTableCellBorderColor
- cardHeaderDefaultLabelTextColor
- cardValueHighlightedTextColor
- cardValueClearButtonImage
- cardValueHighlightsWhenTouched
- cardLabelSelectedBackgroundColor
- editorViewColor
- cardLabelHighlightedTextColor
- cardLabelEmphasizedHighlightedTextColor
- personValueImportantColor
- personValueImportantHighlightColor
- personLabelHighlightedColor
- personLabelShadowColor
- personActionFont
- personActionColor
- personActionHighlightedColor
- personActionShadowColor
- personActionShadowOffset
- personHeaderPasteboardColor
- cardActionButtonType
- cardActionButtonBackgroundNormal
- cardActionButtonBackgroundHighlighted
- cardActionConferenceIcon
- cardActionConferenceIconPressed
- cardActionsAllowVoiceFavorites
- cardActionsAllowFaceTimeFavorites
- cardCellDividerShadowColorVertical:
- cardDeleteButtonImage
- cardDeleteButtonImagePressed
- cardTableUsesRowFadeAnimation
- cardShouldUseSeparateSectionsForUnknownCardActions
- cardSectionAlwaysWantsHeader
- cardSectionDrawsDefaultTopShadow
- personViewGetFavoritesBadge
- personViewGetFavoritesBadgeHighlighted
- cardPhotoBackgroundImage
- cardPhotoOffset
- cardPhotoMaskImage
- cardPhotoOverlayImage
- cardPhotoFacebookAttributionImage
- cardPhotoEditOverlayImage
- cardPhotoShouldApplyOverlayImageWhenLabelPresent
- cardPhotoShadowImage
- cardPhotoShadowOffset
- cardPlaceholderPersonImage
- cardPlaceholderCompanyImage
- cardPlaceholderImageShouldApplyMaskAndOverlay
- cardPhotoEditPlaceholderImage
- datePickerHasNavigationTitle
- pickerTransitionStyle
- shouldDefinePickerTransitionStyle
- dialogStyleForDeleteConfirmation
- presentDatePickerInPopover
- presentNewContactsControllersInPopover
- presentModalViewInPopover
- groupsTableShouldRemoveBackgroundView
- groupCellHighlightedTextColor
- groupCellShadowColor
- groupCellSelectionStyle
- groupAccountNameShadowColor
- refreshTinyActionCell
- reloadCallAction
- linkedPhotoLabelStringsDescribeSourceOnly
- linkedPhotoPickerIncludesCurrentPhoto
- labelPickerShouldPushCustomLabelCreator
- memberNameInsets
- memberNameDisabledTextColor
- memberNameShadowOffset
- membersCountToShowIndex
- memberNameBoldFontForSectionHeader
- cardLabelShadowOffset
- cardLabelImportantHighlightedTextColor
- cardLabelBackgroundColor
- cardValueTextFont
- personValueFontMinSize
- cardValueShadowOffset
- cardValueBackgroundColor
- cardLabelEditingTextColor
- cardLabelDisabledTextColor
- cardValueDisabledTextColor
- cardValueTappableColor
- cardLabelEditingTextFont
- cardLabelTextFont
- personViewRowHeightWhenEditing:
- cardValueInsetsWhenEditing:
- memberNameRegularFont
- memberNameBoldFont
- memberNamePlaceholderFont
- cardMaxHeightForSwellTextViewWhenEditing:
- cardLabelInsets
- cardNotesMinimumHeightWhenEditing:
- cardActionButtonsInsets
- accessoryButtonForRelatedNames
- personLabelFontMinSize
- cardLabelWidth
- cardCellBadgePaddingLeft
- cardCellBackgroundInsetsWhenEditing:
- cardPhotoMaskMultipleImage
- cardPhotoEditMultiplePhotoBackdropImage
- cardPhotoEditMultipleOverlayImage
- cardPhotoPasteboardMaskImage
- shouldShowCardPhotoPlaceholder
- cardHeadlineTextFont
- cardNameNumberOfLines
- cardTaglineTextFont
- cardTagNumberOfLines
- cardHeadlineShadowColor
- cardTaglineShadowColor
- personValueHighlightColor
- cardDeleteButtonInsets
- cardDeleteButtonHeight
- personViewHorizontalCellInset
- cardHeaderEditingImageLeftMargin
- cardHeaderDisplayImageLeftMargin
- cardHeaderEditingImageTopMargin
- cardHeaderDisplayImageTopMargin
- cardHeaderImageNameSpacing
- cardHeaderImageNameEditorSpacing
- personViewHeaderRightMargin
- personViewVerticalSpacing
- cardHeaderNameViewAlignOnBottom
- separatorTopShadowColorForCellStyle:
- separatorBottomShadowColorForCellStyle:
- groupSectionDrawsDefaultTopShadow
- cardHeaderViewLeftMargin
- cardHeaderSpacingFromCardBodyWhenEditing:
- personViewHeaderMinimumHeight
- cardActionButtonHeight
- cardActionButtonTitleSingleLineInsets
- cardActionButtonImageInsets
- cardActionButtonTitleDoubleLineInsets
- cardTableViewLinkingHeaderTopPaddingWhenEditing:
- cardTableViewLinkingHeaderBottomPaddingWhenEditing:
- cardSectionHeaderHorizontalPadding
- cardSectionHeaderFont
- cardSectionHeaderTextColor
- cardSectionHeaderShadowColor
- cardSectionHeaderShadowOffset
- personNoValueLabelFont
- personNoValueLabelTextColor
- personNoValueLabelShadowColor
- personNoValueLabelShadowOffset
- personTableHeaderViewScrollsWhenEditing:
- selectWholePartForCell:
- cardNotesHeaderView
- cardAlwaysShowsNotes
- selectLabelPartForCell:
- selectValuePartForCell:
- selectCustomPartWithFrame:occupiedCorners:forCell:
- unselectAllCellParts:
- personLabelFont
- personLabelShadowOffset
- accessoryViewForMailVIPBadge
- accessoryViewForVideoBadge
- accessoryViewForFavoritesBadge
- cardCellAccessoryTypeRingtone
- cardCellAccessoryTypeEditRingtone
- cardCellAccessoryType
- cardCellAccessoryTypeEdit
- cardTableShouldAdjustForKeyboard
- cardTableView:prepareCell:forRowAtIndexPath:
- cardNotesLabelIncludesSource
- cardActionButtonSpacing
- cardCellDisabledBackgroundColor
- cardTableView:wantsHeaderForProperty:inSection:whenEditing:
- cardNotesHeaderViewHeight
- cardSectionHeaderHeightForBottomActions
- cardSectionHeaderHeightForFirstCardActions
- cardSectionHeaderHeightForFollowingCardActions
- linkedCardsShouldAllowDeletion
- composeModalPresentationStyle
- cardTableBackgroundColor
- editorViewSmallFont
- editorViewLargeFont
- personEditorFieldVerticalInset
- cardCellFacebookBadge
- copyLocalizedLabel:
- copyLocalizedPropertyName:lowercase:
- membersCountToShowSections
- memberNameFontSize
- memberNameMeCardImage
- memberNameMeCardSelectedImage
- memberNameMeCardDisabledImage
- memberShowContactPhoto
- serverSearchNavigationBarHidingEnabled
- searchControllerForceKeyboardDisplayEnabled
- personValueColor
- _fontForTextStyle:
- cardHeaderViewTopMargin
- cardValueEditingInsets
- cardValueInsets
- groupSectionHeaderHorizontalPadding
- groupAccountNameFont
- groupAccountNameShadowOffset
- personViewGetNameViewAccessoryImage
- personViewGetNameViewAccessoryImageSelected
- personViewHeaderNameViewTextHorizontalInset
- personViewHeaderNameViewTextVerticalInset
- cardPhotoShouldApplyOverlayImageWhenPersonImagePresent
- shouldApplyMaskImage
- cardHeaderBackgroundColor
- cardLabelShadowColor
- cardLabelHighlightedShadowColor
- cardValueShadowColor
- cardValueHighlightedShadowColor
- cardCellVerticalSpacingBetweenAlertsOfSimilarType
- cardContentOccluderDefaultTopFadingHeight
- cardContentOccluderDefaultBottomFadingHeight
- cardLinkingHeaderLabelHeight
- memberNameRegularFontForSectionHeader
- memberNameInterComponentSpacing
- memberNameMeCardShadowColor
- memberScrollBarInset
- memberSelectedBackgroundColor
- groupSectionHeaderHeight
- groupCellShadowOffset
- newBackgroundViewsForChameleonCell
- cardNameDividerColor
- usesPhoneCardMetrics
- personViewDefaultRowHeight
- personViewVerticalCellInset
- personValueBackgroundColor
- shouldAdjustTableView:forKeyboardOrdering:
- shouldAutorotateToInterfaceOrientation:
- letterpressStyle
@end
