@interface ABUIPerson : NSObject
{
	pointer _record;
	pointer _addressBook;
	pointer _source;
	id _linkedPeople;
}

+ hasValidRecordID
+ photoThumbnail
+ preferredPhotoThumbnail
+ primarySourceName
+ secondarySourceName
+ copyPropertyValue:
+ policy
+ allowsCustomLabelsForProperty:
+ isMeCard
+ linkedPeople
+ preferredPersonForName
+ removePropertyValue:
+ nameIgnoringOrganization:
+ addToGroup:
+ addToAddressBook:
+ updateNewPersonKindFromName
+ preferredPersonForPhoto
+ isFromFacebook
+ hasPhoto
+ policiesForAllLinkedPeople
+ areAllLinkedPeopleReadonly
+ setNamePropertiesFromPerson:
+ linkToPerson:
+ mergeValuesFromRecord:
+ updatePersonKindFromName
+ isRemote
+ hasLinkedPeople
+ preferredName
+ setAsPreferredPersonForName
+ recordWasDeleted
+ reloadFromDB
+ recordType
+ initWithABPerson:
+ initWithABRecordID:fromAddressBook:
+ linkedPeopleCount
+ _updatePersonKindFromNamePreserveOrganizationKind:
+ mergeProperties:fromRecord:
+ setAsPreferredPersonForPhoto
+ hasPreferredPhoto
+ dealloc
+ isEqual:
+ hash
+ description
+ copyWithZone:
+ name
+ source
+ kind
+ valueForProperty:
+ phoneticName
+ setValue:forProperty:
+ addressBook
+ recordID
+ record
+ isReadonly
- hasValidRecordID
- photoThumbnail
- preferredPhotoThumbnail
- primarySourceName
- secondarySourceName
- copyPropertyValue:
- policy
- allowsCustomLabelsForProperty:
- isMeCard
- linkedPeople
- preferredPersonForName
- removePropertyValue:
- nameIgnoringOrganization:
- addToGroup:
- addToAddressBook:
- updateNewPersonKindFromName
- preferredPersonForPhoto
- isFromFacebook
- hasPhoto
- policiesForAllLinkedPeople
- areAllLinkedPeopleReadonly
- setNamePropertiesFromPerson:
- linkToPerson:
- mergeValuesFromRecord:
- updatePersonKindFromName
- isRemote
- hasLinkedPeople
- preferredName
- setAsPreferredPersonForName
- recordWasDeleted
- reloadFromDB
- recordType
- initWithABPerson:
- initWithABRecordID:fromAddressBook:
- linkedPeopleCount
- _updatePersonKindFromNamePreserveOrganizationKind:
- mergeProperties:fromRecord:
- setAsPreferredPersonForPhoto
- hasPreferredPhoto
- dealloc
- isEqual:
- hash
- description
- copyWithZone:
- name
- source
- kind
- valueForProperty:
- phoneticName
- setValue:forProperty:
- addressBook
- recordID
- record
- isReadonly
@end
