@interface ADCommandCenter : NSObject
{
	id _queue;
	id _currentClient;
	id _requestDelegate;
	id _speechDelegate;
	id _uiService;
	id _account;
	id _session;
	id _diagnosticsManager;
	id _syncManager;
	id _speechManager;
	id _serviceManager;
	id _undoManager;
	id _contextManager;
	id _managedStore;
	id _retryManager;
	id _callbacksManager;
	id _locationManager;
	id _motionManager;
	id _offlineSAMetricsManager;
	id _callObserver;
	int _callState;
	id _callKeepAliveTimer;
	BOOL _callIsLikely;
	id _speechCompletion;
	id _outstandingSyncChunks;
	BOOL _needsToSendSyncFinished;
	id _currentSpeechRequestOptions;
	id _startSpeechCommand;
	id _currentRequest;
	id _lastRequest;
	BOOL _startingPronunciationRequest;
	id _pronunciationContext;
	BOOL _speechDelegateHasReceivedSpeechRecognized;
	struct _contextFetchState;
	id _contextDispatchGroup;
	id _lastClearContext;
	id _outstandingRequestIds;
	id _aceCompletionMap;
	BOOL _deviceIsLocked;
	double _requestEffectiveStartTime;
	BOOL _isActive;
	BOOL _hasIsActiveNotifyToken;
	int _isActiveNotifyToken;
	BOOL _sanityCheckAutodownloadedAssets;
	id _requestStatistics;
}

+ _handleCommandInAMOS:
+ _sendAMOSCommand:domain:toBundleWithIdentifier:
+ _sendCreateResponseForCommand:withIdentifier:
+ _handleSADOCommandIfServiceDoesNotUseAMOS:allowInterposing:
+ _amosSADomainObjectCreate:
+ _sendRetrieveResponseForCommand:withSADObjects:
+ _sendAMOSCommandToService:responseHandler:
+ _amosSADomainObjectRetrieve:
+ _sendUpdateResponseForCommand:withUpdatedIdentifier:
+ _updateObjectFromService:sadIdentifier:
+ _amosSADomainObjectUpdate:
+ _sendCancelResponseForCommand:
+ _amosSADomainObjectCancel:
+ _sendDeleteResponseForCommand:
+ _amosSADomainObjectDelete:
+ _sendCommitResponseForCommand:identifier:
+ _amosSADomainObjectCommit:
+ _amosSADomainObjectPunchOut:
+ _saDomainObjectCreate:
+ _saDomainObjectRetrieve:
+ _saDomainObjectUpdate:
+ _saDomainObjectCancel:
+ _saDomainObjectDelete:
+ _saDomainObjectCommit:
+ _saDomainObjectPunchOut:
+ clientDisconnected:
+ clientConnected:
+ sanityCheckAutodownloadedAssets
+ installedAssetsUpdated
+ syncNeeded
+ prepareForShutdown
+ rescheduleValidationRefresh
+ refreshActivation
+ refreshAssistantValidation
+ destroyActiveAccount
+ syncAnchorKeys:forceReset:
+ dismissAssistant
+ openURL:completion:
+ _startObservingCallState
+ _motionManager
+ _cancelSession
+ _requestStatistics
+ _serviceManager
+ _setCallIsLikely:
+ _setCurrentRequest:
+ _setLastRequest:
+ _setStartSpeechCommand:
+ _cancelCurrentRequest
+ _clearSpeechDelegateState
+ _clearRequestDelegateState
+ _setRequestDelegate:
+ _setSpeechDelegate:
+ _setSpeechCompletion:
+ _replaceSpeechDelegateWhenReady:cancelRequestIfDelegatesMatch:withCompletion:
+ _retryManager
+ _addCompletion:forCommandId:
+ _sendCommandToServer:
+ _addOutstandingRequestId:
+ _sendRequestToServer:
+ _retryNakedCommandsIfNeeded
+ _sendRetryableRequestToServer:
+ _undoManager
+ _sendRollbackCommandForCommand:
+ _reallyHandleNewStartRequest:
+ _callbacksManager
+ _handleCommand:
+ _currentRequest
+ _removeOutstandingRequestId:
+ _handleNextCallbacksForReply:
+ _sendCommandFailedForCommand:reason:
+ _sendUndoServiceCommands:toService:
+ _handleValidServiceReply:forCommand:
+ _handleServiceReply:inverse:error:forCommand:service:
+ _syncManager
+ _syncChunkWindowFull
+ _isInCall
+ _continueSyncIfConditionsMet
+ _requestAnchorsForKeys:
+ _cancelCallKeepAlive
+ _scheduleCallKeepAlive
+ _offlineSAMetricsManager
+ _handleBareRequestCompleted:
+ _removeOutstandingSyncChunkId:
+ _refIdIsSpeechStart:
+ _speechManager
+ _contextManager
+ _locationManager
+ _diagnosticsManager
+ _hasOutstandingRequestId:
+ _hasOutstandingSyncChunkId:
+ _processCallbacksForCommand:
+ _handleServiceCommand:
+ _invokeCompletionForCommand:
+ _removeCompletionsForCommandId:
+ _clearSyncChunks
+ _invokeAllCompletions
+ _removeAllCompletions
+ _isRetryableSessionError:
+ _shouldRetryForError:
+ _shouldClearNakedCommandsOnError:
+ _sessionDidFailWithError:
+ _startSpeechCommand
+ _addOutstandingSyncChunkId:
+ _speechCaptureCompleted
+ _sendCancelSpeechForCommand:
+ _setOutputVoice:
+ _replaceSpeechDelegateWhenReady:withCompletion:
+ _resetContextDispatchGroup
+ _replaceRequestDelegate:
+ _setBackgroundContext
+ _contextDispatchGroup
+ _ensureBackgroundContextSentToServer
+ _saRequestCompleted:
+ _handleNewStartRequest:suppressCancelationAlertIfCapturingSpeech:
+ _reallyHandleNewDirectActionRequest:
+ _lastRequest
+ _sendCommandToServer:completion:
+ _clearAccount
+ _managedStore
+ _endSessionForDelegate:
+ _preheat
+ _setLanguageCode:
+ _setLockState:showingLockScreen:
+ _setStarkRestriction:
+ _setVoiceOverIsActive:
+ _startRequest:withDelegate:
+ _startDirectActionRequest:withDelegate:
+ _prepareAudioSessionForDelegate:withOptions:
+ _startSpeechRequestWithDelegate:withOptions:
+ _startSpeechPronunciationRequestWithDelegate:withOptions:pronunciationContext:
+ _startSpeechRequestWithURL:isNarrowBand:withDelegate:
+ _cancelRequestForDelegate:
+ _rollbackRequestForDelegate:
+ _startDictationWithLanguageCode:options:speechOptions:delegate:
+ _startDictationWithURL:isNarrowBand:language:options:delegate:
+ _startSpeechCorrectionWithText:forCorrectionContext:delegate:
+ _removeDelegate:
+ _stopSpeechWithOptions:forDelegate:
+ _cancelSpeechForDelegate:
+ _updateSpeechOptions:forDelegate:
+ _sendSpeechCorrectionInfo:forCorrectionContext:
+ _handleGenericAceCommand:withDelegate:interruptOutstandingRequest:reply:
+ _nakedClearContext
+ _rollbackClearContext
+ _setApplicationContext
+ _setAlertContextWithBulletins:
+ _telephonyRequestCompleted
+ _fetchSupportedLanguagesWithCompletion:
+ fetchSupportedLanguagesWithCompletion:
+ _undoRequest
+ _redoRequest
+ _deleteAccountWithIdentifier:
+ _activeAccountIdentifier
+ _setActiveAccountIdentifier:
+ _destroyActiveAccount
+ _rescheduleValidationRefresh
+ _refreshActivation
+ _managedStoreObjectForKey:
+ _setManagedStoreObject:forKey:
+ _syncAnchorKeys:forceReset:
+ _syncNeeded
+ _setUIService:
+ _startUpdatingMotionActivity
+ _setSiriActiveFlag:
+ _stopUpdatingMotionActivity
+ _sanityCheckAutodownloadedAssets
+ _syncIfNeeded
+ _installedAssetsUpdated
+ assistantSession:receivedCommand:
+ assistantSession:receivedError:
+ assistantSessionShouldLogVisibleRequestFailure:forError:
+ assistantSessionShouldRestartConnectionOnWiFi:
+ assistantSessionConnectionDidReset:
+ assistantSessionShouldAttemptRetry:
+ assistantSession:didChangeRequestIdFrom:toId:
+ assistantSession:didLoadAssistantSyncRequested:syncAnchors:
+ syncManager:chunkForKey:preAnchor:postAnchor:validity:toAdd:toRemove:
+ syncManager:finishedSyncForKeys:
+ speechManagerWillStartRecording:timestamp:
+ speechManager:didStartForDictation:withCodec:source:avRecordRoute:deviceId:modelName:
+ speechManager:capturedPackets:totalCount:
+ speechManager:updatedAveragePower:peakPower:
+ speechManager:finishedWithTotalPackets:endpointMode:
+ speechManagerDidCancel:
+ speechManager:didFailWithError:
+ adShouldSpeakStateDidChange:
+ contextManager:didReceiveNewBackgroundContext:
+ locationManager:wantsToSetRequestOrigin:
+ _hasOutstandingRequests
+ _cancelSessionIfIdle
+ _sendCommandIgnoredForCommand:
+ _sendServiceCommand:reply:
+ _stopObserveringCallState
+ _saSetSupportedLocales:
+ _saCommandFailed:
+ _saCommandIgnored:
+ _saSendCommands:
+ _saAssistantDestroyed:
+ _saCancelSucceeded:
+ _saRollbackSucceeded:
+ _saSyncGetAnchorsResponse:
+ _saSyncChunkDenied:
+ _saSyncChunkAccepted:
+ _sasSpeechRecognized:
+ _sasSpeechFailure:
+ _saAcknowledgeAlert:
+ _saGetRequestOrigin:
+ _saSetLatencyDiagnosticConfiguration:
+ _saUnhandledObject:
+ assistantSessionShouldSetAssistantData:
+ locationManager:shouldStartMonitoringLocationForRequest:
+ setLanguageCode:withCompletion:
+ endSessionForDelegate:
+ startRequest:withDelegate:
+ startDirectActionRequest:withDelegate:
+ prepareAudioSessionForDelegate:withOptions:
+ startSpeechRequestWithDelegate:withOptions:
+ startSpeechPronunciationRequestWithDelegate:withOptions:pronunciationContext:
+ startSpeechRequestWithURL:isNarrowBand:withDelegate:
+ cancelRequestForDelegate:
+ rollbackRequestForDelegate:
+ startDictationWithLanguageCode:options:speechOptions:delegate:
+ startDictationWithURL:isNarrowBand:language:options:delegate:
+ startSpeechCorrectionWithText:forCorrectionContext:delegate:
+ stopSpeechWithOptions:forDelegate:
+ cancelSpeechForDelegate:
+ updateSpeechOptions:forDelegate:
+ handleGenericAceCommand:withDelegate:interruptOutstandingRequest:reply:
+ fetchSupportedLanguages
+ fetchAccounts:
+ fetchActiveAccountIdentifier:
+ fetchManagedStoreObjectForKey:completion:
+ fetchContext:
+ _broadcastCommand:
+ _listInstalledServicesWithCompletion:
+ _requestDelegate
+ _speechDelegate
+ _uiService
+ _speechCompletion
+ setRequestStatistics:
+ _clearContext
+ setActiveAccountIdentifier:
+ dealloc
+ init
+ preheat
+ _queue
+ _requestDidEnd
+ setVoiceOverIsActive:
+ setLockState:showingLockScreen:
+ setIsStark:
+ rollbackClearContext
+ setAlertContextWithBulletins:
+ telephonyRequestCompleted
+ defrost
+ undoRequest
+ redoRequest
+ sendSpeechCorrectionInfo:forCorrectionContext:
+ setManagedStoreObject:forKey:
+ deleteAccountWithIdentifier:
+ setOutputVoice:withCompletion:
+ _refreshAssistantValidation
+ _requestWillStart
+ _session
+ _setAccount:
+ _accounts
+ isDeviceLocked
+ clearContext
+ setApplicationContext
+ _setSession:
+ .cxx_destruct
+ _account
+ removeDelegate:
- _handleCommandInAMOS:
- _sendAMOSCommand:domain:toBundleWithIdentifier:
- _sendCreateResponseForCommand:withIdentifier:
- _handleSADOCommandIfServiceDoesNotUseAMOS:allowInterposing:
- _amosSADomainObjectCreate:
- _sendRetrieveResponseForCommand:withSADObjects:
- _sendAMOSCommandToService:responseHandler:
- _amosSADomainObjectRetrieve:
- _sendUpdateResponseForCommand:withUpdatedIdentifier:
- _updateObjectFromService:sadIdentifier:
- _amosSADomainObjectUpdate:
- _sendCancelResponseForCommand:
- _amosSADomainObjectCancel:
- _sendDeleteResponseForCommand:
- _amosSADomainObjectDelete:
- _sendCommitResponseForCommand:identifier:
- _amosSADomainObjectCommit:
- _amosSADomainObjectPunchOut:
- _saDomainObjectCreate:
- _saDomainObjectRetrieve:
- _saDomainObjectUpdate:
- _saDomainObjectCancel:
- _saDomainObjectDelete:
- _saDomainObjectCommit:
- _saDomainObjectPunchOut:
- clientDisconnected:
- clientConnected:
- sanityCheckAutodownloadedAssets
- installedAssetsUpdated
- syncNeeded
- prepareForShutdown
- rescheduleValidationRefresh
- refreshActivation
- refreshAssistantValidation
- destroyActiveAccount
- syncAnchorKeys:forceReset:
- dismissAssistant
- openURL:completion:
- _startObservingCallState
- _motionManager
- _cancelSession
- _requestStatistics
- _serviceManager
- _setCallIsLikely:
- _setCurrentRequest:
- _setLastRequest:
- _setStartSpeechCommand:
- _cancelCurrentRequest
- _clearSpeechDelegateState
- _clearRequestDelegateState
- _setRequestDelegate:
- _setSpeechDelegate:
- _setSpeechCompletion:
- _replaceSpeechDelegateWhenReady:cancelRequestIfDelegatesMatch:withCompletion:
- _retryManager
- _addCompletion:forCommandId:
- _sendCommandToServer:
- _addOutstandingRequestId:
- _sendRequestToServer:
- _retryNakedCommandsIfNeeded
- _sendRetryableRequestToServer:
- _undoManager
- _sendRollbackCommandForCommand:
- _reallyHandleNewStartRequest:
- _callbacksManager
- _handleCommand:
- _currentRequest
- _removeOutstandingRequestId:
- _handleNextCallbacksForReply:
- _sendCommandFailedForCommand:reason:
- _sendUndoServiceCommands:toService:
- _handleValidServiceReply:forCommand:
- _handleServiceReply:inverse:error:forCommand:service:
- _syncManager
- _syncChunkWindowFull
- _isInCall
- _continueSyncIfConditionsMet
- _requestAnchorsForKeys:
- _cancelCallKeepAlive
- _scheduleCallKeepAlive
- _offlineSAMetricsManager
- _handleBareRequestCompleted:
- _removeOutstandingSyncChunkId:
- _refIdIsSpeechStart:
- _speechManager
- _contextManager
- _locationManager
- _diagnosticsManager
- _hasOutstandingRequestId:
- _hasOutstandingSyncChunkId:
- _processCallbacksForCommand:
- _handleServiceCommand:
- _invokeCompletionForCommand:
- _removeCompletionsForCommandId:
- _clearSyncChunks
- _invokeAllCompletions
- _removeAllCompletions
- _isRetryableSessionError:
- _shouldRetryForError:
- _shouldClearNakedCommandsOnError:
- _sessionDidFailWithError:
- _startSpeechCommand
- _addOutstandingSyncChunkId:
- _speechCaptureCompleted
- _sendCancelSpeechForCommand:
- _setOutputVoice:
- _replaceSpeechDelegateWhenReady:withCompletion:
- _resetContextDispatchGroup
- _replaceRequestDelegate:
- _setBackgroundContext
- _contextDispatchGroup
- _ensureBackgroundContextSentToServer
- _saRequestCompleted:
- _handleNewStartRequest:suppressCancelationAlertIfCapturingSpeech:
- _reallyHandleNewDirectActionRequest:
- _lastRequest
- _sendCommandToServer:completion:
- _clearAccount
- _managedStore
- _endSessionForDelegate:
- _preheat
- _setLanguageCode:
- _setLockState:showingLockScreen:
- _setStarkRestriction:
- _setVoiceOverIsActive:
- _startRequest:withDelegate:
- _startDirectActionRequest:withDelegate:
- _prepareAudioSessionForDelegate:withOptions:
- _startSpeechRequestWithDelegate:withOptions:
- _startSpeechPronunciationRequestWithDelegate:withOptions:pronunciationContext:
- _startSpeechRequestWithURL:isNarrowBand:withDelegate:
- _cancelRequestForDelegate:
- _rollbackRequestForDelegate:
- _startDictationWithLanguageCode:options:speechOptions:delegate:
- _startDictationWithURL:isNarrowBand:language:options:delegate:
- _startSpeechCorrectionWithText:forCorrectionContext:delegate:
- _removeDelegate:
- _stopSpeechWithOptions:forDelegate:
- _cancelSpeechForDelegate:
- _updateSpeechOptions:forDelegate:
- _sendSpeechCorrectionInfo:forCorrectionContext:
- _handleGenericAceCommand:withDelegate:interruptOutstandingRequest:reply:
- _nakedClearContext
- _rollbackClearContext
- _setApplicationContext
- _setAlertContextWithBulletins:
- _telephonyRequestCompleted
- _fetchSupportedLanguagesWithCompletion:
- fetchSupportedLanguagesWithCompletion:
- _undoRequest
- _redoRequest
- _deleteAccountWithIdentifier:
- _activeAccountIdentifier
- _setActiveAccountIdentifier:
- _destroyActiveAccount
- _rescheduleValidationRefresh
- _refreshActivation
- _managedStoreObjectForKey:
- _setManagedStoreObject:forKey:
- _syncAnchorKeys:forceReset:
- _syncNeeded
- _setUIService:
- _startUpdatingMotionActivity
- _setSiriActiveFlag:
- _stopUpdatingMotionActivity
- _sanityCheckAutodownloadedAssets
- _syncIfNeeded
- _installedAssetsUpdated
- assistantSession:receivedCommand:
- assistantSession:receivedError:
- assistantSessionShouldLogVisibleRequestFailure:forError:
- assistantSessionShouldRestartConnectionOnWiFi:
- assistantSessionConnectionDidReset:
- assistantSessionShouldAttemptRetry:
- assistantSession:didChangeRequestIdFrom:toId:
- assistantSession:didLoadAssistantSyncRequested:syncAnchors:
- syncManager:chunkForKey:preAnchor:postAnchor:validity:toAdd:toRemove:
- syncManager:finishedSyncForKeys:
- speechManagerWillStartRecording:timestamp:
- speechManager:didStartForDictation:withCodec:source:avRecordRoute:deviceId:modelName:
- speechManager:capturedPackets:totalCount:
- speechManager:updatedAveragePower:peakPower:
- speechManager:finishedWithTotalPackets:endpointMode:
- speechManagerDidCancel:
- speechManager:didFailWithError:
- adShouldSpeakStateDidChange:
- contextManager:didReceiveNewBackgroundContext:
- locationManager:wantsToSetRequestOrigin:
- _hasOutstandingRequests
- _cancelSessionIfIdle
- _sendCommandIgnoredForCommand:
- _sendServiceCommand:reply:
- _stopObserveringCallState
- _saSetSupportedLocales:
- _saCommandFailed:
- _saCommandIgnored:
- _saSendCommands:
- _saAssistantDestroyed:
- _saCancelSucceeded:
- _saRollbackSucceeded:
- _saSyncGetAnchorsResponse:
- _saSyncChunkDenied:
- _saSyncChunkAccepted:
- _sasSpeechRecognized:
- _sasSpeechFailure:
- _saAcknowledgeAlert:
- _saGetRequestOrigin:
- _saSetLatencyDiagnosticConfiguration:
- _saUnhandledObject:
- assistantSessionShouldSetAssistantData:
- locationManager:shouldStartMonitoringLocationForRequest:
- setLanguageCode:withCompletion:
- endSessionForDelegate:
- startRequest:withDelegate:
- startDirectActionRequest:withDelegate:
- prepareAudioSessionForDelegate:withOptions:
- startSpeechRequestWithDelegate:withOptions:
- startSpeechPronunciationRequestWithDelegate:withOptions:pronunciationContext:
- startSpeechRequestWithURL:isNarrowBand:withDelegate:
- cancelRequestForDelegate:
- rollbackRequestForDelegate:
- startDictationWithLanguageCode:options:speechOptions:delegate:
- startDictationWithURL:isNarrowBand:language:options:delegate:
- startSpeechCorrectionWithText:forCorrectionContext:delegate:
- stopSpeechWithOptions:forDelegate:
- cancelSpeechForDelegate:
- updateSpeechOptions:forDelegate:
- handleGenericAceCommand:withDelegate:interruptOutstandingRequest:reply:
- fetchSupportedLanguages
- fetchAccounts:
- fetchActiveAccountIdentifier:
- fetchManagedStoreObjectForKey:completion:
- fetchContext:
- _broadcastCommand:
- _listInstalledServicesWithCompletion:
- _requestDelegate
- _speechDelegate
- _uiService
- _speechCompletion
- setRequestStatistics:
- _clearContext
- setActiveAccountIdentifier:
- dealloc
- init
- preheat
- _queue
- _requestDidEnd
- setVoiceOverIsActive:
- setLockState:showingLockScreen:
- setIsStark:
- rollbackClearContext
- setAlertContextWithBulletins:
- telephonyRequestCompleted
- defrost
- undoRequest
- redoRequest
- sendSpeechCorrectionInfo:forCorrectionContext:
- setManagedStoreObject:forKey:
- deleteAccountWithIdentifier:
- setOutputVoice:withCompletion:
- _refreshAssistantValidation
- _requestWillStart
- _session
- _setAccount:
- _accounts
- isDeviceLocked
- clearContext
- setApplicationContext
- _setSession:
- .cxx_destruct
- _account
- removeDelegate:
@end
