@interface AVAsset : NSObject
{
	id _assetInternal;
}

+ mpLoadValuesAsynchronouslyForKeys:completionQueue:completionHandler:
+ _chapterTracks
+ _containsAtLeastOnePlayableAudioTrack
+ _containsAtLeastOnePlayableVideoTrack
+ _exportURL
+ unusedTrackID
+ chapterMetadataGroupsBestMatchingPreferredLanguages:
+ availableChapterLocales
+ chapterMetadataGroupsWithTitleLocale:containingItemsWithCommonKeys:
+ cancelLoading
+ _figAsset
+ _assetInspectorLoader
+ _assetInspector
+ _playbackItem
+ preferredRate
+ preferredVolume
+ naturalTimeScale
+ providesPreciseDurationAndTiming
+ referenceRestrictions
+ alternateTrackGroups
+ trackGroups
+ _firstTrackGroupWithMediaType:
+ mediaSelectionGroups
+ availableMetadataFormats
+ metadataForFormat:
+ tracksWithMediaCharacteristics:
+ _serverHasDied
+ isExportable
+ isComposable
+ _weakReference
+ _comparisonToken
+ statusOfValueForKey:
+ _formatReader
+ _absoluteURL
+ audioAlternatesTrackGroup
+ subtitleAlternatesTrackGroup
+ availableMediaCharacteristicsWithMediaSelectionOptions
+ _tracksDidChange
+ tracksWithMediaCharacteristic:
+ compatibleTrackForCompositionTrack:
+ mediaSelectionGroupForMediaCharacteristic:
+ lyrics
+ trackReferences
+ trackWithTrackID:
+ preferredSoundCheckVolumeNormalization
+ loadValuesAsynchronouslyForKeys:keysForCollectionKeys:completionHandler:
+ _isStreaming
+ isPlayable
+ dealloc
+ init
+ isEqual:
+ hash
+ duration
+ copyWithZone:
+ valueForUndefinedKey:
+ naturalSize
+ tracksWithMediaType:
+ statusOfValueForKey:error:
+ loadValuesAsynchronouslyForKeys:completionHandler:
+ hasProtectedContent
+ isReadable
+ creationDate
+ isCompatibleWithSavedPhotosAlbum
+ metadata
+ preferredTransform
+ commonMetadata
+ tracks
- mpLoadValuesAsynchronouslyForKeys:completionQueue:completionHandler:
- _chapterTracks
- _containsAtLeastOnePlayableAudioTrack
- _containsAtLeastOnePlayableVideoTrack
- _exportURL
- unusedTrackID
- chapterMetadataGroupsBestMatchingPreferredLanguages:
- availableChapterLocales
- chapterMetadataGroupsWithTitleLocale:containingItemsWithCommonKeys:
- cancelLoading
- _figAsset
- _assetInspectorLoader
- _assetInspector
- _playbackItem
- preferredRate
- preferredVolume
- naturalTimeScale
- providesPreciseDurationAndTiming
- referenceRestrictions
- alternateTrackGroups
- trackGroups
- _firstTrackGroupWithMediaType:
- mediaSelectionGroups
- availableMetadataFormats
- metadataForFormat:
- tracksWithMediaCharacteristics:
- _serverHasDied
- isExportable
- isComposable
- _weakReference
- _comparisonToken
- statusOfValueForKey:
- _formatReader
- _absoluteURL
- audioAlternatesTrackGroup
- subtitleAlternatesTrackGroup
- availableMediaCharacteristicsWithMediaSelectionOptions
- _tracksDidChange
- tracksWithMediaCharacteristic:
- compatibleTrackForCompositionTrack:
- mediaSelectionGroupForMediaCharacteristic:
- lyrics
- trackReferences
- trackWithTrackID:
- preferredSoundCheckVolumeNormalization
- loadValuesAsynchronouslyForKeys:keysForCollectionKeys:completionHandler:
- _isStreaming
- isPlayable
- dealloc
- init
- isEqual:
- hash
- duration
- copyWithZone:
- valueForUndefinedKey:
- naturalSize
- tracksWithMediaType:
- statusOfValueForKey:error:
- loadValuesAsynchronouslyForKeys:completionHandler:
- hasProtectedContent
- isReadable
- creationDate
- isCompatibleWithSavedPhotosAlbum
- metadata
- preferredTransform
- commonMetadata
- tracks
@end
