@interface AVAssetTrack : NSObject
{
	id _track;
}

+ _hasMultipleEdits
+ _hasScaledEdits
+ preferredVolume
+ naturalTimeScale
+ availableMetadataFormats
+ metadataForFormat:
+ statusOfValueForKey:
+ _initWithAsset:trackID:
+ _initWithAsset:trackIndex:
+ hasMediaCharacteristics:
+ _initWithAsset:trackID:trackIndex:
+ playabilityValidationResult
+ isSelfContained
+ totalSampleDataLength
+ mediaCharacteristics
+ estimatedDataRate
+ extendedLanguageTag
+ segments
+ segmentForTrackTime:
+ samplePresentationTimeForTrackTime:
+ isExcludedFromAutoselectionInTrackGroup
+ associatedTracksOfType:
+ _firstAssociatedTrackWithAssociationType:
+ _pairedForcedOnlySubtitlesTrack
+ _trackReferences
+ _assetTrackInspector
+ _subtitleFormatDescriptionMatchesTextDisplayFlags:flagsMask:
+ minFrameDuration
+ _fallbackTrack
+ _followingTrackAmongTracks:
+ _mostCloselyAssociatedTrackAmongTracks:
+ availableTrackAssociationTypes
+ hasMediaCharacteristic:
+ trackID
+ isPlayable
+ loudnessInfo
+ dealloc
+ layer
+ init
+ isEqual:
+ hash
+ description
+ copyWithZone:
+ isEnabled
+ locale
+ dimensions
+ asset
+ languageCode
+ naturalSize
+ statusOfValueForKey:error:
+ formatDescriptions
+ loadValuesAsynchronouslyForKeys:completionHandler:
+ nominalFrameRate
+ timeRange
+ hasProtectedContent
+ metadata
+ preferredTransform
+ commonMetadata
+ mediaType
+ finalize
- _hasMultipleEdits
- _hasScaledEdits
- preferredVolume
- naturalTimeScale
- availableMetadataFormats
- metadataForFormat:
- statusOfValueForKey:
- _initWithAsset:trackID:
- _initWithAsset:trackIndex:
- hasMediaCharacteristics:
- _initWithAsset:trackID:trackIndex:
- playabilityValidationResult
- isSelfContained
- totalSampleDataLength
- mediaCharacteristics
- estimatedDataRate
- extendedLanguageTag
- segments
- segmentForTrackTime:
- samplePresentationTimeForTrackTime:
- isExcludedFromAutoselectionInTrackGroup
- associatedTracksOfType:
- _firstAssociatedTrackWithAssociationType:
- _pairedForcedOnlySubtitlesTrack
- _trackReferences
- _assetTrackInspector
- _subtitleFormatDescriptionMatchesTextDisplayFlags:flagsMask:
- minFrameDuration
- _fallbackTrack
- _followingTrackAmongTracks:
- _mostCloselyAssociatedTrackAmongTracks:
- availableTrackAssociationTypes
- hasMediaCharacteristic:
- trackID
- isPlayable
- loudnessInfo
- dealloc
- layer
- init
- isEqual:
- hash
- description
- copyWithZone:
- isEnabled
- locale
- dimensions
- asset
- languageCode
- naturalSize
- statusOfValueForKey:error:
- formatDescriptions
- loadValuesAsynchronouslyForKeys:completionHandler:
- nominalFrameRate
- timeRange
- hasProtectedContent
- metadata
- preferredTransform
- commonMetadata
- mediaType
- finalize
@end
