@interface AVURLAsset : AVAsset
{
	id _asset;
}

+ _finishLoadingCustomURLProviderRequestWithResponseProperties:context:
+ _handleURLRequest:
+ resourceLoader
+ _hasResourceLoaderDelegate
+ shouldMatchDataInCacheByURLPathComponentOnly
+ shouldMatchDataInCacheByURLWithoutQueryComponent
+ downloadDestinationURL
+ _shouldOptimizeAccessForLinearMoviePlayback
+ resolvedURL
+ assetCache
+ downloadToken
+ SHA1Digest
+ cacheKey
+ chapterMetadataGroupsBestMatchingPreferredLanguages:
+ _chapterGroupInfo
+ _addChapterMetadataItem:timeRange:toChapters:fromIndex:
+ availableChapterLocales
+ chapterMetadataGroupsWithTitleLocale:containingItemsWithCommonKeys:
+ cancelLoading
+ _addFigAssetNotifications
+ _removeFigAssetNotifications
+ _assetInspectorLoader
+ _assetInspector
+ _formatReader
+ _absoluteURL
+ _tracksDidChange
+ _setAssetInspectorLoader:
+ _tracks
+ _errorForFigNotificationPayload:key:
+ lyrics
+ dealloc
+ init
+ description
+ URL
+ initWithURL:options:
+ tracks
+ finalize
- _finishLoadingCustomURLProviderRequestWithResponseProperties:context:
- _handleURLRequest:
- resourceLoader
- _hasResourceLoaderDelegate
- shouldMatchDataInCacheByURLPathComponentOnly
- shouldMatchDataInCacheByURLWithoutQueryComponent
- downloadDestinationURL
- _shouldOptimizeAccessForLinearMoviePlayback
- resolvedURL
- assetCache
- downloadToken
- SHA1Digest
- cacheKey
- chapterMetadataGroupsBestMatchingPreferredLanguages:
- _chapterGroupInfo
- _addChapterMetadataItem:timeRange:toChapters:fromIndex:
- availableChapterLocales
- chapterMetadataGroupsWithTitleLocale:containingItemsWithCommonKeys:
- cancelLoading
- _addFigAssetNotifications
- _removeFigAssetNotifications
- _assetInspectorLoader
- _assetInspector
- _formatReader
- _absoluteURL
- _tracksDidChange
- _setAssetInspectorLoader:
- _tracks
- _errorForFigNotificationPayload:key:
- lyrics
- dealloc
- init
- description
- URL
- initWithURL:options:
- tracks
- finalize
@end
