@interface CAAnimation : NSObject
{
	pointer _attr;
	unsigned int _flags;
}

+ CAMLParser:setValue:forKey:
+ encodeWithCAMLWriter:
+ CAMLTypeForKey:
+ CA_copyRenderValue
+ setDefaultDuration:
+ beginTimeMode
+ setFrameInterval:
+ setBeginTimeMode:
+ isEnabled
+ setEnabled:
+ frameInterval
+ mutableCopyWithZone:
+ applyForTime:presentationObject:modelObject:
+ completionBlock
+ setCompletionBlock:
+ setAnimationID:
+ animationID
+ performCompletionBlock:
+ animationDidStartBlock
+ setAnimationDidStartBlock:
+ animationDidStopBlock
+ setAnimationDidStopBlock:
+ set_mapkit_ID:
+ _mapkit_ID
+ _mapkit_isScrollingAnimation
+ runActionForKey:object:arguments:
+ _setCARenderAnimation:layer:
+ _propertyFlagsForLayer:
+ shouldArchiveValueForKey:
+ removedOnCompletion
+ dealloc
+ initWithCoder:
+ encodeWithCoder:
+ setDelegate:
+ debugDescription
+ delegate
+ setSpeed:
+ duration
+ setValue:forKey:
+ setDuration:
+ valueForKey:
+ copyWithZone:
+ valueForKeyPath:
+ setFillMode:
+ setValue:forKeyPath:
+ setTimingFunction:
+ setBeginTime:
+ setRepeatCount:
+ setAutoreverses:
+ beginTime
+ speed
+ timeOffset
+ timingFunction
+ setRemovedOnCompletion:
+ setTimeOffset:
+ valueForUndefinedKey:
+ repeatDuration
+ setRepeatDuration:
+ setValue:forUndefinedKey:
+ repeatCount
+ autoreverses
+ fillMode
+ isRemovedOnCompletion
- CAMLParser:setValue:forKey:
- encodeWithCAMLWriter:
- CAMLTypeForKey:
- CA_copyRenderValue
- setDefaultDuration:
- beginTimeMode
- setFrameInterval:
- setBeginTimeMode:
- isEnabled
- setEnabled:
- frameInterval
- mutableCopyWithZone:
- applyForTime:presentationObject:modelObject:
- completionBlock
- setCompletionBlock:
- setAnimationID:
- animationID
- performCompletionBlock:
- animationDidStartBlock
- setAnimationDidStartBlock:
- animationDidStopBlock
- setAnimationDidStopBlock:
- set_mapkit_ID:
- _mapkit_ID
- _mapkit_isScrollingAnimation
- runActionForKey:object:arguments:
- _setCARenderAnimation:layer:
- _propertyFlagsForLayer:
- shouldArchiveValueForKey:
- removedOnCompletion
- dealloc
- initWithCoder:
- encodeWithCoder:
- setDelegate:
- debugDescription
- delegate
- setSpeed:
- duration
- setValue:forKey:
- setDuration:
- valueForKey:
- copyWithZone:
- valueForKeyPath:
- setFillMode:
- setValue:forKeyPath:
- setTimingFunction:
- setBeginTime:
- setRepeatCount:
- setAutoreverses:
- beginTime
- speed
- timeOffset
- timingFunction
- setRemovedOnCompletion:
- setTimeOffset:
- valueForUndefinedKey:
- repeatDuration
- setRepeatDuration:
- setValue:forUndefinedKey:
- repeatCount
- autoreverses
- fillMode
- isRemovedOnCompletion
@end
