@interface CALayer : NSObject
{
	struct _attr;
}

+ uiHasFilterWithName:
+ compareTextEffectsOrdering:
+ getRendererInfo:size:
+ momentOfInertia
+ coefficientOfRestitution
+ setMomentOfInertia:
+ setCoefficientOfRestitution:
+ setMass:
+ mass
+ velocityStretch
+ setBehaviors:
+ setVelocityStretch:
+ behaviors
+ setLights:
+ lights
+ acceptsLights
+ ambientReflectance
+ diffuseReflectance
+ specularReflectance
+ shininess
+ metallicity
+ setAcceptsLights:
+ setAmbientReflectance:
+ setDiffuseReflectance:
+ setSpecularReflectance:
+ setShininess:
+ setMetallicity:
+ meshTransform
+ layerDidBecomeVisible:
+ CAMLParser:setValue:forKey:
+ encodeWithCAMLWriter:
+ CAMLTypeForKey:
+ _renderLayerDefinesProperty:
+ _renderLayerPropertyAnimationFlags:
+ _copyRenderLayer:layerFlags:commitFlags:
+ _renderImageCopyFlags
+ ignoresHitTesting
+ allowsHitTesting
+ sortsSublayers
+ _prepareContext:
+ contentsTransform
+ drawsMipmapLevels
+ setSizeRequisition:
+ sizeRequisition
+ backgroundColorPhase
+ preloadsCache
+ allowsDisplayCompositing
+ allowsGroupBlending
+ hitTestsAsOpaque
+ literalContentsCenter
+ swapsMaskAndLayer
+ invertsShadow
+ shadowPathIsBounds
+ _didCommitLayer:
+ _canDisplayConcurrently
+ layoutIsActive
+ layerBeingDrawn
+ layerAtTime:
+ doubleSided
+ setAllowsHitTesting:
+ setLiteralContentsCenter:
+ setInvertsShadow:
+ setShadowPathIsBounds:
+ contentsOpaque
+ setSwapsMaskAndLayer:
+ setBackgroundColorPhase:
+ size
+ setHitTestsAsOpaque:
+ context
+ implicitAnimationForKeyPath:
+ hasBeenCommitted
+ setAllowsGroupBlending:
+ layoutBelowIfNeeded
+ setClearsContext:
+ clearsContext
+ clearHasBeenCommitted
+ invalidateContents
+ setContentsTransform:
+ isFrozen
+ ancestorSharedWithLayer:
+ needsLayoutOnGeometryChange
+ setNeedsLayoutOnGeometryChange:
+ setPreloadsCache:
+ setFrozen:
+ setFlipped:
+ opaque
+ setMeshTransform:
+ setSortsSublayers:
+ setContentsOpaque:
+ setAllowsDisplayCompositing:
+ isFlipped
+ hidden
+ setContentsChanged
+ acceleratesDrawing
+ setAcceleratesDrawing:
+ canDrawConcurrently
+ setCanDrawConcurrently:
+ regionBeingDrawn
+ isDescendantOf:
+ reloadValueForKeyPath:
+ _scrollPoint:fromLayer:
+ _scrollRect:fromLayer:
+ _visibleRectOfLayer:
+ visibleRect
+ scrollPoint:
+ scrollRectToVisible:
+ insertState:atIndex:
+ addState:
+ removeState:
+ stateWithName:
+ dependentStatesOfState:
+ stateTransitionFrom:to:
+ _mapkit_addAnimation:forKey:completion:
+ _mapKit_mapLayer
+ currentLayer
+ getPresentationValue:forValueKey:animationKey:removeAnimation:
+ getPresentationValue:forKey:removeAnimation:
+ _mapkit_removeAnimationImmediatelyForKey:
+ doubleBounds
+ setDoubleBounds:
+ setDoublePosition:
+ convertDoublePoint:fromLayer:
+ convertDoubleRect:toLayer:
+ doublePosition
+ convertDoublePoint:toLayer:
+ convertDoubleRect:fromLayer:
+ _gkDescriptionWithChildren:
+ _gkRecursiveDescription
+ _gkParentSublayerTransform
+ setActions:
+ modelLayer
+ contentsAreFlipped
+ shouldArchiveValueForKey:
+ _initWithReference:
+ minificationFilterBias
+ setMinificationFilterBias:
+ _renderBackgroundInContext:
+ _scheduleAnimationTimer
+ _cancelAnimationTimer
+ _renderForegroundInContext:
+ _renderSublayersInContext:
+ _renderBorderInContext:
+ drawsAsynchronously
+ _preferredSize
+ convertTime:toLayer:
+ backgroundFilters
+ setBackgroundFilters:
+ shadowPath
+ setDrawsAsynchronously:
+ setOpaque:
+ setNeedsDisplayOnBoundsChange:
+ release
+ retain
+ dealloc
+ setNeedsDisplay
+ bounds
+ setBackgroundColor:
+ initWithCoder:
+ setMask:
+ backgroundColor
+ encodeWithCoder:
+ setDelegate:
+ isHidden
+ setNeedsLayout
+ setHidden:
+ init
+ setFrame:
+ frame
+ setBounds:
+ retainCount
+ debugDescription
+ delegate
+ setStyle:
+ setSpeed:
+ duration
+ setValue:forKey:
+ setDuration:
+ valueForKey:
+ containsPoint:
+ style
+ setShadowColor:
+ setShadowOffset:
+ actionForKey:
+ affineTransform
+ setAffineTransform:
+ setMasksToBounds:
+ setRasterizationScale:
+ addSublayer:
+ setPosition:
+ animationKeys
+ animationForKey:
+ superlayer
+ convertPoint:toLayer:
+ convertPoint:fromLayer:
+ convertRect:toLayer:
+ convertRect:fromLayer:
+ transform
+ removeAnimationForKey:
+ contents
+ setTransform:
+ isOpaque
+ layoutIfNeeded
+ sublayers
+ valueForKeyPath:
+ addAnimation:forKey:
+ setName:
+ setFilters:
+ setFillMode:
+ setValue:forKeyPath:
+ setBeginTime:
+ setRepeatCount:
+ setAutoreverses:
+ presentationLayer
+ setMagnificationFilter:
+ setContentsCenter:
+ contentsCenter
+ setCompositingFilter:
+ mask
+ renderInContext:
+ cornerRadius
+ setCornerRadius:
+ position
+ needsLayout
+ removeFromSuperlayer
+ setSublayers:
+ setContentsGravity:
+ needsDisplayOnBoundsChange
+ contentsGravity
+ setContentsScaling:
+ setContentsRect:
+ contentsScale
+ setContentsScale:
+ setShouldRasterize:
+ setNeedsDisplayInRect:
+ needsDisplay
+ masksToBounds
+ opacity
+ setOpacity:
+ displayIfNeeded
+ convertTime:fromLayer:
+ beginTime
+ speed
+ timeOffset
+ filters
+ name
+ removeAllAnimations
+ shouldRasterize
+ rasterizationScale
+ setContents:
+ insertSublayer:above:
+ insertSublayer:below:
+ insertSublayer:atIndex:
+ setSublayerTransform:
+ anchorPoint
+ shadowOffset
+ setTimeOffset:
+ setAllowsGroupOpacity:
+ setAnchorPoint:
+ shadowColor
+ allowsGroupOpacity
+ setBorderWidth:
+ setBorderColor:
+ setShadowPath:
+ contentsScaling
+ compositingFilter
+ setEdgeAntialiasingMask:
+ _dealloc
+ valueForUndefinedKey:
+ allowsWeakReference
+ retainWeakReference
+ hitTest:
+ .cxx_construct
+ _display
+ setZPosition:
+ borderWidth
+ borderColor
+ initWithLayer:
+ setShadowOpacity:
+ setShadowRadius:
+ contentsRect
+ isDoubleSided
+ setDoubleSided:
+ shadowRadius
+ edgeAntialiasingMask
+ display
+ setMinificationFilter:
+ setAllowsEdgeAntialiasing:
+ isGeometryFlipped
+ setGeometryFlipped:
+ actions
+ preferredFrameSize
+ initWithBounds:
+ repeatDuration
+ setRepeatDuration:
+ allowsEdgeAntialiasing
+ shadowOpacity
+ minificationFilter
+ magnificationFilter
+ setValue:forUndefinedKey:
+ repeatCount
+ autoreverses
+ fillMode
+ replaceSublayer:with:
+ zPosition
+ anchorPointZ
+ setAnchorPointZ:
+ sublayerTransform
+ drawInContext:
+ layoutSublayers
- uiHasFilterWithName:
- compareTextEffectsOrdering:
- getRendererInfo:size:
- momentOfInertia
- coefficientOfRestitution
- setMomentOfInertia:
- setCoefficientOfRestitution:
- setMass:
- mass
- velocityStretch
- setBehaviors:
- setVelocityStretch:
- behaviors
- setLights:
- lights
- acceptsLights
- ambientReflectance
- diffuseReflectance
- specularReflectance
- shininess
- metallicity
- setAcceptsLights:
- setAmbientReflectance:
- setDiffuseReflectance:
- setSpecularReflectance:
- setShininess:
- setMetallicity:
- meshTransform
- layerDidBecomeVisible:
- CAMLParser:setValue:forKey:
- encodeWithCAMLWriter:
- CAMLTypeForKey:
- _renderLayerDefinesProperty:
- _renderLayerPropertyAnimationFlags:
- _copyRenderLayer:layerFlags:commitFlags:
- _renderImageCopyFlags
- ignoresHitTesting
- allowsHitTesting
- sortsSublayers
- _prepareContext:
- contentsTransform
- drawsMipmapLevels
- setSizeRequisition:
- sizeRequisition
- backgroundColorPhase
- preloadsCache
- allowsDisplayCompositing
- allowsGroupBlending
- hitTestsAsOpaque
- literalContentsCenter
- swapsMaskAndLayer
- invertsShadow
- shadowPathIsBounds
- _didCommitLayer:
- _canDisplayConcurrently
- layoutIsActive
- layerBeingDrawn
- layerAtTime:
- doubleSided
- setAllowsHitTesting:
- setLiteralContentsCenter:
- setInvertsShadow:
- setShadowPathIsBounds:
- contentsOpaque
- setSwapsMaskAndLayer:
- setBackgroundColorPhase:
- size
- setHitTestsAsOpaque:
- context
- implicitAnimationForKeyPath:
- hasBeenCommitted
- setAllowsGroupBlending:
- layoutBelowIfNeeded
- setClearsContext:
- clearsContext
- clearHasBeenCommitted
- invalidateContents
- setContentsTransform:
- isFrozen
- ancestorSharedWithLayer:
- needsLayoutOnGeometryChange
- setNeedsLayoutOnGeometryChange:
- setPreloadsCache:
- setFrozen:
- setFlipped:
- opaque
- setMeshTransform:
- setSortsSublayers:
- setContentsOpaque:
- setAllowsDisplayCompositing:
- isFlipped
- hidden
- setContentsChanged
- acceleratesDrawing
- setAcceleratesDrawing:
- canDrawConcurrently
- setCanDrawConcurrently:
- regionBeingDrawn
- isDescendantOf:
- reloadValueForKeyPath:
- _scrollPoint:fromLayer:
- _scrollRect:fromLayer:
- _visibleRectOfLayer:
- visibleRect
- scrollPoint:
- scrollRectToVisible:
- insertState:atIndex:
- addState:
- removeState:
- stateWithName:
- dependentStatesOfState:
- stateTransitionFrom:to:
- _mapkit_addAnimation:forKey:completion:
- _mapKit_mapLayer
- currentLayer
- getPresentationValue:forValueKey:animationKey:removeAnimation:
- getPresentationValue:forKey:removeAnimation:
- _mapkit_removeAnimationImmediatelyForKey:
- doubleBounds
- setDoubleBounds:
- setDoublePosition:
- convertDoublePoint:fromLayer:
- convertDoubleRect:toLayer:
- doublePosition
- convertDoublePoint:toLayer:
- convertDoubleRect:fromLayer:
- _gkDescriptionWithChildren:
- _gkRecursiveDescription
- _gkParentSublayerTransform
- setActions:
- modelLayer
- contentsAreFlipped
- shouldArchiveValueForKey:
- _initWithReference:
- minificationFilterBias
- setMinificationFilterBias:
- _renderBackgroundInContext:
- _scheduleAnimationTimer
- _cancelAnimationTimer
- _renderForegroundInContext:
- _renderSublayersInContext:
- _renderBorderInContext:
- drawsAsynchronously
- _preferredSize
- convertTime:toLayer:
- backgroundFilters
- setBackgroundFilters:
- shadowPath
- setDrawsAsynchronously:
- setOpaque:
- setNeedsDisplayOnBoundsChange:
- release
- retain
- dealloc
- setNeedsDisplay
- bounds
- setBackgroundColor:
- initWithCoder:
- setMask:
- backgroundColor
- encodeWithCoder:
- setDelegate:
- isHidden
- setNeedsLayout
- setHidden:
- init
- setFrame:
- frame
- setBounds:
- retainCount
- debugDescription
- delegate
- setStyle:
- setSpeed:
- duration
- setValue:forKey:
- setDuration:
- valueForKey:
- containsPoint:
- style
- setShadowColor:
- setShadowOffset:
- actionForKey:
- affineTransform
- setAffineTransform:
- setMasksToBounds:
- setRasterizationScale:
- addSublayer:
- setPosition:
- animationKeys
- animationForKey:
- superlayer
- convertPoint:toLayer:
- convertPoint:fromLayer:
- convertRect:toLayer:
- convertRect:fromLayer:
- transform
- removeAnimationForKey:
- contents
- setTransform:
- isOpaque
- layoutIfNeeded
- sublayers
- valueForKeyPath:
- addAnimation:forKey:
- setName:
- setFilters:
- setFillMode:
- setValue:forKeyPath:
- setBeginTime:
- setRepeatCount:
- setAutoreverses:
- presentationLayer
- setMagnificationFilter:
- setContentsCenter:
- contentsCenter
- setCompositingFilter:
- mask
- renderInContext:
- cornerRadius
- setCornerRadius:
- position
- needsLayout
- removeFromSuperlayer
- setSublayers:
- setContentsGravity:
- needsDisplayOnBoundsChange
- contentsGravity
- setContentsScaling:
- setContentsRect:
- contentsScale
- setContentsScale:
- setShouldRasterize:
- setNeedsDisplayInRect:
- needsDisplay
- masksToBounds
- opacity
- setOpacity:
- displayIfNeeded
- convertTime:fromLayer:
- beginTime
- speed
- timeOffset
- filters
- name
- removeAllAnimations
- shouldRasterize
- rasterizationScale
- setContents:
- insertSublayer:above:
- insertSublayer:below:
- insertSublayer:atIndex:
- setSublayerTransform:
- anchorPoint
- shadowOffset
- setTimeOffset:
- setAllowsGroupOpacity:
- setAnchorPoint:
- shadowColor
- allowsGroupOpacity
- setBorderWidth:
- setBorderColor:
- setShadowPath:
- contentsScaling
- compositingFilter
- setEdgeAntialiasingMask:
- _dealloc
- valueForUndefinedKey:
- allowsWeakReference
- retainWeakReference
- hitTest:
- .cxx_construct
- _display
- setZPosition:
- borderWidth
- borderColor
- initWithLayer:
- setShadowOpacity:
- setShadowRadius:
- contentsRect
- isDoubleSided
- setDoubleSided:
- shadowRadius
- edgeAntialiasingMask
- display
- setMinificationFilter:
- setAllowsEdgeAntialiasing:
- isGeometryFlipped
- setGeometryFlipped:
- actions
- preferredFrameSize
- initWithBounds:
- repeatDuration
- setRepeatDuration:
- allowsEdgeAntialiasing
- shadowOpacity
- minificationFilter
- magnificationFilter
- setValue:forUndefinedKey:
- repeatCount
- autoreverses
- fillMode
- replaceSublayer:with:
- zPosition
- anchorPointZ
- setAnchorPointZ:
- sublayerTransform
- drawInContext:
- layoutSublayers
@end
