@interface CalendarPreferences : NSObject
{
	BOOL _hideCalendarsInNCTodayView;
}

+ immediateAlarmCreation
+ viewedTimeZoneAutomatic
+ weekStart
+ simulatedCurrentDate
+ showWeekNumbers
+ setShowWeekNumbers:
+ _synchronizePreferences
+ _getNumberPreference:withDefaultValue:
+ _preferenceChangedInternally:
+ _getNumberPreference:
+ _setPreference:number:notificationName:
+ _getStringPreference:
+ _setPreference:stringValue:notificationName:forceSync:
+ _getPreference:defaultBoolValue:
+ _setPreference:boolValue:notificationName:
+ _getPreference:defaultArrayValue:
+ _setPreference:arrayValue:notificationName:forceSync:
+ setCalendarUUIDsExcludedFromNotifications:
+ calendarUUIDsExcludedFromNotifications
+ _preferenceChangedExternally:
+ setSimulatedCurrentDate:
+ setWeekStart:
+ lastViewMode
+ setLastViewMode:
+ lastViewedDate
+ setLastViewedDate:
+ lastSuspendTime
+ setLastSuspendTime:
+ showDebugGridOverlay
+ setShowDebugGridOverlay:
+ setImmediateAlarmCreation:
+ setViewedTimeZoneAutomatic:
+ requestSyncOnApplicationLaunch
+ setRequestSyncOnApplicationLaunch:
+ drawDebugViewColors
+ setDrawDebugViewColors:
+ usePickerStyleInlineEditorMenus
+ setUsePickerStyleInlineEditorMenus:
+ deselectedCalendarIDsFromCalendars:
+ setDeselectedCalendarIDs:
+ hideCalendarsInNCTodayView
+ showEventsInPhoneMonthView
+ setShowEventsInPhoneMonthView:
+ setNotificationEnabledCalendars:usingEventStore:entityType:
+ notificationEnabledCalendarsFromEventStore:entityType:
+ areAllCalendarsNotificationEnabledInEventStore:
+ setHideCalendarsInNCTodayView:
+ init
+ setSearchString:
+ searchString
- immediateAlarmCreation
- viewedTimeZoneAutomatic
- weekStart
- simulatedCurrentDate
- showWeekNumbers
- setShowWeekNumbers:
- _synchronizePreferences
- _getNumberPreference:withDefaultValue:
- _preferenceChangedInternally:
- _getNumberPreference:
- _setPreference:number:notificationName:
- _getStringPreference:
- _setPreference:stringValue:notificationName:forceSync:
- _getPreference:defaultBoolValue:
- _setPreference:boolValue:notificationName:
- _getPreference:defaultArrayValue:
- _setPreference:arrayValue:notificationName:forceSync:
- setCalendarUUIDsExcludedFromNotifications:
- calendarUUIDsExcludedFromNotifications
- _preferenceChangedExternally:
- setSimulatedCurrentDate:
- setWeekStart:
- lastViewMode
- setLastViewMode:
- lastViewedDate
- setLastViewedDate:
- lastSuspendTime
- setLastSuspendTime:
- showDebugGridOverlay
- setShowDebugGridOverlay:
- setImmediateAlarmCreation:
- setViewedTimeZoneAutomatic:
- requestSyncOnApplicationLaunch
- setRequestSyncOnApplicationLaunch:
- drawDebugViewColors
- setDrawDebugViewColors:
- usePickerStyleInlineEditorMenus
- setUsePickerStyleInlineEditorMenus:
- deselectedCalendarIDsFromCalendars:
- setDeselectedCalendarIDs:
- hideCalendarsInNCTodayView
- showEventsInPhoneMonthView
- setShowEventsInPhoneMonthView:
- setNotificationEnabledCalendars:usingEventStore:entityType:
- notificationEnabledCalendarsFromEventStore:entityType:
- areAllCalendarsNotificationEnabledInEventStore:
- setHideCalendarsInNCTodayView:
- init
- setSearchString:
- searchString
@end
