@interface CAMCameraRollSpec : NSObject
{

}

+ prepareAlbumViewControllerForReuse:withAlbum:inApplicationCameraViewController:
+ newAlbumNavigationControllerForAlbum:inApplicationCameraViewController:
- prepareAlbumViewControllerForReuse:withAlbum:inApplicationCameraViewController:
- newAlbumNavigationControllerForAlbum:inApplicationCameraViewController:
@end
