@interface CKConversation : NSObject
{
	id _recipients;
	id _name;
	id _messages;
	id _pendingMessages;
	id _placeholderMessage;
	id _chat;
	id _incomingTypingMessage;
	id _cachedPreferredService;
	unsigned int _limitToLoad;
	int _bulkMessageAddStack;
	char _cachedPreferredServiceError;
	char _downgradeState;
	struct _conversationFlags;
	id _pendingHandles;
	id _thumbnailImage;
	id _failedMessages;
}

+ thumbnail
+ regenerateThumbnail
+ __generateThumbnailOfDiameter:withRecipientImage:andOtherRecipient:
+ __messageOrderedABRecordIDs
+ __generateThumbnailOfDiameter:withRecordIDs:recipientCount:
+ _sms_canSendToRecipients:withAttachments:alertIfUnable:
+ _sms_supportsCharacterCountForAddresses:
+ _sms_willSendMMSByDefaultForAddresses:
+ _iMessage_canSendToRecipients:withAttachments:alertIfUnable:
+ _iMessage_supportsCharacterCountForAddresses:
+ recipientCount
+ groupID
+ dealloc
+ init
+ description
+ date
+ isEmpty
+ name
+ shortDescription
+ handles
+ uniqueIdentifier
+ thumbnailImage
+ copyForPendingConversation
+ shouldShowCharacterCount
+ isGroupConversation
+ setUnsentComposition:
+ markAllMessagesAsRead
+ chat
+ invalidatePreferredServiceCache
+ isPending
+ setPendingComposeRecipients:
+ hasUnreadMessages
+ canSendWithError:
+ serviceDisplayName
+ unsentComposition
+ displayNameForMediaObjects:subject:
+ setIgnoringTypingUpdates:
+ forceMMS
+ setForceMMS:
+ setLoadedMessageCount:completion:
+ newMessageWithComposition:addToConversation:
+ sendMessage:newComposition:
+ preferredService
+ pendingHandles
+ pendingEntities
+ canSendToRecipients:withAttachments:alertIfUnable:
+ canSendMessageComposition:error:
+ newMessageContentChangedWithComposition:
+ canAcceptMediaObjects:givenMediaObjects:
+ canAcceptMediaObject:givenMediaObjects:
+ latestMessage
+ deleteAllMessages
+ addPlaceholderMessageIfNeededWithDate:
+ acceptTransfer:
+ restrictMediaObjects
+ requestRecipientStatuses
+ initWithChat:updatesDisabled:
+ addMessage:
+ postChangedUpdate:
+ setUpdatesDisabled:quietly:
+ markAsStale
+ setPendingHandles:
+ reloadIfStale
+ compareBySequenceNumberAndDateDescending:
+ deleteAllMessagesAndRemoveGroup
+ previewText
+ outgoingBubbleColor
+ canAcceptMediaObjectType:givenMediaObjects:
+ pendingMessages
+ updateMessage:
+ resetPendingMessages
+ isDowngraded
+ isFromFilteredSender
+ setChat:
+ setUpdatesDisabled:
+ _handleItemsDidChangeNotification:
+ _handleChatPropertiesChangedNotification:
+ _cleanupMessages
+ _calculateDowngradeStateTimerFired
+ resetNameCaches
+ _CKMessageFromIMMessage:
+ limitToLoad
+ incomingTypingMessage
+ setIncomingTypingMessage:
+ _handleTypingIndicationMessage:
+ _existingMadridMessageForIMMessage:
+ _addCKMessageFromIMMessage:
+ _postNotification:forMessage:
+ removeMessage:postUpdate:
+ beginBulkMessageAdd
+ _handleChangedMessage:forQuery:
+ _handleRemovedMessage:
+ endBulkMessageAddForcePost:
+ downgradeStateDidChange
+ _beginBatchUpdates
+ _endBatchUpdates
+ loadAllMessages
+ _handlePreferredServiceChangedNotification:
+ _invalidateDowngradeState
+ _setupPreferredServiceChangeHandlers
+ _preferredServiceCheckWithServer:canSend:error:
+ _handleIsForThisConversation:
+ _clearTypingIndicatorsIfNecessary
+ _calculateDowngradeState
+ _consecutiveDowngradeAttemptsViaManualDowngrades:
+ _updateDowngradeState:checkAgainInterval:
+ _refreshMoreToLoadFlag
+ _postChangeUpdate:
+ removeAllMessages
+ _deleteAllMessagesAndRemoveGroup:
+ _messagesFromChat:
+ setLoadedMessages:
+ setLimitToLoad:
+ _setPlaceholderMessage:
+ latestIncomingMessage
+ placeholderMessage
+ canSendMessageWithParts:subject:onService:error:
+ canSendMessageWithParts:subject:error:
+ _IMMessageWithMessageParts:subject:date:isFinished:messageGUID:needsDataDetection:
+ newMessageWithComposition:guid:addToConversation:
+ _updateTypingIndicatorForComposition:
+ _accountIsOperational:forService:
+ _chatHasValidAccount:forService:
+ _targetChat:toService:newComposition:
+ _recordRecentContact
+ sendMessage:onService:newComposition:
+ _chatSupportsTypingIndicators
+ _targetChatToPreferredService:newComposition:
+ __rescindTypingIndicatorIfNecessary
+ __sendTypingIndicatorIfNecessary
+ preferredServiceWithCanSend:error:
+ recipientStrings
+ _nameForHandle:
+ _headerTitleForPendingMediaObjects:subject:onService:
+ _headerTitleForService:
+ hasUnreadiMessages
+ ckMessageWithGUID:
+ setRememberedKeyboard:
+ rememberedKeyboard
+ isIgnoringTypingUpdates
+ moreMessagesToLoad
+ updatesDisabled
+ removeMessage:
+ deleteMessages:
+ deleteMessage:
+ loadMoreMessages
+ canSendMessageWithMediaObjectTypes:
+ maxTrimDurationForMediaType:
+ newMessageWithComposition:
+ incomingTypingCKMessage
+ disclosureAtomStyle
+ sendDowngradePingForMessage:manualDowngrade:
+ failedMessages
+ unreadCount
+ isPlaceholder
+ messages
+ recipients
+ buttonColor
+ setThumbnailImage:
+ setRecipients:
+ recipient
+ resetCaches
- thumbnail
- regenerateThumbnail
- __generateThumbnailOfDiameter:withRecipientImage:andOtherRecipient:
- __messageOrderedABRecordIDs
- __generateThumbnailOfDiameter:withRecordIDs:recipientCount:
- _sms_canSendToRecipients:withAttachments:alertIfUnable:
- _sms_supportsCharacterCountForAddresses:
- _sms_willSendMMSByDefaultForAddresses:
- _iMessage_canSendToRecipients:withAttachments:alertIfUnable:
- _iMessage_supportsCharacterCountForAddresses:
- recipientCount
- groupID
- dealloc
- init
- description
- date
- isEmpty
- name
- shortDescription
- handles
- uniqueIdentifier
- thumbnailImage
- copyForPendingConversation
- shouldShowCharacterCount
- isGroupConversation
- setUnsentComposition:
- markAllMessagesAsRead
- chat
- invalidatePreferredServiceCache
- isPending
- setPendingComposeRecipients:
- hasUnreadMessages
- canSendWithError:
- serviceDisplayName
- unsentComposition
- displayNameForMediaObjects:subject:
- setIgnoringTypingUpdates:
- forceMMS
- setForceMMS:
- setLoadedMessageCount:completion:
- newMessageWithComposition:addToConversation:
- sendMessage:newComposition:
- preferredService
- pendingHandles
- pendingEntities
- canSendToRecipients:withAttachments:alertIfUnable:
- canSendMessageComposition:error:
- newMessageContentChangedWithComposition:
- canAcceptMediaObjects:givenMediaObjects:
- canAcceptMediaObject:givenMediaObjects:
- latestMessage
- deleteAllMessages
- addPlaceholderMessageIfNeededWithDate:
- acceptTransfer:
- restrictMediaObjects
- requestRecipientStatuses
- initWithChat:updatesDisabled:
- addMessage:
- postChangedUpdate:
- setUpdatesDisabled:quietly:
- markAsStale
- setPendingHandles:
- reloadIfStale
- compareBySequenceNumberAndDateDescending:
- deleteAllMessagesAndRemoveGroup
- previewText
- outgoingBubbleColor
- canAcceptMediaObjectType:givenMediaObjects:
- pendingMessages
- updateMessage:
- resetPendingMessages
- isDowngraded
- isFromFilteredSender
- setChat:
- setUpdatesDisabled:
- _handleItemsDidChangeNotification:
- _handleChatPropertiesChangedNotification:
- _cleanupMessages
- _calculateDowngradeStateTimerFired
- resetNameCaches
- _CKMessageFromIMMessage:
- limitToLoad
- incomingTypingMessage
- setIncomingTypingMessage:
- _handleTypingIndicationMessage:
- _existingMadridMessageForIMMessage:
- _addCKMessageFromIMMessage:
- _postNotification:forMessage:
- removeMessage:postUpdate:
- beginBulkMessageAdd
- _handleChangedMessage:forQuery:
- _handleRemovedMessage:
- endBulkMessageAddForcePost:
- downgradeStateDidChange
- _beginBatchUpdates
- _endBatchUpdates
- loadAllMessages
- _handlePreferredServiceChangedNotification:
- _invalidateDowngradeState
- _setupPreferredServiceChangeHandlers
- _preferredServiceCheckWithServer:canSend:error:
- _handleIsForThisConversation:
- _clearTypingIndicatorsIfNecessary
- _calculateDowngradeState
- _consecutiveDowngradeAttemptsViaManualDowngrades:
- _updateDowngradeState:checkAgainInterval:
- _refreshMoreToLoadFlag
- _postChangeUpdate:
- removeAllMessages
- _deleteAllMessagesAndRemoveGroup:
- _messagesFromChat:
- setLoadedMessages:
- setLimitToLoad:
- _setPlaceholderMessage:
- latestIncomingMessage
- placeholderMessage
- canSendMessageWithParts:subject:onService:error:
- canSendMessageWithParts:subject:error:
- _IMMessageWithMessageParts:subject:date:isFinished:messageGUID:needsDataDetection:
- newMessageWithComposition:guid:addToConversation:
- _updateTypingIndicatorForComposition:
- _accountIsOperational:forService:
- _chatHasValidAccount:forService:
- _targetChat:toService:newComposition:
- _recordRecentContact
- sendMessage:onService:newComposition:
- _chatSupportsTypingIndicators
- _targetChatToPreferredService:newComposition:
- __rescindTypingIndicatorIfNecessary
- __sendTypingIndicatorIfNecessary
- preferredServiceWithCanSend:error:
- recipientStrings
- _nameForHandle:
- _headerTitleForPendingMediaObjects:subject:onService:
- _headerTitleForService:
- hasUnreadiMessages
- ckMessageWithGUID:
- setRememberedKeyboard:
- rememberedKeyboard
- isIgnoringTypingUpdates
- moreMessagesToLoad
- updatesDisabled
- removeMessage:
- deleteMessages:
- deleteMessage:
- loadMoreMessages
- canSendMessageWithMediaObjectTypes:
- maxTrimDurationForMediaType:
- newMessageWithComposition:
- incomingTypingCKMessage
- disclosureAtomStyle
- sendDowngradePingForMessage:manualDowngrade:
- failedMessages
- unreadCount
- isPlaceholder
- messages
- recipients
- buttonColor
- setThumbnailImage:
- setRecipients:
- recipient
- resetCaches
@end
