@interface CKIMMessage : NSObject
{
	id _date;
	id _conversation;
	id _imMessage;
	id _parts;
	long long _partCount;
	float _cachedPercentComplete;
	struct _messageFlags;
}

+ service
+ rowID
+ sequenceNumber
+ hasAttachments
+ dealloc
+ isEqual:
+ description
+ percentComplete
+ date
+ compare:
+ sender
+ url
+ subject
+ conversation
+ IMMessage
+ setConversation:
+ isOutgoing
+ initWithIMMessage:
+ postMessageReceivedIfNecessary
+ isRead
+ previewText
+ outgoingBubbleColor
+ shouldUseSeparateSubject
+ wantsSendStatus
+ failedSend
+ hasBeenSent
+ isFromMe
+ _parseIMMessagePartsWithTextProcessingBlock:fileTransferProcessingBlock:
+ _loadCounts
+ pendingCount
+ totalMessageCount
+ timeRead
+ _resetData
+ failedSendCount
+ sentCount
+ isDelivered
+ partiallyFailedSend
+ timeDelivered
+ isiMessage
+ loadParts
+ parts
+ _rawPreviewText
+ attachmentText:
+ messagePartCount
+ messagePartAtIndex:
+ setIMMessage:
+ isSMS
+ deleteMessageParts:
+ resetParts
+ isFromDowngrading
+ setIsFromDowngrading:
+ isWaitingForDelivery
+ isFromFilteredSender
+ supportsDeliveryReceipts
+ isToEmailAddress
+ shouldPlayReceivedTone
+ initPlaceholderWithDate:
+ messageCount
+ markAsRead
+ pending
+ updateMessageCompleteQuietly
+ guid
+ isPlaceholder
+ recipients
+ address
+ error
+ isTypingIndicator
- service
- rowID
- sequenceNumber
- hasAttachments
- dealloc
- isEqual:
- description
- percentComplete
- date
- compare:
- sender
- url
- subject
- conversation
- IMMessage
- setConversation:
- isOutgoing
- initWithIMMessage:
- postMessageReceivedIfNecessary
- isRead
- previewText
- outgoingBubbleColor
- shouldUseSeparateSubject
- wantsSendStatus
- failedSend
- hasBeenSent
- isFromMe
- _parseIMMessagePartsWithTextProcessingBlock:fileTransferProcessingBlock:
- _loadCounts
- pendingCount
- totalMessageCount
- timeRead
- _resetData
- failedSendCount
- sentCount
- isDelivered
- partiallyFailedSend
- timeDelivered
- isiMessage
- loadParts
- parts
- _rawPreviewText
- attachmentText:
- messagePartCount
- messagePartAtIndex:
- setIMMessage:
- isSMS
- deleteMessageParts:
- resetParts
- isFromDowngrading
- setIsFromDowngrading:
- isWaitingForDelivery
- isFromFilteredSender
- supportsDeliveryReceipts
- isToEmailAddress
- shouldPlayReceivedTone
- initPlaceholderWithDate:
- messageCount
- markAsRead
- pending
- updateMessageCompleteQuietly
- guid
- isPlaceholder
- recipients
- address
- error
- isTypingIndicator
@end
