@interface CKTranscriptController : UIViewController
{
	id _conversation;
	id _navItem;
	id _statusBar;
	id _actionItem;
	id _clearAllItem;
	id _backPlacard;
	id _entryView;
	id _composeDelegate;
	id _typingIndicatorForSendAnimation;
	id _scrollBlock;
	id _presetMessageParts;
	id _newCompositionAddresses;
	id _serviceAvailabilityKey;
	id _newComposition;
	id _textMessageEncodingInfo;
	id _audioTrimController;
	id _videoTrimController;
	long long _storedStatusBarStyle;
	int _setupState;
	BOOL _dimmed;
	id _loggingTapGestureRecognizer;
	id _alertViewHandler;
	id _autorotateDisabledWindow;
	id _trimAlert;
	bit[1] _locked;
	bit[1] _visible;
	bit[1] _viewNeedsSetup;
	bit[1] _newRecipient;
	bit[1] _sending;
	bit[1] _transitioningToTranscript;
	bit[1] _entryViewCanAcceptFocus;
	bit[1] _isAnimatingMessageSend;
	bit[1] _entryViewWasActiveBeforeEdit;
	bit[1] _entryViewWasActiveBeforePushingViewController;
	bit[1] _entryViewWasActiveBeforeNewComposeThrow;
	bit[1] _entryViewWasActiveBeforeSwitchingConversations;
	bit[1] _recipientSelectionViewWasActiveBeforeFirstResponderChange;
	bit[1] _automaticKeyboardWasDisabled;
	bit[1] _togglingEditing;
	bit[1] _keyboardUndocked;
	bit[1] _suspendScrollDueToMediaViewing;
	bit[1] _triedToResetEntryViewSizeWhileNotInAWindow;
	bit[1] _triedToResetOverlayViewSizeWhileNotInAWindow;
	bit[1] _preparingForResume;
	bit[1] _appeared;
	bit[1] _appearing;
	bit[1] _settingConversation;
	bit[1] _needsTransitionToFullTranscript;
	unsigned int _transcriptNeedsUpdate;
	bit[1] _storedStatusBarIsHidden;
	id _actionsToolbar;
	BOOL _canSafelyDismissImagePicker;
	struct _transcriptAreaInsets;
	double _transcriptTableBottomOffset;
	struct _keyboardScreenFrame;
	struct _keyboardScreenFrameWithoutAccessoryView;
	id _keyboardNotification;
	BOOL _showingKeyboard;
	BOOL _hidingKeyboard;
	BOOL _keyboardInteractionCancelled;
	long long _pendingInterfaceOrientation;
	BOOL _inRotation;
	BOOL _willRotateView;
	BOOL _shouldAdjustTranscriptOffsetForRotation;
	BOOL _didCancel;
	id _initialSystemKeyboardID;
	id _mediaController;
	id _previewController;
	BOOL _safeToMarkAsRead;
	BOOL _hasPrepopulatedRecipients;
	id _collectionViewController;
	id _recipientSelectionController;
	id _transcriptHeaderViewController;
	id _throwAnimationEnforcementView;
	id _throwAnimationSnapshotView;
	id _throwBalloonViews;
	id _throwIntermediateFrames;
	id _throwEndFrames;
}

@end
