@interface CKUIBehavior : NSObject
{
	double _bubbleIndentationDuringEditMode;
}

+ lightGrayColor
+ usesPopovers
+ recipientTextColorForColorType:
+ canAccessCoreRecents
+ shouldBackfillTranscript
+ entryFieldElementPadding
+ balloonTextFont
+ transcriptPortraitWidth
+ characterCountFont
+ entryFieldLineFragmentPadding
+ entryFieldBackgroundColor
+ entryFieldDividerColor
+ sendButtonColorForColorType:
+ photoButtonColor
+ entryFieldGrayColor
+ dimmingViewBackgroundColor
+ transcriptBackgroundColor
+ lowClearanceInLandscape
+ splitViewEnabled
+ balloonMaskSize
+ balloonMaxWidthForOrientation:
+ bottomTranscriptSpace
+ defaultConversationViewingMessageCount
+ updateTranscriptInsetsAnimationDuration
+ resizeMessageEntryViewAnimationDuration
+ shouldShowSendProgressIndicator
+ transcriptSeparatorColor
+ forwardImage
+ cameraIsWhitelisted
+ photosIsWhitelisted
+ balloonColorsForColorType:
+ transcriptBoldTextFont
+ transcriptDrawerOverlap
+ transcriptDrawerWidth
+ statusTranscriptInsets
+ conversationListRowHeight
+ conversationListDateFont
+ conversationListSenderFont
+ conversationListSummaryFont
+ showsChevronImage
+ chevronImage
+ topConversationListSpace
+ senderSummaryConversationListSpace
+ bottomConversationListSpace
+ conversationListContactImageDiameter
+ showPendingInConversationList
+ usesPersistentConversationSelection
+ isSupportedInterfaceOrientation:
+ selectNewConversationOnDeletion
+ shouldDimTranscript
+ transcriptContactImageDiameter
+ transcriptTextFont
+ transcriptTextColor
+ documentIconAlignmentRectInsets
+ skinnyBalloonMaskCapInsets
+ balloonMaskCapInsets
+ balloonMaskAlignmentRectInsets
+ balloonMaskFrameInsets
+ balloonSubjectFont
+ balloonTextColorForColorType:
+ supportsTypingIndicatorAnimation
+ canAccessPhotos
+ presentsQuickLookController
+ presentsReaderController
+ thumbnailFillSizeForImageSize:
+ minimumPlayButtonInsets
+ balloonMaskTailWidth
+ attachmentBalloonSize
+ errorDocumentIcon
+ genericDocumentIcon
+ timestampDateFormatter
+ previewTitleFont
+ chevronImageForColorType:
+ previewTitleBarHeight
+ useContactPhotosInConversationList
+ shouldShowDisclosureChevronInRecipientAtoms
+ leftSplitPaneWidthForUIInterfaceOrientation:
+ madridRegistrationShowsSplashScreen
+ canAccessContacts
+ _transcriptAnimationScaleFactor
+ gray_recipientTextColor
+ green_recipientTextColor
+ blue_recipientTextColor
+ siri_recipientTextColor
+ red_recipientTextColor
+ green_balloonColors
+ blue_balloonColors
+ siri_balloonColors
+ untailedPreviewFillSizeForImageSize:
+ balloonTranscriptInsets
+ shouldShowContactPhotos
+ contactPhotoTranscriptInsets
+ contactPhotoBalloonMargin
+ timestampBodyLeading
+ timestampBodyLeadingFraction:
+ balloonBalloonTranscriptSpace:
+ gray_balloonColors
+ red_balloonColors
+ gray_unfilledBalloonColor
+ green_unfilledBalloonColor
+ blue_unfilledBalloonColor
+ siri_unfilledBalloonColor
+ red_unfilledBalloonColor
+ gray_balloonTextColor
+ green_balloonTextColor
+ blue_balloonTextColor
+ siri_balloonTextColor
+ red_balloonTextColor
+ gray_balloonTextLinkColor
+ green_balloonTextLinkColor
+ blue_balloonTextLinkColor
+ siri_balloonTextLinkColor
+ red_balloonTextLinkColor
+ gray_backgroundBalloonColor
+ green_backgroundBalloonColor
+ blue_backgroundBalloonColor
+ siri_backgroundBalloonColor
+ red_backgroundBalloonColor
+ gray_balloonOverlayColor
+ green_balloonOverlayColor
+ blue_balloonOverlayColor
+ siri_balloonOverlayColor
+ red_balloonOverlayColor
+ skinnyBalloonMaskSize
+ skinnyBalloonWidthDifference
+ rightBalloonMaxWidth
+ leftBalloonMaxWidth
+ gray_sendButtonColor
+ green_sendButtonColor
+ blue_sendButtonColor
+ siri_sendButtonColor
+ red_sendButtonColor
+ gray_chevronImage
+ green_chevronImage
+ blue_chevronImage
+ siri_chevronImage
+ red_chevronImage
+ systemGrayChevronImage
+ whiteChevronImage
+ appTintColor
+ conversationListSenderBodyLeading
+ conversationListSummaryBodyLeading
+ showTranscriptButtonsInNavigationBar
+ defaultConversationSummaryMessageCount
+ madridRegistrationAppearanceStyle
+ madridRegistrationShowsSplashScreenOnSignin
+ phoneIsWhitelisted
+ faceTimeVideoIsWhitelisted
+ faceTimeAudioIsWhitelisted
+ mailIsWhitelisted
+ returnKeySendsMessage
+ usesScrollGestureToHideKeyboard
+ usesDistanceToDetermineWhetherToHideKeyboard
+ usesVelocityDirectionToDetermineWhetherToHideKeyboard
+ velocityThresholdForHidingKeyboard
+ escapeVelocityForHidingKeyboard
+ scrollToHideKeyboardGestureThreshold
+ shouldSetConversationKeyboardOnSearchBeginEnd
+ isN9xScreen
+ fadeInBubbleAnimationDuration
+ scrollInNewMessageAnimationDuration
+ throwMessageAnimationDuration
+ editingTransitionAnimationDuration
+ selectNewConversationOnStateRestore
+ presentForwardingUIModally
+ conversationListMultipleContactsImageDiameter
+ shouldHomogenizeAtomsForPreferredService
+ collapsedRecipientListLeftPadding
+ shouldAutomaticallyCheckAvailabilityOfAlternateAddresses
+ shouldRefreshAlternateAddressesSheet
+ recipientOverlaySingleLineContentHeight
+ transcriptHeaderTextFont
+ mapThumbnailFillSize
+ isAccessibilityPreferredContentSizeCategory
+ spaceBetweenEditToolbarButtons
+ readerFont
+ transcriptStatusParagraphStyle
+ transcriptBoldTextAlignmentInsets
+ transcriptBoldTextHeight
+ entityTranscriptInsets
+ timestampTranscriptInsets
+ serviceTranscriptInsets
+ invalidateTranscriptDrawerWidth
+ smallTranscriptSpace
+ mediumTranscriptSpace
+ largeTranscriptSpace
+ topTranscriptSpace
+ unfilledBalloonColorForColorType:
+ balloonTextLinkColorForColorType:
+ backgroundBalloonColorForColorType:
+ balloonOverlayColorForColorType:
+ attachmentBalloonActionColor
+ attachmentBalloonTextColor
+ balloonTextLineHeight
+ balloonMaskFrameCapInsets
+ supportsPassbookAttachments
+ documentIconSize
+ textDocumentIcon
+ conversationListDateBodyLeading
+ dimsTranscriptWhileEditingConversations
+ conversationCacheSize
+ conversationListDefaultPNG
+ transcriptDefaultPNG
+ bubbleIndentationDuringEditMode
- lightGrayColor
- usesPopovers
- recipientTextColorForColorType:
- canAccessCoreRecents
- shouldBackfillTranscript
- entryFieldElementPadding
- balloonTextFont
- transcriptPortraitWidth
- characterCountFont
- entryFieldLineFragmentPadding
- entryFieldBackgroundColor
- entryFieldDividerColor
- sendButtonColorForColorType:
- photoButtonColor
- entryFieldGrayColor
- dimmingViewBackgroundColor
- transcriptBackgroundColor
- lowClearanceInLandscape
- splitViewEnabled
- balloonMaskSize
- balloonMaxWidthForOrientation:
- bottomTranscriptSpace
- defaultConversationViewingMessageCount
- updateTranscriptInsetsAnimationDuration
- resizeMessageEntryViewAnimationDuration
- shouldShowSendProgressIndicator
- transcriptSeparatorColor
- forwardImage
- cameraIsWhitelisted
- photosIsWhitelisted
- balloonColorsForColorType:
- transcriptBoldTextFont
- transcriptDrawerOverlap
- transcriptDrawerWidth
- statusTranscriptInsets
- conversationListRowHeight
- conversationListDateFont
- conversationListSenderFont
- conversationListSummaryFont
- showsChevronImage
- chevronImage
- topConversationListSpace
- senderSummaryConversationListSpace
- bottomConversationListSpace
- conversationListContactImageDiameter
- showPendingInConversationList
- usesPersistentConversationSelection
- isSupportedInterfaceOrientation:
- selectNewConversationOnDeletion
- shouldDimTranscript
- transcriptContactImageDiameter
- transcriptTextFont
- transcriptTextColor
- documentIconAlignmentRectInsets
- skinnyBalloonMaskCapInsets
- balloonMaskCapInsets
- balloonMaskAlignmentRectInsets
- balloonMaskFrameInsets
- balloonSubjectFont
- balloonTextColorForColorType:
- supportsTypingIndicatorAnimation
- canAccessPhotos
- presentsQuickLookController
- presentsReaderController
- thumbnailFillSizeForImageSize:
- minimumPlayButtonInsets
- balloonMaskTailWidth
- attachmentBalloonSize
- errorDocumentIcon
- genericDocumentIcon
- timestampDateFormatter
- previewTitleFont
- chevronImageForColorType:
- previewTitleBarHeight
- useContactPhotosInConversationList
- shouldShowDisclosureChevronInRecipientAtoms
- leftSplitPaneWidthForUIInterfaceOrientation:
- madridRegistrationShowsSplashScreen
- canAccessContacts
- _transcriptAnimationScaleFactor
- gray_recipientTextColor
- green_recipientTextColor
- blue_recipientTextColor
- siri_recipientTextColor
- red_recipientTextColor
- green_balloonColors
- blue_balloonColors
- siri_balloonColors
- untailedPreviewFillSizeForImageSize:
- balloonTranscriptInsets
- shouldShowContactPhotos
- contactPhotoTranscriptInsets
- contactPhotoBalloonMargin
- timestampBodyLeading
- timestampBodyLeadingFraction:
- balloonBalloonTranscriptSpace:
- gray_balloonColors
- red_balloonColors
- gray_unfilledBalloonColor
- green_unfilledBalloonColor
- blue_unfilledBalloonColor
- siri_unfilledBalloonColor
- red_unfilledBalloonColor
- gray_balloonTextColor
- green_balloonTextColor
- blue_balloonTextColor
- siri_balloonTextColor
- red_balloonTextColor
- gray_balloonTextLinkColor
- green_balloonTextLinkColor
- blue_balloonTextLinkColor
- siri_balloonTextLinkColor
- red_balloonTextLinkColor
- gray_backgroundBalloonColor
- green_backgroundBalloonColor
- blue_backgroundBalloonColor
- siri_backgroundBalloonColor
- red_backgroundBalloonColor
- gray_balloonOverlayColor
- green_balloonOverlayColor
- blue_balloonOverlayColor
- siri_balloonOverlayColor
- red_balloonOverlayColor
- skinnyBalloonMaskSize
- skinnyBalloonWidthDifference
- rightBalloonMaxWidth
- leftBalloonMaxWidth
- gray_sendButtonColor
- green_sendButtonColor
- blue_sendButtonColor
- siri_sendButtonColor
- red_sendButtonColor
- gray_chevronImage
- green_chevronImage
- blue_chevronImage
- siri_chevronImage
- red_chevronImage
- systemGrayChevronImage
- whiteChevronImage
- appTintColor
- conversationListSenderBodyLeading
- conversationListSummaryBodyLeading
- showTranscriptButtonsInNavigationBar
- defaultConversationSummaryMessageCount
- madridRegistrationAppearanceStyle
- madridRegistrationShowsSplashScreenOnSignin
- phoneIsWhitelisted
- faceTimeVideoIsWhitelisted
- faceTimeAudioIsWhitelisted
- mailIsWhitelisted
- returnKeySendsMessage
- usesScrollGestureToHideKeyboard
- usesDistanceToDetermineWhetherToHideKeyboard
- usesVelocityDirectionToDetermineWhetherToHideKeyboard
- velocityThresholdForHidingKeyboard
- escapeVelocityForHidingKeyboard
- scrollToHideKeyboardGestureThreshold
- shouldSetConversationKeyboardOnSearchBeginEnd
- isN9xScreen
- fadeInBubbleAnimationDuration
- scrollInNewMessageAnimationDuration
- throwMessageAnimationDuration
- editingTransitionAnimationDuration
- selectNewConversationOnStateRestore
- presentForwardingUIModally
- conversationListMultipleContactsImageDiameter
- shouldHomogenizeAtomsForPreferredService
- collapsedRecipientListLeftPadding
- shouldAutomaticallyCheckAvailabilityOfAlternateAddresses
- shouldRefreshAlternateAddressesSheet
- recipientOverlaySingleLineContentHeight
- transcriptHeaderTextFont
- mapThumbnailFillSize
- isAccessibilityPreferredContentSizeCategory
- spaceBetweenEditToolbarButtons
- readerFont
- transcriptStatusParagraphStyle
- transcriptBoldTextAlignmentInsets
- transcriptBoldTextHeight
- entityTranscriptInsets
- timestampTranscriptInsets
- serviceTranscriptInsets
- invalidateTranscriptDrawerWidth
- smallTranscriptSpace
- mediumTranscriptSpace
- largeTranscriptSpace
- topTranscriptSpace
- unfilledBalloonColorForColorType:
- balloonTextLinkColorForColorType:
- backgroundBalloonColorForColorType:
- balloonOverlayColorForColorType:
- attachmentBalloonActionColor
- attachmentBalloonTextColor
- balloonTextLineHeight
- balloonMaskFrameCapInsets
- supportsPassbookAttachments
- documentIconSize
- textDocumentIcon
- conversationListDateBodyLeading
- dimsTranscriptWhileEditingConversations
- conversationCacheSize
- conversationListDefaultPNG
- transcriptDefaultPNG
- bubbleIndentationDuringEditMode
@end
