@interface CNContact : NSObject
{
	pointer _record;
	pointer _originalRecord;
	pointer _source;
	pointer _addressBook;
	id _linkedContacts;
	BOOL _unified;
	unsigned int _recordType;
	id _identifier;
}

+ initWithRecord:
+ hasValidRecordID
+ linkedContacts
+ setLinkedContacts:
+ isUnknown
+ maximumNumberOfValuesForProperty:
+ supportedLabelsForProperty:
+ supportsInstantMessageService
+ originalRecord
+ deleteContact
+ photoThumbnail
+ personName
+ contactType
+ organizationName
+ phoneticFullName
+ jobTitle
+ departmentName
+ largestAvailablePhotoAndCropRect:
+ removePhoto
+ setImageData:forFormat:cropRect:
+ isUnified
+ preferredContactForPhoto
+ largestAvailablePhoto
+ phoneNumbers
+ reloadRecord
+ givenName
+ primarySourceName
+ supportsCustomLabelsForProperty:
+ recordType
+ localizedNameForProperty:
+ isPreferredForPhoto
+ isPreferredForName
+ setPreferredForPhoto:
+ setPreferredForName:
+ vCardRepresentation
+ postalAddresses
+ initWithRecord:unify:
+ isEqualToContact:includeIdentifiers:
+ _stringValueForProperty:
+ _labelledValuesForProperty:valueFromABValue:
+ _labelledStringValuesForProperty:
+ _labeledValueForSoundIdentifier:
+ _CNLabelFromABLabel:
+ isEqualToContact:
+ hasLinkedContacts
+ middleName
+ previousFamilyName
+ phoneticGivenName
+ phoneticMiddleName
+ phoneticFamilyName
+ birthday
+ note
+ nameOrder
+ preferredContactForName
+ urlAddresses
+ dates
+ instantMessageAddresses
+ relatedNames
+ socialProfiles
+ ringtone
+ textTone
+ isFacebook
+ dealloc
+ isEqual:
+ hash
+ description
+ copyWithZone:
+ identifier
+ familyName
+ source
+ setSource:
+ displayName
+ mutableCopyWithZone:
+ _squareCropRectForSize:
+ _squareImage:
+ emailAddresses
+ setPhoto:
+ fullName
+ addressBook
+ recordID
+ namePrefix
+ nameSuffix
+ setAddressBook:
+ record
+ isReadonly
+ nickname
- initWithRecord:
- hasValidRecordID
- linkedContacts
- setLinkedContacts:
- isUnknown
- maximumNumberOfValuesForProperty:
- supportedLabelsForProperty:
- supportsInstantMessageService
- originalRecord
- deleteContact
- photoThumbnail
- personName
- contactType
- organizationName
- phoneticFullName
- jobTitle
- departmentName
- largestAvailablePhotoAndCropRect:
- removePhoto
- setImageData:forFormat:cropRect:
- isUnified
- preferredContactForPhoto
- largestAvailablePhoto
- phoneNumbers
- reloadRecord
- givenName
- primarySourceName
- supportsCustomLabelsForProperty:
- recordType
- localizedNameForProperty:
- isPreferredForPhoto
- isPreferredForName
- setPreferredForPhoto:
- setPreferredForName:
- vCardRepresentation
- postalAddresses
- initWithRecord:unify:
- isEqualToContact:includeIdentifiers:
- _stringValueForProperty:
- _labelledValuesForProperty:valueFromABValue:
- _labelledStringValuesForProperty:
- _labeledValueForSoundIdentifier:
- _CNLabelFromABLabel:
- isEqualToContact:
- hasLinkedContacts
- middleName
- previousFamilyName
- phoneticGivenName
- phoneticMiddleName
- phoneticFamilyName
- birthday
- note
- nameOrder
- preferredContactForName
- urlAddresses
- dates
- instantMessageAddresses
- relatedNames
- socialProfiles
- ringtone
- textTone
- isFacebook
- dealloc
- isEqual:
- hash
- description
- copyWithZone:
- identifier
- familyName
- source
- setSource:
- displayName
- mutableCopyWithZone:
- _squareCropRectForSize:
- _squareImage:
- emailAddresses
- setPhoto:
- fullName
- addressBook
- recordID
- namePrefix
- nameSuffix
- setAddressBook:
- record
- isReadonly
- nickname
@end
