@interface CNFConferenceController : NSObject
{
	BOOL _isConnected;
	long long _type;
	id _activeAVChat;
	id _avChatList;
}

+ havePreviouslyConferencedWithID:
+ _countryCode
+ dealloc
+ init
+ type
+ remoteParticipant
+ localCameraAspectRatioForOrientation:
+ faceTimeMuted
+ inFaceTime
+ _chat:isCrossInvitationWithChat:
+ isFullConferenceCapable
+ avChatStateChanged:
+ iChatAgentDisconnected
+ iChatAgentConnected
+ faceTimeHistoryChanged:
+ connectToService
+ disconnectFromService
+ _imHandleFromID:countryCode:
+ faceTimeIsAvailable
+ _imHandleFromURL:
+ sendFaceTimeInvitationTo:isVideo:
+ isInvitationListener
+ remoteCameraOrientation
+ remoteCameraType
+ localCameraType
+ endFaceTime
+ _activeChatExists
+ _handleEndAVChat:withReason:error:
+ faceTimeInvitationExists
+ activeFaceTimeCallExists
+ _cleanUpAfterAVChat
+ _handleConferenceConnecting:
+ _handleConferenceEnded:withReason:withError:
+ _handleAVChatStateChangedToState:
+ activationState
+ activateFaceTime
+ setNeedsPushReliability:
+ validFaceTimeAccountExistsForDestinationID:
+ canSendFaceTimeInvitationTo:
+ sendFaceTimeInvitationTo:
+ avChatForConferenceID:
+ acceptFaceTimeInvitationForChat:
+ declineFaceTimeInvitationForChat:
+ setFaceTimeMuted:
+ faceTimePaused
+ setFaceTimePaused:
+ remoteCameraAspectRatio
+ activeFaceTimeAudioCallExists
+ currentCallRemoteUserId
+ currentCallConnectedDate
+ invitedToIMAVChat:
+ inviteFailedFromIMHandle:reason:
+ avChat
+ _initWithType:
- havePreviouslyConferencedWithID:
- _countryCode
- dealloc
- init
- type
- remoteParticipant
- localCameraAspectRatioForOrientation:
- faceTimeMuted
- inFaceTime
- _chat:isCrossInvitationWithChat:
- isFullConferenceCapable
- avChatStateChanged:
- iChatAgentDisconnected
- iChatAgentConnected
- faceTimeHistoryChanged:
- connectToService
- disconnectFromService
- _imHandleFromID:countryCode:
- faceTimeIsAvailable
- _imHandleFromURL:
- sendFaceTimeInvitationTo:isVideo:
- isInvitationListener
- remoteCameraOrientation
- remoteCameraType
- localCameraType
- endFaceTime
- _activeChatExists
- _handleEndAVChat:withReason:error:
- faceTimeInvitationExists
- activeFaceTimeCallExists
- _cleanUpAfterAVChat
- _handleConferenceConnecting:
- _handleConferenceEnded:withReason:withError:
- _handleAVChatStateChangedToState:
- activationState
- activateFaceTime
- setNeedsPushReliability:
- validFaceTimeAccountExistsForDestinationID:
- canSendFaceTimeInvitationTo:
- sendFaceTimeInvitationTo:
- avChatForConferenceID:
- acceptFaceTimeInvitationForChat:
- declineFaceTimeInvitationForChat:
- setFaceTimeMuted:
- faceTimePaused
- setFaceTimePaused:
- remoteCameraAspectRatio
- activeFaceTimeAudioCallExists
- currentCallRemoteUserId
- currentCallConnectedDate
- invitedToIMAVChat:
- inviteFailedFromIMHandle:reason:
- avChat
- _initWithType:
@end
