@interface CNFRegAppearanceController : NSObject
{

}

+ modalPresentationStyle
+ tableBackgroundColor
+ tableCellBackgroundColor
+ keyboardAppearance
+ navigationBarStyle
+ navigationBarIsTranslucent
+ styleUsesCustomTableStyle
+ customBackgroundColor
+ userInteractionColor
+ tableCellCheckmarkImageDisabled
+ tableCellEditableTextFieldClearButton
+ tableCellEditableTextFieldClearButtonPressed
+ tableCellTextLabelBackgroundColor
+ tableCellTextLabelColor
+ tableCellDetailLabelColor
+ tableCellDetailLabelBackgroundColor
+ tableSeparatorStyle
+ tableSeparatorColor
+ tableHeaderTextColor
+ tableFooterTextColor
+ splashScreenShowsIcon
+ splashTitleLabelTextColor
+ splashEntryFieldTextColor
+ splashEntryPlaceholderTextColor
+ splashEntryFieldLabelTextColor
+ splashSignInFieldsBorderColor
+ splashSignInFieldsBackgroundColor
+ splashSignInProgressIndicatorColor
+ navigationBarActivityIndicatorStyle
+ navigationBarTintColor
+ navigationBarTranslucent
+ navigationBarBackgroundImage
+ learnMoreTextColor
+ learnMoreArrowImage
+ styleUsesCustomAccessoryView
+ styleUsesCustomSeparatorStyle
+ styleUsesCustomSearchResultsStyle
+ tableSeparatorTopShadowColor
+ tableSeparatorBottomShadowColor
+ tableCellButtonImage
+ tableCellButtonImageSelected
+ tableCellEditableTextColor
+ tableCellEditableTextPlaceholderColor
+ tableSectionBorderColor
+ tableSectionShadowImage
+ tableCellEditableInsertionPointColor
+ tableCellCustomAccessoryViewDisclosureIndicator
+ tableCellCheckmarkImage
+ tableCellCheckmarkImageSelected
+ tableHeaderTextColorSelected
+ tableHeaderTextShadowColor
+ tableHeaderTextShadowOffset
+ tableHeaderFont
+ tableFooterFont
+ tableHeaderTextAlignment
+ tableFooterTextAlignment
+ searchResultsTableSeparatorStyle
+ searchResultsTableSeparatorColor
+ searchResultsTableSeparatorTopShadowColor
+ searchResultsTableSeparatorBottomShadowColor
+ webViewBackgroundView
+ webViewBackgroundColor
+ webViewIsOpaque
+ webViewDrawsShadows
+ firstNavigationBarHidden
+ navigationBarHidesTitle
+ navigationBarHidesShadow
+ learnMoreTextColorSelected
+ learnMoreShadowColor
+ learnMoreArrowImagePressed
+ learnMoreButtonDrawsUnderline
+ actionSheetsUsePopoverStyle
- modalPresentationStyle
- tableBackgroundColor
- tableCellBackgroundColor
- keyboardAppearance
- navigationBarStyle
- navigationBarIsTranslucent
- styleUsesCustomTableStyle
- customBackgroundColor
- userInteractionColor
- tableCellCheckmarkImageDisabled
- tableCellEditableTextFieldClearButton
- tableCellEditableTextFieldClearButtonPressed
- tableCellTextLabelBackgroundColor
- tableCellTextLabelColor
- tableCellDetailLabelColor
- tableCellDetailLabelBackgroundColor
- tableSeparatorStyle
- tableSeparatorColor
- tableHeaderTextColor
- tableFooterTextColor
- splashScreenShowsIcon
- splashTitleLabelTextColor
- splashEntryFieldTextColor
- splashEntryPlaceholderTextColor
- splashEntryFieldLabelTextColor
- splashSignInFieldsBorderColor
- splashSignInFieldsBackgroundColor
- splashSignInProgressIndicatorColor
- navigationBarActivityIndicatorStyle
- navigationBarTintColor
- navigationBarTranslucent
- navigationBarBackgroundImage
- learnMoreTextColor
- learnMoreArrowImage
- styleUsesCustomAccessoryView
- styleUsesCustomSeparatorStyle
- styleUsesCustomSearchResultsStyle
- tableSeparatorTopShadowColor
- tableSeparatorBottomShadowColor
- tableCellButtonImage
- tableCellButtonImageSelected
- tableCellEditableTextColor
- tableCellEditableTextPlaceholderColor
- tableSectionBorderColor
- tableSectionShadowImage
- tableCellEditableInsertionPointColor
- tableCellCustomAccessoryViewDisclosureIndicator
- tableCellCheckmarkImage
- tableCellCheckmarkImageSelected
- tableHeaderTextColorSelected
- tableHeaderTextShadowColor
- tableHeaderTextShadowOffset
- tableHeaderFont
- tableFooterFont
- tableHeaderTextAlignment
- tableFooterTextAlignment
- searchResultsTableSeparatorStyle
- searchResultsTableSeparatorColor
- searchResultsTableSeparatorTopShadowColor
- searchResultsTableSeparatorBottomShadowColor
- webViewBackgroundView
- webViewBackgroundColor
- webViewIsOpaque
- webViewDrawsShadows
- firstNavigationBarHidden
- navigationBarHidesTitle
- navigationBarHidesShadow
- learnMoreTextColorSelected
- learnMoreShadowColor
- learnMoreArrowImagePressed
- learnMoreButtonDrawsUnderline
- actionSheetsUsePopoverStyle
@end
