@interface EKCalendar : EKObject
{
	pointer _color;
	BOOL _isMain;
	unsigned int _loadFlags;
}

+ uiColor
+ allowsTasks
+ allowsEvents
+ commit:
+ allowedEntityTypes
+ allowsContentModifications
+ validate:
+ getColorRed:green:blue:
+ isSubscribed
+ sharedOwnerAddress
+ _sourceRelation
+ _setSource:
+ _shareesRelation
+ selfIdentityFirstName
+ selfIdentityLastName
+ ownerIdentityFirstName
+ ownerIdentityLastName
+ isImmutable
+ symbolicColorName
+ setSymbolicColorName:
+ setColorString:
+ setCGColor:
+ displayOrder
+ setDisplayOrder:
+ isDefaultCalendarForSource
+ prohibitsScheduling
+ isSharingInvitation
+ sharingStatus
+ setSharingStatus:
+ invitationStatus
+ setInvitationStatus:
+ setSharingInvitationResponse:
+ sharingInvitationResponse
+ setSharedOwnerName:
+ sharedOwnerName
+ setSharedOwnerAddress:
+ sharedOwnerEmail
+ publishedURL
+ setIsPublished:
+ isPublished
+ canBePublished
+ canBeShared
+ schedulingProhibited
+ isFacebookBirthdayCalendar
+ externalModificationTag
+ setExternalModificationTag:
+ externalURI
+ lazyLoadRelationForKey:
+ hasEvents
+ hasTasks
+ supportedEventAvailabilities
+ sharees
+ setSharees:
+ addSharee:
+ removeSharee:
+ selfIdentityDisplayName
+ setSelfIdentityDisplayName:
+ selfIdentityEmail
+ setSelfIdentityEmail:
+ selfIdentityAddress
+ setSelfIdentityAddress:
+ setSelfIdentityFirstName:
+ setSelfIdentityLastName:
+ ownerIdentityDisplayName
+ setOwnerIdentityDisplayName:
+ ownerIdentityEmail
+ setOwnerIdentityEmail:
+ ownerIdentityAddress
+ setOwnerIdentityAddress:
+ setOwnerIdentityFirstName:
+ setOwnerIdentityLastName:
+ bulkRequests
+ setBulkRequests:
+ subcalAccountID
+ setSubcalAccountID:
+ pushKey
+ setPushKey:
+ loadFlags
+ setLoadFlags:
+ isMainCalendarForSource
+ setIsMainCalendarForSource:
+ entityType
+ dealloc
+ CGColor
+ isHidden
+ init
+ setTitle:
+ description
+ type
+ title
+ calendarIdentifier
+ source
+ setSource:
+ reset
+ setExternalID:
+ externalID
+ refresh
+ colorString
+ remove:
- uiColor
- allowsTasks
- allowsEvents
- commit:
- allowedEntityTypes
- allowsContentModifications
- validate:
- getColorRed:green:blue:
- isSubscribed
- sharedOwnerAddress
- _sourceRelation
- _setSource:
- _shareesRelation
- selfIdentityFirstName
- selfIdentityLastName
- ownerIdentityFirstName
- ownerIdentityLastName
- isImmutable
- symbolicColorName
- setSymbolicColorName:
- setColorString:
- setCGColor:
- displayOrder
- setDisplayOrder:
- isDefaultCalendarForSource
- prohibitsScheduling
- isSharingInvitation
- sharingStatus
- setSharingStatus:
- invitationStatus
- setInvitationStatus:
- setSharingInvitationResponse:
- sharingInvitationResponse
- setSharedOwnerName:
- sharedOwnerName
- setSharedOwnerAddress:
- sharedOwnerEmail
- publishedURL
- setIsPublished:
- isPublished
- canBePublished
- canBeShared
- schedulingProhibited
- isFacebookBirthdayCalendar
- externalModificationTag
- setExternalModificationTag:
- externalURI
- lazyLoadRelationForKey:
- hasEvents
- hasTasks
- supportedEventAvailabilities
- sharees
- setSharees:
- addSharee:
- removeSharee:
- selfIdentityDisplayName
- setSelfIdentityDisplayName:
- selfIdentityEmail
- setSelfIdentityEmail:
- selfIdentityAddress
- setSelfIdentityAddress:
- setSelfIdentityFirstName:
- setSelfIdentityLastName:
- ownerIdentityDisplayName
- setOwnerIdentityDisplayName:
- ownerIdentityEmail
- setOwnerIdentityEmail:
- ownerIdentityAddress
- setOwnerIdentityAddress:
- setOwnerIdentityFirstName:
- setOwnerIdentityLastName:
- bulkRequests
- setBulkRequests:
- subcalAccountID
- setSubcalAccountID:
- pushKey
- setPushKey:
- loadFlags
- setLoadFlags:
- isMainCalendarForSource
- setIsMainCalendarForSource:
- entityType
- dealloc
- CGColor
- isHidden
- init
- setTitle:
- description
- type
- title
- calendarIdentifier
- source
- setSource:
- reset
- setExternalID:
- externalID
- refresh
- colorString
- remove:
@end
