@interface EKPersistentCalendar : EKPersistentObject
{

}

+ allowedEntityTypes
+ allowsContentModifications
+ validate:
+ setAllowedEntityTypes:
+ isSubscribed
+ sharedOwnerAddress
+ setCanBeShared:
+ setCanBePublished:
+ selfIdentityFirstName
+ selfIdentityLastName
+ ownerIdentityFirstName
+ ownerIdentityLastName
+ isImmutable
+ symbolicColorName
+ setSymbolicColorName:
+ setColorString:
+ displayOrder
+ setDisplayOrder:
+ isDefaultCalendarForSource
+ prohibitsScheduling
+ isSharingInvitation
+ sharingStatus
+ setSharingStatus:
+ invitationStatus
+ setInvitationStatus:
+ setSharingInvitationResponse:
+ sharingInvitationResponse
+ setSharedOwnerName:
+ sharedOwnerName
+ setSharedOwnerAddress:
+ publishedURL
+ setIsPublished:
+ isPublished
+ canBePublished
+ canBeShared
+ schedulingProhibited
+ isFacebookBirthdayCalendar
+ externalModificationTag
+ setExternalModificationTag:
+ sharees
+ setSharees:
+ addSharee:
+ removeSharee:
+ selfIdentityDisplayName
+ setSelfIdentityDisplayName:
+ selfIdentityEmail
+ setSelfIdentityEmail:
+ selfIdentityAddress
+ setSelfIdentityAddress:
+ setSelfIdentityFirstName:
+ setSelfIdentityLastName:
+ ownerIdentityDisplayName
+ setOwnerIdentityDisplayName:
+ ownerIdentityEmail
+ setOwnerIdentityEmail:
+ ownerIdentityAddress
+ setOwnerIdentityAddress:
+ setOwnerIdentityFirstName:
+ setOwnerIdentityLastName:
+ bulkRequests
+ setBulkRequests:
+ subcalAccountID
+ setSubcalAccountID:
+ pushKey
+ setPushKey:
+ isColorDisplayOnly
+ setColorDisplayOnly:
+ setAllowsContentModifications:
+ setProhibitsScheduling:
+ setSubscribed:
+ setImmutable:
+ setSharingInvitation:
+ setSchedulingProhibited:
+ setIsFacebookBirthdayCalendar:
+ setPublishedURL:
+ setPublished:
+ entityType
+ isHidden
+ setHidden:
+ init
+ setTitle:
+ description
+ UUID
+ title
+ source
+ setSource:
+ setUUID:
+ setExternalID:
+ externalID
+ colorString
- allowedEntityTypes
- allowsContentModifications
- validate:
- setAllowedEntityTypes:
- isSubscribed
- sharedOwnerAddress
- setCanBeShared:
- setCanBePublished:
- selfIdentityFirstName
- selfIdentityLastName
- ownerIdentityFirstName
- ownerIdentityLastName
- isImmutable
- symbolicColorName
- setSymbolicColorName:
- setColorString:
- displayOrder
- setDisplayOrder:
- isDefaultCalendarForSource
- prohibitsScheduling
- isSharingInvitation
- sharingStatus
- setSharingStatus:
- invitationStatus
- setInvitationStatus:
- setSharingInvitationResponse:
- sharingInvitationResponse
- setSharedOwnerName:
- sharedOwnerName
- setSharedOwnerAddress:
- publishedURL
- setIsPublished:
- isPublished
- canBePublished
- canBeShared
- schedulingProhibited
- isFacebookBirthdayCalendar
- externalModificationTag
- setExternalModificationTag:
- sharees
- setSharees:
- addSharee:
- removeSharee:
- selfIdentityDisplayName
- setSelfIdentityDisplayName:
- selfIdentityEmail
- setSelfIdentityEmail:
- selfIdentityAddress
- setSelfIdentityAddress:
- setSelfIdentityFirstName:
- setSelfIdentityLastName:
- ownerIdentityDisplayName
- setOwnerIdentityDisplayName:
- ownerIdentityEmail
- setOwnerIdentityEmail:
- ownerIdentityAddress
- setOwnerIdentityAddress:
- setOwnerIdentityFirstName:
- setOwnerIdentityLastName:
- bulkRequests
- setBulkRequests:
- subcalAccountID
- setSubcalAccountID:
- pushKey
- setPushKey:
- isColorDisplayOnly
- setColorDisplayOnly:
- setAllowsContentModifications:
- setProhibitsScheduling:
- setSubscribed:
- setImmutable:
- setSharingInvitation:
- setSchedulingProhibited:
- setIsFacebookBirthdayCalendar:
- setPublishedURL:
- setPublished:
- entityType
- isHidden
- setHidden:
- init
- setTitle:
- description
- UUID
- title
- source
- setSource:
- setUUID:
- setExternalID:
- externalID
- colorString
@end
