@interface EKPersistentObject : NSObject
{
	struct _lock;
	id _eventStore;
	id _objectID;
	pointer _loadedProperties;
	id _referencers;
	id _dirtyProperties;
	unsigned int _flags;
	id _committedProperties;
}

+ primitiveSetStringValue:forKey:
+ primitiveStringValueForKey:
+ primitiveURLValueForKey:
+ primitiveSetURLValue:forKey:
+ primitiveIntValueForKey:
+ primitiveSetIntValue:forKey:
+ primitiveSetRelationValue:forKey:
+ primitiveRelationValueForKey:
+ _setEventStore:
+ isNew
+ _setPendingInsert:
+ _setPendingUpdate:
+ _setPendingDelete:
+ eventStore
+ validate:
+ _isPendingInsert
+ takeValues:forProperties:
+ _setObjectID:
+ _takeValuesForDefaultProperties:inSet:
+ _isPendingDelete
+ _isPendingUpdate
+ pushDirtyProperties:
+ saved
+ dirtyProperties
+ isPropertyDirty:
+ committedValueForKey:
+ unloadPropertyForKey:
+ _clearReferences
+ _clearWeakRelations
+ _releaseLoadedProperties
+ _loadedPropertyKeys
+ changed
+ _relationForKey:
+ _setDefaultPropertiesLoaded:
+ _shouldRetainPropertyForKey:
+ _addReference:forKey:
+ _removeReference:forKey:
+ _loadRelationForKey:value:
+ _loadDefaultPropertiesIfNeeded
+ _loadChildIdentifiersForKey:values:
+ _addDirtyProperty:
+ _addObjectCore:toValues:relation:
+ primitiveValueChangedForKey:
+ _removeObjectCore:fromValues:relation:
+ _primitiveValueForKey:loader:
+ _primitiveSetValue:forKey:daemonSetter:
+ _loadStringValueForKey:
+ _fastpathSetProperty:forKey:isRelation:
+ isPropertyLoaded:
+ _areDefaultPropertiesLoaded
+ existsInStore
+ refreshExcludingProperties:
+ primitiveAddRelatedObject:forKey:
+ primitiveRemoveRelatedObject:forKey:
+ primitiveNumberValueForKey:
+ primitiveSetNumberValue:forKey:
+ primitiveDoubleValueForKey:
+ primitiveSetDoubleValue:forKey:
+ primitiveBoolValueForKey:
+ primitiveSetBoolValue:forKey:
+ primitiveDateValueForKey:
+ primitiveSetDateValue:forKey:
+ primitiveUnboundedStringValueForKey:
+ primitiveSetUnboundedStringValue:forKey:
+ primitiveDataValueForKey:
+ primitiveSetDataValue:forKey:
+ committedProperties
+ setCommittedProperties:
+ dump
+ _propertyForKey:
+ _setProperty:forKey:
+ entityType
+ dealloc
+ init
+ isEqual:
+ reset
+ initCommon
+ refresh
+ objectID
+ rollback
+ isDirty
- primitiveSetStringValue:forKey:
- primitiveStringValueForKey:
- primitiveURLValueForKey:
- primitiveSetURLValue:forKey:
- primitiveIntValueForKey:
- primitiveSetIntValue:forKey:
- primitiveSetRelationValue:forKey:
- primitiveRelationValueForKey:
- _setEventStore:
- isNew
- _setPendingInsert:
- _setPendingUpdate:
- _setPendingDelete:
- eventStore
- validate:
- _isPendingInsert
- takeValues:forProperties:
- _setObjectID:
- _takeValuesForDefaultProperties:inSet:
- _isPendingDelete
- _isPendingUpdate
- pushDirtyProperties:
- saved
- dirtyProperties
- isPropertyDirty:
- committedValueForKey:
- unloadPropertyForKey:
- _clearReferences
- _clearWeakRelations
- _releaseLoadedProperties
- _loadedPropertyKeys
- changed
- _relationForKey:
- _setDefaultPropertiesLoaded:
- _shouldRetainPropertyForKey:
- _addReference:forKey:
- _removeReference:forKey:
- _loadRelationForKey:value:
- _loadDefaultPropertiesIfNeeded
- _loadChildIdentifiersForKey:values:
- _addDirtyProperty:
- _addObjectCore:toValues:relation:
- primitiveValueChangedForKey:
- _removeObjectCore:fromValues:relation:
- _primitiveValueForKey:loader:
- _primitiveSetValue:forKey:daemonSetter:
- _loadStringValueForKey:
- _fastpathSetProperty:forKey:isRelation:
- isPropertyLoaded:
- _areDefaultPropertiesLoaded
- existsInStore
- refreshExcludingProperties:
- primitiveAddRelatedObject:forKey:
- primitiveRemoveRelatedObject:forKey:
- primitiveNumberValueForKey:
- primitiveSetNumberValue:forKey:
- primitiveDoubleValueForKey:
- primitiveSetDoubleValue:forKey:
- primitiveBoolValueForKey:
- primitiveSetBoolValue:forKey:
- primitiveDateValueForKey:
- primitiveSetDateValue:forKey:
- primitiveUnboundedStringValueForKey:
- primitiveSetUnboundedStringValue:forKey:
- primitiveDataValueForKey:
- primitiveSetDataValue:forKey:
- committedProperties
- setCommittedProperties:
- dump
- _propertyForKey:
- _setProperty:forKey:
- entityType
- dealloc
- init
- isEqual:
- reset
- initCommon
- refresh
- objectID
- rollback
- isDirty
@end
