@interface EKPersistentCalendarItem : EKPersistentObject
{

}

+ sequence
+ isAllDay
+ validate:
+ externalModificationTag
+ setExternalModificationTag:
+ setAllDay:
+ selfAttendee
+ originalItem
+ attendees
+ organizer
+ hasRecurrenceRules
+ recurrenceRules
+ setRecurrenceRules:
+ isDetached
+ participationStatusModifiedDate
+ addAlarm:
+ hasAttendees
+ moveToCalendar:
+ setExceptionDates:
+ setDetachedItems:
+ alarms
+ detachedItems
+ addExceptionDate:
+ deleteSelfAndDetached
+ exceptionDates
+ removeRecurrenceRule:
+ setOrganizer:
+ addAttendee:
+ setSelfAttendee:
+ addRecurrenceRule:
+ setOriginalItem:
+ removeAlarm:
+ addDetachedItem:
+ attendeeCount
+ notes
+ hasNotes
+ selfParticipantStatus
+ sharedItemCreatedByFirstName
+ sharedItemCreatedByLastName
+ sharedItemModifiedByFirstName
+ sharedItemModifiedByLastName
+ removeAttachment:
+ setNotes:
+ setLastModifiedDate:
+ isDefaultAlarmRemoved
+ setDefaultAlarmRemoved:
+ hasAlarms
+ setAlarms:
+ setAttendees:
+ removeAttendee:
+ sharedItemCreatedByDisplayName
+ setSharedItemCreatedByDisplayName:
+ sharedItemCreatedByEmailAddress
+ setSharedItemCreatedByFirstName:
+ setSharedItemCreatedByLastName:
+ sharedItemCreatedDate
+ setSharedItemCreatedDate:
+ sharedItemCreatedTimeZone
+ setSharedItemCreatedTimeZone:
+ sharedItemModifiedByDisplayName
+ setSharedItemModifiedByDisplayName:
+ sharedItemModifiedByEmailAddress
+ setSharedItemModifiedByEmailAddress:
+ setSharedItemModifiedByFirstName:
+ setSharedItemModifiedByLastName:
+ sharedItemModifiedDate
+ setSharedItemModifiedDate:
+ sharedItemModifiedTimeZone
+ setSharedItemModifiedTimeZone:
+ setSharedItemCreatedByEmailAddress:
+ setParticipationStatusModifiedDate:
+ primitiveValueChangedForKey:
+ setSequence:
+ removeExceptionDate:
+ removeDetachedItem:
+ moveToCalendar:skipItem:
+ itemDidReplicateInNewCalendar:
+ hasAttachments
+ setAttachments:
+ init
+ setTitle:
+ action
+ setTimeZone:
+ UUID
+ title
+ setAction:
+ URL
+ location
+ setURL:
+ setCalendar:
+ timeZone
+ calendar
+ priority
+ setPriority:
+ addAttachment:
+ uniqueID
+ setUniqueID:
+ attachments
+ setExternalID:
+ externalID
+ externalData
+ setExternalData:
+ startDate
+ creationDate
+ setCreationDate:
+ setStartDate:
+ lastModifiedDate
+ setLocation:
- sequence
- isAllDay
- validate:
- externalModificationTag
- setExternalModificationTag:
- setAllDay:
- selfAttendee
- originalItem
- attendees
- organizer
- hasRecurrenceRules
- recurrenceRules
- setRecurrenceRules:
- isDetached
- participationStatusModifiedDate
- addAlarm:
- hasAttendees
- moveToCalendar:
- setExceptionDates:
- setDetachedItems:
- alarms
- detachedItems
- addExceptionDate:
- deleteSelfAndDetached
- exceptionDates
- removeRecurrenceRule:
- setOrganizer:
- addAttendee:
- setSelfAttendee:
- addRecurrenceRule:
- setOriginalItem:
- removeAlarm:
- addDetachedItem:
- attendeeCount
- notes
- hasNotes
- selfParticipantStatus
- sharedItemCreatedByFirstName
- sharedItemCreatedByLastName
- sharedItemModifiedByFirstName
- sharedItemModifiedByLastName
- removeAttachment:
- setNotes:
- setLastModifiedDate:
- isDefaultAlarmRemoved
- setDefaultAlarmRemoved:
- hasAlarms
- setAlarms:
- setAttendees:
- removeAttendee:
- sharedItemCreatedByDisplayName
- setSharedItemCreatedByDisplayName:
- sharedItemCreatedByEmailAddress
- setSharedItemCreatedByFirstName:
- setSharedItemCreatedByLastName:
- sharedItemCreatedDate
- setSharedItemCreatedDate:
- sharedItemCreatedTimeZone
- setSharedItemCreatedTimeZone:
- sharedItemModifiedByDisplayName
- setSharedItemModifiedByDisplayName:
- sharedItemModifiedByEmailAddress
- setSharedItemModifiedByEmailAddress:
- setSharedItemModifiedByFirstName:
- setSharedItemModifiedByLastName:
- sharedItemModifiedDate
- setSharedItemModifiedDate:
- sharedItemModifiedTimeZone
- setSharedItemModifiedTimeZone:
- setSharedItemCreatedByEmailAddress:
- setParticipationStatusModifiedDate:
- primitiveValueChangedForKey:
- setSequence:
- removeExceptionDate:
- removeDetachedItem:
- moveToCalendar:skipItem:
- itemDidReplicateInNewCalendar:
- hasAttachments
- setAttachments:
- init
- setTitle:
- action
- setTimeZone:
- UUID
- title
- setAction:
- URL
- location
- setURL:
- setCalendar:
- timeZone
- calendar
- priority
- setPriority:
- addAttachment:
- uniqueID
- setUniqueID:
- attachments
- setExternalID:
- externalID
- externalData
- setExternalData:
- startDate
- creationDate
- setCreationDate:
- setStartDate:
- lastModifiedDate
- setLocation:
@end
