@interface GKCollectionViewAggregateDataSource : GKCollectionViewDataSource
{
	id _mappings;
	id _dataSourceToMappings;
	id _globalSectionToMappings;
	usigned long long _sectionCount;
}

+ refreshContentsForDataType:userInfo:updateNotifier:
+ configureCollectionView:
+ dataSource:didInsertItemsAtIndexPaths:
+ dataSource:didRemoveItemsAtIndexPaths:
+ dataSource:didRefreshItemsAtIndexPaths:
+ itemAtIndexPath:
+ removeItemAtIndexPath:
+ _gkDescriptionWithChildren:
+ collectionViewDidBecomeInactive:
+ indexPathsForItem:
+ collectionViewWillBecomeActive:
+ resetViewFactories
+ item:matchesSearchTerms:inSection:
+ dataSource:didMoveItemAtIndexPath:toIndexPath:
+ dataSource:didInsertSections:
+ dataSource:didRemoveSections:
+ dataSource:didRefreshSections:
+ dataSource:didMoveSection:toSection:
+ dataSourceDidReloadData:
+ dataSource:performBatchUpdate:complete:
+ collectionView:evaluateFactoryForSupplementaryElementOfKind:atIndexPath:isRecursive:
+ localDescription
+ dataSourceForSection:
+ sectionForDataSource:
+ containsDataSource:
+ createMetricsTreeWithGridLayout:
+ mappings
+ wrapperForView:mapping:
+ updateMappings
+ mappingForDataSource:
+ mappingForGlobalSection:
+ allDataSources
+ globalIndexPathsForLocal:dataSource:
+ globalSectionsForLocal:dataSource:
+ _gkDescription
+ addDataSource:withTag:
+ removeDataSource:
+ setDataSource:forTag:
+ setMappings:
+ dataSourceToMappings
+ setDataSourceToMappings:
+ globalSectionToMappings
+ setGlobalSectionToMappings:
+ setSectionCount:
+ dealloc
+ init
+ collectionView:numberOfItemsInSection:
+ collectionView:cellForItemAtIndexPath:
+ numberOfSectionsInCollectionView:
+ collectionView:viewForSupplementaryElementOfKind:atIndexPath:
+ sectionCount
- refreshContentsForDataType:userInfo:updateNotifier:
- configureCollectionView:
- dataSource:didInsertItemsAtIndexPaths:
- dataSource:didRemoveItemsAtIndexPaths:
- dataSource:didRefreshItemsAtIndexPaths:
- itemAtIndexPath:
- removeItemAtIndexPath:
- _gkDescriptionWithChildren:
- collectionViewDidBecomeInactive:
- indexPathsForItem:
- collectionViewWillBecomeActive:
- resetViewFactories
- item:matchesSearchTerms:inSection:
- dataSource:didMoveItemAtIndexPath:toIndexPath:
- dataSource:didInsertSections:
- dataSource:didRemoveSections:
- dataSource:didRefreshSections:
- dataSource:didMoveSection:toSection:
- dataSourceDidReloadData:
- dataSource:performBatchUpdate:complete:
- collectionView:evaluateFactoryForSupplementaryElementOfKind:atIndexPath:isRecursive:
- localDescription
- dataSourceForSection:
- sectionForDataSource:
- containsDataSource:
- createMetricsTreeWithGridLayout:
- mappings
- wrapperForView:mapping:
- updateMappings
- mappingForDataSource:
- mappingForGlobalSection:
- allDataSources
- globalIndexPathsForLocal:dataSource:
- globalSectionsForLocal:dataSource:
- _gkDescription
- addDataSource:withTag:
- removeDataSource:
- setDataSource:forTag:
- setMappings:
- dataSourceToMappings
- setDataSourceToMappings:
- globalSectionToMappings
- setGlobalSectionToMappings:
- setSectionCount:
- dealloc
- init
- collectionView:numberOfItemsInSection:
- collectionView:cellForItemAtIndexPath:
- numberOfSectionsInCollectionView:
- collectionView:viewForSupplementaryElementOfKind:atIndexPath:
- sectionCount
@end
