@interface GKGame : NSObject
{
	BOOL _sandboxed;
	id _internal;
}

+ _gkSharingInfo
+ _gkSetSharingInfo:
+ fetchSharingInfo
+ activityViewControllerPlaceholderItems:
+ activityViewController:thumbnailForActivityType:
+ activityViewController:attachmentULRTypeForActivityType:
+ activityViewControllerSubject:
+ activityViewController:itemsForActivityType:
+ activityViewControllerOperation:
+ loadIconForStyle:withCompletionHandler:
+ imageSourceForIconStyle:
+ URLStringForImageWithShineIfNeeded
+ imageSourceForiOSIconStyle:
+ macBrushForIconStyle:
+ _imageURLForIconStyle:
+ iconForStyle:
+ cachedIconForStyle:
+ loadIconForSize:completionHandler:
+ uninstallGameWithCompletionHandler:
+ isDownloading
+ isInternal
+ isInstalled
+ isGameRecommendation
+ loadGameRatingWithCompletionHandler:
+ submitRating:withCompletionHandler:
+ getFriendPlayersIncludingCompatibleGames:handler:
+ getFriendPlayersForAchievement:handler:
+ getFriendPlayersForLeaderboard:handler:
+ loadTellAFriendMessageWithCompletionHandler:
+ setInternal:
+ gameInfo
+ isStoreItemUnexpired
+ setSandboxed:
+ internal
+ isGameCenter
+ isSandboxed
+ initWithInternalRepresentation:
+ gameDescriptor
+ dealloc
+ initWithCoder:
+ encodeWithCoder:
+ respondsToSelector:
+ init
+ isEqual:
+ hash
+ description
+ methodSignatureForSelector:
+ copyWithZone:
+ forwardingTargetForSelector:
+ valueForUndefinedKey:
+ cacheKey
+ setValue:forUndefinedKey:
- _gkSharingInfo
- _gkSetSharingInfo:
- fetchSharingInfo
- activityViewControllerPlaceholderItems:
- activityViewController:thumbnailForActivityType:
- activityViewController:attachmentULRTypeForActivityType:
- activityViewControllerSubject:
- activityViewController:itemsForActivityType:
- activityViewControllerOperation:
- loadIconForStyle:withCompletionHandler:
- imageSourceForIconStyle:
- URLStringForImageWithShineIfNeeded
- imageSourceForiOSIconStyle:
- macBrushForIconStyle:
- _imageURLForIconStyle:
- iconForStyle:
- cachedIconForStyle:
- loadIconForSize:completionHandler:
- uninstallGameWithCompletionHandler:
- isDownloading
- isInternal
- isInstalled
- isGameRecommendation
- loadGameRatingWithCompletionHandler:
- submitRating:withCompletionHandler:
- getFriendPlayersIncludingCompatibleGames:handler:
- getFriendPlayersForAchievement:handler:
- getFriendPlayersForLeaderboard:handler:
- loadTellAFriendMessageWithCompletionHandler:
- setInternal:
- gameInfo
- isStoreItemUnexpired
- setSandboxed:
- internal
- isGameCenter
- isSandboxed
- initWithInternalRepresentation:
- gameDescriptor
- dealloc
- initWithCoder:
- encodeWithCoder:
- respondsToSelector:
- init
- isEqual:
- hash
- description
- methodSignatureForSelector:
- copyWithZone:
- forwardingTargetForSelector:
- valueForUndefinedKey:
- cacheKey
- setValue:forUndefinedKey:
@end
