@interface GKPlayer : NSObject
{
	id _internal;
	id _friends;
	id _lastPlayedGame;
}

+ loadPhotoForSize:withCompletionHandler:
+ photoURLForSize:
+ placeholderImageForType:
+ imageSourceForPlaceholders
+ imageURLForPhotoSizeList
+ placeholderImage
+ isFriendRecommendation
+ initWithPendingFriendRequest:
+ isFriendRequest
+ hasPhoto
+ setInternal:
+ setFriends:
+ loadCommonFriends:asPlayersWithCompletionHandler:
+ loadGamesPlayedIncludingInstalledGames:completionHandler:
+ acceptFriendRequestWithCompletionHandler:
+ declineFriendRequestWithCompletionHandler:
+ loadGamesPlayed:
+ loadGamesPlayedDetailsWithCompletionHandler:
+ displayNameWithOptions:
+ lastPlayedGame
+ stats
+ internal
+ initWithInternalRepresentation:
+ loadRecentMatchesForGame:block:
+ friends
+ loadProfileWithCompletionHandler:
+ sortName
+ loadFriendsAsPlayersWithCompletionHandler:
+ dealloc
+ initWithCoder:
+ encodeWithCoder:
+ respondsToSelector:
+ init
+ isEqual:
+ hash
+ description
+ methodSignatureForSelector:
+ forwardingTargetForSelector:
+ valueForUndefinedKey:
+ displayName
+ cacheKey
+ email
+ emails
+ _postChangeNotification
+ postChangeNotification
+ setValue:forUndefinedKey:
- loadPhotoForSize:withCompletionHandler:
- photoURLForSize:
- placeholderImageForType:
- imageSourceForPlaceholders
- imageURLForPhotoSizeList
- placeholderImage
- isFriendRecommendation
- initWithPendingFriendRequest:
- isFriendRequest
- hasPhoto
- setInternal:
- setFriends:
- loadCommonFriends:asPlayersWithCompletionHandler:
- loadGamesPlayedIncludingInstalledGames:completionHandler:
- acceptFriendRequestWithCompletionHandler:
- declineFriendRequestWithCompletionHandler:
- loadGamesPlayed:
- loadGamesPlayedDetailsWithCompletionHandler:
- displayNameWithOptions:
- lastPlayedGame
- stats
- internal
- initWithInternalRepresentation:
- loadRecentMatchesForGame:block:
- friends
- loadProfileWithCompletionHandler:
- sortName
- loadFriendsAsPlayersWithCompletionHandler:
- dealloc
- initWithCoder:
- encodeWithCoder:
- respondsToSelector:
- init
- isEqual:
- hash
- description
- methodSignatureForSelector:
- forwardingTargetForSelector:
- valueForUndefinedKey:
- displayName
- cacheKey
- email
- emails
- _postChangeNotification
- postChangeNotification
- setValue:forUndefinedKey:
@end
