@interface GKPreferences : NSObject
{
	BOOL _webKitInspectElementEnabled;
	BOOL __shouldSynchronizeOnNextRead;
	id _overrideValues;
}

+ preferencesDelegate
+ restrictionEnabledForKey:
+ setPreferencesDelegate:
+ executionAllowedForBundleID:
+ isAppInstallationRestricted
+ isMultiplayerGamingRestricted
+ isAddingFriendsRestricted
+ isGameCenterRestricted
+ isStoreDemoModeEnabled
+ isAccountModificationRestricted
+ profileConnectionDidReceiveEffectiveSettingsChangedNotification:userInfo:
+ setEnvironment:
+ HTTPShouldUsePipelining
+ minimumCacheTTL
+ initWithoutUIKitNotifications
+ logFilter
+ useTestProtocols
+ applicationWillEnterBackground:
+ initWithUIKitNotifications
+ _shouldSynchronizeOnNextRead
+ set_shouldSynchronizeOnNextRead:
+ removeOverrideForKey:
+ preferencesValueForKey:
+ booleanValueForKey:defaultValue:
+ _didWriteKey:
+ setOverrideValues:
+ integerValueForKey:defaultValue:
+ setIntegerValue:forKey:
+ booleanValueForKey:
+ setBooleanValue:forKey:
+ unsignedIntegerValueForKey:defaultValue:
+ setUnsignedIntegerValue:forKey:
+ timeIntervalForKey:defaultValue:
+ setTimeInterval:forKey:
+ maxDefaultPlayersP2P
+ maxDefaultPlayersHosted
+ maxDefaultPlayersTurnBased
+ maxDefaultGameStateSizeTurnBased
+ exchangeDataDefaultMaximumSize
+ exchangeDefaultMaxInitiatedExchangesPerPlayer
+ stringValueForKey:defaultValue:
+ setStringValue:forKey:
+ storeBagURL
+ setStoreBagURL:
+ allowUnsignedBag
+ setAllowUnsignedBag:
+ setUseTestProtocols:
+ mescalSetupRetries
+ setMescalSetupRetries:
+ ignoreSandbox
+ setIgnoreSandbox:
+ loginDisableThreshold
+ setLoginDisableThreshold:
+ operationTimeout
+ setOperationTimeout:
+ operationRetryDelay
+ setOperationRetryDelay:
+ operationRetryCount
+ setOperationRetryCount:
+ debugRequestTimeout
+ setDebugRequestTimeout:
+ verboseLogging
+ setVerboseLogging:
+ setLogFilter:
+ forceRelay
+ setForceRelay:
+ preemptiveRelay
+ setPreemptiveRelay:
+ pushEnvironment
+ setPushEnvironment:
+ pipeliningSetting
+ setPipeliningSetting:
+ maxPlayersP2P
+ setMaxPlayersP2P:
+ maxPlayersHosted
+ setMaxPlayersHosted:
+ maxPlayersTurnBased
+ setMaxPlayersTurnBased:
+ maxGameStateSizeTurnBased
+ setMaxGameStateSizeTurnBased:
+ exchangeDataMaximumSize
+ setExchangeDataMaximumSize:
+ exchangeMaxInitiatedExchangesPerPlayer
+ setExchangeMaxInitiatedExchangesPerPlayer:
+ useInternalHeader
+ setUseInternalHeader:
+ terminationInterval
+ setTerminationInterval:
+ garbageCollectionInterval
+ setGarbageCollectionInterval:
+ setMinimumCacheTTL:
+ cacheTTLOverride
+ setCacheTTLOverride:
+ setShouldAnnotateImageUsage:
+ shouldTrackAtlasImageUsage
+ setShouldTrackAtlasImageUsage:
+ setShouldUseTestIcons:
+ shouldLinkPlayerToICloud
+ setShouldLinkPlayerToICloud:
+ shouldLinkPlayerToTwitter
+ setShouldLinkPlayerToTwitter:
+ shouldLinkPlayerToFacebook
+ setShouldLinkPlayerToFacebook:
+ shouldAllowGameInvites
+ shouldDisallowInvitesFromStrangers
+ shouldAddPlayerInfoToAddressBook
+ setShouldAddPlayerInfoToAddressBook:
+ overrideValues
+ isWebKitInspectElementEnabled
+ setWebKitInspectElementEnabled:
+ setShouldAllowGameInvites:
+ setShouldAllowNearbyMultiplayer:
+ shouldAllowNearbyMultiplayer
+ shouldAnnotateImageUsage
+ notificationBadgesEnabled
+ notificationSoundsEnabled
+ notificationAlertsEnabled
+ setNotificationBadgesEnabled:
+ setNotificationSoundsEnabled:
+ setNotificationAlertsEnabled:
+ isNotificationCenterEnabled
+ setNotificationCenterEnabled:
+ shouldUseTestIcons
+ dealloc
+ init
+ invalidate
+ synchronize
+ environment
- preferencesDelegate
- restrictionEnabledForKey:
- setPreferencesDelegate:
- executionAllowedForBundleID:
- isAppInstallationRestricted
- isMultiplayerGamingRestricted
- isAddingFriendsRestricted
- isGameCenterRestricted
- isStoreDemoModeEnabled
- isAccountModificationRestricted
- profileConnectionDidReceiveEffectiveSettingsChangedNotification:userInfo:
- setEnvironment:
- HTTPShouldUsePipelining
- minimumCacheTTL
- initWithoutUIKitNotifications
- logFilter
- useTestProtocols
- applicationWillEnterBackground:
- initWithUIKitNotifications
- _shouldSynchronizeOnNextRead
- set_shouldSynchronizeOnNextRead:
- removeOverrideForKey:
- preferencesValueForKey:
- booleanValueForKey:defaultValue:
- _didWriteKey:
- setOverrideValues:
- integerValueForKey:defaultValue:
- setIntegerValue:forKey:
- booleanValueForKey:
- setBooleanValue:forKey:
- unsignedIntegerValueForKey:defaultValue:
- setUnsignedIntegerValue:forKey:
- timeIntervalForKey:defaultValue:
- setTimeInterval:forKey:
- maxDefaultPlayersP2P
- maxDefaultPlayersHosted
- maxDefaultPlayersTurnBased
- maxDefaultGameStateSizeTurnBased
- exchangeDataDefaultMaximumSize
- exchangeDefaultMaxInitiatedExchangesPerPlayer
- stringValueForKey:defaultValue:
- setStringValue:forKey:
- storeBagURL
- setStoreBagURL:
- allowUnsignedBag
- setAllowUnsignedBag:
- setUseTestProtocols:
- mescalSetupRetries
- setMescalSetupRetries:
- ignoreSandbox
- setIgnoreSandbox:
- loginDisableThreshold
- setLoginDisableThreshold:
- operationTimeout
- setOperationTimeout:
- operationRetryDelay
- setOperationRetryDelay:
- operationRetryCount
- setOperationRetryCount:
- debugRequestTimeout
- setDebugRequestTimeout:
- verboseLogging
- setVerboseLogging:
- setLogFilter:
- forceRelay
- setForceRelay:
- preemptiveRelay
- setPreemptiveRelay:
- pushEnvironment
- setPushEnvironment:
- pipeliningSetting
- setPipeliningSetting:
- maxPlayersP2P
- setMaxPlayersP2P:
- maxPlayersHosted
- setMaxPlayersHosted:
- maxPlayersTurnBased
- setMaxPlayersTurnBased:
- maxGameStateSizeTurnBased
- setMaxGameStateSizeTurnBased:
- exchangeDataMaximumSize
- setExchangeDataMaximumSize:
- exchangeMaxInitiatedExchangesPerPlayer
- setExchangeMaxInitiatedExchangesPerPlayer:
- useInternalHeader
- setUseInternalHeader:
- terminationInterval
- setTerminationInterval:
- garbageCollectionInterval
- setGarbageCollectionInterval:
- setMinimumCacheTTL:
- cacheTTLOverride
- setCacheTTLOverride:
- setShouldAnnotateImageUsage:
- shouldTrackAtlasImageUsage
- setShouldTrackAtlasImageUsage:
- setShouldUseTestIcons:
- shouldLinkPlayerToICloud
- setShouldLinkPlayerToICloud:
- shouldLinkPlayerToTwitter
- setShouldLinkPlayerToTwitter:
- shouldLinkPlayerToFacebook
- setShouldLinkPlayerToFacebook:
- shouldAllowGameInvites
- shouldDisallowInvitesFromStrangers
- shouldAddPlayerInfoToAddressBook
- setShouldAddPlayerInfoToAddressBook:
- overrideValues
- isWebKitInspectElementEnabled
- setWebKitInspectElementEnabled:
- setShouldAllowGameInvites:
- setShouldAllowNearbyMultiplayer:
- shouldAllowNearbyMultiplayer
- shouldAnnotateImageUsage
- notificationBadgesEnabled
- notificationSoundsEnabled
- notificationAlertsEnabled
- setNotificationBadgesEnabled:
- setNotificationSoundsEnabled:
- setNotificationAlertsEnabled:
- isNotificationCenterEnabled
- setNotificationCenterEnabled:
- shouldUseTestIcons
- dealloc
- init
- invalidate
- synchronize
- environment
@end
