@interface GKTextStyle : NSObject
{
	BOOL _needsParagraphStyle;
	id _palette;
	id _fontName;
	double _fontSize;
	id _color;
	long long _textAlignment;
	long long _lineBreakMode;
	double _minimumLineHeight;
	double _m34;
	double _zPosition;
	SEL _fontSizeRebaseSelector;
}

+ tableCellSubtitle
+ strong
+ cellActionItem
+ tableCellTitle
+ roundButtonTitle
+ alignment:lineBreakMode:
+ sectionCaptionSmall
+ achievementValueText
+ styleWithName:fallback:layoutMode:
+ replayOnBaseStyle:
+ applyToEditField:
+ centered
+ header3
+ header4
+ emphasizedOnDarkBackground
+ emphasized
+ tableFooterStyle
+ lineHeight:
+ header2
+ thin
+ bubbleText
+ composeMessage
+ composeFields
+ baseFontSizeSelector
+ fontSizeRebaseSelector
+ copyWithBaseClass:
+ applyScaleForMesh
+ initEmpty
+ resolveFont
+ setFontSize:rebaseSelector:
+ applyToLabel:
+ header0
+ header1
+ bannerTitle
+ bannerMessage
+ buyButtonTitle
+ selectedBuyButtonTitle
+ small
+ smallInfo
+ viewBackground
+ scaledForM34:zPosition:
+ localPlayerColor
+ friendColor
+ friendCaptionColor
+ regular
+ light
+ bubbleCaptionSmall
+ bubbleValueSmall
+ bubbleCaption
+ bubbleValue
+ segmentBubbleCaption
+ segmentBubbleValue
+ bubbleHeadline
+ signInTitle
+ signInSubtitle
+ signInField
+ signInFieldLabel
+ signInLink
+ leaderboardRankSmall
+ leaderboardRankMedium
+ leaderboardRankLarge
+ achievementLeaderboardRank
+ achievementLeaderboardPointsText
+ sectionCaption
+ tabIconCaption
+ removeButtonTitle
+ remoteUISectionHeader:
+ remoteUISectionFooter:
+ remoteUILabel:
+ remoteUIDetailLabel:
+ remoteUITableHeaderLabel:
+ remoteUITableHeaderSubLabel:
+ remoteUITableFooterButton:
+ remoteUITableHeaderButton:
+ remoteUIEditField:
+ remoteUIEditLabel:
+ remoteUISelectLabel:
+ remoteUISelectField:
+ remoteUINickNameField:
+ remoteUINickNameLabel:
+ settingsLinkText
+ settingsButton
+ settingsBoldButton
+ settingsLabel
+ settingsHeader
+ settingsFooter
+ bubbleTextSmall
+ setPalette:
+ needsParagraphStyle
+ setNeedsParagraphStyle:
+ setFontSizeRebaseSelector:
+ dealloc
+ init
+ copy
+ isEqual:
+ hash
+ description
+ setLineBreakMode:
+ setMinimumLineHeight:
+ setTextAlignment:
+ textAlignment
+ info
+ color
+ lineBreakMode
+ minimumLineHeight
+ fontName
+ setColor:
+ setZPosition:
+ setFontName:
+ attributes
+ buttonTitle
+ sectionHeader
+ fontSize
+ bold
+ palette
+ caption
+ m34
+ setM34:
+ zPosition
- tableCellSubtitle
- strong
- cellActionItem
- tableCellTitle
- roundButtonTitle
- alignment:lineBreakMode:
- sectionCaptionSmall
- achievementValueText
- styleWithName:fallback:layoutMode:
- replayOnBaseStyle:
- applyToEditField:
- centered
- header3
- header4
- emphasizedOnDarkBackground
- emphasized
- tableFooterStyle
- lineHeight:
- header2
- thin
- bubbleText
- composeMessage
- composeFields
- baseFontSizeSelector
- fontSizeRebaseSelector
- copyWithBaseClass:
- applyScaleForMesh
- initEmpty
- resolveFont
- setFontSize:rebaseSelector:
- applyToLabel:
- header0
- header1
- bannerTitle
- bannerMessage
- buyButtonTitle
- selectedBuyButtonTitle
- small
- smallInfo
- viewBackground
- scaledForM34:zPosition:
- localPlayerColor
- friendColor
- friendCaptionColor
- regular
- light
- bubbleCaptionSmall
- bubbleValueSmall
- bubbleCaption
- bubbleValue
- segmentBubbleCaption
- segmentBubbleValue
- bubbleHeadline
- signInTitle
- signInSubtitle
- signInField
- signInFieldLabel
- signInLink
- leaderboardRankSmall
- leaderboardRankMedium
- leaderboardRankLarge
- achievementLeaderboardRank
- achievementLeaderboardPointsText
- sectionCaption
- tabIconCaption
- removeButtonTitle
- remoteUISectionHeader:
- remoteUISectionFooter:
- remoteUILabel:
- remoteUIDetailLabel:
- remoteUITableHeaderLabel:
- remoteUITableHeaderSubLabel:
- remoteUITableFooterButton:
- remoteUITableHeaderButton:
- remoteUIEditField:
- remoteUIEditLabel:
- remoteUISelectLabel:
- remoteUISelectField:
- remoteUINickNameField:
- remoteUINickNameLabel:
- settingsLinkText
- settingsButton
- settingsBoldButton
- settingsLabel
- settingsHeader
- settingsFooter
- bubbleTextSmall
- setPalette:
- needsParagraphStyle
- setNeedsParagraphStyle:
- setFontSizeRebaseSelector:
- dealloc
- init
- copy
- isEqual:
- hash
- description
- setLineBreakMode:
- setMinimumLineHeight:
- setTextAlignment:
- textAlignment
- info
- color
- lineBreakMode
- minimumLineHeight
- fontName
- setColor:
- setZPosition:
- setFontName:
- attributes
- buttonTitle
- sectionHeader
- fontSize
- bold
- palette
- caption
- m34
- setM34:
- zPosition
@end
