@interface GKUITheme : NSObject
{
	id _resourceCache;
	id _leaderboardCategoryIconSourceSmall;
}

+ statusDotImage
+ photoListSource
+ photoDetailSource
+ formSheetCornerRadius
+ untreatedAchievementImageSource
+ clearResourceCache
+ resourceCache
+ setResourceCache:
+ _tabBarIconImageNamed:selectedName:selected:
+ resourceWithName:missingHandler:
+ resourceForSelector:missingHandler:
+ gameListIconBrush
+ achievementIconBrush
+ achievementIconBrushPad
+ defaultPlayerPhoto
+ defaultLeaderboardIcon
+ ratingStarsBackgroundImage
+ ratingStarsForegroundImage
+ interactiveRatingStarsForeground
+ interactiveRatingStarsBackground
+ eventIconImage
+ achievementsNotStartedIcon
+ automatchPlayerPlaceholder
+ achievementsDefaultIcon
+ tabbarIconFriendsSelected:
+ tabbarIconGamesSelected:
+ tabbarIconMeSelected:
+ tabbarIconChallengesSelected:
+ tabbarIconTurnsSelected:
+ macGameIconSource
+ gameListIconSource
+ achievementIconSource
+ achievementIconSourcePad
+ iconLeaderboardListSource
+ iconLeaderboardSetListSource
+ photoLeaderboardSource
+ addPlayerButtonImage
+ removePlayerButtonImage
+ playerPickerUnselectedImage
+ playerPickerSelectedImage
+ bubbleAccept
+ bubbleChallenges
+ bubbleDecline
+ bubbleFriends
+ bubbleGames
+ bubbleInvite
+ bubblePlay
+ bubblePoints
+ bubbleRequests
+ bubbleShare
+ bubbleSignin
+ bubbleTurns
+ bubbleHighlight
+ navbarActionButtonIcon
+ leaderboardCategoryIconSourceSmall
+ dealloc
+ init
+ imageNamed:
+ formSheetSize
- statusDotImage
- photoListSource
- photoDetailSource
- formSheetCornerRadius
- untreatedAchievementImageSource
- clearResourceCache
- resourceCache
- setResourceCache:
- _tabBarIconImageNamed:selectedName:selected:
- resourceWithName:missingHandler:
- resourceForSelector:missingHandler:
- gameListIconBrush
- achievementIconBrush
- achievementIconBrushPad
- defaultPlayerPhoto
- defaultLeaderboardIcon
- ratingStarsBackgroundImage
- ratingStarsForegroundImage
- interactiveRatingStarsForeground
- interactiveRatingStarsBackground
- eventIconImage
- achievementsNotStartedIcon
- automatchPlayerPlaceholder
- achievementsDefaultIcon
- tabbarIconFriendsSelected:
- tabbarIconGamesSelected:
- tabbarIconMeSelected:
- tabbarIconChallengesSelected:
- tabbarIconTurnsSelected:
- macGameIconSource
- gameListIconSource
- achievementIconSource
- achievementIconSourcePad
- iconLeaderboardListSource
- iconLeaderboardSetListSource
- photoLeaderboardSource
- addPlayerButtonImage
- removePlayerButtonImage
- playerPickerUnselectedImage
- playerPickerSelectedImage
- bubbleAccept
- bubbleChallenges
- bubbleDecline
- bubbleFriends
- bubbleGames
- bubbleInvite
- bubblePlay
- bubblePoints
- bubbleRequests
- bubbleShare
- bubbleSignin
- bubbleTurns
- bubbleHighlight
- navbarActionButtonIcon
- leaderboardCategoryIconSourceSmall
- dealloc
- init
- imageNamed:
- formSheetSize
@end
