@interface IDSAccount : NSObject
{
	id _internal;
}

+ setPassword:
+ serviceName
+ setAuthToken:
+ pushToken
+ _internal
+ dealloc
+ description
+ isActive
+ _isEnabled
+ canSend
+ addDelegate:queue:
+ uniqueID
+ devices
+ aliasStrings
+ _initWithDictionary:uniqueID:serviceName:
+ setAccountInfo:
+ _setIsEnabled:
+ setLoginID:
+ dateRegistered
+ initWithLoginID:uniqueID:serviceName:
+ profileID
+ registrationStatus
+ regionID
+ regionBasePhoneNumber
+ nextRegistrationDate
+ regionServerContext
+ aliases
+ profileInfo
+ vettedAliases
+ authenticateAccount
+ addAliases:
+ removeAliases:
+ unvalidateAliases:
+ validateAliases:
+ registerAccount
+ unregisterAccount
+ updateAuthorizationCredentials:token:
+ validateProfile
+ loginID
+ passwordUpdated
+ updateAccountWithAccountInfo:
+ accountInfo
+ addRegistrationDelegate:queue:
+ removeRegistrationDelegate:
+ initWithDictionary:uniqueID:serviceName:
+ registeredURIs
+ deactivateAndPurgeIdentify
+ _reregisterAndReidentify:
+ registrationCertificate
+ removeDelegate:
+ accountType
- setPassword:
- serviceName
- setAuthToken:
- pushToken
- _internal
- dealloc
- description
- isActive
- _isEnabled
- canSend
- addDelegate:queue:
- uniqueID
- devices
- aliasStrings
- _initWithDictionary:uniqueID:serviceName:
- setAccountInfo:
- _setIsEnabled:
- setLoginID:
- dateRegistered
- initWithLoginID:uniqueID:serviceName:
- profileID
- registrationStatus
- regionID
- regionBasePhoneNumber
- nextRegistrationDate
- regionServerContext
- aliases
- profileInfo
- vettedAliases
- authenticateAccount
- addAliases:
- removeAliases:
- unvalidateAliases:
- validateAliases:
- registerAccount
- unregisterAccount
- updateAuthorizationCredentials:token:
- validateProfile
- loginID
- passwordUpdated
- updateAccountWithAccountInfo:
- accountInfo
- addRegistrationDelegate:queue:
- removeRegistrationDelegate:
- initWithDictionary:uniqueID:serviceName:
- registeredURIs
- deactivateAndPurgeIdentify
- _reregisterAndReidentify:
- registrationCertificate
- removeDelegate:
- accountType
@end
