@interface IMAVConferenceInterface : IMAVInterface
{
	id _avConferencesToCleanup;
	id _avConferences;
	id _avConferencesLock;
	BOOL _duringInit;
	BOOL _pendingCleanup;
}

+ dealloc
+ init
+ controller
+ conference:didStartSession:withUserInfo:
+ conference:didStopWithCallID:error:
+ conference:didStopWithCallID:error:callMetadata:
+ conference:localIPChange:withCallID:
+ conference:receivedNoRemotePacketsForTime:callID:
+ conference:withCallID:remoteMediaStalled:
+ conference:receivedFirstRemoteFrameForCallID:
+ conference:remoteVideoAttributesChanged:callID:
+ conference:remoteAudioPaused:callID:
+ conference:remoteVideoPaused:callID:
+ conference:remoteScreenAttributesChanged:callID:
+ conference:updateInputMeterLevel:
+ conference:updateOutputMeterLevel:
+ conference:inititiateRelayRequest:requestDict:
+ conference:sendRelayUpdate:updateDict:
+ conference:cancelRelayRequest:requestDict:
+ conference:videoQualityNotificationForCallID:isDegraded:isRemote:
+ conference:withCallID:networkHint:
+ conference:didChangeLocalVariablesForCallID:
+ serverDiedForConference:
+ stopPreview
+ setLocalVideoLayer:
+ localVideoLayer
+ setRemoteVideoLayersFromChat:toChat:
+ _notifyAboutPotentialCallForChat:
+ _avChatDealloc:
+ chatStateUpdated
+ endConferenceForAVChat:
+ isAVInterfaceReady
+ initAVInterface
+ processRemoteIPChanged:fromParticipant:
+ natTypeForAVChat:
+ endAVConferenceWithChat:callID:
+ avChat:prepareConnectionWithCallInfo:
+ avChat:generateCallInfoForID:service:usingRelay:callInfo:
+ _conferenceEnded:
+ isMuteForAVChat:
+ avChat:setMute:
+ isPausedForAVChat:
+ avChat:setPaused:
+ isSendingAudioForAVChat:
+ avChat:setSendingAudio:
+ isSendingVideoForAVChat:
+ avChat:setSendingVideo:
+ capabilitiesOfNetwork
+ capabilitiesOfCPU
+ startPreviewWithError:
+ avChat:endConferenceForUserID:
+ getNatIPFromICEData:
+ supportsLayers
+ remoteVideoLayerForChat:
+ setRemoteVideoLayer:forChat:
+ remoteVideoBackLayerForChat:
+ setRemoteVideoBackLayer:forChat:
+ localVideoBackLayer
+ setLocalVideoBackLayer:
+ supportsRelay
+ handleRelayInitate:fromParticipant:callInfo:
+ handleRelayUpdate:fromParticipant:callInfo:
+ handleRelayCancel:fromParticipant:callInfo:
+ _controller
+ avChat:setLocalLandscapeAspectRatio:localPortraitAspectRatio:
+ _submitLoggingInformation:forChat:
+ _submitEndCallMetric:forCallID:
+ updateAVChat:withCallMetadata:
+ _setAudioSessionPropertiesForChat:
+ _existingConferenceForAVChat:
+ _configureAVConference:forChat:
+ _avChatForConference:callID:errorString:
+ _avChatForConference:
+ _cleanupAVInterface
+ _queueAVConferenceForCleanup:
+ _conferenceForAVChat:
+ _existingConferenceForAVChatGUID:
+ _hasAVConferenceObjectsForChatsOtherThan:
+ _imAVChatParticipantForConference:callID:errorString:
+ capabilities
- dealloc
- init
- controller
- conference:didStartSession:withUserInfo:
- conference:didStopWithCallID:error:
- conference:didStopWithCallID:error:callMetadata:
- conference:localIPChange:withCallID:
- conference:receivedNoRemotePacketsForTime:callID:
- conference:withCallID:remoteMediaStalled:
- conference:receivedFirstRemoteFrameForCallID:
- conference:remoteVideoAttributesChanged:callID:
- conference:remoteAudioPaused:callID:
- conference:remoteVideoPaused:callID:
- conference:remoteScreenAttributesChanged:callID:
- conference:updateInputMeterLevel:
- conference:updateOutputMeterLevel:
- conference:inititiateRelayRequest:requestDict:
- conference:sendRelayUpdate:updateDict:
- conference:cancelRelayRequest:requestDict:
- conference:videoQualityNotificationForCallID:isDegraded:isRemote:
- conference:withCallID:networkHint:
- conference:didChangeLocalVariablesForCallID:
- serverDiedForConference:
- stopPreview
- setLocalVideoLayer:
- localVideoLayer
- setRemoteVideoLayersFromChat:toChat:
- _notifyAboutPotentialCallForChat:
- _avChatDealloc:
- chatStateUpdated
- endConferenceForAVChat:
- isAVInterfaceReady
- initAVInterface
- processRemoteIPChanged:fromParticipant:
- natTypeForAVChat:
- endAVConferenceWithChat:callID:
- avChat:prepareConnectionWithCallInfo:
- avChat:generateCallInfoForID:service:usingRelay:callInfo:
- _conferenceEnded:
- isMuteForAVChat:
- avChat:setMute:
- isPausedForAVChat:
- avChat:setPaused:
- isSendingAudioForAVChat:
- avChat:setSendingAudio:
- isSendingVideoForAVChat:
- avChat:setSendingVideo:
- capabilitiesOfNetwork
- capabilitiesOfCPU
- startPreviewWithError:
- avChat:endConferenceForUserID:
- getNatIPFromICEData:
- supportsLayers
- remoteVideoLayerForChat:
- setRemoteVideoLayer:forChat:
- remoteVideoBackLayerForChat:
- setRemoteVideoBackLayer:forChat:
- localVideoBackLayer
- setLocalVideoBackLayer:
- supportsRelay
- handleRelayInitate:fromParticipant:callInfo:
- handleRelayUpdate:fromParticipant:callInfo:
- handleRelayCancel:fromParticipant:callInfo:
- _controller
- avChat:setLocalLandscapeAspectRatio:localPortraitAspectRatio:
- _submitLoggingInformation:forChat:
- _submitEndCallMetric:forCallID:
- updateAVChat:withCallMetadata:
- _setAudioSessionPropertiesForChat:
- _existingConferenceForAVChat:
- _configureAVConference:forChat:
- _avChatForConference:callID:errorString:
- _avChatForConference:
- _cleanupAVInterface
- _queueAVConferenceForCleanup:
- _conferenceForAVChat:
- _existingConferenceForAVChatGUID:
- _hasAVConferenceObjectsForChatsOtherThan:
- _imAVChatParticipantForConference:callID:errorString:
- capabilities
@end
