@interface IMService : NSObject
{

}

+ __ck_displayGUIDWithMessage:
+ __ck_displayCellClass
+ __ck_displayCellIdentifier
+ __ck_prewarmForDisplay
+ __ck_displayContactImage
+ __ck_displayContentAlignmentInsets
+ __ck_displayTranscriptOrientation
+ __ck_transcriptUsesTextAlignmentInsets
+ __ck_displayDuringSend
+ __ck_wantsDrawerLayout
+ __ck_displaySize:
+ __ck_displayColor
+ __ck_isSMS
+ __ck_isiMessage
+ __ck_displayName
+ attributedTranscriptText
+ __ck_maxRecipientCount
+ infoForPerson:
+ infoForAllPeople
+ infoForDisplayedPeople
+ copyWithZone:
+ isEnabled
+ name
+ localizedName
+ status
+ login
+ logout
+ initialSyncPerformed
+ localizedShortName
+ infoForScreenName:
+ infoForAllScreenNames
+ infoForPreferredScreenNames
+ canonicalFormOfID:
+ peopleWithScreenName:
+ screenNamesForPerson:
+ myScreenNames
- __ck_displayGUIDWithMessage:
- __ck_displayCellClass
- __ck_displayCellIdentifier
- __ck_prewarmForDisplay
- __ck_displayContactImage
- __ck_displayContentAlignmentInsets
- __ck_displayTranscriptOrientation
- __ck_transcriptUsesTextAlignmentInsets
- __ck_displayDuringSend
- __ck_wantsDrawerLayout
- __ck_displaySize:
- __ck_displayColor
- __ck_isSMS
- __ck_isiMessage
- __ck_displayName
- attributedTranscriptText
- __ck_maxRecipientCount
- infoForPerson:
- infoForAllPeople
- infoForDisplayedPeople
- copyWithZone:
- isEnabled
- name
- localizedName
- status
- login
- logout
- initialSyncPerformed
- localizedShortName
- infoForScreenName:
- infoForAllScreenNames
- infoForPreferredScreenNames
- canonicalFormOfID:
- peopleWithScreenName:
- screenNamesForPerson:
- myScreenNames
@end
