@interface LSApplicationWorkspace : NSObject
{

}

+ applicationsWithAudioComponents
+ unrestrictedApplications
+ uninstallApplication:withOptions:
+ establishConnection
+ remoteObserver
+ operationToOpenResource:usingApplication:uniqueDocumentIdentifier:userInfo:delegate:
+ operationToOpenResource:usingApplication:uniqueDocumentIdentifier:userInfo:
+ installApplication:withOptions:error:usingBlock:
+ installProgressForApplication:withPhase:
+ registerApplicationDictionary:withObserverNotification:
+ installPhaseFinishedForProgress:
+ uninstallApplication:withOptions:usingBlock:
+ clearCreatedProgressForBundleID:
+ removeInstallProgressForBundleID:
+ delegateProxy
+ applicationForOpeningResource:
+ directionsApplications
+ applicationsWithUIBackgroundModes
+ openApplicationWithBundleID:
+ operationToOpenResource:usingApplication:userInfo:
+ installedApplications
+ allInstalledApplications
+ placeholderApplications
+ allApplications
+ publicURLSchemes
+ installApplication:withOptions:
+ installApplication:withOptions:error:
+ registerApplicationDictionary:
+ registerApplication:
+ unregisterApplication:
+ invalidateIconCache:
+ clearAdvertisingIdentifier
+ _clearCachedAdvertisingIdentifier
+ deviceIdentifierForAdvertising
+ installProgressForBundleID:makeSynchronous:
+ _LSPrivateRebuildApplicationDatabasesForSystemApps:internal:user:
+ _LSPrivateRebuildLaunchServicesDatabase
+ applicationsAvailableForHandlingURLScheme:
+ privateURLSchemes
+ URLOverrideForURL:
+ openURL:
+ removeObserver:
+ deviceIdentifierForVendor
+ applicationsAvailableForOpeningDocument:
+ operationToOpenResource:usingApplication:uniqueDocumentIdentifier:sourceIsManaged:userInfo:delegate:
+ openURL:withOptions:
+ openSensitiveURL:withOptions:
+ addObserver:
+ applicationIsInstalled:
- applicationsWithAudioComponents
- unrestrictedApplications
- uninstallApplication:withOptions:
- establishConnection
- remoteObserver
- operationToOpenResource:usingApplication:uniqueDocumentIdentifier:userInfo:delegate:
- operationToOpenResource:usingApplication:uniqueDocumentIdentifier:userInfo:
- installApplication:withOptions:error:usingBlock:
- installProgressForApplication:withPhase:
- registerApplicationDictionary:withObserverNotification:
- installPhaseFinishedForProgress:
- uninstallApplication:withOptions:usingBlock:
- clearCreatedProgressForBundleID:
- removeInstallProgressForBundleID:
- delegateProxy
- applicationForOpeningResource:
- directionsApplications
- applicationsWithUIBackgroundModes
- openApplicationWithBundleID:
- operationToOpenResource:usingApplication:userInfo:
- installedApplications
- allInstalledApplications
- placeholderApplications
- allApplications
- publicURLSchemes
- installApplication:withOptions:
- installApplication:withOptions:error:
- registerApplicationDictionary:
- registerApplication:
- unregisterApplication:
- invalidateIconCache:
- clearAdvertisingIdentifier
- _clearCachedAdvertisingIdentifier
- deviceIdentifierForAdvertising
- installProgressForBundleID:makeSynchronous:
- _LSPrivateRebuildApplicationDatabasesForSystemApps:internal:user:
- _LSPrivateRebuildLaunchServicesDatabase
- applicationsAvailableForHandlingURLScheme:
- privateURLSchemes
- URLOverrideForURL:
- openURL:
- removeObserver:
- deviceIdentifierForVendor
- applicationsAvailableForOpeningDocument:
- operationToOpenResource:usingApplication:uniqueDocumentIdentifier:sourceIsManaged:userInfo:delegate:
- openURL:withOptions:
- openSensitiveURL:withOptions:
- addObserver:
- applicationIsInstalled:
@end
