@interface MCProfileConnection : NSObject
{
	id _messageCenter;
	pointer _observers;
	id _interactionServer;
	id _interactionDelegate;
	id _interactionLockDelayedContext;
	id _preflightResponse;
	id _originalProfileData;
	BOOL _needToRestoreOriginalProfileData;
	int _userInputTimeoutType;
	id _userInputTimer;
	id _notificationSyncQueue;
	id _notificationTokens;
}

+ mayOpenFromManagedToUnmanaged
+ mayOpenFromUnmanagedToManaged
+ isOpenInRestrictionInEffect
+ isAppManaged:
+ allowedOpenInAppBundleIDsAfterApplyingFilterToAppBundleIDs:originatingAppBundleID:originatingAccountIsManaged:
+ filteredMailSheetAccountsForBundleID:sourceAccountManagement:
+ isSupervised
+ cloudConfigurationDetails
+ storeCloudConfigurationDetails:
+ retrieveCloudConfigurationDetailsCompletionBlock:
+ isCloudConfigurationAvailable
+ markStoredProfileForPurposeAsInstalled:
+ profileDataStoredForPurpose:completionBlock:
+ retrieveAndStoreCloudConfigurationDetailsCompletionBlock:
+ retrieveCloudConfigurationFromURL:username:password:anchorCertificates:completionBlock:
+ wasCloudConfigurationApplied
+ wasTeslaCloudConfigurationApplied
+ cloudConfigurationUIDidCompleteWasApplied:
+ shouldSkipSetupPanes
+ isTeslaCloudConfigurationAvailable
+ shouldShowCloudConfigurationUI
+ installProfileDataStoredForPurpose:completionBlock:
+ storeProfileData:configurationSource:purpose:
+ shouldInstallStoredProfileForPurpose:
+ setupAssistantDidFinish
+ knownAirPrintIPPURLStrings
+ appWhitelistState
+ effectiveWhitelistedAppBundleIDs
+ isInSingleAppMode
+ isPasscodeRequiredToAccessWhitelistedApps
+ mayEnterPasscodeToAccessNonWhitelistedApps
+ parentalControlsAvailableAppBundleIDsForWhitelisting
+ parentalControlsWhitelistedAppBundleIDs
+ setParentalControlsWhitelistedAppBundleIDs:
+ isParentalControlsAllowPasscodeAccessToNonWhitelistedAppsUIForcedByRestrictions
+ parentalControlsAllowPasscodeAccessToNonWhitelistedApps
+ parentalControlsSetAllowPasscodeAccessToNonWhitelistedApps:
+ autonomousSingleAppModePermittedBundleIDs
+ hostMayPairWithOptions:challenge:
+ lockdownDidReceiveActivationRecord:
+ setUserBookmarks:
+ userBookmarks
+ stashUserBookmarksWithLabel:newUserBookmarks:
+ unstashUserBookmarksFromLabel:
+ defaultUserBookmarks
+ isWebFilterUIActive
+ setWebContentFilterAutoPermittedURLStrings:
+ addWebContentFilterAutoPermittedURLString:
+ addUserBookmark:
+ webContentFilterUserBlacklistedURLStrings
+ webContentFilterEffectiveBlacklistedURLStrings
+ setWebContentFilterUserBlacklistedURLStrings:
+ checkCarrierProfileForceInstallation:
+ messageCenter
+ publicMessageCenter
+ checkCarrierProfile
+ performBootTimeChecks
+ removeExpiredProfiles
+ storeCertificateData:forHostIdentifier:
+ rereadManagedAppAttributes
+ isAutomaticAppUpdatesAllowed
+ shutDown
+ isActivationLockAllowed
+ managedAppIDsWithFlags:
+ isFingerprintUnlockAllowed
+ managedWiFiNetworkNames
+ managedSystemConfigurationServiceIDs
+ doNotBackupAppIDs
+ doNotDocumentSyncAppIDs
+ processProfilesPostRestore
+ processProfilesPostMigrate
+ migratePostDataMigrator
+ isCloudKeychainSyncAllowed
+ isVehicleUIAllowed
+ isOTAPKIUpdatesAllowed
+ setAutomaticAppUpdatesAllowed:
+ isAutomaticAppUpdatesModificationAllowed
+ isWebTextDefineAllowed
+ isAdTrackingLimited
+ isLockScreenWiFiModificationAllowed
+ isAppInstallationAllowed
+ isAppRatingLimitInEffect
+ isAirDropAllowed
+ isLockScreenNotificationsViewAllowed
+ isLockScreenTodayViewAllowed
+ isLockScreenControlCenterAllowed
+ isControlCenterAllowedInApps
+ isAssistantUserGeneratedContentAllowed
+ isFingerprintModificationAllowed
+ isMUAllowed
+ setGracePeriod:passcode:completionBlock:
+ gracePeriod
+ setFingerprintUnlockAllowed:passcode:completionBlock:
+ isPasscodeRequired
+ isPasscodeRequiredByProfiles
+ passcodeExpiryDateOutError:
+ unlockDeviceWithPasscode:outError:
+ lockDeviceImmediately:
+ isPasscodeSet
+ notifyUserHasSeenComplianceMessageWithLastLockDate:
+ recomputeUserComplianceWarningSynchronously
+ _getPasscodeComplianceWarningExpiryDate:lastLockDate:outLocalizedTitle:outLocalizedMessage:
+ newPasscodeEntryScreenType
+ lockDevice
+ changePasscodeFrom:to:outError:
+ clearPasscodeWithEscrowKeybagData:secret:outError:
+ isContentProtectionInEffect
+ passcode:meetsCurrentConstraintsOutError:
+ currentPasscodeIsCompliantWithGlobalRestrictionsOutError:
+ currentPasscodeIsCompliantWithProfileRestrictionsOutError:
+ getPasscodeComplianceWarningLastLockDate:outLocalizedTitle:outLocalizedMessage:
+ getPasscodeComplianceWarningLastLockDate:completionBlock:
+ recomputeUserComplianceWarning
+ notifyClientsToRecomputeCompliance
+ unlockScreenType
+ localizedDescriptionOfCurrentPasscodeConstraints
+ effectiveBoolValueForSetting:
+ defaultValueForSetting:
+ setParametersForSettingsByType:passcode:
+ setParametersForSettingsByType:
+ setBoolValue:forSetting:passcode:
+ setValue:forSetting:passcode:
+ userSettings
+ defaultBoolValueForSetting:
+ defaultParametersForBoolSetting:
+ defaultParametersForValueSetting:
+ effectiveParametersForBoolSetting:
+ effectiveParametersForUnionSetting:
+ effectiveParametersForValueSetting:
+ effectiveParametersForIntersectionSetting:
+ isBoolSettingLockedDownByRestrictions:
+ isValueSettingLockedDownByRestrictions:
+ effectiveUserSettings
+ setParameters:forBoolSetting:
+ setParameters:forValueSetting:
+ setBoolValue:forSetting:
+ setValue:forSetting:
+ setValues:forIntersectionSetting:
+ setValues:forUnionSetting:
+ parametersForBoolSetting:
+ parametersForValueSetting:
+ parametersForIntersectionSetting:
+ parametersForUnionSetting:
+ defaultValuesForIntersectionSetting:
+ defaultValuesForUnionSetting:
+ defaultParametersForIntersectionSetting:
+ defaultParametersForUnionSetting:
+ effectiveValuesForIntersectionSetting:
+ effectiveValuesForUnionSetting:
+ isIntersectionSettingLockedDownByRestrictions:
+ isUnionSettingLockedDownByRestrictions:
+ removeBoolSetting:
+ removeValueSetting:
+ resetAllSettingsToDefaults
+ effectiveValueForSetting:
+ userInfoForClientUUID:
+ setUserInfo:forClientUUID:
+ applyRestrictionDictionary:clientType:clientUUID:localizedClientDescription:localizedWarningMessage:outRestrictionChanged:outEffectiveSettingsChanged:outError:
+ boolRestrictionForFeature:
+ valueRestrictionForFeature:
+ objectRestrictionForFeature:
+ allClientUUIDsForClientType:
+ effectiveRestrictions
+ applyRestrictionDictionary:clientType:clientUUID:localizedClientDescription:localizedWarningMessage:complianceBlocking:displayImmediateAlert:outRestrictionChanged:outEffectiveSettingsChanged:outError:
+ removeOrphanedClientRestrictions
+ effectiveWhitelistedAppsAndOptions
+ setInteractionDelegate:
+ installedProfileWithIdentifier:
+ _queueDataForAcceptance:originalFileName:transitionToUI:outError:
+ installedProfileIdentifiersWithFilterFlags:
+ installProfileData:options:outError:
+ removeProfileWithIdentifier:
+ _openSensitiveURLString:unlock:
+ transitionToProfileAcceptanceUIAndReturnToBundleID:
+ installedProfilesWithFilterFlags:
+ __checkForProfiledCrash
+ _doMCICDidUpdateStatus:params:
+ _doMCICDidBeginInstallingNextProfileData:params:
+ _doMCICDidFinish:params:
+ _doMCICRequestUserInput:params:
+ _doMCICPreflightResponse:params:
+ _doMCICShowUserWarnings:params:
+ _doMCICDidRequestCurrentPasscode:params:
+ installProfileData:options:interactionDelegate:
+ _detectProfiledCrashes
+ _registerSelectorsForInteractionServer:
+ _userInputTimerFired
+ _cancelUserInputTimeout
+ _setTimeoutWaitingForUserInputType:
+ _tearDownInteractionServer
+ __doMCICDidFinish:
+ installedProfileIdentifiers
+ popProfileDataFromHeadOfInstallationQueue
+ popProvisioningProfileDataFromHeadOfInstallationQueue
+ queueFileDataForAcceptance:originalFileName:outError:
+ removeProfilesFromInstallationQueue
+ installProfileData:outError:
+ removeProfileAsyncWithIdentifier:
+ removeProfileWithIdentifier:completion:
+ updateProfileWithIdentifier:outError:
+ acceptedMIMETypes
+ acceptedFileExtensions
+ transitionToProfileOverviewUI
+ transitionToProfileAcceptanceUI
+ showProfileErrorUIWithProfileIdentifier:outError:
+ installProvisioningProfileData:managingProfileIdentifier:outError:
+ removeProvisioningProfileWithUUID:outError:
+ installProfileData:interactionDelegate:
+ updateProfileWithIdentifier:interactionDelegate:
+ preflightUserInputResponses:forPayloadIndex:
+ cancelUserInputResponses
+ submitUserInputResponses:
+ respondToWarningsContinueInstallation:
+ respondToCurrentPasscodeRequestContinue:passcode:
+ isChaperoned
+ chaperoneOrganization
+ setDelegate:
+ profileFromProfileData:outError:
+ queueProfileDataForAcceptance:outError:
+ queueProfileDataForInstallation:outError:
+ queueFileDataForProfileInstallation:originalFileName:outError:
+ isPasscodeRequiredByPolicy
+ passcodeExpiryDate
+ validatePasscode:
+ validatePasscode:andUnlockContentProtectedDevice:
+ applyRestrictionDictionary:clientType:clientUUID:outRestrictionChanged:outEffectiveSettingsChanged:outError:
+ setPasscodeWasSetInBackup:
+ restrictedBoolValueForFeature:
+ valueForFeature:
+ objectForFeature:
+ effectiveRestrictedBoolValueForSetting:
+ dealloc
+ _init
+ removeObserver:
+ addObserver:
+ checkIn
+ _restrictionDidChange
+ _passcodePolicyDidChange
+ _passcodeDidChange
+ _profileListDidChange
+ _effectiveSettingsDidChange:
+ _defaultsDidChange
+ _appWhitelistDidChange:
+ _applyToObservers:
+ _internalDefaultsDidChange
+ checkInAsynchronously
+ .cxx_destruct
- mayOpenFromManagedToUnmanaged
- mayOpenFromUnmanagedToManaged
- isOpenInRestrictionInEffect
- isAppManaged:
- allowedOpenInAppBundleIDsAfterApplyingFilterToAppBundleIDs:originatingAppBundleID:originatingAccountIsManaged:
- filteredMailSheetAccountsForBundleID:sourceAccountManagement:
- isSupervised
- cloudConfigurationDetails
- storeCloudConfigurationDetails:
- retrieveCloudConfigurationDetailsCompletionBlock:
- isCloudConfigurationAvailable
- markStoredProfileForPurposeAsInstalled:
- profileDataStoredForPurpose:completionBlock:
- retrieveAndStoreCloudConfigurationDetailsCompletionBlock:
- retrieveCloudConfigurationFromURL:username:password:anchorCertificates:completionBlock:
- wasCloudConfigurationApplied
- wasTeslaCloudConfigurationApplied
- cloudConfigurationUIDidCompleteWasApplied:
- shouldSkipSetupPanes
- isTeslaCloudConfigurationAvailable
- shouldShowCloudConfigurationUI
- installProfileDataStoredForPurpose:completionBlock:
- storeProfileData:configurationSource:purpose:
- shouldInstallStoredProfileForPurpose:
- setupAssistantDidFinish
- knownAirPrintIPPURLStrings
- appWhitelistState
- effectiveWhitelistedAppBundleIDs
- isInSingleAppMode
- isPasscodeRequiredToAccessWhitelistedApps
- mayEnterPasscodeToAccessNonWhitelistedApps
- parentalControlsAvailableAppBundleIDsForWhitelisting
- parentalControlsWhitelistedAppBundleIDs
- setParentalControlsWhitelistedAppBundleIDs:
- isParentalControlsAllowPasscodeAccessToNonWhitelistedAppsUIForcedByRestrictions
- parentalControlsAllowPasscodeAccessToNonWhitelistedApps
- parentalControlsSetAllowPasscodeAccessToNonWhitelistedApps:
- autonomousSingleAppModePermittedBundleIDs
- hostMayPairWithOptions:challenge:
- lockdownDidReceiveActivationRecord:
- setUserBookmarks:
- userBookmarks
- stashUserBookmarksWithLabel:newUserBookmarks:
- unstashUserBookmarksFromLabel:
- defaultUserBookmarks
- isWebFilterUIActive
- setWebContentFilterAutoPermittedURLStrings:
- addWebContentFilterAutoPermittedURLString:
- addUserBookmark:
- webContentFilterUserBlacklistedURLStrings
- webContentFilterEffectiveBlacklistedURLStrings
- setWebContentFilterUserBlacklistedURLStrings:
- checkCarrierProfileForceInstallation:
- messageCenter
- publicMessageCenter
- checkCarrierProfile
- performBootTimeChecks
- removeExpiredProfiles
- storeCertificateData:forHostIdentifier:
- rereadManagedAppAttributes
- isAutomaticAppUpdatesAllowed
- shutDown
- isActivationLockAllowed
- managedAppIDsWithFlags:
- isFingerprintUnlockAllowed
- managedWiFiNetworkNames
- managedSystemConfigurationServiceIDs
- doNotBackupAppIDs
- doNotDocumentSyncAppIDs
- processProfilesPostRestore
- processProfilesPostMigrate
- migratePostDataMigrator
- isCloudKeychainSyncAllowed
- isVehicleUIAllowed
- isOTAPKIUpdatesAllowed
- setAutomaticAppUpdatesAllowed:
- isAutomaticAppUpdatesModificationAllowed
- isWebTextDefineAllowed
- isAdTrackingLimited
- isLockScreenWiFiModificationAllowed
- isAppInstallationAllowed
- isAppRatingLimitInEffect
- isAirDropAllowed
- isLockScreenNotificationsViewAllowed
- isLockScreenTodayViewAllowed
- isLockScreenControlCenterAllowed
- isControlCenterAllowedInApps
- isAssistantUserGeneratedContentAllowed
- isFingerprintModificationAllowed
- isMUAllowed
- setGracePeriod:passcode:completionBlock:
- gracePeriod
- setFingerprintUnlockAllowed:passcode:completionBlock:
- isPasscodeRequired
- isPasscodeRequiredByProfiles
- passcodeExpiryDateOutError:
- unlockDeviceWithPasscode:outError:
- lockDeviceImmediately:
- isPasscodeSet
- notifyUserHasSeenComplianceMessageWithLastLockDate:
- recomputeUserComplianceWarningSynchronously
- _getPasscodeComplianceWarningExpiryDate:lastLockDate:outLocalizedTitle:outLocalizedMessage:
- newPasscodeEntryScreenType
- lockDevice
- changePasscodeFrom:to:outError:
- clearPasscodeWithEscrowKeybagData:secret:outError:
- isContentProtectionInEffect
- passcode:meetsCurrentConstraintsOutError:
- currentPasscodeIsCompliantWithGlobalRestrictionsOutError:
- currentPasscodeIsCompliantWithProfileRestrictionsOutError:
- getPasscodeComplianceWarningLastLockDate:outLocalizedTitle:outLocalizedMessage:
- getPasscodeComplianceWarningLastLockDate:completionBlock:
- recomputeUserComplianceWarning
- notifyClientsToRecomputeCompliance
- unlockScreenType
- localizedDescriptionOfCurrentPasscodeConstraints
- effectiveBoolValueForSetting:
- defaultValueForSetting:
- setParametersForSettingsByType:passcode:
- setParametersForSettingsByType:
- setBoolValue:forSetting:passcode:
- setValue:forSetting:passcode:
- userSettings
- defaultBoolValueForSetting:
- defaultParametersForBoolSetting:
- defaultParametersForValueSetting:
- effectiveParametersForBoolSetting:
- effectiveParametersForUnionSetting:
- effectiveParametersForValueSetting:
- effectiveParametersForIntersectionSetting:
- isBoolSettingLockedDownByRestrictions:
- isValueSettingLockedDownByRestrictions:
- effectiveUserSettings
- setParameters:forBoolSetting:
- setParameters:forValueSetting:
- setBoolValue:forSetting:
- setValue:forSetting:
- setValues:forIntersectionSetting:
- setValues:forUnionSetting:
- parametersForBoolSetting:
- parametersForValueSetting:
- parametersForIntersectionSetting:
- parametersForUnionSetting:
- defaultValuesForIntersectionSetting:
- defaultValuesForUnionSetting:
- defaultParametersForIntersectionSetting:
- defaultParametersForUnionSetting:
- effectiveValuesForIntersectionSetting:
- effectiveValuesForUnionSetting:
- isIntersectionSettingLockedDownByRestrictions:
- isUnionSettingLockedDownByRestrictions:
- removeBoolSetting:
- removeValueSetting:
- resetAllSettingsToDefaults
- effectiveValueForSetting:
- userInfoForClientUUID:
- setUserInfo:forClientUUID:
- applyRestrictionDictionary:clientType:clientUUID:localizedClientDescription:localizedWarningMessage:outRestrictionChanged:outEffectiveSettingsChanged:outError:
- boolRestrictionForFeature:
- valueRestrictionForFeature:
- objectRestrictionForFeature:
- allClientUUIDsForClientType:
- effectiveRestrictions
- applyRestrictionDictionary:clientType:clientUUID:localizedClientDescription:localizedWarningMessage:complianceBlocking:displayImmediateAlert:outRestrictionChanged:outEffectiveSettingsChanged:outError:
- removeOrphanedClientRestrictions
- effectiveWhitelistedAppsAndOptions
- setInteractionDelegate:
- installedProfileWithIdentifier:
- _queueDataForAcceptance:originalFileName:transitionToUI:outError:
- installedProfileIdentifiersWithFilterFlags:
- installProfileData:options:outError:
- removeProfileWithIdentifier:
- _openSensitiveURLString:unlock:
- transitionToProfileAcceptanceUIAndReturnToBundleID:
- installedProfilesWithFilterFlags:
- __checkForProfiledCrash
- _doMCICDidUpdateStatus:params:
- _doMCICDidBeginInstallingNextProfileData:params:
- _doMCICDidFinish:params:
- _doMCICRequestUserInput:params:
- _doMCICPreflightResponse:params:
- _doMCICShowUserWarnings:params:
- _doMCICDidRequestCurrentPasscode:params:
- installProfileData:options:interactionDelegate:
- _detectProfiledCrashes
- _registerSelectorsForInteractionServer:
- _userInputTimerFired
- _cancelUserInputTimeout
- _setTimeoutWaitingForUserInputType:
- _tearDownInteractionServer
- __doMCICDidFinish:
- installedProfileIdentifiers
- popProfileDataFromHeadOfInstallationQueue
- popProvisioningProfileDataFromHeadOfInstallationQueue
- queueFileDataForAcceptance:originalFileName:outError:
- removeProfilesFromInstallationQueue
- installProfileData:outError:
- removeProfileAsyncWithIdentifier:
- removeProfileWithIdentifier:completion:
- updateProfileWithIdentifier:outError:
- acceptedMIMETypes
- acceptedFileExtensions
- transitionToProfileOverviewUI
- transitionToProfileAcceptanceUI
- showProfileErrorUIWithProfileIdentifier:outError:
- installProvisioningProfileData:managingProfileIdentifier:outError:
- removeProvisioningProfileWithUUID:outError:
- installProfileData:interactionDelegate:
- updateProfileWithIdentifier:interactionDelegate:
- preflightUserInputResponses:forPayloadIndex:
- cancelUserInputResponses
- submitUserInputResponses:
- respondToWarningsContinueInstallation:
- respondToCurrentPasscodeRequestContinue:passcode:
- isChaperoned
- chaperoneOrganization
- setDelegate:
- profileFromProfileData:outError:
- queueProfileDataForAcceptance:outError:
- queueProfileDataForInstallation:outError:
- queueFileDataForProfileInstallation:originalFileName:outError:
- isPasscodeRequiredByPolicy
- passcodeExpiryDate
- validatePasscode:
- validatePasscode:andUnlockContentProtectedDevice:
- applyRestrictionDictionary:clientType:clientUUID:outRestrictionChanged:outEffectiveSettingsChanged:outError:
- setPasscodeWasSetInBackup:
- restrictedBoolValueForFeature:
- valueForFeature:
- objectForFeature:
- effectiveRestrictedBoolValueForSetting:
- dealloc
- _init
- removeObserver:
- addObserver:
- checkIn
- _restrictionDidChange
- _passcodePolicyDidChange
- _passcodeDidChange
- _profileListDidChange
- _effectiveSettingsDidChange:
- _defaultsDidChange
- _appWhitelistDidChange:
- _applyToObservers:
- _internalDefaultsDidChange
- checkInAsynchronously
- .cxx_destruct
@end
