@interface MCProfileServiceServer : NSObject
{
	id _messageCenter;
	id _publicMessageCenter;
	id _workerQueue;
	id _workerGroup;
	BOOL _memberQueueNeedToRecomputeNagMetadata;
	int _powerAssertionAssertedNotificationToken;
	int _powerAssertionDeassertedNotificationToken;
	int _mobileKeybagLockStateChangeNotificationToken;
	id _delegate;
	id _memberQueue;
	id _memberQueueTimerContext;
	double _memberQueueIdleTimeInterval;
}

+ setIdleTimeInterval:
+ popProfileDataFromHeadOfInstallationQueue:params:
+ queueProfileDataForInstallation:params:
+ installProfileData:params:
+ updateProfileIdentifier:params:
+ updateProfileIdentifierInteractive:params:
+ installProfileDataInteractive:params:
+ removeProfileWithIdentifier:param:
+ removeProfileAsyncWithIdentifier:param:
+ applyRestrictionDictionary:params:
+ changePasscode:params:
+ clearPasscode:params:
+ removeOrphanedClientTruths:params:
+ managedSystemConfigurationServiceIDs:params:
+ managedWiFiNetworkNames:params:
+ processProfilesPostRestore:params:
+ processProfilesPostMigrate:params:
+ migratePostDataMigrator:params:
+ setParametersForSettingsByType:params:
+ removeBoolSetting:params:
+ removeValueSetting:params:
+ openSensitiveURL:params:
+ storeCertificateDataForHostIdentifier:params:
+ installProvisioningProfileData:params:
+ removeProvisioningProfile:params:
+ popProvisioningProfileFromHeadOfInstallationQueue:params:
+ crashDetection:params:
+ notifyStartComplianceTimer:params:
+ notifyHaveSeenComplianceMessage:params:
+ removeProfilesFromInstallationQueue:params:
+ recomputeNagMetadata:params:
+ recomputeNagMetadataSynchronously:params:
+ recomputeClientCompliance:params:
+ resetAllSettingsToDefaults:params:
+ setUserInfoForClientUUID:params:
+ managedAppIDsWithFlags:params:
+ removeExpiredProfiles:params:
+ storeProfileData:params:
+ profileStoredForPurpose:params:
+ markStoredProfileAsInstalled:params:
+ rereadManagedAppAttributes:params:
+ cloudConfigurationMachineInfoData:params:
+ cloudConfigurationStoreDetails:params:
+ storeActivationRecord:params:
+ setUserBookmarks:params:
+ stashUserBookmarks:params:
+ unstashUserBookmarks:params:
+ checkIn:params:
+ checkCarrierProfile:params:
+ performBootTimeChecks:params:
+ shutDown:params:
+ allowedOpenInAppBundleIDs:params:auditToken:
+ setAllowedURLStrings:params:
+ addAllowedURLString:params:
+ addBookmark:params:
+ memberQueueTimerContext
+ setMemberQueueTimerContext:
+ memberQueueNeedToRecomputeNagMetadata
+ memberQueueIdleTimeInterval
+ _startIdleTimerWithTimeInterval:context:
+ didReceiveKeybagLockStateChangeNotification
+ _workerQueuePrepareForService
+ workerQueueRecomputeNagMessage
+ _idleTimeout
+ setMemberQueueIdleTimeInterval:
+ setMemberQueueNeedToRecomputeNagMetadata:
+ workerQueueDidRecomputeNagMessageWithResult:
+ _startCrashDetection
+ _stopCrashDetiction
+ _sendRestrictionChangedNotification
+ _sendEffectiveSettingsChangedNotification
+ bookmarkDictsFromBookmarks:
+ setURLsFromUserBookmarkDictsAsSettings:
+ _removeAllCarrierProfiles
+ _checkCarrierProfileForceReinstallation:
+ _badProvisioningProfileError
+ workerQueueRemoveExpiredProfiles
+ bookmarksFromBookmarkDicts:
+ idleTimeInterval
+ powerAssertionAssertedNotificationToken
+ setPowerAssertionAssertedNotificationToken:
+ powerAssertionDeassertedNotificationToken
+ setPowerAssertionDeassertedNotificationToken:
+ mobileKeybagLockStateChangeNotificationToken
+ setMobileKeybagLockStateChangeNotificationToken:
+ dealloc
+ setDelegate:
+ init
+ delegate
+ start
+ stop
+ memberQueue
+ setMemberQueue:
+ removeExpiredProfiles
+ storeCloudConfigurationDetails:
+ fetchConfigurationWithCompletionBlock:
+ mayOpenFromManagedToUnmanaged
+ mayOpenFromUnmanagedToManaged
+ isOpenInRestrictionInEffect
+ .cxx_destruct
- setIdleTimeInterval:
- popProfileDataFromHeadOfInstallationQueue:params:
- queueProfileDataForInstallation:params:
- installProfileData:params:
- updateProfileIdentifier:params:
- updateProfileIdentifierInteractive:params:
- installProfileDataInteractive:params:
- removeProfileWithIdentifier:param:
- removeProfileAsyncWithIdentifier:param:
- applyRestrictionDictionary:params:
- changePasscode:params:
- clearPasscode:params:
- removeOrphanedClientTruths:params:
- managedSystemConfigurationServiceIDs:params:
- managedWiFiNetworkNames:params:
- processProfilesPostRestore:params:
- processProfilesPostMigrate:params:
- migratePostDataMigrator:params:
- setParametersForSettingsByType:params:
- removeBoolSetting:params:
- removeValueSetting:params:
- openSensitiveURL:params:
- storeCertificateDataForHostIdentifier:params:
- installProvisioningProfileData:params:
- removeProvisioningProfile:params:
- popProvisioningProfileFromHeadOfInstallationQueue:params:
- crashDetection:params:
- notifyStartComplianceTimer:params:
- notifyHaveSeenComplianceMessage:params:
- removeProfilesFromInstallationQueue:params:
- recomputeNagMetadata:params:
- recomputeNagMetadataSynchronously:params:
- recomputeClientCompliance:params:
- resetAllSettingsToDefaults:params:
- setUserInfoForClientUUID:params:
- managedAppIDsWithFlags:params:
- removeExpiredProfiles:params:
- storeProfileData:params:
- profileStoredForPurpose:params:
- markStoredProfileAsInstalled:params:
- rereadManagedAppAttributes:params:
- cloudConfigurationMachineInfoData:params:
- cloudConfigurationStoreDetails:params:
- storeActivationRecord:params:
- setUserBookmarks:params:
- stashUserBookmarks:params:
- unstashUserBookmarks:params:
- checkIn:params:
- checkCarrierProfile:params:
- performBootTimeChecks:params:
- shutDown:params:
- allowedOpenInAppBundleIDs:params:auditToken:
- setAllowedURLStrings:params:
- addAllowedURLString:params:
- addBookmark:params:
- memberQueueTimerContext
- setMemberQueueTimerContext:
- memberQueueNeedToRecomputeNagMetadata
- memberQueueIdleTimeInterval
- _startIdleTimerWithTimeInterval:context:
- didReceiveKeybagLockStateChangeNotification
- _workerQueuePrepareForService
- workerQueueRecomputeNagMessage
- _idleTimeout
- setMemberQueueIdleTimeInterval:
- setMemberQueueNeedToRecomputeNagMetadata:
- workerQueueDidRecomputeNagMessageWithResult:
- _startCrashDetection
- _stopCrashDetiction
- _sendRestrictionChangedNotification
- _sendEffectiveSettingsChangedNotification
- bookmarkDictsFromBookmarks:
- setURLsFromUserBookmarkDictsAsSettings:
- _removeAllCarrierProfiles
- _checkCarrierProfileForceReinstallation:
- _badProvisioningProfileError
- workerQueueRemoveExpiredProfiles
- bookmarksFromBookmarkDicts:
- idleTimeInterval
- powerAssertionAssertedNotificationToken
- setPowerAssertionAssertedNotificationToken:
- powerAssertionDeassertedNotificationToken
- setPowerAssertionDeassertedNotificationToken:
- mobileKeybagLockStateChangeNotificationToken
- setMobileKeybagLockStateChangeNotificationToken:
- dealloc
- setDelegate:
- init
- delegate
- start
- stop
- memberQueue
- setMemberQueue:
- removeExpiredProfiles
- storeCloudConfigurationDetails:
- fetchConfigurationWithCompletionBlock:
- mayOpenFromManagedToUnmanaged
- mayOpenFromUnmanagedToManaged
- isOpenInRestrictionInEffect
- .cxx_destruct
@end
