@interface MPMediaItem : MPMediaEntity
{

}

+ MPSD_isDownloadable
+ MPSD_isDownloadInProgress
+ mediaTypeCanSeedGenius
+ artist
+ composer
+ genre
+ albumTrackNumber
+ representativeItem
+ stopTime
+ setRating:
+ albumArtist
+ bookmarkTime
+ isITunesU
+ artwork
+ initWithPersistentID:
+ _directStoreURL
+ _libraryLinkURL
+ playbackDuration
+ chaptersOfType:
+ _libraryLinkKind
+ _libraryLinkArtist
+ _libraryLinkPlaylistName
+ itemArrayCoderPIDDataCodingClass
+ valuesForProperties:
+ didSkipWithPlayedToTime:
+ markNominalAmountHasBeenPlayed
+ noteWasPlayedToTime:skipped:
+ incrementSkipCount
+ incrementPlayCountForPlayingToEnd
+ incrementPlayCountForStopTime:
+ updateDateAccessedToCurrentDateWithWriteCompletionBlock:
+ _bestStoreURL
+ albumTitle
+ isRental
+ effectiveStopTime
+ podcastTitle
+ rating
+ releaseDate
+ predicateForProperty:
+ playCount
+ setPlayCount:
+ playCountSinceSync
+ setPlayCountSinceSync:
+ lastPlayedDate
+ setLastPlayedDate:
+ dateAccessed
+ setDateAccessed:
+ skipCount
+ setSkipCount:
+ skipCountSinceSync
+ setSkipCountSinceSync:
+ lastSkippedDate
+ setLastSkippedDate:
+ hasBeenPlayed
+ setHasBeenPlayed:
+ rememberBookmarkTime
+ chapterOfType:atIndex:
+ chapterOfType:atTime:
+ countOfChaptersOfType:
+ gaplessHeuristicInfo:durationInSamples:lastPacketsResync:encodingDelay:encodingDrain:
+ isUsableAsRepresentativeItem
+ initWithCoder:
+ encodeWithCoder:
+ isEqual:
+ hash
+ didReceiveMemoryWarning
+ title
+ year
+ startTime
+ valueForProperty:
+ existsInLibrary
+ chapters
+ populateLocationPropertiesWithPath:
+ effectiveAlbumArtist
+ mediaType
- MPSD_isDownloadable
- MPSD_isDownloadInProgress
- mediaTypeCanSeedGenius
- artist
- composer
- genre
- albumTrackNumber
- representativeItem
- stopTime
- setRating:
- albumArtist
- bookmarkTime
- isITunesU
- artwork
- initWithPersistentID:
- _directStoreURL
- _libraryLinkURL
- playbackDuration
- chaptersOfType:
- _libraryLinkKind
- _libraryLinkArtist
- _libraryLinkPlaylistName
- itemArrayCoderPIDDataCodingClass
- valuesForProperties:
- didSkipWithPlayedToTime:
- markNominalAmountHasBeenPlayed
- noteWasPlayedToTime:skipped:
- incrementSkipCount
- incrementPlayCountForPlayingToEnd
- incrementPlayCountForStopTime:
- updateDateAccessedToCurrentDateWithWriteCompletionBlock:
- _bestStoreURL
- albumTitle
- isRental
- effectiveStopTime
- podcastTitle
- rating
- releaseDate
- predicateForProperty:
- playCount
- setPlayCount:
- playCountSinceSync
- setPlayCountSinceSync:
- lastPlayedDate
- setLastPlayedDate:
- dateAccessed
- setDateAccessed:
- skipCount
- setSkipCount:
- skipCountSinceSync
- setSkipCountSinceSync:
- lastSkippedDate
- setLastSkippedDate:
- hasBeenPlayed
- setHasBeenPlayed:
- rememberBookmarkTime
- chapterOfType:atIndex:
- chapterOfType:atTime:
- countOfChaptersOfType:
- gaplessHeuristicInfo:durationInSamples:lastPacketsResync:encodingDelay:encodingDrain:
- isUsableAsRepresentativeItem
- initWithCoder:
- encodeWithCoder:
- isEqual:
- hash
- didReceiveMemoryWarning
- title
- year
- startTime
- valueForProperty:
- existsInLibrary
- chapters
- populateLocationPropertiesWithPath:
- effectiveAlbumArtist
- mediaType
@end
