@interface MPMediaLibrary : NSObject
{
	id _libraryDataProvider;
	long long _libraryChangeObservers;
	id _entityCacheQueue;
	id _fixedQueue;
	id _itemsForCriteriaCache;
	id _hasItemsForCriteriaCache;
	id _countOfItemsForCriteriaCache;
	id _itemResultSetsForCriteriaCache;
	id _collectionsForCriteriaCache;
	id _hasCollectionsForCriteriaCache;
	id _countOfCollectionsForCriteriaCache;
	id _collectionsResultSetsForCriteriaCache;
	id _hasItemsDidLoadForCriteria;
	id _hasCollectionsDidLoadForCriteria;
	id _countOfCollectionsDidLoadForCriteria;
	id _countOfItemsDidLoadForCriteria;
	id _additionalLibraryFilterPredicates;
	id _additionalLibraryFilterPredicatesAccessQueue;
	id _connectionAssertions;
	BOOL _disconnectAfterReleasingAssertions;
	float _connectionProgress;
	id _connectionProgressDisplayLink;
	double _connectionProgressStartTime;
	long long _removalReason;
	bit[1] _determinedHasMedia;
	bit[1] _hasMedia;
	bit[1] _determinedHasSongs;
	bit[1] _hasSongs;
	bit[1] _determinedHasGeniusMixes;
	bit[1] _hasGeniusMixes;
	bit[1] _determinedHasPlaylists;
	bit[1] _hasPlaylists;
	bit[1] _determinedHasComposers;
	bit[1] _hasComposers;
	bit[1] _determinedHasPodcasts;
	bit[1] _hasPodcasts;
	bit[1] _determinedHasUbiquitousBookmarkableItems;
	bit[1] _hasUbiquitousBookmarkableContent;
	bit[1] _determinedHasAudiobooks;
	bit[1] _hasAudiobooks;
	long long _cloudFilteringType;
	BOOL _filteringDisabled;
	BOOL _hasVideos;
	BOOL _determinedHasVideos;
	BOOL _hasMusicVideos;
	BOOL _determinedHasMusicVideos;
	BOOL _hasAudibleAudioBooks;
	BOOL _determinedHasAudibleAudioBooks;
	BOOL _hasMovies;
	BOOL _determinedHasMovies;
	BOOL _hasCompilations;
	BOOL _determinedHasCompilations;
	BOOL _hasITunesU;
	BOOL _determinedHasITunesU;
	BOOL _hasVideoITunesU;
	BOOL _determinedHasVideoITunesU;
	BOOL _hasMovieRentals;
	BOOL _determinedHasMovieRentals;
	BOOL _hasTVShows;
	BOOL _determinedHasTVShows;
	BOOL _hasHomeVideos;
	BOOL _determinedHasHomeVideos;
	BOOL _hasVideoPodcasts;
	BOOL _determinedHasVideoPodcasts;
	unsigned char _originalCellNetworkFlags;
	unsigned char _originalWiFiNetworkFlags;
}

@end
