@interface MPMediaQueryNowPlayingItem : MPAVItem
{
	id _mediaItem;
	id _cache;
}

+ mainTitle
+ artist
+ composer
+ genre
+ albumTrackNumber
+ albumTrackCount
+ discNumber
+ discCount
+ supportsRewindAndFastForward15Seconds
+ isExplicitTrack
+ artworkImageData
+ artworkMIMEType
+ chapterTimeMarkers
+ setAlternateAudioTrackID:
+ loadAssetAndPlayerItem
+ displayableText
+ useEmbeddedChapterData
+ imageCacheRequestWithSize:time:usePlaceholderAsFallback:
+ artworkTimeMarkers
+ urlTimeMarkers
+ durationFromExternalMetadata
+ customAVEQPreset
+ allowsEQ
+ isSupportedDefaultPlaybackSpeed:
+ setPlaybackStoppedTime:
+ notePlaybackFinishedByHittingEnd
+ playbackCheckpointCurrentTime
+ setPlaybackCheckpointCurrentTime:
+ setPlaybackFinishedTime:
+ setRating:
+ albumArtist
+ canSeedGenius
+ isValidPlayerSubstituteForItem:
+ isPlaceholderForItem:
+ isAssetURLValid
+ hasAlternatesForTypes:
+ hasDataForItemArtwork
+ isStreamable
+ supportsAddStation
+ imageCache
+ titlesForTime:
+ reevaluateType
+ mediaItem
+ setLoudnessInfoVolumeNormalization:
+ initWithMediaItem:
+ _newTimeMarkersForChapterType:
+ _handlePlaybackFinishedTime:finishedByHittingEnd:
+ _applyLoudnessInfo
+ _updateBookmarkTimeIfNecessary:isCheckpoint:
+ _chapterTitleForTime:
+ handlePlaybackFinishedTime:finishedByHittingEnd:
+ description
+ type
+ persistentID
+ userRating
+ album
+ .cxx_destruct
- mainTitle
- artist
- composer
- genre
- albumTrackNumber
- albumTrackCount
- discNumber
- discCount
- supportsRewindAndFastForward15Seconds
- isExplicitTrack
- artworkImageData
- artworkMIMEType
- chapterTimeMarkers
- setAlternateAudioTrackID:
- loadAssetAndPlayerItem
- displayableText
- useEmbeddedChapterData
- imageCacheRequestWithSize:time:usePlaceholderAsFallback:
- artworkTimeMarkers
- urlTimeMarkers
- durationFromExternalMetadata
- customAVEQPreset
- allowsEQ
- isSupportedDefaultPlaybackSpeed:
- setPlaybackStoppedTime:
- notePlaybackFinishedByHittingEnd
- playbackCheckpointCurrentTime
- setPlaybackCheckpointCurrentTime:
- setPlaybackFinishedTime:
- setRating:
- albumArtist
- canSeedGenius
- isValidPlayerSubstituteForItem:
- isPlaceholderForItem:
- isAssetURLValid
- hasAlternatesForTypes:
- hasDataForItemArtwork
- isStreamable
- supportsAddStation
- imageCache
- titlesForTime:
- reevaluateType
- mediaItem
- setLoudnessInfoVolumeNormalization:
- initWithMediaItem:
- _newTimeMarkersForChapterType:
- _handlePlaybackFinishedTime:finishedByHittingEnd:
- _applyLoudnessInfo
- _updateBookmarkTimeIfNecessary:isCheckpoint:
- _chapterTitleForTime:
- handlePlaybackFinishedTime:finishedByHittingEnd:
- description
- type
- persistentID
- userRating
- album
- .cxx_destruct
@end
