@interface MPUDataSource : NSObject
{
	long long _entityType;
}

+ initWithEntityType:
+ entityType
+ initWithCoder:
+ encodeWithCoder:
+ count
+ invalidate
+ isEmpty
+ numberOfSections
+ dataSourceFromEntityAtIndex:entityType:
+ indexOfSectionForSectionTitleAtIndex:
+ indexOfSectionEntity:
+ titleForGlobalHeader
+ localizedSectionIndexTitles
+ entityIsNowPlayingAtIndex:
+ playbackContextForIndex:
+ invalidateCalculatedEntities
+ editingTypeForEntityAtIndex:
+ isIgnoringInvalidation
+ endIgnoringInvalidation
+ beginIgnoringInvalidation
+ entityCountFormat
+ showsEntityCountFooter
+ showsIndexBar
+ invalidateWithInsertedObjects:updatedObjects:deletedObjects:
+ canEditEntityAtIndex:
+ deleteEntityAtIndex:
+ rangeOfSectionAtIndex:
+ sectionEntityAtIndex:
+ anyEntity
+ canSelectEntityAtIndex:
+ dataSourceFromEntityAtIndex:
+ indexOfEntity:
+ sectionEntities
+ usesSections
+ localizedSectionTitleAtIndex:
+ entityAtIndex:
+ entities
- initWithEntityType:
- entityType
- initWithCoder:
- encodeWithCoder:
- count
- invalidate
- isEmpty
- numberOfSections
- dataSourceFromEntityAtIndex:entityType:
- indexOfSectionForSectionTitleAtIndex:
- indexOfSectionEntity:
- titleForGlobalHeader
- localizedSectionIndexTitles
- entityIsNowPlayingAtIndex:
- playbackContextForIndex:
- invalidateCalculatedEntities
- editingTypeForEntityAtIndex:
- isIgnoringInvalidation
- endIgnoringInvalidation
- beginIgnoringInvalidation
- entityCountFormat
- showsEntityCountFooter
- showsIndexBar
- invalidateWithInsertedObjects:updatedObjects:deletedObjects:
- canEditEntityAtIndex:
- deleteEntityAtIndex:
- rangeOfSectionAtIndex:
- sectionEntityAtIndex:
- anyEntity
- canSelectEntityAtIndex:
- dataSourceFromEntityAtIndex:
- indexOfEntity:
- sectionEntities
- usesSections
- localizedSectionTitleAtIndex:
- entityAtIndex:
- entities
@end
