@interface NSMutableSet : NSSet
{

}

+ filterUsingPredicate:
+ classForCoder
+ mf_uniquedObject:
+ CDVAddItemParserMappingWithNameSpace:name:parseClass:
+ setSet:
+ addObjects:count:
+ intersectOrderedSet:
+ replaceObject:
+ _mutate
+ removeObjectsWithOptions:passingTest:
+ addObjectsFromArray:range:
+ addObjectsFromOrderedSet:range:
+ addObjectsFromOrderedSet:
+ addObjectsFromSet:
+ removeObjectsInArray:range:
+ removeObjectsInOrderedSet:range:
+ removeObjectsInOrderedSet:
+ removeObjectsInSet:
+ removeObjectsPassingTest:
+ setOrderedSet:
+ removeObject:
+ addObject:
+ removeAllObjects
+ addObjectsFromArray:
+ removeObjectsInArray:
+ initWithCapacity:
+ intersectSet:
+ minusSet:
+ initWithObjects:count:
+ setArray:
+ setObject:
+ unionSet:
+ unionOrderedSet:
+ minusOrderedSet:
- filterUsingPredicate:
- classForCoder
- mf_uniquedObject:
- CDVAddItemParserMappingWithNameSpace:name:parseClass:
- setSet:
- addObjects:count:
- intersectOrderedSet:
- replaceObject:
- _mutate
- removeObjectsWithOptions:passingTest:
- addObjectsFromArray:range:
- addObjectsFromOrderedSet:range:
- addObjectsFromOrderedSet:
- addObjectsFromSet:
- removeObjectsInArray:range:
- removeObjectsInOrderedSet:range:
- removeObjectsInOrderedSet:
- removeObjectsInSet:
- removeObjectsPassingTest:
- setOrderedSet:
- removeObject:
- addObject:
- removeAllObjects
- addObjectsFromArray:
- removeObjectsInArray:
- initWithCapacity:
- intersectSet:
- minusSet:
- initWithObjects:count:
- setArray:
- setObject:
- unionSet:
- unionOrderedSet:
- minusOrderedSet:
@end
