@interface NSMutableOrderedSet : NSOrderedSet
{

}

+ filterUsingPredicate:
+ sortUsingDescriptors:
+ setSet:
+ addObjects:count:
+ insertObjects:count:atIndex:
+ sortRange:options:usingComparator:
+ setObject:atIndex:
+ replaceObjectsInRange:withObjects:count:
+ intersectOrderedSet:
+ replaceObject:
+ _mutate
+ insertObjectsFromArray:range:atIndex:
+ insertObjectsFromOrderedSet:range:atIndex:
+ insertObjectsFromSet:atIndex:
+ removeObjectsInRange:inArray:range:
+ removeObjectsInRange:inOrderedSet:range:
+ removeObjectsInRange:inSet:
+ removeObjectsWithOptions:passingTest:
+ addObjectsFromArray:range:
+ addObjectsFromOrderedSet:range:
+ addObjectsFromOrderedSet:
+ addObjectsFromSet:
+ insertObjectsFromArray:atIndex:
+ insertObjectsFromOrderedSet:atIndex:
+ removeFirstObject
+ removeObjectsInRange:inArray:
+ removeObjectsInArray:range:
+ removeObjectsInRange:inOrderedSet:
+ removeObjectsInOrderedSet:range:
+ removeObjectsInOrderedSet:
+ removeObjectsInSet:
+ removeObjectsAtIndexes:options:passingTest:
+ removeObjectsPassingTest:
+ replaceObject:inRange:
+ replaceObjectsInRange:withObjectsFromArray:range:
+ replaceObjectsInRange:withObjectsFromArray:
+ replaceObjectsInRange:withObjectsFromOrderedSet:range:
+ replaceObjectsInRange:withObjectsFromOrderedSet:
+ replaceObjectsInRange:withObjectsFromSet:
+ rollObjectsInRange:by:
+ setObject:atIndexedSubscript:
+ setOrderedSet:
+ removeObject:
+ addObject:
+ removeAllObjects
+ removeLastObject
+ addObjectsFromArray:
+ removeObjectsInArray:
+ initWithCapacity:
+ intersectSet:
+ minusSet:
+ insertObject:atIndex:
+ removeObjectAtIndex:
+ removeObject:inRange:
+ classForCoder
+ sortUsingComparator:
+ removeObjectsAtIndexes:
+ exchangeObjectAtIndex:withObjectAtIndex:
+ initWithObjects:count:
+ replaceObjectAtIndex:withObject:
+ removeObjectsInRange:
+ setArray:
+ setObject:
+ sortWithOptions:usingComparator:
+ unionSet:
+ insertObjects:atIndexes:
+ replaceObjectsAtIndexes:withObjects:
+ moveObjectsAtIndexes:toIndex:
+ unionOrderedSet:
+ minusOrderedSet:
- filterUsingPredicate:
- sortUsingDescriptors:
- setSet:
- addObjects:count:
- insertObjects:count:atIndex:
- sortRange:options:usingComparator:
- setObject:atIndex:
- replaceObjectsInRange:withObjects:count:
- intersectOrderedSet:
- replaceObject:
- _mutate
- insertObjectsFromArray:range:atIndex:
- insertObjectsFromOrderedSet:range:atIndex:
- insertObjectsFromSet:atIndex:
- removeObjectsInRange:inArray:range:
- removeObjectsInRange:inOrderedSet:range:
- removeObjectsInRange:inSet:
- removeObjectsWithOptions:passingTest:
- addObjectsFromArray:range:
- addObjectsFromOrderedSet:range:
- addObjectsFromOrderedSet:
- addObjectsFromSet:
- insertObjectsFromArray:atIndex:
- insertObjectsFromOrderedSet:atIndex:
- removeFirstObject
- removeObjectsInRange:inArray:
- removeObjectsInArray:range:
- removeObjectsInRange:inOrderedSet:
- removeObjectsInOrderedSet:range:
- removeObjectsInOrderedSet:
- removeObjectsInSet:
- removeObjectsAtIndexes:options:passingTest:
- removeObjectsPassingTest:
- replaceObject:inRange:
- replaceObjectsInRange:withObjectsFromArray:range:
- replaceObjectsInRange:withObjectsFromArray:
- replaceObjectsInRange:withObjectsFromOrderedSet:range:
- replaceObjectsInRange:withObjectsFromOrderedSet:
- replaceObjectsInRange:withObjectsFromSet:
- rollObjectsInRange:by:
- setObject:atIndexedSubscript:
- setOrderedSet:
- removeObject:
- addObject:
- removeAllObjects
- removeLastObject
- addObjectsFromArray:
- removeObjectsInArray:
- initWithCapacity:
- intersectSet:
- minusSet:
- insertObject:atIndex:
- removeObjectAtIndex:
- removeObject:inRange:
- classForCoder
- sortUsingComparator:
- removeObjectsAtIndexes:
- exchangeObjectAtIndex:withObjectAtIndex:
- initWithObjects:count:
- replaceObjectAtIndex:withObject:
- removeObjectsInRange:
- setArray:
- setObject:
- sortWithOptions:usingComparator:
- unionSet:
- insertObjects:atIndexes:
- replaceObjectsAtIndexes:withObjects:
- moveObjectsAtIndexes:toIndex:
- unionOrderedSet:
- minusOrderedSet:
@end
