@interface NSObject_QSExtras : NSObject_QSExtras_super
{

}

+ _accessibilitySpeakSelectionTextInputResponder
+ _accessibilityQuickSpeakContentIsSpeakable
+ _accessibilityQScanPerformAction:withSender:
+ _accessibilityShouldShowPauseBubble
+ _accessibilitySystemShouldShowPauseBubble
+ _accessibilityShouldShowSpeakLanguageBubble
+ _accessibilityShouldShowSpeakBubble
+ _accessibilitySystemShouldShowSpeakBubble
+ _accessibilitySystemShouldShowSpeakBubbleCommon
+ _accessibilityShouldUpdateQuickSpeakContent
+ _accessibilityCacheContentIfNecessary
+ _accessibilitySystemShouldShowSpeakLanguageBubble
+ _accessibilityQuickSpeakContent
+ _accessibilitySpeakWithLanguage:
+ _accessibilitySpeak:
+ _accessibilitySpeakLanguageSelection:
+ _accessibilityPauseSpeaking:
- _accessibilitySpeakSelectionTextInputResponder
- _accessibilityQuickSpeakContentIsSpeakable
- _accessibilityQScanPerformAction:withSender:
- _accessibilityShouldShowPauseBubble
- _accessibilitySystemShouldShowPauseBubble
- _accessibilityShouldShowSpeakLanguageBubble
- _accessibilityShouldShowSpeakBubble
- _accessibilitySystemShouldShowSpeakBubble
- _accessibilitySystemShouldShowSpeakBubbleCommon
- _accessibilityShouldUpdateQuickSpeakContent
- _accessibilityCacheContentIfNecessary
- _accessibilitySystemShouldShowSpeakLanguageBubble
- _accessibilityQuickSpeakContent
- _accessibilitySpeakWithLanguage:
- _accessibilitySpeak:
- _accessibilitySpeakLanguageSelection:
- _accessibilityPauseSpeaking:
@end
