@interface NSSQLAdapter : NSObject
{
	id _connections;
	id _sqlCore;
}

+ sqlCore
+ sqlTypeForExpressionConstantValue:
+ supportsCorrelatedSubqueries
+ statementClass
+ generatorClass
+ newStatementWithEntity:
+ newGeneratorWithStatement:
+ _originalRowForUpdate:
+ _newSelectStatementWithFetchRequest:ignoreInheritance:
+ newStatementWithoutEntity
+ typeStringForColumn:
+ newStatementWithSQLString:
+ typeStringForSQLType:
+ newCreateIndexStatementForColumnWithName:inTableWithName:
+ initWithSQLCore:
+ connections
+ hasOpenConnections
+ newInsertStatementWithRow:
+ newUpdateStatementWithRow:
+ newDeleteStatementWithRow:
+ newSelectStatementWithFetchRequest:
+ newCountStatementWithFetchRequest:
+ newInsertStatementWithCorrelation:
+ newUpdateStatementWithCorrelation:
+ newDeleteStatementWithCorrelation:
+ newCreateTableStatementForEntity:
+ newCreatePrimaryKeyTableStatement
+ newPrimaryKeyInitializeStatementForEntity:withInitialMaxPK:
+ newRenameTableStatementFromManyToMany:toManyToMany:orToRandomSpot:
+ newCopyAndInsertStatementForManyToMany:toManyToMany:intermediateTableName:invertColumns:
+ newDropTableStatementForTableNamed:
+ newRenameTableStatementFrom:to:
+ newCreateTableStatementForManyToMany:
+ newCreateIndexStatementForColumn:
+ newCreateIndexStatementForColumns:
+ registerConnection:
+ unregisterConnection:
+ dealloc
+ type
+ url
+ createConnection
- sqlCore
- sqlTypeForExpressionConstantValue:
- supportsCorrelatedSubqueries
- statementClass
- generatorClass
- newStatementWithEntity:
- newGeneratorWithStatement:
- _originalRowForUpdate:
- _newSelectStatementWithFetchRequest:ignoreInheritance:
- newStatementWithoutEntity
- typeStringForColumn:
- newStatementWithSQLString:
- typeStringForSQLType:
- newCreateIndexStatementForColumnWithName:inTableWithName:
- initWithSQLCore:
- connections
- hasOpenConnections
- newInsertStatementWithRow:
- newUpdateStatementWithRow:
- newDeleteStatementWithRow:
- newSelectStatementWithFetchRequest:
- newCountStatementWithFetchRequest:
- newInsertStatementWithCorrelation:
- newUpdateStatementWithCorrelation:
- newDeleteStatementWithCorrelation:
- newCreateTableStatementForEntity:
- newCreatePrimaryKeyTableStatement
- newPrimaryKeyInitializeStatementForEntity:withInitialMaxPK:
- newRenameTableStatementFromManyToMany:toManyToMany:orToRandomSpot:
- newCopyAndInsertStatementForManyToMany:toManyToMany:intermediateTableName:invertColumns:
- newDropTableStatementForTableNamed:
- newRenameTableStatementFrom:to:
- newCreateTableStatementForManyToMany:
- newCreateIndexStatementForColumn:
- newCreateIndexStatementForColumns:
- registerConnection:
- unregisterConnection:
- dealloc
- type
- url
- createConnection
@end
