@interface NSURLRequest : NSObject
{
	id _internal;
}

+ DARequestByApplyingStorageSession:
+ initWithXPCEncoding:
+ copyXPCEncoding
+ _web_HTTPReferrer
+ _web_HTTPContentType
+ _web_isConditionalRequest
+ HTTPShouldUsePipelining
+ HTTPShouldHandleCookies
+ valueForHTTPHeaderField:
+ HTTPMethod
+ allHTTPHeaderFields
+ HTTPBody
+ HTTPBodyStream
+ HTTPContentType
+ HTTPExtraCookies
+ HTTPReferrer
+ HTTPUserAgent
+ contentDispositionEncodingFallbackArray
+ networkServiceType
+ allowsCellularAccess
+ _URLHasScheme:
+ _propertyForKey:
+ _setProperty:forKey:
+ _removePropertyForKey:
+ _copyReplacingURLWithURL:
+ cachePolicy
+ timeoutInterval
+ mainDocumentURL
+ boundInterfaceIdentifier
+ dealloc
+ initWithCoder:
+ encodeWithCoder:
+ init
+ isEqual:
+ hash
+ description
+ copyWithZone:
+ URL
+ initWithURL:
+ mutableCopyWithZone:
+ initWithURL:cachePolicy:timeoutInterval:
+ _CFURLRequest
+ _initWithCFURLRequest:
- DARequestByApplyingStorageSession:
- initWithXPCEncoding:
- copyXPCEncoding
- _web_HTTPReferrer
- _web_HTTPContentType
- _web_isConditionalRequest
- HTTPShouldUsePipelining
- HTTPShouldHandleCookies
- valueForHTTPHeaderField:
- HTTPMethod
- allHTTPHeaderFields
- HTTPBody
- HTTPBodyStream
- HTTPContentType
- HTTPExtraCookies
- HTTPReferrer
- HTTPUserAgent
- contentDispositionEncodingFallbackArray
- networkServiceType
- allowsCellularAccess
- _URLHasScheme:
- _propertyForKey:
- _setProperty:forKey:
- _removePropertyForKey:
- _copyReplacingURLWithURL:
- cachePolicy
- timeoutInterval
- mainDocumentURL
- boundInterfaceIdentifier
- dealloc
- initWithCoder:
- encodeWithCoder:
- init
- isEqual:
- hash
- description
- copyWithZone:
- URL
- initWithURL:
- mutableCopyWithZone:
- initWithURL:cachePolicy:timeoutInterval:
- _CFURLRequest
- _initWithCFURLRequest:
@end
