@interface NSURLCache : NSObject
{
	id _internal;
}

+ diskCapacity
+ currentMemoryUsage
+ currentDiskUsage
+ cachedResponseForRequest:
+ storeCachedResponse:forRequest:
+ setDiskCapacity:
+ removeCachedResponseForRequest:
+ removeAllCachedResponses
+ initWithMemoryCapacity:diskCapacity:diskPath:
+ _initWithExistingCFURLCache:
+ _diskCacheDefaultPath
+ _memoryCacheRemoveNodeFromLRUList:
+ _memoryCacheAppendNodeToLRUList:
+ _memoryCacheTouchNode:
+ _memoryCacheTruncate:
+ _diskCacheSync
+ _diskCacheExecuteWrite:
+ _diskCacheExecuteRemoval:
+ _diskCacheSetSyncTimer
+ _cacheDirectory
+ _diskCacheCreateLRUList:
+ _diskCacheCreateDirectory
+ _diskCacheClear
+ _diskCacheTruncate:
+ _nscfBridgeURLCacheCopyResponseForRequest:
+ _nscfBridgeURLCacheStoreCachedResponse:forRequest:
+ _nscfBridgeURLCacheDiskCapacity
+ _nscfBridgeURLCacheSetMemoryCapacity:
+ _nscfBridgeURLCacheSetDiskCapacity:
+ _nscfBridgeURLCacheRemoveCachedResponseForRequest:
+ _nscfBridgeURLCacheRemoveAllCachedResponses
+ _nscfBridgeURLCacheMemoryCapacity
+ _nscfBridgeURLCacheCurrentMemoryUsage
+ _nscfBridgeURLCacheCurrentDiskUsage
+ initWithExistingSharedCFURLCache:
+ _cacheStatistics
+ _CFURLCache
+ _memoryCacheGet:
+ _memoryCachePut:
+ _memoryCacheRemove:
+ _memoryCacheClear
+ _diskCacheGet:
+ _diskCacheScheduleWrite:
+ _diskCacheScheduleRemoval:
+ dealloc
+ init
+ memoryCapacity
+ setMemoryCapacity:
- diskCapacity
- currentMemoryUsage
- currentDiskUsage
- cachedResponseForRequest:
- storeCachedResponse:forRequest:
- setDiskCapacity:
- removeCachedResponseForRequest:
- removeAllCachedResponses
- initWithMemoryCapacity:diskCapacity:diskPath:
- _initWithExistingCFURLCache:
- _diskCacheDefaultPath
- _memoryCacheRemoveNodeFromLRUList:
- _memoryCacheAppendNodeToLRUList:
- _memoryCacheTouchNode:
- _memoryCacheTruncate:
- _diskCacheSync
- _diskCacheExecuteWrite:
- _diskCacheExecuteRemoval:
- _diskCacheSetSyncTimer
- _cacheDirectory
- _diskCacheCreateLRUList:
- _diskCacheCreateDirectory
- _diskCacheClear
- _diskCacheTruncate:
- _nscfBridgeURLCacheCopyResponseForRequest:
- _nscfBridgeURLCacheStoreCachedResponse:forRequest:
- _nscfBridgeURLCacheDiskCapacity
- _nscfBridgeURLCacheSetMemoryCapacity:
- _nscfBridgeURLCacheSetDiskCapacity:
- _nscfBridgeURLCacheRemoveCachedResponseForRequest:
- _nscfBridgeURLCacheRemoveAllCachedResponses
- _nscfBridgeURLCacheMemoryCapacity
- _nscfBridgeURLCacheCurrentMemoryUsage
- _nscfBridgeURLCacheCurrentDiskUsage
- initWithExistingSharedCFURLCache:
- _cacheStatistics
- _CFURLCache
- _memoryCacheGet:
- _memoryCachePut:
- _memoryCacheRemove:
- _memoryCacheClear
- _diskCacheGet:
- _diskCacheScheduleWrite:
- _diskCacheScheduleRemoval:
- dealloc
- init
- memoryCapacity
- setMemoryCapacity:
@end
