@interface PLGatekeeperClient : NSObject
{
	id _serialReplyQueue;
	id connection;
}

+ init
+ connection
+ setConnection:
+ fileURLForAssetURL:withAdjustments:
+ getPhotosAndVideosCountWithHandler:
+ cleanupModelAfteriTunesRestore
+ dataMigrationWillFinish
+ getLibrarySizes:
+ replyQueue
+ sendQueue
+ deviceSpecificReplyQueue
+ fileDescriptorForAssetURL:
+ addGroupWithName:handler:
+ addAssetWithURL:toAlbumWithUUID:handler:
+ deleteAssetWithURL:handler:
+ setExternalUsageIntent:forAssetWithURL:handler:
+ setLargePreviewImageForAssetWithURL:imageData:properties:handler:
+ finalizeOTARestoreRecreatingAlbums:
+ updateRestoredAssetWithUUID:paths:
+ clearChangeStore
+ getCurrentBulletins
+ getCurrentApplicationBadgeCount
+ getThumbnailImageDataForBulletinWithRecordID:
+ clearAllBulletinsWithLastClearedRecordID:
+ rebuildMomentsIncremental:
+ rebuildMomentLists
+ analyzeAllMoments
+ rebuildCloudFeed
+ resetDupesAnalysis
+ rebuildAllThumbnails
+ analyzeInvalidMomentsAndDupesIfNeeded
+ notifyAboutTerminationDueToUncaughtException:
+ launchAssetsd
+ importFileSystemAssetsWaitingForReply:
+ enablePhotostreamsWithStreamID:
+ updateModelAfterOTARestore
+ repairSingletonObjects
+ createPhotoLibraryDatabase
+ hasCompletedRestorePostProcessing
+ hasCompletedMomentAnalysis
+ recoverFromCrashIfNeeded
+ cleanupForStoreDemoMode
+ requestAccessWithHandler:
+ fileURLForNewAssetWithType:extension:
+ imageDataForAsset:format:
+ requestImageDataForAsset:format:handler:
+ batchSaveAssetsWithJobDictionaries:handler:
+ waitUntilConnectionSendsAllMessages
+ saveAssetWithJobDictionary:handler:imageSurface:previewImageSurface:
+ downloadAsset:requestThumbnail:shouldPrioritize:shouldExtendTimer:
+ updateThumbnailsForPhotos:waitForReply:assignNewIndex:forceRefresh:
+ createPhotostreamAlbumWithStreamID:
+ automaticallyDeleteEmptyAlbum:
+ updateCameraPreviewWellImage:
+ recalculateCachedAlbumCounts
+ getCurrentModelVersion
+ repairPotentialModelCorruption
+ secondsNeededToCleanupModelAfteriTunesRestore
+ writeDataInBackground:toFileURL:
+ estimatedOutputFileLengthForVideoURL:fallbackFilePath:exportPreset:exportProperties:
+ personInfoDictionaryForPersonID:
+ setPersonInfoDictionary:forPersonID:
+ sendDaemonJob:replyHandler:
+ updateSharedAlbumsCachedServerConfigurationLimits
+ purgeableSharedAssetsSpace
+ attemptToPurgeSharedAssetsSpace:
+ emailAddressForKey:
+ keyForEmailAddress:
+ videoMetadataAtPath:
+ analyzeMoment:
+ analyzeMomentList:
- init
- connection
- setConnection:
- fileURLForAssetURL:withAdjustments:
- getPhotosAndVideosCountWithHandler:
- cleanupModelAfteriTunesRestore
- dataMigrationWillFinish
- getLibrarySizes:
- replyQueue
- sendQueue
- deviceSpecificReplyQueue
- fileDescriptorForAssetURL:
- addGroupWithName:handler:
- addAssetWithURL:toAlbumWithUUID:handler:
- deleteAssetWithURL:handler:
- setExternalUsageIntent:forAssetWithURL:handler:
- setLargePreviewImageForAssetWithURL:imageData:properties:handler:
- finalizeOTARestoreRecreatingAlbums:
- updateRestoredAssetWithUUID:paths:
- clearChangeStore
- getCurrentBulletins
- getCurrentApplicationBadgeCount
- getThumbnailImageDataForBulletinWithRecordID:
- clearAllBulletinsWithLastClearedRecordID:
- rebuildMomentsIncremental:
- rebuildMomentLists
- analyzeAllMoments
- rebuildCloudFeed
- resetDupesAnalysis
- rebuildAllThumbnails
- analyzeInvalidMomentsAndDupesIfNeeded
- notifyAboutTerminationDueToUncaughtException:
- launchAssetsd
- importFileSystemAssetsWaitingForReply:
- enablePhotostreamsWithStreamID:
- updateModelAfterOTARestore
- repairSingletonObjects
- createPhotoLibraryDatabase
- hasCompletedRestorePostProcessing
- hasCompletedMomentAnalysis
- recoverFromCrashIfNeeded
- cleanupForStoreDemoMode
- requestAccessWithHandler:
- fileURLForNewAssetWithType:extension:
- imageDataForAsset:format:
- requestImageDataForAsset:format:handler:
- batchSaveAssetsWithJobDictionaries:handler:
- waitUntilConnectionSendsAllMessages
- saveAssetWithJobDictionary:handler:imageSurface:previewImageSurface:
- downloadAsset:requestThumbnail:shouldPrioritize:shouldExtendTimer:
- updateThumbnailsForPhotos:waitForReply:assignNewIndex:forceRefresh:
- createPhotostreamAlbumWithStreamID:
- automaticallyDeleteEmptyAlbum:
- updateCameraPreviewWellImage:
- recalculateCachedAlbumCounts
- getCurrentModelVersion
- repairPotentialModelCorruption
- secondsNeededToCleanupModelAfteriTunesRestore
- writeDataInBackground:toFileURL:
- estimatedOutputFileLengthForVideoURL:fallbackFilePath:exportPreset:exportProperties:
- personInfoDictionaryForPersonID:
- setPersonInfoDictionary:forPersonID:
- sendDaemonJob:replyHandler:
- updateSharedAlbumsCachedServerConfigurationLimits
- purgeableSharedAssetsSpace
- attemptToPurgeSharedAssetsSpace:
- emailAddressForKey:
- keyForEmailAddress:
- videoMetadataAtPath:
- analyzeMoment:
- analyzeMomentList:
@end
