@interface PLInFlightAssetsAlbum : NSObject
{
	id _fetchRequest;
	id _albumOIDs;
	id _inflightAssets;
	usigned long long _photosCount;
	usigned long long _videosCount;
	id __assetCache;
	id _backingAlbum;
	BOOL _sessionLimited;
	id _weak_assets;
	Array _derivedAlbums;
	BOOL __notificationsEnabled;
}

+ dealloc
+ count
+ description
+ isEmpty
+ title
+ kind
+ localizedTitle
+ addInFlightAsset:
+ removeInflightAssets:
+ isCameraAlbum
+ kindValue
+ isCloudSharedAlbum
+ titleForSectionStartingAtIndex:
+ displayableIndexesForCount:
+ reducePendingItemsCountBy:
+ batchFetchAssets:
+ filteredIndexesForPredicate:
+ setUINotificationsEnabled:
+ mutableAssets
+ hasUnseenContentBoolValue
+ setHasUnseenContentBoolValue:
+ posterImage
+ isLibrary
+ isPanoramasAlbum
+ isWallpaperAlbum
+ isPhotoStreamAlbum
+ isPendingPhotoStreamAlbum
+ isStandInAlbum
+ isOwnedCloudSharedAlbum
+ isMultipleContributorCloudSharedAlbum
+ canContributeToCloudSharedAlbum
+ shouldDeleteWhenEmpty
+ slideshowSettings
+ setSlideshowSettings:
+ importSessionID
+ setImportSessionID:
+ groupURL
+ sortingComparator
+ sectioningComparator
+ pendingItemsCount
+ setPendingItemsCount:
+ pendingItemsType
+ setPendingItemsType:
+ canPerformEditOperation:
+ uuid
+ assets
+ approximateCount
+ assetsCount
+ photosCount
+ videosCount
+ keyAsset
+ setKeyAsset:
+ secondaryKeyAsset
+ setSecondaryKeyAsset:
+ tertiaryKeyAsset
+ setTertiaryKeyAsset:
+ canShowComments
+ canShowAvalancheStacks
+ localizedLocationNames
+ batchSize
+ fetchRequest
+ _fetchedCountForAssetsOfKind:
+ countForAssetsOfKind:
+ unregisterAllDerivedAlbums
+ enumerateDerivedAlbums:
+ registerDerivedAlbum:
+ hasDerivedIndexMappers
+ assetsByObjectIDAtIndexes:
+ backingAlbum
+ set_assets:
+ _assets
+ mappedDataSourceChanged:remoteNotificationData:
+ derivedChangeNotificationClass
+ currentStateForChange
+ cachedIndexMapState
+ initWithBackingAlbum:
+ sessionLimited
+ _albumOIDs
+ _resetAlbumOIDs
+ managedObjectForOID:
+ managedObjectsForOIDs:
+ managedObjectsAtAlbumIndexes:
+ managedObjectAtAlbumIndex:
+ setSessionLimited:
+ clearAssetCaches
+ countOfMergedAssets
+ indexInMergedAssetsOfObject:
+ objectInMergedAssetsAtIndex:
+ getMergedAssets:range:
+ insertObject:inMergedAssetsAtIndex:
+ removeObjectFromMergedAssetsAtIndex:
+ startNewSession
+ _notificationsEnabled
+ set_notificationsEnabled:
- dealloc
- count
- description
- isEmpty
- title
- kind
- localizedTitle
- addInFlightAsset:
- removeInflightAssets:
- isCameraAlbum
- kindValue
- isCloudSharedAlbum
- titleForSectionStartingAtIndex:
- displayableIndexesForCount:
- reducePendingItemsCountBy:
- batchFetchAssets:
- filteredIndexesForPredicate:
- setUINotificationsEnabled:
- mutableAssets
- hasUnseenContentBoolValue
- setHasUnseenContentBoolValue:
- posterImage
- isLibrary
- isPanoramasAlbum
- isWallpaperAlbum
- isPhotoStreamAlbum
- isPendingPhotoStreamAlbum
- isStandInAlbum
- isOwnedCloudSharedAlbum
- isMultipleContributorCloudSharedAlbum
- canContributeToCloudSharedAlbum
- shouldDeleteWhenEmpty
- slideshowSettings
- setSlideshowSettings:
- importSessionID
- setImportSessionID:
- groupURL
- sortingComparator
- sectioningComparator
- pendingItemsCount
- setPendingItemsCount:
- pendingItemsType
- setPendingItemsType:
- canPerformEditOperation:
- uuid
- assets
- approximateCount
- assetsCount
- photosCount
- videosCount
- keyAsset
- setKeyAsset:
- secondaryKeyAsset
- setSecondaryKeyAsset:
- tertiaryKeyAsset
- setTertiaryKeyAsset:
- canShowComments
- canShowAvalancheStacks
- localizedLocationNames
- batchSize
- fetchRequest
- _fetchedCountForAssetsOfKind:
- countForAssetsOfKind:
- unregisterAllDerivedAlbums
- enumerateDerivedAlbums:
- registerDerivedAlbum:
- hasDerivedIndexMappers
- assetsByObjectIDAtIndexes:
- backingAlbum
- set_assets:
- _assets
- mappedDataSourceChanged:remoteNotificationData:
- derivedChangeNotificationClass
- currentStateForChange
- cachedIndexMapState
- initWithBackingAlbum:
- sessionLimited
- _albumOIDs
- _resetAlbumOIDs
- managedObjectForOID:
- managedObjectsForOIDs:
- managedObjectsAtAlbumIndexes:
- managedObjectAtAlbumIndex:
- setSessionLimited:
- clearAssetCaches
- countOfMergedAssets
- indexInMergedAssetsOfObject:
- objectInMergedAssetsAtIndex:
- getMergedAssets:range:
- insertObject:inMergedAssetsAtIndex:
- removeObjectFromMergedAssetsAtIndex:
- startNewSession
- _notificationsEnabled
- set_notificationsEnabled:
@end
