@interface RadioStation : NSObject
{
	id _context;
	id _managedObject;
}

+ setSortOrder:
+ isSubscribed
+ sortOrder
+ setSubscribed:
+ isShared
+ adamID
+ stationID
+ stationHash
+ streamURL
+ artworkURL
+ tracksForPlayback
+ stationDescription
+ stationType
+ adData
+ currentPlayingTrack
+ skipInterval
+ isGatewayVideoAdEnabled
+ currentPlayingTrackTime
+ dealloc
+ isEqual:
+ hash
+ context
+ setName:
+ name
+ dictionaryRepresentation
+ setShared:
+ persistentID
+ managedObject
+ debugDictionary
+ isFeatured
+ isSponsored
+ trackDescriptorsForPlayback
+ orderedTrackDescriptorsForPlayback
+ trackDescriptorsForPlaybackByExpirationDate
+ songMixType
+ seedTracks
+ additionalReferencedTrackDescriptors
+ artworkURLData
+ coreSeedName
+ currentPlayingTrackDescriptor
+ editableFields
+ editEnabled
+ feedbackDictionaryRepresentation
+ impressionThreshold
+ isPremiumPlacement
+ isPreview
+ isSharingEnabled
+ likesEnabled
+ setAdditionalReferencedTrackDescriptors:
+ setAdData:
+ setArtworkURL:
+ setArtworkURLData:
+ setCoreSeedName:
+ setCurrentPlayingTrackDescriptor:
+ setCurrentPlayingTrackTime:
+ setDebugDictionary:
+ setEditEnabled:
+ setEditableFields:
+ setFeatured:
+ setGatewayVideoAdEnabled:
+ setImpressionThreshold:
+ setLikesEnabled:
+ setOrderedTrackDescriptorsForPlayback:
+ setPersistentID:
+ setPremiumPlacement:
+ setSeedTracks:
+ setSharingEnabled:
+ setShareToken:
+ setSkipEnabled:
+ setSkipFrequency:
+ setSkipIdentifier:
+ setSkipInterval:
+ setSkipTimestamps:
+ setSongMixType:
+ setSponsored:
+ setStationDescription:
+ setStationID:
+ setStationHash:
+ setStreamURL:
+ setStreamCertificateURL:
+ setStreamKeyURL:
+ setSubscriberCount:
+ setTrackDescriptorsForPlaybackByExpirationDate:
+ setTracksForPlaybackNeedRefresh:
+ setVirtualPlayEnabled:
+ shareToken
+ skipEnabled
+ skipFrequency
+ skipIdentifier
+ skipTimestamps
+ streamCertificateURL
+ streamKeyURL
+ subscriberCount
+ tracksForPlaybackNeedRefresh
+ virtualPlayEnabled
+ _radioModelWasDeletedNotification:
+ isPreviewOnly
+ setPreviewOnly:
+ setTrackDescriptorsForPlayback:
+ initWithManagedObject:context:
+ addTracksForPlayback:withExpirationDate:
+ artworkURLForSize:expectedSize:
+ currentPlayingTrackID
+ removeTrackForPlayback:
+ removeAllTracksForPlayback
+ setCurrentPlayingTrack:
+ .cxx_destruct
+ setAdamID:
- setSortOrder:
- isSubscribed
- sortOrder
- setSubscribed:
- isShared
- adamID
- stationID
- stationHash
- streamURL
- artworkURL
- tracksForPlayback
- stationDescription
- stationType
- adData
- currentPlayingTrack
- skipInterval
- isGatewayVideoAdEnabled
- currentPlayingTrackTime
- dealloc
- isEqual:
- hash
- context
- setName:
- name
- dictionaryRepresentation
- setShared:
- persistentID
- managedObject
- debugDictionary
- isFeatured
- isSponsored
- trackDescriptorsForPlayback
- orderedTrackDescriptorsForPlayback
- trackDescriptorsForPlaybackByExpirationDate
- songMixType
- seedTracks
- additionalReferencedTrackDescriptors
- artworkURLData
- coreSeedName
- currentPlayingTrackDescriptor
- editableFields
- editEnabled
- feedbackDictionaryRepresentation
- impressionThreshold
- isPremiumPlacement
- isPreview
- isSharingEnabled
- likesEnabled
- setAdditionalReferencedTrackDescriptors:
- setAdData:
- setArtworkURL:
- setArtworkURLData:
- setCoreSeedName:
- setCurrentPlayingTrackDescriptor:
- setCurrentPlayingTrackTime:
- setDebugDictionary:
- setEditEnabled:
- setEditableFields:
- setFeatured:
- setGatewayVideoAdEnabled:
- setImpressionThreshold:
- setLikesEnabled:
- setOrderedTrackDescriptorsForPlayback:
- setPersistentID:
- setPremiumPlacement:
- setSeedTracks:
- setSharingEnabled:
- setShareToken:
- setSkipEnabled:
- setSkipFrequency:
- setSkipIdentifier:
- setSkipInterval:
- setSkipTimestamps:
- setSongMixType:
- setSponsored:
- setStationDescription:
- setStationID:
- setStationHash:
- setStreamURL:
- setStreamCertificateURL:
- setStreamKeyURL:
- setSubscriberCount:
- setTrackDescriptorsForPlaybackByExpirationDate:
- setTracksForPlaybackNeedRefresh:
- setVirtualPlayEnabled:
- shareToken
- skipEnabled
- skipFrequency
- skipIdentifier
- skipTimestamps
- streamCertificateURL
- streamKeyURL
- subscriberCount
- tracksForPlaybackNeedRefresh
- virtualPlayEnabled
- _radioModelWasDeletedNotification:
- isPreviewOnly
- setPreviewOnly:
- setTrackDescriptorsForPlayback:
- initWithManagedObject:context:
- addTracksForPlayback:withExpirationDate:
- artworkURLForSize:expectedSize:
- currentPlayingTrackID
- removeTrackForPlayback:
- removeAllTracksForPlayback
- setCurrentPlayingTrack:
- .cxx_destruct
- setAdamID:
@end
