@interface SAPerson : SADomainObject
{

}

+ company
+ isBlocked
+ middleName
+ birthday
+ relatedNames
+ socialProfiles
+ setMiddleName:
+ setBirthday:
+ setRelatedNames:
+ setSocialProfiles:
+ addresses
+ groupIdentifier
+ setCompany:
+ setNickName:
+ nickName
+ me
+ setSuffix:
+ suffix
+ firstName
+ lastName
+ fullName
+ emails
+ phones
+ setEmails:
+ setPhones:
+ setFirstName:
+ setLastName:
+ setFullName:
+ setAddresses:
+ encodedClassName
+ updateUsingSet:add:remove:
+ setMe:
+ firstNameAPGs
+ setFirstNameAPGs:
+ firstNamePhonetic
+ setFirstNamePhonetic:
+ setIsBlocked:
+ lastNameAPGs
+ setLastNameAPGs:
+ lastNamePhonetic
+ setLastNamePhonetic:
+ nickNameAPGs
+ setNickNameAPGs:
+ phonemeData
+ setPhonemeData:
+ prefix
+ setPrefix:
- company
- isBlocked
- middleName
- birthday
- relatedNames
- socialProfiles
- setMiddleName:
- setBirthday:
- setRelatedNames:
- setSocialProfiles:
- addresses
- groupIdentifier
- setCompany:
- setNickName:
- nickName
- me
- setSuffix:
- suffix
- firstName
- lastName
- fullName
- emails
- phones
- setEmails:
- setPhones:
- setFirstName:
- setLastName:
- setFullName:
- setAddresses:
- encodedClassName
- updateUsingSet:add:remove:
- setMe:
- firstNameAPGs
- setFirstNameAPGs:
- firstNamePhonetic
- setFirstNamePhonetic:
- setIsBlocked:
- lastNameAPGs
- setLastNameAPGs:
- lastNamePhonetic
- setLastNamePhonetic:
- nickNameAPGs
- setNickNameAPGs:
- phonemeData
- setPhonemeData:
- prefix
- setPrefix:
@end
