@interface SASetAssistantData : SABaseCommand
{

}

+ groupIdentifier
+ osVersion
+ anchor
+ setAnchor:
+ setCountryCode:
+ setOsVersion:
+ deviceVersion
+ setDeviceVersion:
+ setRegion:
+ region
+ countryCode
+ firstName
+ lastName
+ setFirstName:
+ setLastName:
+ encodedClassName
+ timeZoneId
+ setTimeZoneId:
+ censorSpeech
+ setCensorSpeech:
+ handsFree
+ setHandsFree:
+ abSources
+ setAbSources:
+ allowUserGeneratedContent
+ setAllowUserGeneratedContent:
+ debugFlags
+ setDebugFlags:
+ deviceCapabilities
+ setDeviceCapabilities:
+ meCards
+ setMeCards:
+ parentalRestrictions
+ setParentalRestrictions:
+ storefront
+ setStorefront:
+ temperatureUnit
+ setTemperatureUnit:
+ ttsVoice
+ setTtsVoice:
+ twentyFourHourTimeDisplay
+ setTwentyFourHourTimeDisplay:
+ uiScale
+ setUiScale:
+ voiceOver
+ setVoiceOver:
- groupIdentifier
- osVersion
- anchor
- setAnchor:
- setCountryCode:
- setOsVersion:
- deviceVersion
- setDeviceVersion:
- setRegion:
- region
- countryCode
- firstName
- lastName
- setFirstName:
- setLastName:
- encodedClassName
- timeZoneId
- setTimeZoneId:
- censorSpeech
- setCensorSpeech:
- handsFree
- setHandsFree:
- abSources
- setAbSources:
- allowUserGeneratedContent
- setAllowUserGeneratedContent:
- debugFlags
- setDebugFlags:
- deviceCapabilities
- setDeviceCapabilities:
- meCards
- setMeCards:
- parentalRestrictions
- setParentalRestrictions:
- storefront
- setStorefront:
- temperatureUnit
- setTemperatureUnit:
- ttsVoice
- setTtsVoice:
- twentyFourHourTimeDisplay
- setTwentyFourHourTimeDisplay:
- uiScale
- setUiScale:
- voiceOver
- setVoiceOver:
@end
