@interface SASStartSpeech : SABaseCommand
{

}

+ af_logDiagnostics
+ _ad_isRetryableCommand
+ setAFSpeechRequestOptions:
+ setAFSpeechEvent:
+ groupIdentifier
+ origin
+ setOrigin:
+ encodedClassName
+ audioSource
+ setAudioSource:
+ clearContext
+ setClearContext:
+ codec
+ setCodec:
+ setDeviceIdentifier:
+ setDeviceModel:
+ disableAutoEndpointing
+ setDisableAutoEndpointing:
+ dspStatus
+ setDspStatus:
+ headsetAddress
+ setHeadsetAddress:
+ headsetId
+ setHeadsetId:
+ headsetName
+ setHeadsetName:
+ motionActivity
+ setMotionActivity:
+ motionConfidence
+ setMotionConfidence:
+ noiseReductionLevel
+ setNoiseReductionLevel:
+ deviceIdentifier
+ deviceModel
- af_logDiagnostics
- _ad_isRetryableCommand
- setAFSpeechRequestOptions:
- setAFSpeechEvent:
- groupIdentifier
- origin
- setOrigin:
- encodedClassName
- audioSource
- setAudioSource:
- clearContext
- setClearContext:
- codec
- setCodec:
- setDeviceIdentifier:
- setDeviceModel:
- disableAutoEndpointing
- setDisableAutoEndpointing:
- dspStatus
- setDspStatus:
- headsetAddress
- setHeadsetAddress:
- headsetId
- setHeadsetId:
- headsetName
- setHeadsetName:
- motionActivity
- setMotionActivity:
- motionConfidence
- setMotionConfidence:
- noiseReductionLevel
- setNoiseReductionLevel:
- deviceIdentifier
- deviceModel
@end
