@interface SASStartSpeechDictation : SASStartSpeech
{

}

+ setAFDictationOptions:
+ _sasKeyboardTypeFromAFDicatationKeyboardType:
+ _sasReturnKeyTypeFromAFDictationReturnKeyType:
+ groupIdentifier
+ keyboardType
+ setKeyboardType:
+ selectedText
+ setApplicationName:
+ setApplicationVersion:
+ language
+ setFieldLabel:
+ setPrefixText:
+ setPostfixText:
+ setSelectedText:
+ prefixText
+ postfixText
+ setLanguage:
+ applicationVersion
+ fieldId
+ setFieldId:
+ applicationName
+ setRegion:
+ region
+ encodedClassName
+ activationToken
+ setActivationToken:
+ censorSpeech
+ setCensorSpeech:
+ fieldLabel
+ interactionId
+ setInteractionId:
+ keyboardReturnKey
+ setKeyboardReturnKey:
- setAFDictationOptions:
- _sasKeyboardTypeFromAFDicatationKeyboardType:
- _sasReturnKeyTypeFromAFDictationReturnKeyType:
- groupIdentifier
- keyboardType
- setKeyboardType:
- selectedText
- setApplicationName:
- setApplicationVersion:
- language
- setFieldLabel:
- setPrefixText:
- setPostfixText:
- setSelectedText:
- prefixText
- postfixText
- setLanguage:
- applicationVersion
- fieldId
- setFieldId:
- applicationName
- setRegion:
- region
- encodedClassName
- activationToken
- setActivationToken:
- censorSpeech
- setCensorSpeech:
- fieldLabel
- interactionId
- setInteractionId:
- keyboardReturnKey
- setKeyboardReturnKey:
@end
