@interface SBAwayViewPluginController : NSObject
{
	id _view;
	BOOL _viewCanBeDisplayed;
	BOOL _fullscreen;
	BOOL _alwaysFullscreen;
	long long _orientation;
	id _disableTransitionBlock;
	usigned long long _effectivePresentationStyle;
	id _enablingApplicationBundleIdentifier;
}

+ customHeaderView
+ isFullscreen
+ setFullscreen:animated:
+ dealloc
+ init
+ view
+ orientation
+ setView:
+ backgroundView
+ viewWillAppear:
+ loadView
+ viewDidAppear:
+ viewWillDisappear:
+ viewDidDisappear:
+ willRotateToInterfaceOrientation:duration:
+ willAnimateRotationToInterfaceOrientation:duration:
+ didRotateFromInterfaceOrientation:
+ transitionDuration
+ setOrientation:
+ presentationStyle
+ disable
+ legibilitySettings
+ disableWithTransitionBlock:
+ _setDisableTransitionBlock:
+ setFullscreen:duration:
+ viewWantsOverlayLayout
+ disablesAwayItemsCompletely
+ shouldAutoHideNotifications
+ viewFadeInDuration
+ canBeAlwaysFullscreen
+ alwaysFullscreenValueHasChanged
+ showDateView
+ purgeView
+ setViewCanBeDisplayed:
+ setActivationContext:
+ setDeactivationContext:
+ _disableTransitionBlock
+ enableTransitionBlock
+ viewWantsFullscreenLayout
+ notificationBehavior
+ shouldDisableOnRelock
+ shouldDisableOnUnlock
+ shouldShowLockStatusBarTime
+ allowsNotificationCenter
+ allowsControlCenter
+ allowsTimer
+ setAlwaysFullscreen:
+ isAlwaysFullscreen
+ deviceLockViewWillShow
+ deviceLockViewDidHide
+ retainsPriorityWhileInactive
+ pluginPriority
+ animateResumingToApplicationWithIdentifier:
+ bundleIDForUnlock
+ showAwayItems
+ showDate
+ showStatusBar
+ showHeaderView
+ canScreenDim
+ allowsLockScreenCamera
+ allowsLockScreenMediaControls
+ allowsPhotoSlideshow
+ allowsSiri
+ wantsToOpenURLsWhilePasscodeLocked
+ wantsHardwareEventsWhenScreenDimmed
+ wantsUserWallpaper
+ showsDuringCall
+ handleMenuButtonTap
+ handleMenuButtonDoubleTap
+ wantsMenuButtonHeldEvent
+ handleMenuButtonHeld
+ handleGesture:fingerCount:
+ handleLockButtonPressed
+ handleVolumeUpButtonPressed
+ handleVolumeDownButtonPressed
+ handleHeadsetButtonPressed:
+ wantsAutomaticFullscreenTimer
+ wantsSwipeGestureRecognizer
+ wantsMesaAutoUnlock
+ lockScreenMediaControlsShown:
+ viewCanBeDisplayed
+ _effectivePresentationStyle
+ _setEffectivePresentationStyle:
+ enablingApplicationBundleIdentifier
+ setEnablingApplicationBundleIdentifier:
+ overlayStyle
- customHeaderView
- isFullscreen
- setFullscreen:animated:
- dealloc
- init
- view
- orientation
- setView:
- backgroundView
- viewWillAppear:
- loadView
- viewDidAppear:
- viewWillDisappear:
- viewDidDisappear:
- willRotateToInterfaceOrientation:duration:
- willAnimateRotationToInterfaceOrientation:duration:
- didRotateFromInterfaceOrientation:
- transitionDuration
- setOrientation:
- presentationStyle
- disable
- legibilitySettings
- disableWithTransitionBlock:
- _setDisableTransitionBlock:
- setFullscreen:duration:
- viewWantsOverlayLayout
- disablesAwayItemsCompletely
- shouldAutoHideNotifications
- viewFadeInDuration
- canBeAlwaysFullscreen
- alwaysFullscreenValueHasChanged
- showDateView
- purgeView
- setViewCanBeDisplayed:
- setActivationContext:
- setDeactivationContext:
- _disableTransitionBlock
- enableTransitionBlock
- viewWantsFullscreenLayout
- notificationBehavior
- shouldDisableOnRelock
- shouldDisableOnUnlock
- shouldShowLockStatusBarTime
- allowsNotificationCenter
- allowsControlCenter
- allowsTimer
- setAlwaysFullscreen:
- isAlwaysFullscreen
- deviceLockViewWillShow
- deviceLockViewDidHide
- retainsPriorityWhileInactive
- pluginPriority
- animateResumingToApplicationWithIdentifier:
- bundleIDForUnlock
- showAwayItems
- showDate
- showStatusBar
- showHeaderView
- canScreenDim
- allowsLockScreenCamera
- allowsLockScreenMediaControls
- allowsPhotoSlideshow
- allowsSiri
- wantsToOpenURLsWhilePasscodeLocked
- wantsHardwareEventsWhenScreenDimmed
- wantsUserWallpaper
- showsDuringCall
- handleMenuButtonTap
- handleMenuButtonDoubleTap
- wantsMenuButtonHeldEvent
- handleMenuButtonHeld
- handleGesture:fingerCount:
- handleLockButtonPressed
- handleVolumeUpButtonPressed
- handleVolumeDownButtonPressed
- handleHeadsetButtonPressed:
- wantsAutomaticFullscreenTimer
- wantsSwipeGestureRecognizer
- wantsMesaAutoUnlock
- lockScreenMediaControlsShown:
- viewCanBeDisplayed
- _effectivePresentationStyle
- _setEffectivePresentationStyle:
- enablingApplicationBundleIdentifier
- setEnablingApplicationBundleIdentifier:
- overlayStyle
@end
