@interface SBControlCenterSettings : _UISettings
{
	BOOL _highlightUsesPlusL;
	BOOL _backgroundDarkensCC;
	double _controlAlpha;
	double _controlAlpha1x;
	double _disabledAlpha;
	double _disabledAlpha1x;
	double _highlightAlpha;
	double _glowAlpha;
	id _highlightColor;
	double _bounceFriction;
	double _backgroundColorAlpha;
}

+ bounceFriction
+ backgroundDarkensCC
+ backgroundColorAlpha
+ setControlAlpha:
+ setControlAlpha1x:
+ setDisabledAlpha:
+ setDisabledAlpha1x:
+ setHighlightAlpha:
+ setHighlightUsesPlusL:
+ setGlowAlpha:
+ setBounceFriction:
+ setBackgroundColorAlpha:
+ setBackgroundDarkensCC:
+ controlAlpha1x
+ controlAlpha
+ disabledAlpha1x
+ disabledAlpha
+ setDefaultValues
+ setHighlightColor:
+ highlightColor
+ highlightAlpha
+ resolvedDisabledAlpha
+ resolvedControlAlpha
+ highlightUsesPlusL
+ glowAlpha
- bounceFriction
- backgroundDarkensCC
- backgroundColorAlpha
- setControlAlpha:
- setControlAlpha1x:
- setDisabledAlpha:
- setDisabledAlpha1x:
- setHighlightAlpha:
- setHighlightUsesPlusL:
- setGlowAlpha:
- setBounceFriction:
- setBackgroundColorAlpha:
- setBackgroundDarkensCC:
- controlAlpha1x
- controlAlpha
- disabledAlpha1x
- disabledAlpha
- setDefaultValues
- setHighlightColor:
- highlightColor
- highlightAlpha
- resolvedDisabledAlpha
- resolvedControlAlpha
- highlightUsesPlusL
- glowAlpha
@end
