@interface SBLegibilitySettings : _UISettings
{
	double _slideToUnlockDarkShadowStrength;
	double _slideToUnlockLightShadowStrength;
	double _cameraGrabberDarkShadowStrength;
	double _cameraGrabberLightShadowStrength;
	double _timeDarkShadowStrength;
	double _timeLightShadowStrength;
	double _dateDarkShadowStrength;
	double _dateLightShadowStrength;
	double _legalDarkShadowStrength;
	double _legalLightShadowStrength;
	double _iconLabelDarkShadowStrength;
	double _iconLabelLightShadowStrength;
	double _folderTitleDarkShadowStrength;
	double _folderTitleLightShadowStrength;
	double _timerTextDarkShadowStrength;
	double _timerTextLightShadowStrength;
	double _timerDialDarkShadowStrength;
	double _timerDialLightShadowStrength;
}

+ setSlideToUnlockDarkShadowStrength:
+ setSlideToUnlockLightShadowStrength:
+ setCameraGrabberDarkShadowStrength:
+ setCameraGrabberLightShadowStrength:
+ setTimeDarkShadowStrength:
+ setTimeLightShadowStrength:
+ setDateDarkShadowStrength:
+ setDateLightShadowStrength:
+ setLegalDarkShadowStrength:
+ setLegalLightShadowStrength:
+ setIconLabelDarkShadowStrength:
+ setIconLabelLightShadowStrength:
+ setFolderTitleDarkShadowStrength:
+ setFolderTitleLightShadowStrength:
+ setTimerDialDarkShadowStrength:
+ setTimerDialLightShadowStrength:
+ setTimerTextDarkShadowStrength:
+ setTimerTextLightShadowStrength:
+ slideToUnlockLightShadowStrength
+ slideToUnlockDarkShadowStrength
+ cameraGrabberLightShadowStrength
+ cameraGrabberDarkShadowStrength
+ timeLightShadowStrength
+ timeDarkShadowStrength
+ dateLightShadowStrength
+ dateDarkShadowStrength
+ legalLightShadowStrength
+ legalDarkShadowStrength
+ iconLabelLightShadowStrength
+ iconLabelDarkShadowStrength
+ folderTitleLightShadowStrength
+ folderTitleDarkShadowStrength
+ timerTextLightShadowStrength
+ timerTextDarkShadowStrength
+ timerDialLightShadowStrength
+ timerDialDarkShadowStrength
+ slideToUnlockStrengthForStyle:
+ cameraGrabberStrengthForStyle:
+ timeStrengthForStyle:
+ dateStrengthForStyle:
+ legalStrengthForStyle:
+ iconLabelStrengthForStyle:
+ folderTitleStrengthForStyle:
+ timerTextStrengthForStyle:
+ timerDialStrengthForStyle:
+ setDefaultValues
- setSlideToUnlockDarkShadowStrength:
- setSlideToUnlockLightShadowStrength:
- setCameraGrabberDarkShadowStrength:
- setCameraGrabberLightShadowStrength:
- setTimeDarkShadowStrength:
- setTimeLightShadowStrength:
- setDateDarkShadowStrength:
- setDateLightShadowStrength:
- setLegalDarkShadowStrength:
- setLegalLightShadowStrength:
- setIconLabelDarkShadowStrength:
- setIconLabelLightShadowStrength:
- setFolderTitleDarkShadowStrength:
- setFolderTitleLightShadowStrength:
- setTimerDialDarkShadowStrength:
- setTimerDialLightShadowStrength:
- setTimerTextDarkShadowStrength:
- setTimerTextLightShadowStrength:
- slideToUnlockLightShadowStrength
- slideToUnlockDarkShadowStrength
- cameraGrabberLightShadowStrength
- cameraGrabberDarkShadowStrength
- timeLightShadowStrength
- timeDarkShadowStrength
- dateLightShadowStrength
- dateDarkShadowStrength
- legalLightShadowStrength
- legalDarkShadowStrength
- iconLabelLightShadowStrength
- iconLabelDarkShadowStrength
- folderTitleLightShadowStrength
- folderTitleDarkShadowStrength
- timerTextLightShadowStrength
- timerTextDarkShadowStrength
- timerDialLightShadowStrength
- timerDialDarkShadowStrength
- slideToUnlockStrengthForStyle:
- cameraGrabberStrengthForStyle:
- timeStrengthForStyle:
- dateStrengthForStyle:
- legalStrengthForStyle:
- iconLabelStrengthForStyle:
- folderTitleStrengthForStyle:
- timerTextStrengthForStyle:
- timerDialStrengthForStyle:
- setDefaultValues
@end
