@interface SSMetricsBaseEvent : SSMetricsMutableEvent
{

}

+ eventType
+ setAccountIdentifier:
+ init
+ description
+ applicationIdentifier
+ setPageURL:
+ pageURL
+ connection
+ setConnection:
+ setUserAgent:
+ setTopic:
+ topic
+ accountIdentifier
+ setPageType:
+ pageType
+ setWindowOrientation:
+ setOriginalTimeUsingDate:
+ setPageContext:
+ setApplicationIdentifier:
+ pageContext
+ windowOrientation
+ isBlacklistedByConfiguration:
+ eventVersion
+ baseVersion
+ clientVersion
+ originalTime
+ pageDescription
+ pageID
+ pixelRatio
+ previousClientVersion
+ setBaseVersion:
+ setClientVersion:
+ setEventType:
+ setEventVersion:
+ setOriginalTime:
+ setPageDescription:
+ setPageID:
+ setPixelRatio:
+ setPreviousClientVersion:
+ setScreenWidth:
+ setWindowHeight:
+ setWindowWidth:
+ windowHeight
+ windowWidth
+ setScreenHeight:
+ screenHeight
+ userAgent
+ screenWidth
- eventType
- setAccountIdentifier:
- init
- description
- applicationIdentifier
- setPageURL:
- pageURL
- connection
- setConnection:
- setUserAgent:
- setTopic:
- topic
- accountIdentifier
- setPageType:
- pageType
- setWindowOrientation:
- setOriginalTimeUsingDate:
- setPageContext:
- setApplicationIdentifier:
- pageContext
- windowOrientation
- isBlacklistedByConfiguration:
- eventVersion
- baseVersion
- clientVersion
- originalTime
- pageDescription
- pageID
- pixelRatio
- previousClientVersion
- setBaseVersion:
- setClientVersion:
- setEventType:
- setEventVersion:
- setOriginalTime:
- setPageDescription:
- setPageID:
- setPixelRatio:
- setPreviousClientVersion:
- setScreenWidth:
- setWindowHeight:
- setWindowWidth:
- windowHeight
- windowWidth
- setScreenHeight:
- screenHeight
- userAgent
- screenWidth
@end
