@interface TLToneManager : NSObject
{
	id _iTunesTonesByIdentifier;
	id _textTonesByIdentifier;
	id _iTunesIdentifiersByPID;
	id _previewBehaviorForDefaultIdentifier;
	id _identifierAliasMap;
	id _accessQueue;
	id _delegate;
}

+ _performBlockOnMainThread:
+ defaultIdentifierForContext:
+ currentIdentifierForContext:
+ _performBlockInAccessQueue:
+ currentNewMailToneIdentifier
+ defaultNewMailToneIdentifier
+ currentNewMailToneIdentifierForAccount:
+ currentSentMailToneIdentifier
+ defaultSentMailToneIdentifier
+ currentNewVoicemailToneIdentifier
+ defaultNewVoicemailToneIdentifier
+ currentCalendarAlertToneIdentifier
+ defaultCalendarAlertToneIdentifier
+ currentReminderAlertToneIdentifier
+ defaultReminderAlertToneIdentifier
+ currentSentTweetToneIdentifier
+ defaultSentTweetToneIdentifier
+ currentFacebookPostToneIdentifier
+ defaultFacebookPostToneIdentifier
+ currentPhotoStreamPostToneIdentifier
+ defaultPhotoStreamPostToneIdentifier
+ currentAirDropInvitationToneIdentifier
+ defaultAirDropInvitationToneIdentifier
+ newMailPreferenceKeyForAccount:
+ defaultAlarmToneIdentifier
+ currentNewMailToneSoundID
+ currentNewMailToneSoundIDForAccount:
+ currentSentMailToneSoundID
+ currentNewVoicemailToneSoundID
+ currentNewCalendarAlertToneSoundID
+ currentNewReminderAlertToneSoundID
+ currentSentTweetToneSoundID
+ currentFacebookPostToneSoundID
+ currentPhotoStreamPostToneSoundID
+ currentAirDropInvitationToneSoundID
+ removeNewMailToneForAccount:
+ toneWithIdentifierIsValid:
+ copyNameOfRingtoneWithIdentifier:
+ rootDirectory
+ dealloc
+ setDelegate:
+ init
+ currentTextToneIdentifier
+ toneWithIdentifierIsNone:
+ _accessQueue
+ copyNameOfIdentifier:isValid:
+ aliasForIdentifier:
+ copyIdentifierForRingtoneAtPath:isValid:
+ iTunesRingtoneDirectory
+ deviceITunesRingtoneDirectory
+ isTonePrivateWithIdentifier:
+ durationOfToneWithIdentifier:
+ isToneProtectedWithIdentifier:
+ isAlertTone:
+ isRingtonePurchased:
+ defaultRingtoneIdentifier
+ copyCurrentRingtoneName
+ copyCurrentRingtoneIdentifier
+ copyCurrentTextToneName
+ copyCurrentTextToneIdentifier
+ createPreviewSoundIDForToneIdentifier:
+ previewBehaviorForDefaultIdentifier:
+ newAVItemWithRingtoneIdentifier:
+ initWithGraphicsServicesInitialization:
+ initWithITunesRingtonePlistAtPath:shouldInitializeGraphicsServices:
+ _setAccessQueue:
+ loadITunesRingtoneInfoPlistAtPath:
+ loadTextToneInfo
+ _copyITunesRingtonesFromManifestPath:mediaDirectoryPath:
+ _reloadITunesRingtonesAfterExternalChange
+ defaultRingtoneName
+ currentToneIdentifierForAlertType:
+ _defaultToneIdentifierForAlertType:
+ localizedNameWithIdentifier:
+ copyNameOfRingtoneWithIdentifier:isValid:
+ copyPathOfRingtoneWithIdentifier:isValid:
+ defaultRingtonePath
+ pathFromIdentifier:withPrefix:
+ systemRingtoneDirectory
+ systemSoundDirectory
+ systemNewSoundDirectory
+ systemModernSoundDirectory
+ copyNameOfTextToneWithIdentifier:isValid:
+ localizedRingtoneNameWithIdentifier:
+ _toneWithIdentifierIsValid:
+ copyPathOfRingtoneWithIdentifier:
+ _copySystemWideTonePreferenceKeyForAlertType:accountIdentifier:
+ _currentToneIdentifierForAlertType:accountIdentifier:
+ currentToneIdentifierForAlertType:accountIdentifier:
+ setCurrentToneIdentifier:forAlertType:accountIdentifier:
+ setCurrentToneIdentifier:forAlertType:
+ _defaultToneNameForAlertType:
+ defaultTextToneIdentifier
+ _currentToneSoundID:defaultIdentifier:
+ nullTextToneName
+ soundIDForToneIdentifier:isValid:
+ _soundIDForSystemTone:isValid:
+ previewSoundIDForTextToneIdentifier:
+ soundIDForToneIdentifier:
+ _addToneToManifest:metadata:fileName:mediaDirectory:
+ _removeToneFromManifest:fileName:deletedMetadata:
+ _lockManifest:
+ installedTones
+ initWithITunesRingtonePlistAtPath:
+ shouldShowRingtones
+ shouldShowAlarmSounds
+ _deviceRingtonesChangedNotification
+ currentRingtoneIdentifier
+ currentRingtoneName
+ deviceITunesRingtoneInformationPlist
+ ITunesRingtoneInformationPlist
+ setCurrentTextToneIdentifier:
+ setCurrentRingtoneIdentifier:
+ defaultTextToneName
+ currentTextToneSoundID
+ soundIDForTextToneIdentifier:
+ soundIDForTextToneIdentifier:isValid:
+ insertSyncedToneMetadata:filename:
+ insertPurchasedToneMetadata:filename:
+ deleteSyncedToneByPID:
+ importTone:metadata:completionBlock:
+ removeImportedToneWithIdentifier:
+ iTunesToneForPID:
+ deleteAllSyncedData
+ installedTonesSize
+ transferPurchasedToITunes:
+ ensureDirectoryExists:
- _performBlockOnMainThread:
- defaultIdentifierForContext:
- currentIdentifierForContext:
- _performBlockInAccessQueue:
- currentNewMailToneIdentifier
- defaultNewMailToneIdentifier
- currentNewMailToneIdentifierForAccount:
- currentSentMailToneIdentifier
- defaultSentMailToneIdentifier
- currentNewVoicemailToneIdentifier
- defaultNewVoicemailToneIdentifier
- currentCalendarAlertToneIdentifier
- defaultCalendarAlertToneIdentifier
- currentReminderAlertToneIdentifier
- defaultReminderAlertToneIdentifier
- currentSentTweetToneIdentifier
- defaultSentTweetToneIdentifier
- currentFacebookPostToneIdentifier
- defaultFacebookPostToneIdentifier
- currentPhotoStreamPostToneIdentifier
- defaultPhotoStreamPostToneIdentifier
- currentAirDropInvitationToneIdentifier
- defaultAirDropInvitationToneIdentifier
- newMailPreferenceKeyForAccount:
- defaultAlarmToneIdentifier
- currentNewMailToneSoundID
- currentNewMailToneSoundIDForAccount:
- currentSentMailToneSoundID
- currentNewVoicemailToneSoundID
- currentNewCalendarAlertToneSoundID
- currentNewReminderAlertToneSoundID
- currentSentTweetToneSoundID
- currentFacebookPostToneSoundID
- currentPhotoStreamPostToneSoundID
- currentAirDropInvitationToneSoundID
- removeNewMailToneForAccount:
- toneWithIdentifierIsValid:
- copyNameOfRingtoneWithIdentifier:
- rootDirectory
- dealloc
- setDelegate:
- init
- currentTextToneIdentifier
- toneWithIdentifierIsNone:
- _accessQueue
- copyNameOfIdentifier:isValid:
- aliasForIdentifier:
- copyIdentifierForRingtoneAtPath:isValid:
- iTunesRingtoneDirectory
- deviceITunesRingtoneDirectory
- isTonePrivateWithIdentifier:
- durationOfToneWithIdentifier:
- isToneProtectedWithIdentifier:
- isAlertTone:
- isRingtonePurchased:
- defaultRingtoneIdentifier
- copyCurrentRingtoneName
- copyCurrentRingtoneIdentifier
- copyCurrentTextToneName
- copyCurrentTextToneIdentifier
- createPreviewSoundIDForToneIdentifier:
- previewBehaviorForDefaultIdentifier:
- newAVItemWithRingtoneIdentifier:
- initWithGraphicsServicesInitialization:
- initWithITunesRingtonePlistAtPath:shouldInitializeGraphicsServices:
- _setAccessQueue:
- loadITunesRingtoneInfoPlistAtPath:
- loadTextToneInfo
- _copyITunesRingtonesFromManifestPath:mediaDirectoryPath:
- _reloadITunesRingtonesAfterExternalChange
- defaultRingtoneName
- currentToneIdentifierForAlertType:
- _defaultToneIdentifierForAlertType:
- localizedNameWithIdentifier:
- copyNameOfRingtoneWithIdentifier:isValid:
- copyPathOfRingtoneWithIdentifier:isValid:
- defaultRingtonePath
- pathFromIdentifier:withPrefix:
- systemRingtoneDirectory
- systemSoundDirectory
- systemNewSoundDirectory
- systemModernSoundDirectory
- copyNameOfTextToneWithIdentifier:isValid:
- localizedRingtoneNameWithIdentifier:
- _toneWithIdentifierIsValid:
- copyPathOfRingtoneWithIdentifier:
- _copySystemWideTonePreferenceKeyForAlertType:accountIdentifier:
- _currentToneIdentifierForAlertType:accountIdentifier:
- currentToneIdentifierForAlertType:accountIdentifier:
- setCurrentToneIdentifier:forAlertType:accountIdentifier:
- setCurrentToneIdentifier:forAlertType:
- _defaultToneNameForAlertType:
- defaultTextToneIdentifier
- _currentToneSoundID:defaultIdentifier:
- nullTextToneName
- soundIDForToneIdentifier:isValid:
- _soundIDForSystemTone:isValid:
- previewSoundIDForTextToneIdentifier:
- soundIDForToneIdentifier:
- _addToneToManifest:metadata:fileName:mediaDirectory:
- _removeToneFromManifest:fileName:deletedMetadata:
- _lockManifest:
- installedTones
- initWithITunesRingtonePlistAtPath:
- shouldShowRingtones
- shouldShowAlarmSounds
- _deviceRingtonesChangedNotification
- currentRingtoneIdentifier
- currentRingtoneName
- deviceITunesRingtoneInformationPlist
- ITunesRingtoneInformationPlist
- setCurrentTextToneIdentifier:
- setCurrentRingtoneIdentifier:
- defaultTextToneName
- currentTextToneSoundID
- soundIDForTextToneIdentifier:
- soundIDForTextToneIdentifier:isValid:
- insertSyncedToneMetadata:filename:
- insertPurchasedToneMetadata:filename:
- deleteSyncedToneByPID:
- importTone:metadata:completionBlock:
- removeImportedToneWithIdentifier:
- iTunesToneForPID:
- deleteAllSyncedData
- installedTonesSize
- transferPurchasedToITunes:
- ensureDirectoryExists:
@end
