@interface UIButton : UIControl
{
	pointer _contentLookup;
	struct _contentEdgeInsets;
	struct _titleEdgeInsets;
	struct _imageEdgeInsets;
	id _backgroundView;
	id _imageView;
	id _titleView;
	BOOL _initialized;
	usigned long long _lastDrawingControlState;
	struct _buttonFlags;
	id _maskAnimationView;
	id _selectionView;
	id _lazyTitleViewFont;
	id _contentConstraints;
	struct _internalTitlePaddingInsets;
}

+ ab_addConferenceIcon
+ defaultAccessibilityTraits
+ isAccessibilityElementByDefault
+ isElementAccessibilityExposedToInterfaceBuilder
+ _scriptingInfo
+ insetsForRightAlignedImage:imageInset:
+ showActionSheet:animated:
+ cam_updateContentInsetsToCenterImageWithinMinimumSize:
+ configureFromScriptButton:
+ initWithFrame:
+ dealloc
+ initWithCoder:
+ _populateArchivedSubviews:
+ encodeWithCoder:
+ _intrinsicSizeWithinSize:
+ setFrame:
+ layoutSubviews
+ setBounds:
+ setTitle:
+ _contentHuggingDefault_isUsuallyFixedHeight
+ _contentHuggingDefault_isUsuallyFixedWidth
+ sizeThatFits:
+ _backgroundView
+ gestureRecognizerShouldBegin:
+ _buttonType
+ alignmentRectInsets
+ image
+ setLineBreakMode:
+ _font
+ _lineBreakMode
+ setTintColor:
+ invalidateIntrinsicContentSize
+ tintColorDidChange
+ _willMoveToWindow:
+ setEnabled:
+ _alwaysHandleScrollerMouseEvent
+ setBackgroundImage:forState:
+ titleForState:
+ _setLineBreakMode:
+ title
+ setFont:
+ font
+ _titleView
+ _setTitleShadowOffset:
+ titleLabel
+ setTitleColor:forState:
+ setTitleShadowColor:forState:
+ setTitleColor:forStates:
+ setAdjustsImageWhenHighlighted:
+ setAdjustsImageWhenDisabled:
+ setBackgroundImage:forStates:
+ setTitleEdgeInsets:
+ _isTitleFrozen
+ _setFont:
+ _setTitleFrozen:
+ setTitleShadowColor:forStates:
+ setTitle:forStates:
+ setImage:forStates:
+ setContentHorizontalAlignment:
+ setContentVerticalAlignment:
+ setDisabledDimsImage:
+ imageForState:
+ backgroundImageForState:
+ setHighlighted:
+ setContentEdgeInsets:
+ _sendSetNeedsLayoutToSuperviewOnTitleAnimationCompletionIfNecessary
+ _pathTitleEdgeInsets
+ _pathImageEdgeInsets
+ _isModernButton
+ _imageView
+ setSelected:
+ _clippedHighlightBounds
+ _highlightCornerRadius
+ updateConstraints
+ _setButtonType:
+ imageView
+ viewForBaselineLayout
+ backgroundRectForBounds:
+ setAutosizesToFit:
+ setImage:forState:
+ setTitle:forState:
+ currentTitle
+ currentImage
+ _contentForState:
+ _setContent:forState:
+ lineBreakMode
+ contentRectForBounds:
+ titleRectForContentRect:
+ imageRectForContentRect:
+ setShowPressFeedback:
+ _titleAttributesChanged
+ buttonType
+ _backgroundForState:usesBackgroundForNormalState:
+ _setupBackgroundView
+ _setTitleColor:forStates:
+ _setShadowColor:forStates:
+ titleColorForState:
+ titleShadowColorForState:
+ contentEdgeInsets
+ _setContentConstraints:
+ _invalidateContentConstraints
+ setShowsTouchWhenHighlighted:
+ _applyAppropriateChargeForButtonType
+ _takeContentFromArchivableContent:
+ _archivableContent:
+ autosizesToFit
+ pressFeedbackPosition
+ _canHaveTitle
+ _setupTitleView
+ _setupImageView
+ _hasDrawingStyle
+ _imageForState:usesImageForNormalState:
+ _hasHighlightColor
+ _selectedIndicatorViewWithImage:
+ _selectedIndicatorBounds
+ _selectedIndicatorAlpha
+ _borderColorForState:
+ _transitionAnimationWithKeyPath:
+ _borderWidthForState:bounds:
+ _fadeOutAnimationWithKeyPath:
+ _updateMaskState
+ _drawingStrokeForState:
+ _outsetInsets:
+ _highlightBounds
+ _titleForState:
+ _titleColorForState:
+ _shadowColorForState:
+ _attributedTitleForState:
+ _imageColorForState:
+ attributedTitleForState:
+ _combinedContentPaddingInsets
+ titleEdgeInsets
+ _titleRectForContentRect:calculatePositionForEmptyTitle:
+ imageEdgeInsets
+ _setContentHuggingPriorities:
+ _titleOrImageViewForBaselineLayout
+ _likelyToHaveTitle
+ _highlightRectForImageRect:
+ _highlightRectForTextRect:
+ adjustsImageWhenHighlighted
+ showsTouchWhenHighlighted
+ adjustsImageWhenDisabled
+ _beginTitleAnimation
+ _letterpressStyleForState:
+ _setupDrawingStyleForState:
+ _updateSelectionViewForState:
+ _setupPressednessForState:
+ _titleShadowOffset
+ _newImageViewWithFrame:
+ _updateEffectsForImageView:background:
+ _newLabelWithFrame:
+ _setTitle:forStates:
+ _setImage:forStates:
+ _setBackground:forStates:
+ _drawingStrokeForStyle:
+ _setDrawingStroke:forState:
+ _drawingStyleForStroke:
+ _shouldDefaultToTemplatesForImageViewBackground:
+ reversesTitleShadowWhenHighlighted
+ setReversesTitleShadowWhenHighlighted:
+ setImageEdgeInsets:
+ _setImageColor:forState:
+ setAttributedTitle:forState:
+ currentTitleColor
+ _currentImageColor
+ currentTitleShadowColor
+ currentBackgroundImage
+ currentAttributedTitle
+ titleShadowOffset
+ setTitleShadowOffset:
+ _setShouldHandleScrollerMouseEvent:
+ crossfadeToImage:forState:
+ _setLetterpressStyle:forState:
+ _setDrawingStyle:forState:
+ _drawingStyleForState:
+ _setImageColor:forStates:
+ _setAttributedTitle:forStates:
+ _contentConstraints
+ _internalTitlePaddingInsets
+ _setInternalTitlePaddingInsets:
- ab_addConferenceIcon
- defaultAccessibilityTraits
- isAccessibilityElementByDefault
- isElementAccessibilityExposedToInterfaceBuilder
- _scriptingInfo
- insetsForRightAlignedImage:imageInset:
- showActionSheet:animated:
- cam_updateContentInsetsToCenterImageWithinMinimumSize:
- configureFromScriptButton:
- initWithFrame:
- dealloc
- initWithCoder:
- _populateArchivedSubviews:
- encodeWithCoder:
- _intrinsicSizeWithinSize:
- setFrame:
- layoutSubviews
- setBounds:
- setTitle:
- _contentHuggingDefault_isUsuallyFixedHeight
- _contentHuggingDefault_isUsuallyFixedWidth
- sizeThatFits:
- _backgroundView
- gestureRecognizerShouldBegin:
- _buttonType
- alignmentRectInsets
- image
- setLineBreakMode:
- _font
- _lineBreakMode
- setTintColor:
- invalidateIntrinsicContentSize
- tintColorDidChange
- _willMoveToWindow:
- setEnabled:
- _alwaysHandleScrollerMouseEvent
- setBackgroundImage:forState:
- titleForState:
- _setLineBreakMode:
- title
- setFont:
- font
- _titleView
- _setTitleShadowOffset:
- titleLabel
- setTitleColor:forState:
- setTitleShadowColor:forState:
- setTitleColor:forStates:
- setAdjustsImageWhenHighlighted:
- setAdjustsImageWhenDisabled:
- setBackgroundImage:forStates:
- setTitleEdgeInsets:
- _isTitleFrozen
- _setFont:
- _setTitleFrozen:
- setTitleShadowColor:forStates:
- setTitle:forStates:
- setImage:forStates:
- setContentHorizontalAlignment:
- setContentVerticalAlignment:
- setDisabledDimsImage:
- imageForState:
- backgroundImageForState:
- setHighlighted:
- setContentEdgeInsets:
- _sendSetNeedsLayoutToSuperviewOnTitleAnimationCompletionIfNecessary
- _pathTitleEdgeInsets
- _pathImageEdgeInsets
- _isModernButton
- _imageView
- setSelected:
- _clippedHighlightBounds
- _highlightCornerRadius
- updateConstraints
- _setButtonType:
- imageView
- viewForBaselineLayout
- backgroundRectForBounds:
- setAutosizesToFit:
- setImage:forState:
- setTitle:forState:
- currentTitle
- currentImage
- _contentForState:
- _setContent:forState:
- lineBreakMode
- contentRectForBounds:
- titleRectForContentRect:
- imageRectForContentRect:
- setShowPressFeedback:
- _titleAttributesChanged
- buttonType
- _backgroundForState:usesBackgroundForNormalState:
- _setupBackgroundView
- _setTitleColor:forStates:
- _setShadowColor:forStates:
- titleColorForState:
- titleShadowColorForState:
- contentEdgeInsets
- _setContentConstraints:
- _invalidateContentConstraints
- setShowsTouchWhenHighlighted:
- _applyAppropriateChargeForButtonType
- _takeContentFromArchivableContent:
- _archivableContent:
- autosizesToFit
- pressFeedbackPosition
- _canHaveTitle
- _setupTitleView
- _setupImageView
- _hasDrawingStyle
- _imageForState:usesImageForNormalState:
- _hasHighlightColor
- _selectedIndicatorViewWithImage:
- _selectedIndicatorBounds
- _selectedIndicatorAlpha
- _borderColorForState:
- _transitionAnimationWithKeyPath:
- _borderWidthForState:bounds:
- _fadeOutAnimationWithKeyPath:
- _updateMaskState
- _drawingStrokeForState:
- _outsetInsets:
- _highlightBounds
- _titleForState:
- _titleColorForState:
- _shadowColorForState:
- _attributedTitleForState:
- _imageColorForState:
- attributedTitleForState:
- _combinedContentPaddingInsets
- titleEdgeInsets
- _titleRectForContentRect:calculatePositionForEmptyTitle:
- imageEdgeInsets
- _setContentHuggingPriorities:
- _titleOrImageViewForBaselineLayout
- _likelyToHaveTitle
- _highlightRectForImageRect:
- _highlightRectForTextRect:
- adjustsImageWhenHighlighted
- showsTouchWhenHighlighted
- adjustsImageWhenDisabled
- _beginTitleAnimation
- _letterpressStyleForState:
- _setupDrawingStyleForState:
- _updateSelectionViewForState:
- _setupPressednessForState:
- _titleShadowOffset
- _newImageViewWithFrame:
- _updateEffectsForImageView:background:
- _newLabelWithFrame:
- _setTitle:forStates:
- _setImage:forStates:
- _setBackground:forStates:
- _drawingStrokeForStyle:
- _setDrawingStroke:forState:
- _drawingStyleForStroke:
- _shouldDefaultToTemplatesForImageViewBackground:
- reversesTitleShadowWhenHighlighted
- setReversesTitleShadowWhenHighlighted:
- setImageEdgeInsets:
- _setImageColor:forState:
- setAttributedTitle:forState:
- currentTitleColor
- _currentImageColor
- currentTitleShadowColor
- currentBackgroundImage
- currentAttributedTitle
- titleShadowOffset
- setTitleShadowOffset:
- _setShouldHandleScrollerMouseEvent:
- crossfadeToImage:forState:
- _setLetterpressStyle:forState:
- _setDrawingStyle:forState:
- _drawingStyleForState:
- _setImageColor:forStates:
- _setAttributedTitle:forStates:
- _contentConstraints
- _internalTitlePaddingInsets
- _setInternalTitlePaddingInsets:
@end
