@interface UIDatePicker : UIControl
{
	id _pickerView;
	BOOL _useCurrentDateDuringDecoding;
}

+ timeInterval
+ setTimeInterval:
+ _selectedTextForCalendarUnit:
+ _labelTextForCalendarUnit:
+ _setTextColor:
+ _drawsBackground
+ _usesModernStyle
+ _textColor
+ _setDrawsBackground:
+ _setUsesModernStyle:
+ _highlightColor
+ _setHighlightColor:
+ _textShadowColor
+ _setTextShadowColor:
+ _contentWidth
+ _isTimeIntervalMode
+ _setUseCurrentDateDuringDecoding:
+ _useCurrentDateDuringDecoding
+ _setHidesLabels:
+ _setUsesBlackChrome:
+ _usesBlackChrome
+ _allowsZeroCountDownDuration
+ _setAllowsZeroCountDownDuration:
+ _allowsZeroTimeInterval
+ _setAllowsZeroTimeInterval:
+ _setHighlightsToday:
+ _dateUnderSelectionBar
+ setBackgroundColor:
+ setDelegate:
+ setFrame:
+ setBounds:
+ hour
+ dateComponents
+ setDateComponents:
+ setStaggerTimeIntervals:
+ setHighlightsToday:
+ minute
+ second
+ setDate:animate:
+ initWithFrame:
+ initWithCoder:
+ _populateArchivedSubviews:
+ encodeWithCoder:
+ hitTest:withEvent:
+ _intrinsicSizeWithinSize:
+ _contentHuggingDefault_isUsuallyFixedHeight
+ _contentHuggingDefault_isUsuallyFixedWidth
+ sizeThatFits:
+ setTimeZone:
+ date
+ awakeFromNib
+ invalidateIntrinsicContentSize
+ setDate:
+ setLocale:
+ _insertPickerView
+ setDatePickerMode:
+ _setLocale:
+ setCalendar:
+ setMinuteInterval:
+ setMinimumDate:
+ setMaximumDate:
+ datePickerMode
+ _locale
+ timeZone
+ calendar
+ minimumDate
+ maximumDate
+ minuteInterval
+ setDate:animated:
+ locale
+ countDownDuration
+ setCountDownDuration:
- timeInterval
- setTimeInterval:
- _selectedTextForCalendarUnit:
- _labelTextForCalendarUnit:
- _setTextColor:
- _drawsBackground
- _usesModernStyle
- _textColor
- _setDrawsBackground:
- _setUsesModernStyle:
- _highlightColor
- _setHighlightColor:
- _textShadowColor
- _setTextShadowColor:
- _contentWidth
- _isTimeIntervalMode
- _setUseCurrentDateDuringDecoding:
- _useCurrentDateDuringDecoding
- _setHidesLabels:
- _setUsesBlackChrome:
- _usesBlackChrome
- _allowsZeroCountDownDuration
- _setAllowsZeroCountDownDuration:
- _allowsZeroTimeInterval
- _setAllowsZeroTimeInterval:
- _setHighlightsToday:
- _dateUnderSelectionBar
- setBackgroundColor:
- setDelegate:
- setFrame:
- setBounds:
- hour
- dateComponents
- setDateComponents:
- setStaggerTimeIntervals:
- setHighlightsToday:
- minute
- second
- setDate:animate:
- initWithFrame:
- initWithCoder:
- _populateArchivedSubviews:
- encodeWithCoder:
- hitTest:withEvent:
- _intrinsicSizeWithinSize:
- _contentHuggingDefault_isUsuallyFixedHeight
- _contentHuggingDefault_isUsuallyFixedWidth
- sizeThatFits:
- setTimeZone:
- date
- awakeFromNib
- invalidateIntrinsicContentSize
- setDate:
- setLocale:
- _insertPickerView
- setDatePickerMode:
- _setLocale:
- setCalendar:
- setMinuteInterval:
- setMinimumDate:
- setMaximumDate:
- datePickerMode
- _locale
- timeZone
- calendar
- minimumDate
- maximumDate
- minuteInterval
- setDate:animated:
- locale
- countDownDuration
- setCountDownDuration:
@end
