@interface UIGestureRecognizer : NSObject
{
	id _targets;
	id _delayedTouches;
	id _view;
	id _updateEvent;
	id _updateButtonEvent;
	id _delegate;
	id _friends;
	long long _state;
	struct _gestureFlags;
	id _failureRequirements;
	id _failureDependents;
	id _dynamicFailureRequirements;
	id _dynamicFailureDependents;
	id _failureMap;
}

+ _detach
+ _connectInterfaceBuilderEventConnection:
+ dealloc
+ initWithCoder:
+ encodeWithCoder:
+ setDelegate:
+ init
+ description
+ delegate
+ view
+ setDelaysTouchesBegan:
+ state
+ initWithTarget:action:
+ _setRequiresSystemGesturesToFail:
+ locationInView:
+ _physicalButtonsBegan:withEvent:
+ _isDirty
+ touchesCancelled:withEvent:
+ ignoreTouch:forEvent:
+ setState:
+ _updateGestureStateWithEvent:buttonEvent:afterDelay:
+ _queueForResetIfFinished
+ _ignorePhysicalButton:forEvent:
+ _physicalButtonsEnded:withEvent:
+ _physicalButtonsCancelled:withEvent:
+ setView:
+ touchesBegan:withEvent:
+ touchesMoved:withEvent:
+ touchesEnded:withEvent:
+ _setDirty
+ isEnabled
+ setEnabled:
+ _requiresSystemGesturesToFail
+ removeTarget:action:
+ setDelaysTouchesEnded:
+ requireGestureRecognizerToFail:
+ numberOfTouches
+ locationOfTouch:inView:
+ _activeTouchesForEvent:
+ _isRecognized
+ canBePreventedByGestureRecognizer:
+ canPreventGestureRecognizer:
+ _delegateShouldReceiveTouch:
+ addTarget:action:
+ requireOtherGestureToFail:
+ _resetGestureRecognizer
+ setCancelsTouchesInView:
+ reset
+ _setAcceptsFailureRequiments:
+ delaysTouchesBegan
+ _shouldReceiveTouch:
+ _shouldBeRequiredToFailByGestureRecognizer:
+ _clearReferencesToRelatedGesture:
+ _enqueueDelayedTouchesToSend
+ _clearUpdateTimer
+ _shouldBegin
+ _isFriendWithGesture:
+ _enqueueDelayedTouchToSend:
+ _delayTouch:forEvent:
+ _clearDelayedTouches
+ _willBeginAfterSatisfyingFailureRequirements
+ _delayTouchesForEvent:
+ _updateGestureWithEvent:buttonEvent:
+ _affectedByGesture:
+ _delegateCanPreventGestureRecognizer:
+ _addFailureDependent:
+ _removeFailureDependent:
+ _appendDescriptionToString:atLevel:includingDependencies:
+ cancelsTouchesInView
+ delaysTouchesEnded
+ _appendSubclassDescription:
+ _appendDescription:forDependencies:toString:atLevel:
+ _failureMap
+ _setFailureMap:
+ _delayedTouches
+ _hasTargets
+ _shouldRequireFailureOfGestureRecognizer:
+ shouldRequireFailureOfGestureRecognizer:
+ shouldBeRequiredToFailByGestureRecognizer:
+ _centroidOfTouches:excludingEnded:
+ _distanceBetweenTouches:
+ _touchWasCancelled:
+ _requiresGestureRecognizerToFail:
+ _delayedUpdateGesture
+ _resetIfFinished
+ _depthFirstViewCompare:
+ _addFriendGesture:
+ _isExcludedByGesture:
+ _cancelRecognition
+ _exclude
+ _addDynamicFailureDependent:
+ _addDynamicFailureRequirement:
+ removeFailureRequirement:
+ _failureRequirementCompleted:withEvent:
+ _acceptsFailureRequirements
+ _briefDescription
+ _invalidate
- _detach
- _connectInterfaceBuilderEventConnection:
- dealloc
- initWithCoder:
- encodeWithCoder:
- setDelegate:
- init
- description
- delegate
- view
- setDelaysTouchesBegan:
- state
- initWithTarget:action:
- _setRequiresSystemGesturesToFail:
- locationInView:
- _physicalButtonsBegan:withEvent:
- _isDirty
- touchesCancelled:withEvent:
- ignoreTouch:forEvent:
- setState:
- _updateGestureStateWithEvent:buttonEvent:afterDelay:
- _queueForResetIfFinished
- _ignorePhysicalButton:forEvent:
- _physicalButtonsEnded:withEvent:
- _physicalButtonsCancelled:withEvent:
- setView:
- touchesBegan:withEvent:
- touchesMoved:withEvent:
- touchesEnded:withEvent:
- _setDirty
- isEnabled
- setEnabled:
- _requiresSystemGesturesToFail
- removeTarget:action:
- setDelaysTouchesEnded:
- requireGestureRecognizerToFail:
- numberOfTouches
- locationOfTouch:inView:
- _activeTouchesForEvent:
- _isRecognized
- canBePreventedByGestureRecognizer:
- canPreventGestureRecognizer:
- _delegateShouldReceiveTouch:
- addTarget:action:
- requireOtherGestureToFail:
- _resetGestureRecognizer
- setCancelsTouchesInView:
- reset
- _setAcceptsFailureRequiments:
- delaysTouchesBegan
- _shouldReceiveTouch:
- _shouldBeRequiredToFailByGestureRecognizer:
- _clearReferencesToRelatedGesture:
- _enqueueDelayedTouchesToSend
- _clearUpdateTimer
- _shouldBegin
- _isFriendWithGesture:
- _enqueueDelayedTouchToSend:
- _delayTouch:forEvent:
- _clearDelayedTouches
- _willBeginAfterSatisfyingFailureRequirements
- _delayTouchesForEvent:
- _updateGestureWithEvent:buttonEvent:
- _affectedByGesture:
- _delegateCanPreventGestureRecognizer:
- _addFailureDependent:
- _removeFailureDependent:
- _appendDescriptionToString:atLevel:includingDependencies:
- cancelsTouchesInView
- delaysTouchesEnded
- _appendSubclassDescription:
- _appendDescription:forDependencies:toString:atLevel:
- _failureMap
- _setFailureMap:
- _delayedTouches
- _hasTargets
- _shouldRequireFailureOfGestureRecognizer:
- shouldRequireFailureOfGestureRecognizer:
- shouldBeRequiredToFailByGestureRecognizer:
- _centroidOfTouches:excludingEnded:
- _distanceBetweenTouches:
- _touchWasCancelled:
- _requiresGestureRecognizerToFail:
- _delayedUpdateGesture
- _resetIfFinished
- _depthFirstViewCompare:
- _addFriendGesture:
- _isExcludedByGesture:
- _cancelRecognition
- _exclude
- _addDynamicFailureDependent:
- _addDynamicFailureRequirement:
- removeFailureRequirement:
- _failureRequirementCompleted:withEvent:
- _acceptsFailureRequirements
- _briefDescription
- _invalidate
@end
