@interface UIKBRenderFactoryiPad : UIKBRenderFactoryiPhone
{

}

+ _traitsForKey:onKeyplane:
+ lightKeycapsFontName
+ _customizeTraits:forPopupForKey:withRenderConfig:keycapsFontName:
+ thinKeycapsFontName
+ keyCornerRadius
+ multitapCompleteKeyImageName
+ muttitapReverseKeyImageName
+ setupLayoutSegments
+ shiftKeyImageName
+ shiftOnKeyImageName
+ spaceKeyFontSize
+ deleteKeyFontSize
+ moreKeyFontSize
+ internationalKeyFontSize
+ dictationKeyFontSize
+ dismissKeyFontSize
+ dismissKeyOffset
+ deleteKeyImageName
+ skinnyKeyThreshold
+ globalKeyImageName
+ dismissKeyImageName
+ dictationKeyImageName
+ shouldClearBaseDisplayStringForVariants
+ internationalKeyOffset
+ dictationKeyOffset
+ deleteKeyOffset
+ shiftKeyOffset
+ _customizeSymbolStyle:forKey:contents:
+ _customizeGeometry:forKey:contents:
+ _customizePopupTraits:forKey:onKeyplane:
+ variantDisplayFrameInsets
+ variantSymbolFrameInsets
+ variantGeometriesForGeometry:variantCount:
+ _row4ControlSegmentWidth
+ keyInsetBottom
+ symbolFrameInset
+ shiftKeySymbolFrame
+ dismissKeySymbolFrame
+ returnKeySymbolFrameInset
+ stringKeyFontSize
+ fontSizeAdjustmentForNonAlphanumericKeycaps
+ dualStringKeyFontSizeAdjustment
+ bottomRowDefaultFontSize
+ shiftKeyFontSize
+ fallbackFontSize
+ smallKanaKeyFontSize
+ emailDotKeyFontSize
+ facemarkKeyFontSize
+ defaultVariantGeometrySize
+ defaultVariantSizeThreshold
+ dualStringKeyOffset
+ dualStringKeyMiddleMargin
+ defaultPathWeight
- _traitsForKey:onKeyplane:
- lightKeycapsFontName
- _customizeTraits:forPopupForKey:withRenderConfig:keycapsFontName:
- thinKeycapsFontName
- keyCornerRadius
- multitapCompleteKeyImageName
- muttitapReverseKeyImageName
- setupLayoutSegments
- shiftKeyImageName
- shiftOnKeyImageName
- spaceKeyFontSize
- deleteKeyFontSize
- moreKeyFontSize
- internationalKeyFontSize
- dictationKeyFontSize
- dismissKeyFontSize
- dismissKeyOffset
- deleteKeyImageName
- skinnyKeyThreshold
- globalKeyImageName
- dismissKeyImageName
- dictationKeyImageName
- shouldClearBaseDisplayStringForVariants
- internationalKeyOffset
- dictationKeyOffset
- deleteKeyOffset
- shiftKeyOffset
- _customizeSymbolStyle:forKey:contents:
- _customizeGeometry:forKey:contents:
- _customizePopupTraits:forKey:onKeyplane:
- variantDisplayFrameInsets
- variantSymbolFrameInsets
- variantGeometriesForGeometry:variantCount:
- _row4ControlSegmentWidth
- keyInsetBottom
- symbolFrameInset
- shiftKeySymbolFrame
- dismissKeySymbolFrame
- returnKeySymbolFrameInset
- stringKeyFontSize
- fontSizeAdjustmentForNonAlphanumericKeycaps
- dualStringKeyFontSizeAdjustment
- bottomRowDefaultFontSize
- shiftKeyFontSize
- fallbackFontSize
- smallKanaKeyFontSize
- emailDotKeyFontSize
- facemarkKeyFontSize
- defaultVariantGeometrySize
- defaultVariantSizeThreshold
- dualStringKeyOffset
- dualStringKeyMiddleMargin
- defaultPathWeight
@end
