@interface UIKBTree : NSObject
{
	int type;
	id name;
	id properties;
	id subtrees;
	id cache;
	id layoutTag;
}

+ dealloc
+ setFrame:
+ frame
+ description
+ state
+ setType:
+ type
+ setState:
+ copyWithZone:
+ initWithType:
+ setName:
+ name
+ recursiveDescription
+ setTextAlignment:
+ setVisible:
+ textAlignment
+ setVisualStyling:
+ visualStyling
+ isSplit
+ isAlphabeticPlane
+ frameForKeylayoutName:
+ usesAutoShift
+ shouldSkipCandidateSelection
+ visible
+ isShiftKeyPlaneChooser
+ layoutTag
+ setLayoutTag:
+ keyplaneForKey:
+ displayType
+ geometry
+ paddedFrame
+ setPaddedFrame:
+ setVisualStyle:
+ clipCorners
+ displayString
+ interactionType
+ setDisplayString:
+ setRepresentedString:
+ setDisplayType:
+ setInteractionType:
+ setRendering:
+ shape
+ setShape:
+ setSubtrees:
+ setHighlightedVariantIndex:
+ disabled
+ setDisabled:
+ visualStyle
+ displayRowHint
+ rendering
+ intForProperty:
+ ghost
+ overrideDisplayString
+ displayTypeHint
+ setClipCorners:
+ setGeometry:
+ setFrameOnly:
+ cachedKeysByKeyName:
+ layoutName
+ stringForProperty:
+ subtreeWithName:
+ keysWithString:
+ subtrees
+ keys
+ fullRepresentedString
+ representedString
+ setDisplayTypeHint:
+ autolocalizedKeyCacheIterator
+ localizationKey
+ looksLikeShiftAlternate
+ isShiftKeyplane
+ shiftAlternateKeyplaneName
+ keysByKeyName:
+ firstCachedKeyWithName:
+ setOverrideDisplayString:
+ zipGeometrySet
+ setIsGenerated:
+ precacheLayoutName:
+ keySet
+ numberForProperty:
+ setDisplayRowHint:
+ setFlickDirection:
+ notUseCandidateSelection
+ cache
+ updateMoreAndInternationalKeysWithOptions:
+ supportsType:
+ usesKeyCharging
+ shouldSkipCandidateSelectionForVariants
+ forceMultitap
+ hasLayoutTag:
+ componentName
+ updateVariantTypeForActions:
+ setVariantPopupBias:
+ noLanguageIndicator
+ keysOrderedByPositionWithoutZip
+ setObject:forProperty:
+ avoidsLanguageIndicator
+ alternateKeyplaneName
+ modifiesKeyplane
+ dragThreshold
+ flickDirection
+ highlightedVariantIndex
+ behavesAsShiftKey
+ variantType
+ boolForProperty:
+ variantPopupBias
+ orderVariantKeys:
+ properties
+ dynamicDisplayTypeHint
+ setProperties:
+ isLeafType
+ setCache:
+ isSameAsTree:
+ isGenerated
+ _needsScaling
+ geometrySet:
+ attributeSet:
+ zipGeometries:attributes:
+ _keyplaneFrame
+ stylingFromVisualStyle
+ unhashedName
+ _cacheRootNameForKey:
+ shouldCacheKey
+ cacheKey:
+ geometries
+ findLeftMoreKey
+ updateDictationKeyOnNumberPads:
+ _variantType
+ setVariantType:
+ _renderAsStringKey
+ nameFromAttributes
+ isHashed
+ isEqualToTree:
+ isDuplicateOfTree:
+ subtreeWithType:
+ subtreeWithName:rows:
+ subtreesWithProperty:value:
+ indexOfSubtree:
+ zipAttributes
+ subtreesAreOrdered
+ keyForString:
+ setAttributes:
+ keyAttributes
+ clearTransientCaches
+ keysOrderedByPosition
+ geometriesOrderedByPosition
+ usesAdaptiveKeys
+ isLetters
+ looksLike:
+ setGhost:
+ splitMode
+ setSplitMode:
+ setForceMultitap:
+ canFadeOutFromState:toState:
+ fadeOutDuration
+ variantDisplayString
+ cacheDisplayString
+ renderKeyInKeyplane:
+ initWithType:withName:withProperties:withSubtrees:withCache:
- dealloc
- setFrame:
- frame
- description
- state
- setType:
- type
- setState:
- copyWithZone:
- initWithType:
- setName:
- name
- recursiveDescription
- setTextAlignment:
- setVisible:
- textAlignment
- setVisualStyling:
- visualStyling
- isSplit
- isAlphabeticPlane
- frameForKeylayoutName:
- usesAutoShift
- shouldSkipCandidateSelection
- visible
- isShiftKeyPlaneChooser
- layoutTag
- setLayoutTag:
- keyplaneForKey:
- displayType
- geometry
- paddedFrame
- setPaddedFrame:
- setVisualStyle:
- clipCorners
- displayString
- interactionType
- setDisplayString:
- setRepresentedString:
- setDisplayType:
- setInteractionType:
- setRendering:
- shape
- setShape:
- setSubtrees:
- setHighlightedVariantIndex:
- disabled
- setDisabled:
- visualStyle
- displayRowHint
- rendering
- intForProperty:
- ghost
- overrideDisplayString
- displayTypeHint
- setClipCorners:
- setGeometry:
- setFrameOnly:
- cachedKeysByKeyName:
- layoutName
- stringForProperty:
- subtreeWithName:
- keysWithString:
- subtrees
- keys
- fullRepresentedString
- representedString
- setDisplayTypeHint:
- autolocalizedKeyCacheIterator
- localizationKey
- looksLikeShiftAlternate
- isShiftKeyplane
- shiftAlternateKeyplaneName
- keysByKeyName:
- firstCachedKeyWithName:
- setOverrideDisplayString:
- zipGeometrySet
- setIsGenerated:
- precacheLayoutName:
- keySet
- numberForProperty:
- setDisplayRowHint:
- setFlickDirection:
- notUseCandidateSelection
- cache
- updateMoreAndInternationalKeysWithOptions:
- supportsType:
- usesKeyCharging
- shouldSkipCandidateSelectionForVariants
- forceMultitap
- hasLayoutTag:
- componentName
- updateVariantTypeForActions:
- setVariantPopupBias:
- noLanguageIndicator
- keysOrderedByPositionWithoutZip
- setObject:forProperty:
- avoidsLanguageIndicator
- alternateKeyplaneName
- modifiesKeyplane
- dragThreshold
- flickDirection
- highlightedVariantIndex
- behavesAsShiftKey
- variantType
- boolForProperty:
- variantPopupBias
- orderVariantKeys:
- properties
- dynamicDisplayTypeHint
- setProperties:
- isLeafType
- setCache:
- isSameAsTree:
- isGenerated
- _needsScaling
- geometrySet:
- attributeSet:
- zipGeometries:attributes:
- _keyplaneFrame
- stylingFromVisualStyle
- unhashedName
- _cacheRootNameForKey:
- shouldCacheKey
- cacheKey:
- geometries
- findLeftMoreKey
- updateDictationKeyOnNumberPads:
- _variantType
- setVariantType:
- _renderAsStringKey
- nameFromAttributes
- isHashed
- isEqualToTree:
- isDuplicateOfTree:
- subtreeWithType:
- subtreeWithName:rows:
- subtreesWithProperty:value:
- indexOfSubtree:
- zipAttributes
- subtreesAreOrdered
- keyForString:
- setAttributes:
- keyAttributes
- clearTransientCaches
- keysOrderedByPosition
- geometriesOrderedByPosition
- usesAdaptiveKeys
- isLetters
- looksLike:
- setGhost:
- splitMode
- setSplitMode:
- setForceMultitap:
- canFadeOutFromState:toState:
- fadeOutDuration
- variantDisplayString
- cacheDisplayString
- renderKeyInKeyplane:
- initWithType:withName:withProperties:withSubtrees:withCache:
@end
