@interface UIKeyboard : UIView
{
	id m_snapshot;
	id m_defaultTraits;
	BOOL m_typingDisabled;
	BOOL m_minimized;
	BOOL m_respondingToImplGeometryChange;
	long long m_orientation;
	long long m_idiom;
}

+ _isAutomaticKeyboard
+ _getCurrentKeyboardName
+ _getCurrentKeyplaneName
+ _getLocalizedInputMode
+ _setAutocorrects:
+ _getAutocorrection
+ _hasCandidates
+ _positionInCandidateList:
+ _baseKeyForRepresentedString:
+ _keyplaneForKey:
+ _keyplaneNamed:
+ _changeToKeyplane:
+ _touchPoint:
+ _typeCharacter:withError:shouldTypeVariants:baseKeyForVariants:
+ _setInputMode:
+ _acceptCurrentCandidate
+ manualKeyboardWillBeOrderedIn
+ manualKeyboardWasOrderedIn
+ manualKeyboardWillBeOrderedOut
+ manualKeyboardWasOrderedOut
+ initWithFrame:
+ dealloc
+ setNeedsDisplay
+ hitTest:withEvent:
+ pointInside:withEvent:
+ setFrame:
+ removeFromSuperview
+ delegate
+ isActive
+ interfaceOrientation
+ _deactivateForBackgrounding
+ touchesCancelled:withEvent:
+ touchesBegan:withEvent:
+ touchesMoved:withEvent:
+ touchesEnded:withEvent:
+ movedFromSuperview:
+ pointInside:forEvent:
+ deactivate
+ updateLayout
+ setCaretBlinks:
+ activate
+ _setRenderConfig:
+ textEffectsVisibilityLevel
+ acceptAutocorrection
+ removeAutocorrectPrompt
+ shouldSaveMinimizationState
+ isMinimized
+ setCaretVisible:
+ setReturnKeyEnabled:
+ keyboardIdiom
+ resizeForKeyplaneSize:
+ prepareForImplBoundsHeightChange:suppressNotification:
+ implBoundsHeightChangeDone:suppressNotification:
+ prepareForGeometryChange
+ setMinimized:
+ geometryChangeDone:
+ canDismiss
+ caretBlinks
+ setCorrectionLearningAllowed:
+ setDefaultTextInputTraits:
+ returnKeyEnabled
+ caretVisible
+ autoAdjustOrientation
+ autoAdjustOrientationForSize:
+ clearSnapshot
+ takeSnapshot
+ geometryForMinimize:
+ keyboardMinMaximized:finished:context:
+ minimize
+ maximize
+ geometryForImplHeightDelta:
+ initWithDefaultSize
+ hasAutocorrectPrompt
+ defaultTextInputTraits
+ typingEnabled
+ setTypingEnabled:
+ displayLayer:
+ syncMinimizedStateToHardwareKeyboardAttachedState
+ targetWindow
+ showsCandidatesInline
+ setShowsCandidatesInline:
+ setKeyboardIdiom:
- _isAutomaticKeyboard
- _getCurrentKeyboardName
- _getCurrentKeyplaneName
- _getLocalizedInputMode
- _setAutocorrects:
- _getAutocorrection
- _hasCandidates
- _positionInCandidateList:
- _baseKeyForRepresentedString:
- _keyplaneForKey:
- _keyplaneNamed:
- _changeToKeyplane:
- _touchPoint:
- _typeCharacter:withError:shouldTypeVariants:baseKeyForVariants:
- _setInputMode:
- _acceptCurrentCandidate
- manualKeyboardWillBeOrderedIn
- manualKeyboardWasOrderedIn
- manualKeyboardWillBeOrderedOut
- manualKeyboardWasOrderedOut
- initWithFrame:
- dealloc
- setNeedsDisplay
- hitTest:withEvent:
- pointInside:withEvent:
- setFrame:
- removeFromSuperview
- delegate
- isActive
- interfaceOrientation
- _deactivateForBackgrounding
- touchesCancelled:withEvent:
- touchesBegan:withEvent:
- touchesMoved:withEvent:
- touchesEnded:withEvent:
- movedFromSuperview:
- pointInside:forEvent:
- deactivate
- updateLayout
- setCaretBlinks:
- activate
- _setRenderConfig:
- textEffectsVisibilityLevel
- acceptAutocorrection
- removeAutocorrectPrompt
- shouldSaveMinimizationState
- isMinimized
- setCaretVisible:
- setReturnKeyEnabled:
- keyboardIdiom
- resizeForKeyplaneSize:
- prepareForImplBoundsHeightChange:suppressNotification:
- implBoundsHeightChangeDone:suppressNotification:
- prepareForGeometryChange
- setMinimized:
- geometryChangeDone:
- canDismiss
- caretBlinks
- setCorrectionLearningAllowed:
- setDefaultTextInputTraits:
- returnKeyEnabled
- caretVisible
- autoAdjustOrientation
- autoAdjustOrientationForSize:
- clearSnapshot
- takeSnapshot
- geometryForMinimize:
- keyboardMinMaximized:finished:context:
- minimize
- maximize
- geometryForImplHeightDelta:
- initWithDefaultSize
- hasAutocorrectPrompt
- defaultTextInputTraits
- typingEnabled
- setTypingEnabled:
- displayLayer:
- syncMinimizedStateToHardwareKeyboardAttachedState
- targetWindow
- showsCandidatesInline
- setShowsCandidatesInline:
- setKeyboardIdiom:
@end
