@interface UILabel : UIView
{
	struct _size;
	id _highlightedColor;
	long long _numberOfLines;
	long long _measuredNumberOfLines;
	double _lastLineBaseline;
	double _minimumScaleFactor;
	id _attributedText;
	id _synthesizedAttributedText;
	id _defaultAttributes;
	double _minimumFontSize;
	long long _lineSpacing;
	id _layout;
	id _scaledMetrics;
	struct _textLabelFlags;
	double _preferredMaxLayoutWidth;
}

+ stringMetricsForFirstLineWidth:
+ drawWithMetrics:inContext:
+ sb_yPositionForLabelWithContainerBounds:lineHeight:baselineOffset:font:
+ MPU_configureWithTextAttributes:
+ textAttributes
+ setTextAttributes:
+ _isTextFieldCenteredLabel
+ _image
+ defaultAccessibilityTraits
+ isAccessibilityElementByDefault
+ isElementAccessibilityExposedToInterfaceBuilder
+ color
+ textSizeForWidth:
+ _setColor:
+ setAutotrackTextToFit:
+ autotrackTextToFit
+ setColor:
+ setCentersHorizontally:
+ centersHorizontally
+ textRectForBounds:
+ drawContentsInRect:
+ setRawSize:
+ rawSize
+ _measuredNumberOfLines
+ _capOffsetFromBoundsTop
+ _firstLineBaselineOffsetFromBoundsTop
+ _firstLineCapFrameOriginY
+ _setFirstLineCapFrameOriginY:
+ _firstLineBaselineFrameOriginY
+ _setFirstLineBaselineFrameOriginY:
+ _lastLineBaselineFrameOriginY
+ _setLastLineBaselineFrameOriginY:
+ _scriptingInfo
+ labelTextIsTruncated
+ rc_baselinePoint
+ initWithFrame:
+ setUserInteractionEnabled:
+ dealloc
+ drawRect:
+ initWithCoder:
+ encodeWithCoder:
+ _intrinsicSizeWithinSize:
+ setFrame:
+ _setTextColor:
+ setBounds:
+ sizeThatFits:
+ setLineBreakMode:
+ setShadowColor:
+ setShadowOffset:
+ _minimumFontSize
+ _commonInit
+ isEnabled
+ _baselineOffsetFromBottom
+ setEnabled:
+ text
+ _setLineBreakMode:
+ setFont:
+ font
+ shadowOffset
+ intrinsicContentSize
+ _synthesizedAttributedText
+ setAttributedText:
+ shadowColor
+ _setFont:
+ setHighlighted:
+ isHighlighted
+ setTextColor:
+ setText:
+ _lastLineBaseline
+ attributedText
+ setAdjustsFontSizeToFitWidth:
+ adjustsFontSizeToFitWidth
+ setMinimumScaleFactor:
+ setTextAlignment:
+ textColor
+ textAlignment
+ setNumberOfLines:
+ _setMinimumFontSize:
+ setBaselineAdjustment:
+ updateConstraints
+ textSize
+ _disabledFontColor
+ _associatedScalingLabel
+ _actualScaleFactor
+ _defaultAttributes
+ _setSynthesizedAttributedText:
+ _shadow
+ letterpressStyle
+ _compatibilityAttributedString
+ currentTextColor
+ _invalidateAsNeededForNewSize:oldSize:
+ _setText:
+ _setTextAlignment:
+ lineBreakMode
+ _attributedStringHasAttributesNotCoveredByPrimitives
+ minimumScaleFactor
+ adjustsLetterSpacingToFitWidth
+ setLetterpressStyle:
+ _stringDrawingContext
+ _textRectForBounds:limitedToNumberOfLines:includingShadow:
+ _invalidateTextSize
+ _baselineOffsetDidChange
+ _updateScaledMetricsForRect:
+ highlightedTextColor
+ _setShadow:
+ _drawTextInRect:baselineCalculationOnly:
+ _preferredMaxLayoutWidth
+ _needsDoubleUpdateConstraintsPass
+ nsis_valueOfVariable:didChangeInEngine:
+ _prepareForFirstIntrinsicContentSizeCalculation
+ _prepareForSecondIntrinsicContentSizeCalculationWithEngine:
+ textRectForBounds:limitedToNumberOfLines:
+ _drawFullMarqueeTextInRect:
+ _startMarqueeIfNecessary
+ lineSpacing
+ drawTextInRect:
+ numberOfLines
+ setMarqueeRunning:
+ _siblingMarqueeLabels
+ _maximumMarqueeTextWidth
+ _coordinateBeginTimeForMarqueeAnimations:
+ marqueeRunning
+ _startMarquee
+ _stopMarqueeWithRedisplay:
+ _drawsUnderline
+ setPreferredMaxLayoutWidth:
+ _setDefaultAttributes:
+ _invalidateDefaultAttributes
+ setMinimumFontSize:
+ minimumFontSize
+ setHighlightedTextColor:
+ _setShadowUIOffset:
+ setShadowBlur:
+ shadowBlur
+ setLineSpacing:
+ setAdjustsLetterSpacingToFitWidth:
+ _setDrawsDebugBaselines:
+ _drawsDebugBaselines
+ baselineAdjustment
+ _setInSecondConstraintsPass:
+ _setWordRoundingEnabled:
+ _shouldDrawUnderlinesLikeWebKit
+ setMarqueeEnabled:
+ setDrawsLetterpress:
+ drawsLetterpress
+ setDrawsUnderline:
+ drawsUnderline
+ _setUsesSimpleTextEffects:
+ _usesSimpleTextEffects
+ preferredMaxLayoutWidth
- stringMetricsForFirstLineWidth:
- drawWithMetrics:inContext:
- sb_yPositionForLabelWithContainerBounds:lineHeight:baselineOffset:font:
- MPU_configureWithTextAttributes:
- textAttributes
- setTextAttributes:
- _isTextFieldCenteredLabel
- _image
- defaultAccessibilityTraits
- isAccessibilityElementByDefault
- isElementAccessibilityExposedToInterfaceBuilder
- color
- textSizeForWidth:
- _setColor:
- setAutotrackTextToFit:
- autotrackTextToFit
- setColor:
- setCentersHorizontally:
- centersHorizontally
- textRectForBounds:
- drawContentsInRect:
- setRawSize:
- rawSize
- _measuredNumberOfLines
- _capOffsetFromBoundsTop
- _firstLineBaselineOffsetFromBoundsTop
- _firstLineCapFrameOriginY
- _setFirstLineCapFrameOriginY:
- _firstLineBaselineFrameOriginY
- _setFirstLineBaselineFrameOriginY:
- _lastLineBaselineFrameOriginY
- _setLastLineBaselineFrameOriginY:
- _scriptingInfo
- labelTextIsTruncated
- rc_baselinePoint
- initWithFrame:
- setUserInteractionEnabled:
- dealloc
- drawRect:
- initWithCoder:
- encodeWithCoder:
- _intrinsicSizeWithinSize:
- setFrame:
- _setTextColor:
- setBounds:
- sizeThatFits:
- setLineBreakMode:
- setShadowColor:
- setShadowOffset:
- _minimumFontSize
- _commonInit
- isEnabled
- _baselineOffsetFromBottom
- setEnabled:
- text
- _setLineBreakMode:
- setFont:
- font
- shadowOffset
- intrinsicContentSize
- _synthesizedAttributedText
- setAttributedText:
- shadowColor
- _setFont:
- setHighlighted:
- isHighlighted
- setTextColor:
- setText:
- _lastLineBaseline
- attributedText
- setAdjustsFontSizeToFitWidth:
- adjustsFontSizeToFitWidth
- setMinimumScaleFactor:
- setTextAlignment:
- textColor
- textAlignment
- setNumberOfLines:
- _setMinimumFontSize:
- setBaselineAdjustment:
- updateConstraints
- textSize
- _disabledFontColor
- _associatedScalingLabel
- _actualScaleFactor
- _defaultAttributes
- _setSynthesizedAttributedText:
- _shadow
- letterpressStyle
- _compatibilityAttributedString
- currentTextColor
- _invalidateAsNeededForNewSize:oldSize:
- _setText:
- _setTextAlignment:
- lineBreakMode
- _attributedStringHasAttributesNotCoveredByPrimitives
- minimumScaleFactor
- adjustsLetterSpacingToFitWidth
- setLetterpressStyle:
- _stringDrawingContext
- _textRectForBounds:limitedToNumberOfLines:includingShadow:
- _invalidateTextSize
- _baselineOffsetDidChange
- _updateScaledMetricsForRect:
- highlightedTextColor
- _setShadow:
- _drawTextInRect:baselineCalculationOnly:
- _preferredMaxLayoutWidth
- _needsDoubleUpdateConstraintsPass
- nsis_valueOfVariable:didChangeInEngine:
- _prepareForFirstIntrinsicContentSizeCalculation
- _prepareForSecondIntrinsicContentSizeCalculationWithEngine:
- textRectForBounds:limitedToNumberOfLines:
- _drawFullMarqueeTextInRect:
- _startMarqueeIfNecessary
- lineSpacing
- drawTextInRect:
- numberOfLines
- setMarqueeRunning:
- _siblingMarqueeLabels
- _maximumMarqueeTextWidth
- _coordinateBeginTimeForMarqueeAnimations:
- marqueeRunning
- _startMarquee
- _stopMarqueeWithRedisplay:
- _drawsUnderline
- setPreferredMaxLayoutWidth:
- _setDefaultAttributes:
- _invalidateDefaultAttributes
- setMinimumFontSize:
- minimumFontSize
- setHighlightedTextColor:
- _setShadowUIOffset:
- setShadowBlur:
- shadowBlur
- setLineSpacing:
- setAdjustsLetterSpacingToFitWidth:
- _setDrawsDebugBaselines:
- _drawsDebugBaselines
- baselineAdjustment
- _setInSecondConstraintsPass:
- _setWordRoundingEnabled:
- _shouldDrawUnderlinesLikeWebKit
- setMarqueeEnabled:
- setDrawsLetterpress:
- drawsLetterpress
- setDrawsUnderline:
- drawsUnderline
- _setUsesSimpleTextEffects:
- _usesSimpleTextEffects
- preferredMaxLayoutWidth
@end
