@interface UIModalView : UIView
{
	id _delegate;
	id _titleLabel;
	id _subtitleLabel;
	id _bodyTextLabel;
	id _taglineTextLabel;
	double _startX;
	double _startY;
	id _context;
	long long _cancelButton;
	long long _defaultButton;
	long long _firstOtherButton;
	id _toolbar;
	id _originalWindow;
	id _dimWindow;
	long long _suspendTag;
	long long _dismissButtonIndex;
	double _bodyTextHeight;
	id _buttons;
	id _textFields;
	id _keyboard;
	id _table;
	id _dimView;
	id _sheetView;
	struct _modalViewFlags;
}

+ drawRect:
+ _handleKeyUIEvent:
+ context
+ canBecomeFirstResponder
+ setContext:
+ numberOfRows
+ _isAnimating
+ layout
+ textFieldAtIndex:
+ _maxHeight
+ defaultButton
+ setDefaultButton:
+ _defaultButton
+ _keyboardWillShow:
+ _keyboardWillHide:
+ userDidCancelPopoverView:
+ setSubtitle:
+ subtitle
+ dismiss
+ initWithTitle:buttons:defaultButtonIndex:delegate:context:
+ setNumberOfRows:
+ popupAlertAnimated:
+ setTitleMaxLineCount:
+ setRunsModal:
+ textField
+ tableView
+ keyboard
+ _addButtonWithTitleText:
+ _setDefaultButton:
+ requiresPortraitOrientation
+ setAlertSheetStyle:
+ _createBodyTextLabelIfNeeded
+ _createTaglineTextLabelIfNeeded
+ _createSubtitleLabelIfNeeded
+ _alertSheetTextFieldReturn:
+ textFieldCount
+ addTextFieldWithValue:label:
+ _buttonClicked:
+ _currentOrientation
+ buttons
+ _addButtonWithTitle:label:
+ _needsKeyboard
+ layoutAnimated:
+ _cancelAnimated:
+ _temporarilyHideAnimated:
+ _canShowAlerts
+ _layoutIfNeeded
+ _growAnimationDidStop:finished:
+ _cleanupAfterPopupAnimation
+ _bubbleAnimationShrinkDidStop:finished:
+ _bubbleAnimationNormalDidStop:finished:
+ _removeAlertWindowOrShowAnOldAlert
+ _popoutAnimationDidStop:finished:
+ _setupInitialFrame
+ _performPopup:
+ _repopup
+ _hideAnimated:
+ _performPopoutAnimationAnimated:
+ dismissAnimated:
+ _rotatingAnimationDidStop:
+ layoutAnimated:withDuration:
+ _layoutPopupAlertWithOrientation:animated:
+ _appSuspended:
+ popupAlertAnimated:atOffset:
+ _setAlertSheetStyleFromButtonBar:
+ _presentSheetStartingFromYCoordinate:
+ _presentSheetFromView:above:
+ _dimView
+ _alertSheetAnimationDidStop:finished:
+ _setupTitleStyle
+ _titleHorizontalInset
+ _buttonHeight
+ _titleVerticalTopInset
+ _titleVerticalBottomInset
+ _bottomVerticalInset
+ _truncateViewHeight:toFitInFrame:withMinimumHeight:
+ presentSheetFromAboveView:
+ presentSheetFromBehindView:
+ _prepareToBeReplaced
+ groupsTextFields
+ setGroupsTextFields:
+ _createTitleLabelIfNeeded
+ setBodyText:
+ setTaglineText:
+ bodyText
+ titleMaxLineCount
+ setBodyTextMaxLineCount:
+ bodyMaxLineCount
+ _setTextFieldsHidden:
+ setDestructiveButton:
+ destructiveButton
+ addButtonWithTitle:label:
+ _addButtonWithTitle:
+ buttonCount
+ _isSBAlert
+ setTableShouldShowMinimumContent:
+ tableShouldShowMinimumContent
+ _manualKeyboardIsVisible
+ setShowsOverSpringBoardAlerts:
+ showsOverSpringBoardAlerts
+ _repopupNoAnimation
+ _dimsBackground
+ isBodyTextTruncated
+ popupAlertAnimated:fromBarButtonItem:
+ presentSheetInView:
+ presentSheetToAboveView:
+ setDimView:
+ _slideSheetOut:
+ backgroundSize
+ alertSheetStyle
+ setDimsBackground:
+ dimsBackground
+ setSuspendTag:
+ suspendTag
+ setBlocksInteraction:
+ blocksInteraction
+ runsModal
+ titleRect
+ numberOfLinesInTitle
+ presentSheetFromButtonBar:
+ bodyTextView
+ taglineTextView
+ _prepareForDisplay
+ replaceAlert:
+ initWithFrame:
+ dealloc
+ setDelegate:
+ setTitle:
+ delegate
+ cancelButtonIndex
+ dismissWithClickedButtonIndex:animated:
+ addButtonWithTitle:
+ setCancelButtonIndex:
+ title
+ message
+ defaultButtonIndex
+ setMessage:
+ isVisible
+ numberOfButtons
+ setDefaultButtonIndex:
+ buttonTitleAtIndex:
+ initWithTitle:message:delegate:defaultButton:cancelButton:otherButtons:
+ _initWithTelephoneNumber:buttons:defaultButtonIndex:delegate:context:
+ _setFirstOtherButtonIndex:
+ firstOtherButtonIndex
- drawRect:
- _handleKeyUIEvent:
- context
- canBecomeFirstResponder
- setContext:
- numberOfRows
- _isAnimating
- layout
- textFieldAtIndex:
- _maxHeight
- defaultButton
- setDefaultButton:
- _defaultButton
- _keyboardWillShow:
- _keyboardWillHide:
- userDidCancelPopoverView:
- setSubtitle:
- subtitle
- dismiss
- initWithTitle:buttons:defaultButtonIndex:delegate:context:
- setNumberOfRows:
- popupAlertAnimated:
- setTitleMaxLineCount:
- setRunsModal:
- textField
- tableView
- keyboard
- _addButtonWithTitleText:
- _setDefaultButton:
- requiresPortraitOrientation
- setAlertSheetStyle:
- _createBodyTextLabelIfNeeded
- _createTaglineTextLabelIfNeeded
- _createSubtitleLabelIfNeeded
- _alertSheetTextFieldReturn:
- textFieldCount
- addTextFieldWithValue:label:
- _buttonClicked:
- _currentOrientation
- buttons
- _addButtonWithTitle:label:
- _needsKeyboard
- layoutAnimated:
- _cancelAnimated:
- _temporarilyHideAnimated:
- _canShowAlerts
- _layoutIfNeeded
- _growAnimationDidStop:finished:
- _cleanupAfterPopupAnimation
- _bubbleAnimationShrinkDidStop:finished:
- _bubbleAnimationNormalDidStop:finished:
- _removeAlertWindowOrShowAnOldAlert
- _popoutAnimationDidStop:finished:
- _setupInitialFrame
- _performPopup:
- _repopup
- _hideAnimated:
- _performPopoutAnimationAnimated:
- dismissAnimated:
- _rotatingAnimationDidStop:
- layoutAnimated:withDuration:
- _layoutPopupAlertWithOrientation:animated:
- _appSuspended:
- popupAlertAnimated:atOffset:
- _setAlertSheetStyleFromButtonBar:
- _presentSheetStartingFromYCoordinate:
- _presentSheetFromView:above:
- _dimView
- _alertSheetAnimationDidStop:finished:
- _setupTitleStyle
- _titleHorizontalInset
- _buttonHeight
- _titleVerticalTopInset
- _titleVerticalBottomInset
- _bottomVerticalInset
- _truncateViewHeight:toFitInFrame:withMinimumHeight:
- presentSheetFromAboveView:
- presentSheetFromBehindView:
- _prepareToBeReplaced
- groupsTextFields
- setGroupsTextFields:
- _createTitleLabelIfNeeded
- setBodyText:
- setTaglineText:
- bodyText
- titleMaxLineCount
- setBodyTextMaxLineCount:
- bodyMaxLineCount
- _setTextFieldsHidden:
- setDestructiveButton:
- destructiveButton
- addButtonWithTitle:label:
- _addButtonWithTitle:
- buttonCount
- _isSBAlert
- setTableShouldShowMinimumContent:
- tableShouldShowMinimumContent
- _manualKeyboardIsVisible
- setShowsOverSpringBoardAlerts:
- showsOverSpringBoardAlerts
- _repopupNoAnimation
- _dimsBackground
- isBodyTextTruncated
- popupAlertAnimated:fromBarButtonItem:
- presentSheetInView:
- presentSheetToAboveView:
- setDimView:
- _slideSheetOut:
- backgroundSize
- alertSheetStyle
- setDimsBackground:
- dimsBackground
- setSuspendTag:
- suspendTag
- setBlocksInteraction:
- blocksInteraction
- runsModal
- titleRect
- numberOfLinesInTitle
- presentSheetFromButtonBar:
- bodyTextView
- taglineTextView
- _prepareForDisplay
- replaceAlert:
- initWithFrame:
- dealloc
- setDelegate:
- setTitle:
- delegate
- cancelButtonIndex
- dismissWithClickedButtonIndex:animated:
- addButtonWithTitle:
- setCancelButtonIndex:
- title
- message
- defaultButtonIndex
- setMessage:
- isVisible
- numberOfButtons
- setDefaultButtonIndex:
- buttonTitleAtIndex:
- initWithTitle:message:delegate:defaultButton:cancelButton:otherButtons:
- _initWithTelephoneNumber:buttons:defaultButtonIndex:delegate:context:
- _setFirstOtherButtonIndex:
- firstOtherButtonIndex
@end
