@interface UINavigationItemButtonView : UINavigationItemView
{
	long long _style;
	BOOL _pressed;
	id _appearanceStorage;
	BOOL _customBackgroundImageChangedToOrFromNil;
	id _imageView;
	usigned long long _abbreviatedTitleIndex;
}

+ initWithFrame:
+ dealloc
+ drawRect:
+ layoutSubviews
+ sizeThatFits:
+ setStyle:
+ alignmentRectInsets
+ image
+ _canDrawContent
+ _appearanceGuideClass
+ tintColorDidChange
+ _scriptingInfo
+ _abbreviatedTitleIndex
+ _setAbbreviatedTitleIndex:
+ setPressed:
+ _appearanceStorage
+ _applyBarButtonAppearanceStorage:withTaggedSelectors:
+ title
+ _backButtonBackgroundImageForState:barMetrics:
+ customBackgroundImageChangedToOrFromNil
+ setPressed:initialPress:
+ pressed
+ _UIAppearance_setTintColor:
+ _setTintColor:
+ backIndicatorViewHasRespondedToCustomBackgroundImageChange
+ hasCustomBackgroundImage
+ setStyle:animated:
+ imageSize
+ _defaultFont
+ _backgroundVerticalPositionAdjustmentForBarMetrics:
+ _tintColor
+ _setBackgroundImage:forState:style:barMetrics:
+ _UIAppearance_setBackgroundImage:forState:style:barMetrics:
+ _UIAppearance_setBackgroundImage:forState:barMetrics:
+ _UIAppearance_setTitleTextAttributes:forState:
+ _UIAppearance_setBackgroundVerticalPositionAdjustment:forBarMetrics:
+ _UIAppearance_setTitlePositionAdjustment:forBarMetrics:
+ _setTitleTextAttributes:forState:
+ _setTitlePositionAdjustment:forBarMetrics:
+ _setBackgroundVerticalPositionAdjustment:forBarMetrics:
+ _setBackgroundImage:forState:barMetrics:
+ _titleTextAttributesForState:
+ _UIAppearance_setBackButtonBackgroundImage:forState:barMetrics:
+ _setBackButtonBackgroundImage:forState:barMetrics:
+ _UIAppearance_setBackButtonTitlePositionAdjustment:forBarMetrics:
+ _setBackButtonTitlePositionAdjustment:forBarMetrics:
+ _UIAppearance_setBackButtonBackgroundVerticalPositionAdjustment:forBarMetrics:
+ _setBackButtonBackgroundVerticalPositionAdjustment:forBarMetrics:
+ _labelFrame
+ _useSilverLookForBarStyle:
+ _currentTextColorForBarStyle:
+ _currentTextShadowOffsetForBarStyle:
+ _currentTextShadowColorForBarStyle:
+ _titleYAdjustmentCustomization
+ _currentCustomBackgroundNeedsDarkening:
+ _drawBackground
+ _styleAnimationDidStop:finished:context:
+ _backButtonBackgroundVerticalPositionAdjustmentForBarMetrics:
+ _backButtonTitlePositionAdjustmentForBarMetrics:
- initWithFrame:
- dealloc
- drawRect:
- layoutSubviews
- sizeThatFits:
- setStyle:
- alignmentRectInsets
- image
- _canDrawContent
- _appearanceGuideClass
- tintColorDidChange
- _scriptingInfo
- _abbreviatedTitleIndex
- _setAbbreviatedTitleIndex:
- setPressed:
- _appearanceStorage
- _applyBarButtonAppearanceStorage:withTaggedSelectors:
- title
- _backButtonBackgroundImageForState:barMetrics:
- customBackgroundImageChangedToOrFromNil
- setPressed:initialPress:
- pressed
- _UIAppearance_setTintColor:
- _setTintColor:
- backIndicatorViewHasRespondedToCustomBackgroundImageChange
- hasCustomBackgroundImage
- setStyle:animated:
- imageSize
- _defaultFont
- _backgroundVerticalPositionAdjustmentForBarMetrics:
- _tintColor
- _setBackgroundImage:forState:style:barMetrics:
- _UIAppearance_setBackgroundImage:forState:style:barMetrics:
- _UIAppearance_setBackgroundImage:forState:barMetrics:
- _UIAppearance_setTitleTextAttributes:forState:
- _UIAppearance_setBackgroundVerticalPositionAdjustment:forBarMetrics:
- _UIAppearance_setTitlePositionAdjustment:forBarMetrics:
- _setTitleTextAttributes:forState:
- _setTitlePositionAdjustment:forBarMetrics:
- _setBackgroundVerticalPositionAdjustment:forBarMetrics:
- _setBackgroundImage:forState:barMetrics:
- _titleTextAttributesForState:
- _UIAppearance_setBackButtonBackgroundImage:forState:barMetrics:
- _setBackButtonBackgroundImage:forState:barMetrics:
- _UIAppearance_setBackButtonTitlePositionAdjustment:forBarMetrics:
- _setBackButtonTitlePositionAdjustment:forBarMetrics:
- _UIAppearance_setBackButtonBackgroundVerticalPositionAdjustment:forBarMetrics:
- _setBackButtonBackgroundVerticalPositionAdjustment:forBarMetrics:
- _labelFrame
- _useSilverLookForBarStyle:
- _currentTextColorForBarStyle:
- _currentTextShadowOffsetForBarStyle:
- _currentTextShadowColorForBarStyle:
- _titleYAdjustmentCustomization
- _currentCustomBackgroundNeedsDarkening:
- _drawBackground
- _styleAnimationDidStop:finished:context:
- _backButtonBackgroundVerticalPositionAdjustmentForBarMetrics:
- _backButtonTitlePositionAdjustmentForBarMetrics:
@end
