@interface UIPasteboard : NSObject
{
	id _name;
}

+ _initWithName:system:create:
+ _pasteboardChanged:
+ setImage:
+ setColors:
+ string
+ images
+ image
+ URL
+ color
+ setColor:
+ setString:
+ setURL:
+ setImages:
+ setStrings:
+ strings
+ setURLs:
+ URLs
+ colors
+ __ck_preferredPasteboardValues
+ __ck_pasteboardTypesForIndex:
+ __ck_valueForPasteboardType:atIndex:
+ __ck_pasteboardTypeListRTF
+ __ck_dataForPasteboardType:atIndex:
+ mf_addPasteboardRepresentationsForTextAttachments:
+ mf_getAttachmentsPasteboardRepresentations
+ mf_addPasteboardRepresentationsForAttachments:
+ pl_setAsset:
+ pl_setAssets:
+ pl_assetsInPhotoLibrary:
+ pl_containsAssets
+ dealloc
+ init
+ name
+ items
+ setItems:
+ changeCount
+ numberOfItems
+ valuesForPasteboardType:inItemSet:
+ valueForPasteboardType:
+ dataForPasteboardType:inItemSet:
+ containsPasteboardTypes:inItemSet:
+ setData:forPasteboardType:
+ pasteboardTypesForItemSet:
+ _addItems:oldPasteboardTypes:
+ pasteboardTypes
+ containsPasteboardTypes:
+ dataForPasteboardType:
+ setValue:forPasteboardType:
+ itemSetWithPasteboardTypes:
+ addItems:
+ isPersistent
+ setPersistent:
- _initWithName:system:create:
- _pasteboardChanged:
- setImage:
- setColors:
- string
- images
- image
- URL
- color
- setColor:
- setString:
- setURL:
- setImages:
- setStrings:
- strings
- setURLs:
- URLs
- colors
- __ck_preferredPasteboardValues
- __ck_pasteboardTypesForIndex:
- __ck_valueForPasteboardType:atIndex:
- __ck_pasteboardTypeListRTF
- __ck_dataForPasteboardType:atIndex:
- mf_addPasteboardRepresentationsForTextAttachments:
- mf_getAttachmentsPasteboardRepresentations
- mf_addPasteboardRepresentationsForAttachments:
- pl_setAsset:
- pl_setAssets:
- pl_assetsInPhotoLibrary:
- pl_containsAssets
- dealloc
- init
- name
- items
- setItems:
- changeCount
- numberOfItems
- valuesForPasteboardType:inItemSet:
- valueForPasteboardType:
- dataForPasteboardType:inItemSet:
- containsPasteboardTypes:inItemSet:
- setData:forPasteboardType:
- pasteboardTypesForItemSet:
- _addItems:oldPasteboardTypes:
- pasteboardTypes
- containsPasteboardTypes:
- dataForPasteboardType:
- setValue:forPasteboardType:
- itemSetWithPasteboardTypes:
- addItems:
- isPersistent
- setPersistent:
@end
