@interface UIScrollView : UIView
{
	id _delegate;
	struct _contentSize;
	struct _contentInset;
	id _verticalScrollIndicator;
	id _horizontalScrollIndicator;
	id _staticScrollBar;
	struct _scrollIndicatorInset;
	double _startOffsetX;
	double _startOffsetY;
	double _lastUpdateOffsetX;
	double _lastUpdateOffsetY;
	double _lastUpdateTime;
	double _minimumZoomScale;
	double _maximumZoomScale;
	id _zoomView;
	double _horizontalVelocity;
	double _verticalVelocity;
	double _previousHorizontalVelocity;
	double _previousVerticalVelocity;
	id _scrollHeartbeat;
	struct _pageDecelerationTarget;
	struct _decelerationFactor;
	struct _adjustedDecelerationTarget;
	struct _adjustedDecelerationFactor;
	double _decelerationLnFactorH;
	double _decelerationLnFactorV;
	pointer _shadows;
	id _scrollNotificationViews;
	double _contentOffsetAnimationDuration;
	id _animation;
	id _zoomAnimation;
	id _pinch;
	id _pan;
	id _swipe;
	id _touchDelayGestureRecognizer;
	Array _lowFidelitySwipeGestureRecognizers;
	id _draggingChildScrollView;
	struct _parentAdjustment;
	double _pagingSpringPull;
	double _pagingFriction;
	long long _fastScrollCount;
	double _fastScrollMultiplier;
	double _fastScrollStartMultiplier;
	double _fastScrollEndTime;
	struct _rotationCenterPoint;
	double _accuracy;
	usigned long long _zoomAnimationCount;
	struct _accumulatedOffset;
	long long _touchLevel;
	double _savedKeyboardAdjustmentDelta;
	struct _scrollViewFlags;
	BOOL _useContentDimensionVariablesForConstraintLowering;
	id _scrollTestParameters;
	long long _keyboardDismissMode;
	id _contentWidthVariable;
	id _contentHeightVariable;
	id _automaticContentConstraints;
	struct _zoomAnchorPoint;
}

+ centerToContentView
+ ab_scrollToSelectionOfTextView:
+ ab_scrollToSelectionOfTextView:animated:
+ ab_verticalOverlapUsingKeyboardInfo:
+ ab_adjustForAutomaticKeyboardInfo:lastAdjustment:
+ scrollableDirections
+ maxVelocityInDirection:
+ isElementAccessibilityExposedToInterfaceBuilder
+ _performScrollTest:iterations:delta:length:
+ _incrementForScrollTest
+ _scrollTestExtraResults
+ _performScrollTest:iterations:delta:
+ encodeRestorableStateWithCoder:
+ decodeRestorableStateWithCoder:
+ _viewIsInsideNavigationController
+ _forwardsToParentScroller
+ _addScrollNotificationView:
+ _removeScrollNotificationView:
+ _skipNextStartOffsetAdjustment
+ _clearContentOffsetAnimation:
+ _stopScrollingAndZoomingAnimationsPinningToContentViewport:
+ _canScrollX
+ _canScrollY
+ _adjustContentOffsetIfNecessary
+ _notifyDidScroll
+ _adjustBackgroundShadowsForContentSizeForcedVisible:
+ _stopScrollingNotify:pin:
+ _setContentOffset:animated:animationCurve:
+ _rubberBandOffsetForOffset:maxOffset:minOffset:range:outside:
+ _scrollViewWillBeginDragging
+ _shouldScrollOnGestureRecognizerFailed
+ _scrollViewDidEndDraggingWithDeceleration:
+ _scrollViewDidEndZooming
+ _scrollViewWillBeginZooming
+ _beginTrackingWithEvent:
+ _resetScrollingWithUIEvent:
+ _contentOffsetAnimationDuration
+ _setContentOffsetAnimationDuration:
+ _animatedTargetOffset
+ _horizontalVelocity
+ _verticalVelocity
+ _isBouncing
+ _offsetForRubberBandOffset:maxOffset:minOffset:range:
+ _shadowHeightOffset
+ _adjustBackgroundShadowsForContentSizeForcedVisible:withOffset:
+ _scrollViewDidEndDecelerating
+ _stopScrollDecelerationNotify:
+ _stopScrollingNotify:pin:tramplingDragFlags:
+ _clearContentOffsetAnimation
+ _stopScrollingAndZoomingAnimationsPinningToContentViewport:tramplingDragFlags:
+ _addContentSubview:atBack:
+ _setContentOffset:animated:animationCurve:animationAdjustsForContentOffsetDelta:
+ _originalOffsetForAnimatedSetContentOffset
+ _scrollViewAnimationEnded:finished:
+ _delegateScrollViewAnimationEnded
+ _adjustShadowsIfNecessary
+ _shouldTrackImmediatelyWhileDecelerating
+ _clearParentAdjustment
+ _adjustStartOffsetForGrabbedBouncingScrollView
+ _stopScrollingAndZoomingAnimations
+ _resetScrollingForGestureEvent:
+ _canCancelContentTouches:
+ _moveContentSubview:toBack:
+ _setContentOffset:duration:animationCurve:
+ _setAbsoluteContentOffset:animated:
+ _updateScrollAnimationForChangedTargetOffset:
+ _setAutomaticContentOffsetAdjustmentEnabled:
+ _isAutomaticContentOffsetAdjustmentEnabled
+ _forceDelegateScrollViewDidZoom:
+ _ensureViewsAreLoadedInRect:
+ animator:stopAnimation:fraction:
+ _scrollsToMakeFirstResponderVisible
+ _touchDelayForScrollDetection
+ _setContentOffsetPinned:
+ _setContentOffsetPinned:animated:
+ _parentScrollView
+ _animatedOriginalOffset
+ _setAlwaysBounceVertical:
+ _setShowsVerticalScrollIndicator:
+ _setShowsHorizontalScrollIndicator:
+ _adjustedContentOffsetPinnedToScrollableBounds:
+ _adjustForAutomaticKeyboardInfo:animated:lastAdjustment:
+ _pagingLeft
+ _pagingRight
+ _pagingUp
+ _pagingDown
+ _setAutoscrolling:
+ _isAutoscrolling
+ autoscrollContentOffset
+ setAutoscrollContentOffset:
+ contentFrameForView:
+ _adjustShadowsIfNecessaryForOffset:
+ _backgroundShadowForSlideAnimation
+ _pinContentOffsetToClosestPageBoundary
+ _rectForPageContainingView:
+ _isScrollingEnabled
+ __ck_isScrolledToBottom
+ __ck_scrollToBottom:
+ __ck_isScrolledToTop
+ __ck_scrollToTop:
+ __ck_contentSize
+ __ck_scrollToBottomContentOffset
+ __ck_scrollToTopContentOffset
+ keyForContentMode:
+ saveScrollPositionForKey:
+ restoreScrollPositionForKey:
+ _testingScrollStep
+ scrollBy:forIterations:
+ runScrollTest:withDelta:forIterations:
+ topExtensionViewColor
+ setTopExtensionViewColor:
+ mf_needsToAdjustContentOffset
+ initWithFrame:
+ setUserInteractionEnabled:
+ dealloc
+ initWithCoder:
+ _populateArchivedSubviews:
+ encodeWithCoder:
+ setDelegate:
+ hitTest:withEvent:
+ setFrame:
+ setShowsVerticalScrollIndicator:
+ layoutSubviews
+ removeFromSuperview
+ setBounds:
+ isDragging
+ isDecelerating
+ description
+ delegate
+ gestureRecognizer:shouldReceiveTouch:
+ touchesCancelled:withEvent:
+ isProgrammaticScrollEnabled
+ setProgrammaticScrollEnabled:
+ isScrollEnabled
+ _scrollToTopFromTouchAtScreenLocation:resultHandler:
+ touchesBegan:withEvent:
+ touchesMoved:withEvent:
+ touchesEnded:withEvent:
+ _didChangeFromIdiom:onScreen:traverseHierarchy:
+ isTracking
+ cancelTouchTracking
+ cancelMouseTracking
+ _contentWidthVariable
+ _contentHeightVariable
+ nsli_contentWidthVariable
+ nsli_contentHeightVariable
+ _didAddDependentConstraint:
+ _didRemoveDependentConstraint:
+ _resizeWithOldSuperviewSize:
+ _supportsContentDimensionVariables
+ _willMoveToWindow:
+ _didMoveFromWindow:toWindow:
+ _setSubviewWantsAutolayout
+ _webCustomViewWillBeRemovedFromSuperview
+ setContentOffset:
+ _createGestureRecognizersForCurrentTouchLevel
+ _adjustScrollerIndicators:alwaysShowingThem:
+ setDirectionalLockEnabled:
+ _updateContentFitDisableScrolling
+ _getDelegateZoomView
+ isZooming
+ _centerContentIfNecessary
+ isDirectionalLockEnabled
+ setScrollTestParameters:
+ _staticScrollBar
+ _layoutStaticScrollBar
+ _staticScrollBar:didScrollInDirection:
+ _updateUsesStaticScrollBar
+ _enableOnlyGestureRecognizersForCurrentTouchLevel
+ _setUsesStaticScrollBar:
+ handlePan:
+ handlePinch:
+ _updatePanGestureConfiguration
+ _handleSwipe:
+ _updateScrollGestureRecognizersEnabled
+ _startBeingDraggedByChild:
+ _stopBeingDraggedByChild:
+ isPagingEnabled
+ _transfersScrollToContainer
+ contentOffset
+ _adjustedHorizontalOffsetPinnedToScrollableBounds:
+ _adjustedVerticalOffsetPinnedToScrollableBounds:
+ _startDraggingParent:
+ _stopDraggingParent:
+ contentSize
+ zoomScale
+ setContentSize:
+ _attemptToDragParent:forNewBounds:oldBounds:
+ _automaticContentConstraints
+ _constraintsFromContentSize
+ _setAutomaticContentConstraints:
+ contentInset
+ _registerAsScrollToTopViewIfPossible
+ setContentOffset:animated:
+ _scrollViewTouchDelayGesture
+ setScrollEnabled:
+ _updateZoomGestureRecognizersEnabled
+ _updatePagingGesture
+ _abuttedEdgesForContentOffset:
+ _currentlyAbuttedContentEdges
+ delayed:
+ _updatePinchGesture
+ _systemGestureStateChanged:
+ _handleLowFidelitySwipe:
+ minimumZoomScale
+ willRotateToInterfaceOrientation:
+ willAnimateRotationToInterfaceOrientation:
+ _registerForRotation:ofWindow:
+ _hideScrollIndicators
+ _setShowsBackgroundShadow:
+ alwaysBounceHorizontal
+ alwaysBounceVertical
+ _rubberBandContentOffsetForOffset:outsideX:outsideY:
+ keyboardDismissMode
+ _scrollViewWillEndDraggingWithDeceleration:
+ _startTimer:
+ _popTrackingRunLoopMode
+ _staysCenteredDuringPinch
+ _zoomScaleFromPresentationLayer:
+ _setZoomAnchorPoint:
+ setZoomScale:withAnchorPoint:validatingScrollOffset:allowRubberbanding:animated:duration:notifyDelegate:
+ _updatePinchGestureForState:
+ setZoomScale:withAnchorPoint:validatingScrollOffset:allowRubberbanding:animated:duration:notifyDelegate:force:
+ _prepareToPageWithHorizontalVelocity:verticalVelocity:
+ _endPanNormal:
+ _updatePanGesture
+ _accumulateViewConstraintsIntoArray:
+ _nsis_contentSize
+ _constraintAffectsContentSize:
+ _layoutVariablesWithAmbiguousValue
+ _zoomToCenter:scale:duration:force:
+ setZoomScale:animated:
+ _zoomRubberBandScaleForScale:
+ _zoomAnimationDurationForScale:
+ _zoomAnimationDidStop
+ _adjustContentSizeForView:atScale:
+ _zoomAnchorPoint
+ _markScrollViewAnimationForKey:ofView:
+ _zoomScaleForRubberBandScale:
+ _getPagingDecelerationOffset:forTimeInterval:
+ _getBouncingDecelerationOffset:forTimeInterval:lastUpdateOffset:min:max:decelerationFactor:decelerationLnFactor:velocity:
+ _getStandardDecelerationOffset:forTimeInterval:min:max:decelerationFactor:decelerationLnFactor:velocity:
+ _smoothScrollWithUpdateTime:
+ _smoothScrollTimer:
+ _smoothScrollDisplayLink:
+ _runLoopModePopped:
+ _isAnimatingScroll
+ _contentOffsetForLowFidelityScrollInDirection:duration:
+ _lowFidelityScrollInDirection:
+ _smoothScrollIntoBounds
+ _panGestureRecognizer
+ setContentInset:
+ _isRectFullyVisible:
+ _adjustsTargetsOnContentOffsetChanges
+ _setAdjustsTargetsOnContentOffsetChanges:
+ scrollRectToVisible:animated:
+ setScrollingEnabled:
+ setZoomEnabled:
+ isZoomEnabled
+ _isScrollingToTop
+ setPagingEnabled:
+ _abuttedPagingEdges
+ setBounces:
+ bounces
+ setBouncesHorizontally:
+ bouncesHorizontally
+ setBouncesVertically:
+ bouncesVertically
+ setUpdateInsetBottomDuringKeyboardDismiss:
+ updateInsetBottomDuringKeyboardDismiss
+ setAlwaysBounceVertical:
+ setAlwaysBounceHorizontal:
+ _setTransfersScrollToContainer:
+ _isVerticalBouncing
+ _isHorizontalBouncing
+ showsHorizontalScrollIndicator
+ setShowsHorizontalScrollIndicator:
+ showsVerticalScrollIndicator
+ setScrollIndicatorInsets:
+ scrollIndicatorInsets
+ setIndicatorStyle:
+ decelerationRate
+ setDecelerationRate:
+ indicatorStyle
+ horizontalScrollDecelerationFactor
+ setHorizontalScrollDecelerationFactor:
+ verticalScrollDecelerationFactor
+ setVerticalScrollDecelerationFactor:
+ setAllowsMultipleFingers:
+ allowsMultipleFingers
+ setTracksImmediatelyWhileDecelerating:
+ tracksImmediatelyWhileDecelerating
+ _scrollHysteresis
+ preservesCenterDuringRotation
+ setPreservesCenterDuringRotation:
+ flashScrollIndicators
+ _showsBackgroundShadow
+ setShowBackgroundShadow:
+ _touchPositionForTouches:
+ _rubberBandToOffset:
+ _setStaysCenteredDuringPinch:
+ gestureRecognizer:canPreventGestureRecognizer:
+ _gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:
+ _gestureRecognizer:shouldReceiveTouch:
+ _gestureRecognizerFailed:
+ bouncesZoom
+ setBouncesZoom:
+ canCancelContentTouches
+ setCanCancelContentTouches:
+ delaysContentTouches
+ setDelaysContentTouches:
+ touchesShouldBegin:withEvent:inContentView:
+ touchesShouldCancelInContentView:
+ scrollsToTop
+ setScrollsToTop:
+ _setIgnoreLinkedOnChecks:
+ _ignoreLinkedOnChecks
+ _pagingFriction
+ _setPagingFriction:
+ _defaultPagingFriction
+ setMinimumZoomScale:
+ setMaximumZoomScale:
+ maximumZoomScale
+ _zoomToCenter:scale:duration:
+ _ownsAnimationForKey:ofView:
+ setZoomScale:
+ zoomToRect:animated:
+ isZoomBouncing
+ _isAnimatingZoom
+ _pageDecelerationTarget
+ _staticScrollBarScrollAnimationEnded
+ panGestureRecognizer
+ pinchGestureRecognizer
+ scrollTestParameters
+ setKeyboardDismissMode:
+ _useContentDimensionVariablesForConstraintLowering
+ _setUseContentDimensionVariablesForConstraintLowering:
- centerToContentView
- ab_scrollToSelectionOfTextView:
- ab_scrollToSelectionOfTextView:animated:
- ab_verticalOverlapUsingKeyboardInfo:
- ab_adjustForAutomaticKeyboardInfo:lastAdjustment:
- scrollableDirections
- maxVelocityInDirection:
- isElementAccessibilityExposedToInterfaceBuilder
- _performScrollTest:iterations:delta:length:
- _incrementForScrollTest
- _scrollTestExtraResults
- _performScrollTest:iterations:delta:
- encodeRestorableStateWithCoder:
- decodeRestorableStateWithCoder:
- _viewIsInsideNavigationController
- _forwardsToParentScroller
- _addScrollNotificationView:
- _removeScrollNotificationView:
- _skipNextStartOffsetAdjustment
- _clearContentOffsetAnimation:
- _stopScrollingAndZoomingAnimationsPinningToContentViewport:
- _canScrollX
- _canScrollY
- _adjustContentOffsetIfNecessary
- _notifyDidScroll
- _adjustBackgroundShadowsForContentSizeForcedVisible:
- _stopScrollingNotify:pin:
- _setContentOffset:animated:animationCurve:
- _rubberBandOffsetForOffset:maxOffset:minOffset:range:outside:
- _scrollViewWillBeginDragging
- _shouldScrollOnGestureRecognizerFailed
- _scrollViewDidEndDraggingWithDeceleration:
- _scrollViewDidEndZooming
- _scrollViewWillBeginZooming
- _beginTrackingWithEvent:
- _resetScrollingWithUIEvent:
- _contentOffsetAnimationDuration
- _setContentOffsetAnimationDuration:
- _animatedTargetOffset
- _horizontalVelocity
- _verticalVelocity
- _isBouncing
- _offsetForRubberBandOffset:maxOffset:minOffset:range:
- _shadowHeightOffset
- _adjustBackgroundShadowsForContentSizeForcedVisible:withOffset:
- _scrollViewDidEndDecelerating
- _stopScrollDecelerationNotify:
- _stopScrollingNotify:pin:tramplingDragFlags:
- _clearContentOffsetAnimation
- _stopScrollingAndZoomingAnimationsPinningToContentViewport:tramplingDragFlags:
- _addContentSubview:atBack:
- _setContentOffset:animated:animationCurve:animationAdjustsForContentOffsetDelta:
- _originalOffsetForAnimatedSetContentOffset
- _scrollViewAnimationEnded:finished:
- _delegateScrollViewAnimationEnded
- _adjustShadowsIfNecessary
- _shouldTrackImmediatelyWhileDecelerating
- _clearParentAdjustment
- _adjustStartOffsetForGrabbedBouncingScrollView
- _stopScrollingAndZoomingAnimations
- _resetScrollingForGestureEvent:
- _canCancelContentTouches:
- _moveContentSubview:toBack:
- _setContentOffset:duration:animationCurve:
- _setAbsoluteContentOffset:animated:
- _updateScrollAnimationForChangedTargetOffset:
- _setAutomaticContentOffsetAdjustmentEnabled:
- _isAutomaticContentOffsetAdjustmentEnabled
- _forceDelegateScrollViewDidZoom:
- _ensureViewsAreLoadedInRect:
- animator:stopAnimation:fraction:
- _scrollsToMakeFirstResponderVisible
- _touchDelayForScrollDetection
- _setContentOffsetPinned:
- _setContentOffsetPinned:animated:
- _parentScrollView
- _animatedOriginalOffset
- _setAlwaysBounceVertical:
- _setShowsVerticalScrollIndicator:
- _setShowsHorizontalScrollIndicator:
- _adjustedContentOffsetPinnedToScrollableBounds:
- _adjustForAutomaticKeyboardInfo:animated:lastAdjustment:
- _pagingLeft
- _pagingRight
- _pagingUp
- _pagingDown
- _setAutoscrolling:
- _isAutoscrolling
- autoscrollContentOffset
- setAutoscrollContentOffset:
- contentFrameForView:
- _adjustShadowsIfNecessaryForOffset:
- _backgroundShadowForSlideAnimation
- _pinContentOffsetToClosestPageBoundary
- _rectForPageContainingView:
- _isScrollingEnabled
- __ck_isScrolledToBottom
- __ck_scrollToBottom:
- __ck_isScrolledToTop
- __ck_scrollToTop:
- __ck_contentSize
- __ck_scrollToBottomContentOffset
- __ck_scrollToTopContentOffset
- keyForContentMode:
- saveScrollPositionForKey:
- restoreScrollPositionForKey:
- _testingScrollStep
- scrollBy:forIterations:
- runScrollTest:withDelta:forIterations:
- topExtensionViewColor
- setTopExtensionViewColor:
- mf_needsToAdjustContentOffset
- initWithFrame:
- setUserInteractionEnabled:
- dealloc
- initWithCoder:
- _populateArchivedSubviews:
- encodeWithCoder:
- setDelegate:
- hitTest:withEvent:
- setFrame:
- setShowsVerticalScrollIndicator:
- layoutSubviews
- removeFromSuperview
- setBounds:
- isDragging
- isDecelerating
- description
- delegate
- gestureRecognizer:shouldReceiveTouch:
- touchesCancelled:withEvent:
- isProgrammaticScrollEnabled
- setProgrammaticScrollEnabled:
- isScrollEnabled
- _scrollToTopFromTouchAtScreenLocation:resultHandler:
- touchesBegan:withEvent:
- touchesMoved:withEvent:
- touchesEnded:withEvent:
- _didChangeFromIdiom:onScreen:traverseHierarchy:
- isTracking
- cancelTouchTracking
- cancelMouseTracking
- _contentWidthVariable
- _contentHeightVariable
- nsli_contentWidthVariable
- nsli_contentHeightVariable
- _didAddDependentConstraint:
- _didRemoveDependentConstraint:
- _resizeWithOldSuperviewSize:
- _supportsContentDimensionVariables
- _willMoveToWindow:
- _didMoveFromWindow:toWindow:
- _setSubviewWantsAutolayout
- _webCustomViewWillBeRemovedFromSuperview
- setContentOffset:
- _createGestureRecognizersForCurrentTouchLevel
- _adjustScrollerIndicators:alwaysShowingThem:
- setDirectionalLockEnabled:
- _updateContentFitDisableScrolling
- _getDelegateZoomView
- isZooming
- _centerContentIfNecessary
- isDirectionalLockEnabled
- setScrollTestParameters:
- _staticScrollBar
- _layoutStaticScrollBar
- _staticScrollBar:didScrollInDirection:
- _updateUsesStaticScrollBar
- _enableOnlyGestureRecognizersForCurrentTouchLevel
- _setUsesStaticScrollBar:
- handlePan:
- handlePinch:
- _updatePanGestureConfiguration
- _handleSwipe:
- _updateScrollGestureRecognizersEnabled
- _startBeingDraggedByChild:
- _stopBeingDraggedByChild:
- isPagingEnabled
- _transfersScrollToContainer
- contentOffset
- _adjustedHorizontalOffsetPinnedToScrollableBounds:
- _adjustedVerticalOffsetPinnedToScrollableBounds:
- _startDraggingParent:
- _stopDraggingParent:
- contentSize
- zoomScale
- setContentSize:
- _attemptToDragParent:forNewBounds:oldBounds:
- _automaticContentConstraints
- _constraintsFromContentSize
- _setAutomaticContentConstraints:
- contentInset
- _registerAsScrollToTopViewIfPossible
- setContentOffset:animated:
- _scrollViewTouchDelayGesture
- setScrollEnabled:
- _updateZoomGestureRecognizersEnabled
- _updatePagingGesture
- _abuttedEdgesForContentOffset:
- _currentlyAbuttedContentEdges
- delayed:
- _updatePinchGesture
- _systemGestureStateChanged:
- _handleLowFidelitySwipe:
- minimumZoomScale
- willRotateToInterfaceOrientation:
- willAnimateRotationToInterfaceOrientation:
- _registerForRotation:ofWindow:
- _hideScrollIndicators
- _setShowsBackgroundShadow:
- alwaysBounceHorizontal
- alwaysBounceVertical
- _rubberBandContentOffsetForOffset:outsideX:outsideY:
- keyboardDismissMode
- _scrollViewWillEndDraggingWithDeceleration:
- _startTimer:
- _popTrackingRunLoopMode
- _staysCenteredDuringPinch
- _zoomScaleFromPresentationLayer:
- _setZoomAnchorPoint:
- setZoomScale:withAnchorPoint:validatingScrollOffset:allowRubberbanding:animated:duration:notifyDelegate:
- _updatePinchGestureForState:
- setZoomScale:withAnchorPoint:validatingScrollOffset:allowRubberbanding:animated:duration:notifyDelegate:force:
- _prepareToPageWithHorizontalVelocity:verticalVelocity:
- _endPanNormal:
- _updatePanGesture
- _accumulateViewConstraintsIntoArray:
- _nsis_contentSize
- _constraintAffectsContentSize:
- _layoutVariablesWithAmbiguousValue
- _zoomToCenter:scale:duration:force:
- setZoomScale:animated:
- _zoomRubberBandScaleForScale:
- _zoomAnimationDurationForScale:
- _zoomAnimationDidStop
- _adjustContentSizeForView:atScale:
- _zoomAnchorPoint
- _markScrollViewAnimationForKey:ofView:
- _zoomScaleForRubberBandScale:
- _getPagingDecelerationOffset:forTimeInterval:
- _getBouncingDecelerationOffset:forTimeInterval:lastUpdateOffset:min:max:decelerationFactor:decelerationLnFactor:velocity:
- _getStandardDecelerationOffset:forTimeInterval:min:max:decelerationFactor:decelerationLnFactor:velocity:
- _smoothScrollWithUpdateTime:
- _smoothScrollTimer:
- _smoothScrollDisplayLink:
- _runLoopModePopped:
- _isAnimatingScroll
- _contentOffsetForLowFidelityScrollInDirection:duration:
- _lowFidelityScrollInDirection:
- _smoothScrollIntoBounds
- _panGestureRecognizer
- setContentInset:
- _isRectFullyVisible:
- _adjustsTargetsOnContentOffsetChanges
- _setAdjustsTargetsOnContentOffsetChanges:
- scrollRectToVisible:animated:
- setScrollingEnabled:
- setZoomEnabled:
- isZoomEnabled
- _isScrollingToTop
- setPagingEnabled:
- _abuttedPagingEdges
- setBounces:
- bounces
- setBouncesHorizontally:
- bouncesHorizontally
- setBouncesVertically:
- bouncesVertically
- setUpdateInsetBottomDuringKeyboardDismiss:
- updateInsetBottomDuringKeyboardDismiss
- setAlwaysBounceVertical:
- setAlwaysBounceHorizontal:
- _setTransfersScrollToContainer:
- _isVerticalBouncing
- _isHorizontalBouncing
- showsHorizontalScrollIndicator
- setShowsHorizontalScrollIndicator:
- showsVerticalScrollIndicator
- setScrollIndicatorInsets:
- scrollIndicatorInsets
- setIndicatorStyle:
- decelerationRate
- setDecelerationRate:
- indicatorStyle
- horizontalScrollDecelerationFactor
- setHorizontalScrollDecelerationFactor:
- verticalScrollDecelerationFactor
- setVerticalScrollDecelerationFactor:
- setAllowsMultipleFingers:
- allowsMultipleFingers
- setTracksImmediatelyWhileDecelerating:
- tracksImmediatelyWhileDecelerating
- _scrollHysteresis
- preservesCenterDuringRotation
- setPreservesCenterDuringRotation:
- flashScrollIndicators
- _showsBackgroundShadow
- setShowBackgroundShadow:
- _touchPositionForTouches:
- _rubberBandToOffset:
- _setStaysCenteredDuringPinch:
- gestureRecognizer:canPreventGestureRecognizer:
- _gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:
- _gestureRecognizer:shouldReceiveTouch:
- _gestureRecognizerFailed:
- bouncesZoom
- setBouncesZoom:
- canCancelContentTouches
- setCanCancelContentTouches:
- delaysContentTouches
- setDelaysContentTouches:
- touchesShouldBegin:withEvent:inContentView:
- touchesShouldCancelInContentView:
- scrollsToTop
- setScrollsToTop:
- _setIgnoreLinkedOnChecks:
- _ignoreLinkedOnChecks
- _pagingFriction
- _setPagingFriction:
- _defaultPagingFriction
- setMinimumZoomScale:
- setMaximumZoomScale:
- maximumZoomScale
- _zoomToCenter:scale:duration:
- _ownsAnimationForKey:ofView:
- setZoomScale:
- zoomToRect:animated:
- isZoomBouncing
- _isAnimatingZoom
- _pageDecelerationTarget
- _staticScrollBarScrollAnimationEnded
- panGestureRecognizer
- pinchGestureRecognizer
- scrollTestParameters
- setKeyboardDismissMode:
- _useContentDimensionVariablesForConstraintLowering
- _setUseContentDimensionVariablesForConstraintLowering:
@end
