@interface UITabBar : UIView
{
	id _customizeView;
	id _backgroundView;
	id _adaptiveBackdrop;
	id _shadowView;
	id _delegate;
	id _items;
	id _selectedItem;
	id _customizationItems;
	long long _barOrientation;
	struct _tabBarFlags;
	id _buttonItems;
	pointer _hiddenItems;
	id _appearanceStorage;
	BOOL _dividerImagesChangeWithSelection;
	BOOL _dividerImagesAreInvalid;
	BOOL _hidesShadow;
	double _nextSelectionSlideDuration;
	id _dividerImageViews;
	long long _itemPositioning;
	double _itemDimension;
	double _itemSpacing;
	long long _barMetrics;
	long long _imageStyle;
}

+ _autolayoutSpacingAtEdge:inContainer:
+ _autolayoutSpacingAtEdge:nextToNeighbor:
+ _hasCustomAutolayoutNeighborSpacing
+ isElementAccessibilityExposedToInterfaceBuilder
+ _isHidden:
+ _setVisualAltitude:
+ _setVisualAltitudeBias:
+ hitTest:forEvent:
+ _updateBackgroundImage
+ backdropView:willChangeToGraphicsQuality:
+ backdropView:didChangeToGraphicsQuality:
+ _buttonDownDelayed:
+ _buttonDown:
+ _buttonUp:
+ _buttonCancel:
+ _configureTabBarReplacingItem:withNewItem:dragging:swapping:
+ _positionTabBarButtons:ignoringItem:
+ _updateDividerImagesIfNecessary
+ _customizeWithAvailableItems:
+ _dismissCustomizeSheet:
+ _adjustButtonSelection:
+ _finishCustomizeAnimation:
+ _customizeDoneButtonAction:
+ _updateAppearanceCustomizationIfNecessaryForItem:
+ _configureItems:
+ _alertWillShow:duration:
+ _alertDidHide
+ setAutoresizingMask:
+ drawRect:
+ hitTest:withEvent:
+ setFrame:
+ setBounds:
+ touchesCancelled:withEvent:
+ touchesBegan:withEvent:
+ touchesMoved:withEvent:
+ touchesEnded:withEvent:
+ tintColorDidChange
+ _didMoveFromWindow:toWindow:
+ setBadgeValue:forButton:
+ setBadgeGlyph:forButton:
+ setBadgeAnimated:forButton:
+ buttonItems
+ setButtonItems:
+ _tabBarFinishedAnimating
+ dismissCustomizeSheet:
+ _backgroundView
+ _setBackgroundView:
+ _setBackgroundImage:
+ _setSelectionIndicatorImage:
+ _setLabelFont:
+ _setLabelTextColor:selectedTextColor:
+ _setLabelShadowColor:
+ _setLabelShadowOffset:
+ initWithFrame:
+ dealloc
+ initWithCoder:
+ _populateArchivedSubviews:
+ encodeWithCoder:
+ setDelegate:
+ _intrinsicSizeWithinSize:
+ layoutSubviews
+ _contentHuggingDefault_isUsuallyFixedHeight
+ sizeThatFits:
+ delegate
+ isTranslucent
+ isLocked
+ setTranslatesAutoresizingMaskIntoConstraints:
+ _canDrawContent
+ setTintColor:
+ _willChangeToIdiom:onScreen:
+ _subclassImplementsDrawRect
+ backgroundImage
+ shadowImage
+ setShadowImage:
+ _appearanceStorage
+ _effectiveBarTintColor
+ _shadowView
+ setItems:animated:
+ items
+ setItems:
+ setLocked:
+ addConstraint:
+ removeConstraint:
+ setBarStyle:
+ _wantsAdaptiveBackdrop
+ barStyle
+ setTranslucent:
+ setBarTintColor:
+ _hidesShadow
+ _setHidesShadow:
+ barTintColor
+ _isTranslucent
+ _setBarOrientation:
+ setSelectedItem:
+ beginCustomizingItems:
+ isCustomizing
+ setBackgroundImage:
+ _finishSetItems:finished:context:
+ _sendAction:withEvent:
+ _cleanupAdaptiveBackdrop
+ _setDividerImage:forLeftButtonState:rightButtonState:
+ _dividerImageForLeftButtonState:rightButtonState:
+ selectionIndicatorImage
+ setSelectionIndicatorImage:
+ selectedImageTintColor
+ setSelectedImageTintColor:
+ _barMetrics
+ _setBackgroundNeedsUpdate:
+ setItemWidth:
+ itemWidth
+ setItemSpacing:
+ itemSpacing
+ _setBarMetrics:
+ _setImageStyle:
+ _doCommonTabBarInit
+ _topmostDividerImageView
+ _invalidateDividerImages
+ _animateSelectionChangeFromView:toView:duration:
+ _showItemsAnimated:
+ _imageStyle
+ _hideItemsAnimated:
+ _effectiveBarOrientation
+ _backgroundNeedsUpdate
+ _updateTintedImages:selected:
+ _effectiveBarTintColorDidChange
+ _tabBarTabStyle
+ _setTabBarTabStyle:
+ _setTabButtonWidth:
+ _tabButtonWidth
+ _setInterTabButtonSpacing:
+ _interTabButtonSpacing
+ selectedItem
+ _barOrientation
+ endCustomizingAnimated:
+ _nextSelectionSlideDuration
+ _setNextSelectionSlideDuration:
+ _dividerImagesChangeWithSelection
+ _setDividerImagesChangeWithSelection:
+ _dividerImagesAreInvalid
+ _setDividerImagesAreInvalid:
+ _dividerImageViews
+ _setDividerImageViews:
+ itemPositioning
+ setItemPositioning:
- _autolayoutSpacingAtEdge:inContainer:
- _autolayoutSpacingAtEdge:nextToNeighbor:
- _hasCustomAutolayoutNeighborSpacing
- isElementAccessibilityExposedToInterfaceBuilder
- _isHidden:
- _setVisualAltitude:
- _setVisualAltitudeBias:
- hitTest:forEvent:
- _updateBackgroundImage
- backdropView:willChangeToGraphicsQuality:
- backdropView:didChangeToGraphicsQuality:
- _buttonDownDelayed:
- _buttonDown:
- _buttonUp:
- _buttonCancel:
- _configureTabBarReplacingItem:withNewItem:dragging:swapping:
- _positionTabBarButtons:ignoringItem:
- _updateDividerImagesIfNecessary
- _customizeWithAvailableItems:
- _dismissCustomizeSheet:
- _adjustButtonSelection:
- _finishCustomizeAnimation:
- _customizeDoneButtonAction:
- _updateAppearanceCustomizationIfNecessaryForItem:
- _configureItems:
- _alertWillShow:duration:
- _alertDidHide
- setAutoresizingMask:
- drawRect:
- hitTest:withEvent:
- setFrame:
- setBounds:
- touchesCancelled:withEvent:
- touchesBegan:withEvent:
- touchesMoved:withEvent:
- touchesEnded:withEvent:
- tintColorDidChange
- _didMoveFromWindow:toWindow:
- setBadgeValue:forButton:
- setBadgeGlyph:forButton:
- setBadgeAnimated:forButton:
- buttonItems
- setButtonItems:
- _tabBarFinishedAnimating
- dismissCustomizeSheet:
- _backgroundView
- _setBackgroundView:
- _setBackgroundImage:
- _setSelectionIndicatorImage:
- _setLabelFont:
- _setLabelTextColor:selectedTextColor:
- _setLabelShadowColor:
- _setLabelShadowOffset:
- initWithFrame:
- dealloc
- initWithCoder:
- _populateArchivedSubviews:
- encodeWithCoder:
- setDelegate:
- _intrinsicSizeWithinSize:
- layoutSubviews
- _contentHuggingDefault_isUsuallyFixedHeight
- sizeThatFits:
- delegate
- isTranslucent
- isLocked
- setTranslatesAutoresizingMaskIntoConstraints:
- _canDrawContent
- setTintColor:
- _willChangeToIdiom:onScreen:
- _subclassImplementsDrawRect
- backgroundImage
- shadowImage
- setShadowImage:
- _appearanceStorage
- _effectiveBarTintColor
- _shadowView
- setItems:animated:
- items
- setItems:
- setLocked:
- addConstraint:
- removeConstraint:
- setBarStyle:
- _wantsAdaptiveBackdrop
- barStyle
- setTranslucent:
- setBarTintColor:
- _hidesShadow
- _setHidesShadow:
- barTintColor
- _isTranslucent
- _setBarOrientation:
- setSelectedItem:
- beginCustomizingItems:
- isCustomizing
- setBackgroundImage:
- _finishSetItems:finished:context:
- _sendAction:withEvent:
- _cleanupAdaptiveBackdrop
- _setDividerImage:forLeftButtonState:rightButtonState:
- _dividerImageForLeftButtonState:rightButtonState:
- selectionIndicatorImage
- setSelectionIndicatorImage:
- selectedImageTintColor
- setSelectedImageTintColor:
- _barMetrics
- _setBackgroundNeedsUpdate:
- setItemWidth:
- itemWidth
- setItemSpacing:
- itemSpacing
- _setBarMetrics:
- _setImageStyle:
- _doCommonTabBarInit
- _topmostDividerImageView
- _invalidateDividerImages
- _animateSelectionChangeFromView:toView:duration:
- _showItemsAnimated:
- _imageStyle
- _hideItemsAnimated:
- _effectiveBarOrientation
- _backgroundNeedsUpdate
- _updateTintedImages:selected:
- _effectiveBarTintColorDidChange
- _tabBarTabStyle
- _setTabBarTabStyle:
- _setTabButtonWidth:
- _tabButtonWidth
- _setInterTabButtonSpacing:
- _interTabButtonSpacing
- selectedItem
- _barOrientation
- endCustomizingAnimated:
- _nextSelectionSlideDuration
- _setNextSelectionSlideDuration:
- _dividerImagesChangeWithSelection
- _setDividerImagesChangeWithSelection:
- _dividerImagesAreInvalid
- _setDividerImagesAreInvalid:
- _dividerImageViews
- _setDividerImageViews:
- itemPositioning
- setItemPositioning:
@end
