@interface UITableView : UIScrollView
{
	id _dataSource;
	id _rowData;
	double _rowHeight;
	double _sectionHeaderHeight;
	double _sectionFooterHeight;
	double _estimatedRowHeight;
	double _estimatedSectionHeaderHeight;
	double _estimatedSectionFooterHeight;
	struct _visibleBounds;
	struct _visibleRows;
	id _visibleCells;
	id _firstResponderIndexPath;
	id _firstResponderView;
	int _firstResponderViewType;
	id _reusableTableCells;
	id _nibMap;
	id _headerFooterNibMap;
	id _nibExternalObjectsTables;
	id _topSeparatorCell;
	id _topSeparator;
	id _extraSeparators;
	pointer _visibleHeaderViews;
	pointer _visibleFooterViews;
	id _reusableHeaderFooterViews;
	id _highlightedIndexPaths;
	id _selectedIndexPaths;
	long long _swipeToDeleteSection;
	long long _swipeToDeleteRow;
	id _pendingSelectionIndexPath;
	id _pendingDeselectionIndexPaths;
	id _newContentView;
	id _deleteAnimationSupport;
	id _reorderingSupport;
	id _backgroundView;
	id _clearBlendingView;
	id _wrapperView;
	id _index;
	id _tableHeaderBackgroundView;
	id _tableHeaderView;
	id _tableFooterView;
	id _countLabel;
	long long _tableReloadingSuspendedCount;
	long long _sectionIndexMinimumDisplayRowCount;
	long long _updateAnimationCount;
	id _insertItems;
	id _deleteItems;
	id _reloadItems;
	id _moveItems;
	id _separatorColor;
	id _separatorTopShadowColor;
	id _separatorBottomShadowColor;
	id _checkmarkColor;
	id _sectionBorderColor;
	id _indexColor;
	id _indexBackgroundColor;
	id _indexTrackingBackgroundColor;
	id _defaultSectionIndexTitles;
	id _swipeGestureRecognizer;
	id _swipeToDeleteGobblerGestureRecognizer;
	id _gobblerGestureRecognizer;
	id _swipeToDeleteCell;
	long long _updateCount;
	id _displayingCellContentStringIndexPath;
	id _longPressGestureRecognizer;
	id _longPressAutoscrollTimer;
	int _longPressAutoscrollDirection;
	struct _sectionContentInset;
	double _sectionBorderWidth;
	id _currentTouch;
	id _refreshControl;
	id _cellClassDict;
	id _headerFooterClassDict;
	double _topPadding;
	double _bottomPadding;
	struct _separatorInset;
	id _updateCompletionHandler;
	id _multiSelectCheckmarkImage;
	id _multiSelectNotSelectedImage;
	id _deferredEditingHandler;
	id _hiddenSeparatorIndexPaths;
	struct _tableFlags;
}

@end
