@interface UITextInputController : NSObject
{
	id _inputDelegate;
	id _selectedTextRange;
	id _tokenizer;
	id _layoutManager;
	id _observedScrollViews;
	id _definitionSession;
	id _learnSession;
	id _textInputTraits;
	struct _markedTextRange;
	struct _markedTextSelection;
	struct _tiFlags;
	id _extraItemsBeforeTextStyleOptions;
	id _firstTextView;
	id _undoManager;
	id _undoOperationForCoalescing;
	id _textChecker;
	id _dictationPlaceholder;
	BOOL _allowsEditingTextAttributes;
	BOOL _continuousSpellCheckingEnabled;
	id _emptyStringAttributes;
	id _typingAttributes;
	id _delegate;
	struct _previousSelectedRange;
}

+ dealloc
+ setDelegate:
+ respondsToSelector:
+ delegate
+ undoManager
+ methodSignatureForSelector:
+ increaseSize:
+ decreaseSize:
+ _isDisplayingShortcutViewController
+ isEditable
+ _parentScrollView
+ isEditing
+ layoutManager
+ initWithLayoutManager:
+ _textStorageDidProcessEditing:
+ interactionAssistant
+ selectionView
+ selectedRange
+ setTypingAttributes:
+ _invalidateEmptyStringAttributes
+ didEndEditing
+ typingAttributes
+ beginningOfDocument
+ endOfDocument
+ textRangeFromPosition:toPosition:
+ textInRange:
+ inputDelegate
+ setSelectedRange:
+ addTextAlternativesDisplayStyleToRange:
+ _filteredAttributedTextInRange:
+ caretRectForPosition:
+ drawsAsAtom
+ atomStyle
+ hasText
+ clearText
+ _layoutManager
+ insertText:
+ deleteBackward
+ replaceRange:withText:
+ replaceRangeWithTextWithoutClosingTyping:replacementText:
+ selectedTextRange
+ setSelectedTextRange:
+ markedTextRange
+ markedTextStyle
+ setMarkedTextStyle:
+ setMarkedText:selectedRange:
+ unmarkText
+ positionFromPosition:offset:
+ positionFromPosition:inDirection:offset:
+ comparePosition:toPosition:
+ offsetFromPosition:toPosition:
+ positionWithinRange:farthestInDirection:
+ characterRangeByExtendingPosition:inDirection:
+ setInputDelegate:
+ tokenizer
+ baseWritingDirectionForPosition:inDirection:
+ setBaseWritingDirection:forRange:
+ firstRectForRange:
+ selectionRectsForRange:
+ closestPositionToPoint:
+ closestPositionToPoint:withinRange:
+ characterRangeAtPoint:
+ insertDictationResult:withCorrectionIdentifier:
+ insertDictationResultPlaceholder
+ frameForDictationResultPlaceholder:
+ removeDictationResultPlaceholder:willInsertResult:
+ rangeWithTextAlternatives:atPosition:
+ metadataDictionariesForDictationResults
+ beginSelectionChange
+ endSelectionChange
+ _selectionGeometryChanged
+ _textStorage
+ markedRange
+ _hasDictationPlaceholder
+ textStylingAtPosition:inDirection:
+ selectionAffinity
+ selectAll
+ setLayoutManager:
+ setAllowsEditingTextAttributes:
+ allowsEditingTextAttributes
+ selectAll:
+ makeTextWritingDirectionRightToLeft:
+ makeTextWritingDirectionLeftToRight:
+ replace:
+ cut:
+ copy:
+ paste:
+ _define:
+ _addShortcut:
+ toggleBoldface:
+ toggleItalics:
+ toggleUnderline:
+ _showTextStyleOptions:
+ forwardInvocation:
+ updateSelection
+ select:
+ _promptForReplace:
+ scrollRangeToVisible:
+ _isDisplayingReferenceLibraryViewController
+ setContinuousSpellCheckingEnabled:
+ _insertAttributedTextWithoutClosingTyping:
+ _setGestureRecognizers
+ _resetShowingTextStyle:
+ _firstTextView
+ _caretRect
+ _selectedRange
+ _ensureSelectionVisible
+ _addToTypingAttributes:value:
+ _canHandleResponderAction:
+ _shouldHandleResponderAction:
+ _rangeForBackwardsDelete
+ _insertDictationResult:withCorrectionIdentifier:replacingRange:resultLength:
+ _registerUndoOperationForReplacementWithActionName:replacementText:
+ _mightHaveSelection
+ _removeDefinitionController
+ _clearSelectionUI
+ stopCoalescing
+ _commonInitWithLayoutManager:
+ _textContainerDidChangeView:
+ setPreviousSelectedRange:
+ _updateFirstTextView
+ _cancelDictationIfNecessaryForChangeInRange:
+ _setupTextContainerView:
+ _teardownTextContainerView:
+ _setEmptyStringAttributes:
+ _forceUnmarkTextDueToEditing
+ _ensureSelectionValid
+ _setSelectedTextRange:
+ _sendDelegateChangeNotificationsForText:selection:
+ _coordinateSelectionChange:
+ _invalidateTypingAttributes
+ _setSelectedRange:
+ _sendDelegateWillChangeNotificationsForText:selection:
+ _newAttributedStringForInsertionOfText:inRange:
+ nsRangeForTextRange:
+ registerUndoOperationForType:actionName:affectedRange:replacementText:
+ _insertText:fromKeyboard:
+ checkSpellingForSelectionChangeIfNecessary
+ removeAlternativesForCurrentWord
+ _insertAttributedText:fromKeyboard:
+ removeSpellingMarkersForCurrentWord
+ textChecker
+ removeSpellingMarkersFromWordInRange:
+ continuousSpellCheckingEnabled
+ previousSelectedRange
+ checkSpellingForWordInRange:
+ _shouldConsiderTextViewForGeometry:
+ _validCaretPositionFromCharacterIndex:downstream:
+ _caretRectForOffset:
+ _rectsForRange:
+ _characterPositionForPoint:
+ _attributesForReplacementInRange:
+ _emptyStringAttributes
+ _fixupOriginalFontAttributeForAttributes:
+ _undoManagerWillUndo:
+ isCoalescing
+ _undoRedoInProgress
+ coalesceInTextView:affectedRange:replacementRange:
+ textRangeForNSRange:
+ _selectedText
+ removeTextStylingFromString:
+ _copySelectionToClipboard
+ _delegateShouldChangeTextInRange:replacementText:
+ _removeShortcutController
+ _toggleFontTrait:
+ _selectionDidScroll:
+ preheatTextChecker
+ undoWillChangeText
+ undoDidChangeText
+ _setUndoRedoInProgress:
+ changeWillBeUndone:
+ _selectedAttributedText
+ _isSecureTextEntry
- dealloc
- setDelegate:
- respondsToSelector:
- delegate
- undoManager
- methodSignatureForSelector:
- increaseSize:
- decreaseSize:
- _isDisplayingShortcutViewController
- isEditable
- _parentScrollView
- isEditing
- layoutManager
- initWithLayoutManager:
- _textStorageDidProcessEditing:
- interactionAssistant
- selectionView
- selectedRange
- setTypingAttributes:
- _invalidateEmptyStringAttributes
- didEndEditing
- typingAttributes
- beginningOfDocument
- endOfDocument
- textRangeFromPosition:toPosition:
- textInRange:
- inputDelegate
- setSelectedRange:
- addTextAlternativesDisplayStyleToRange:
- _filteredAttributedTextInRange:
- caretRectForPosition:
- drawsAsAtom
- atomStyle
- hasText
- clearText
- _layoutManager
- insertText:
- deleteBackward
- replaceRange:withText:
- replaceRangeWithTextWithoutClosingTyping:replacementText:
- selectedTextRange
- setSelectedTextRange:
- markedTextRange
- markedTextStyle
- setMarkedTextStyle:
- setMarkedText:selectedRange:
- unmarkText
- positionFromPosition:offset:
- positionFromPosition:inDirection:offset:
- comparePosition:toPosition:
- offsetFromPosition:toPosition:
- positionWithinRange:farthestInDirection:
- characterRangeByExtendingPosition:inDirection:
- setInputDelegate:
- tokenizer
- baseWritingDirectionForPosition:inDirection:
- setBaseWritingDirection:forRange:
- firstRectForRange:
- selectionRectsForRange:
- closestPositionToPoint:
- closestPositionToPoint:withinRange:
- characterRangeAtPoint:
- insertDictationResult:withCorrectionIdentifier:
- insertDictationResultPlaceholder
- frameForDictationResultPlaceholder:
- removeDictationResultPlaceholder:willInsertResult:
- rangeWithTextAlternatives:atPosition:
- metadataDictionariesForDictationResults
- beginSelectionChange
- endSelectionChange
- _selectionGeometryChanged
- _textStorage
- markedRange
- _hasDictationPlaceholder
- textStylingAtPosition:inDirection:
- selectionAffinity
- selectAll
- setLayoutManager:
- setAllowsEditingTextAttributes:
- allowsEditingTextAttributes
- selectAll:
- makeTextWritingDirectionRightToLeft:
- makeTextWritingDirectionLeftToRight:
- replace:
- cut:
- copy:
- paste:
- _define:
- _addShortcut:
- toggleBoldface:
- toggleItalics:
- toggleUnderline:
- _showTextStyleOptions:
- forwardInvocation:
- updateSelection
- select:
- _promptForReplace:
- scrollRangeToVisible:
- _isDisplayingReferenceLibraryViewController
- setContinuousSpellCheckingEnabled:
- _insertAttributedTextWithoutClosingTyping:
- _setGestureRecognizers
- _resetShowingTextStyle:
- _firstTextView
- _caretRect
- _selectedRange
- _ensureSelectionVisible
- _addToTypingAttributes:value:
- _canHandleResponderAction:
- _shouldHandleResponderAction:
- _rangeForBackwardsDelete
- _insertDictationResult:withCorrectionIdentifier:replacingRange:resultLength:
- _registerUndoOperationForReplacementWithActionName:replacementText:
- _mightHaveSelection
- _removeDefinitionController
- _clearSelectionUI
- stopCoalescing
- _commonInitWithLayoutManager:
- _textContainerDidChangeView:
- setPreviousSelectedRange:
- _updateFirstTextView
- _cancelDictationIfNecessaryForChangeInRange:
- _setupTextContainerView:
- _teardownTextContainerView:
- _setEmptyStringAttributes:
- _forceUnmarkTextDueToEditing
- _ensureSelectionValid
- _setSelectedTextRange:
- _sendDelegateChangeNotificationsForText:selection:
- _coordinateSelectionChange:
- _invalidateTypingAttributes
- _setSelectedRange:
- _sendDelegateWillChangeNotificationsForText:selection:
- _newAttributedStringForInsertionOfText:inRange:
- nsRangeForTextRange:
- registerUndoOperationForType:actionName:affectedRange:replacementText:
- _insertText:fromKeyboard:
- checkSpellingForSelectionChangeIfNecessary
- removeAlternativesForCurrentWord
- _insertAttributedText:fromKeyboard:
- removeSpellingMarkersForCurrentWord
- textChecker
- removeSpellingMarkersFromWordInRange:
- continuousSpellCheckingEnabled
- previousSelectedRange
- checkSpellingForWordInRange:
- _shouldConsiderTextViewForGeometry:
- _validCaretPositionFromCharacterIndex:downstream:
- _caretRectForOffset:
- _rectsForRange:
- _characterPositionForPoint:
- _attributesForReplacementInRange:
- _emptyStringAttributes
- _fixupOriginalFontAttributeForAttributes:
- _undoManagerWillUndo:
- isCoalescing
- _undoRedoInProgress
- coalesceInTextView:affectedRange:replacementRange:
- textRangeForNSRange:
- _selectedText
- removeTextStylingFromString:
- _copySelectionToClipboard
- _delegateShouldChangeTextInRange:replacementText:
- _removeShortcutController
- _toggleFontTrait:
- _selectionDidScroll:
- preheatTextChecker
- undoWillChangeText
- undoDidChangeText
- _setUndoRedoInProgress:
- changeWillBeUndone:
- _selectedAttributedText
- _isSecureTextEntry
@end
