@interface UITextInteractionAssistant : NSObject
{
	id _view;
	id _selectionView;
	id _recognizers;
	id _linkGestures;
	id _loupeGesture;
	id _singleTapGesture;
	id _doubleTapGesture;
	int _autoscrollRamp;
	double _autoscrollFactor;
	struct _autoscrollBasePoint;
	struct _autoscrollUntransformedExtentPoint;
	struct _loupeGestureEndPoint;
	id _textChecker;
	BOOL _inGesture;
	BOOL _autoscrolled;
	BOOL _isTryingToHighlightLink;
	BOOL _externalTextInput;
	id _gestureRecognizerViews;
}

+ dealloc
+ view
+ gestureRecognizerShouldBegin:
+ gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:
+ gestureRecognizer:shouldReceiveTouch:
+ fieldEditor
+ selectionView
+ autoscrollWillNotStart
+ cancelAutoscroll
+ setAutoscrolled:
+ autoscrollUntransformedExtentPoint
+ setSelectionWithPoint:
+ rangeWithTextAlternatives:atPosition:
+ startAutoscroll:
+ updateAutoscroll:
+ initWithView:
+ detach
+ attach
+ selectAll:
+ setGestureRecognizers
+ resignedFirstResponder
+ selectWord
+ scheduleReplacementsWithOptions:
+ selectionChanged
+ isInteractingWithLink
+ cancelInteractionWithLink
+ constrainedPoint:
+ disableClearsOnInsertion
+ clearSelection
+ confirmMarkedText:
+ layoutChangedByScrolling:
+ willStartScrollingOverflow
+ didEndScrollingOverflow
+ setInGesture:
+ swallowsDoubleTapWithScale:atPoint:
+ textDocument
+ loupeGesture
+ singleTapGesture
+ scrollView
+ _selectionView
+ updateSelectionWithPoint:
+ clearGestureRecognizers:
+ detach:
+ containerIsBrowserView
+ containerIsAtom
+ containerIsPlainStyleAtom
+ inGesture
+ setLoupeGesture:
+ setSingleTapGesture:
+ setDoubleTapGesture:
+ oneFingerDoubleTapRecognizer:
+ oneFingerDoubleTap:
+ addOneFingerDoubleTapRecognizer:toView:
+ oneFingerTapRecognizer:
+ oneFingerTap:
+ addOneFingerTapRecognizer:toView:
+ oneFingerTripleTap:
+ oneFingerTripleTapRecognizer
+ selectionTapRecognizer:
+ addSelectionTapRecognizer:toView:
+ twoFingerSingleTap:
+ twoFingerSingleTapRecognizer
+ tapAndAHalf:
+ tapAndAHalfRecognizer
+ loupeGesture:
+ loupeGestureRecognizer:
+ twoFingerRangedSelectGesture:
+ twoFingerRangedSelectRecognizer
+ smallDelayRecognizer:
+ longDelayRecognizer:
+ _asText
+ phraseBoundaryGestureRecognizer
+ canBeginDragCursor:
+ addGestureRecognizersToView:
+ linkInteractionView
+ viewCouldBecomeEditable:
+ useGesturesForEditableContent
+ oneFingerTapSelectsAll:
+ addPhraseBoundaryGestureRecognizerToView:
+ addOneFingerTripleTapRecognizerToView:
+ addOneFingerDoubleTapRecognizerToView:
+ addTwoFingerSingleTapRecognizerToView:
+ addTapAndAHalfRecognizerToView:
+ addTwoFingerRangedSelectRecognizerToView:
+ addOneFingerTapRecognizerToView:
+ addLoupeGestureRecognizer:toView:
+ addDragRecognizer
+ addHighlightLinkRecognizerToView:
+ addTapAndHoldOnLinkRecognizerToView:
+ oneFingerTapInUneditable:
+ doubleTapInUneditable:
+ scrollSelectionToVisible
+ setFirstResponderIfNecessary
+ turnOffDrawsAsAtomIfPlainStyleAtom
+ autoscrolled
+ notifyKeyboardSelectionChanged
+ updateWithMagnifierTerminalPoint:
+ shouldHandleFormGestureAtLocation:
+ shouldHandleOneFingerTapInUneditable:
+ shouldIgnoreLinkGestures
+ noCalloutBarAndTouchInSelection:
+ containerChangesSelectionOnOneFingerTap
+ rangeForTextReplacement:
+ distanceBetweenPoint:andRange:
+ selectWordWithoutShowingCommands
+ containerIsTextField
+ scheduleDictationReplacementsForAlternatives:range:
+ scheduleReplacementsForRange:withOptions:
+ tapOnLinkWithGesture:
+ containerAllowsSelectionTintOnly
+ selectionAnimationDidStop:finished:
+ _scrollable
+ setAutoscrollUntransformedExtentPoint:
+ isChineseInputEnabled
+ activateSelection
+ deactivateSelection
+ doubleTapGesture
+ setLoupeGestureEndPoint:
+ loupeGestureEndPoint
+ externalTextInput
+ containerAllowsSelection
+ addSelectionTapRecognizerToView:
+ removeGestureRecognizersFromView:
+ rangeSelectionStarted:
+ rangeSelectionEnded:
+ rangeSelectionMoved:withTouchPoint:
+ initWithResponder:
+ clearGestureRecognizers
+ textSelectionView
- dealloc
- view
- gestureRecognizerShouldBegin:
- gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:
- gestureRecognizer:shouldReceiveTouch:
- fieldEditor
- selectionView
- autoscrollWillNotStart
- cancelAutoscroll
- setAutoscrolled:
- autoscrollUntransformedExtentPoint
- setSelectionWithPoint:
- rangeWithTextAlternatives:atPosition:
- startAutoscroll:
- updateAutoscroll:
- initWithView:
- detach
- attach
- selectAll:
- setGestureRecognizers
- resignedFirstResponder
- selectWord
- scheduleReplacementsWithOptions:
- selectionChanged
- isInteractingWithLink
- cancelInteractionWithLink
- constrainedPoint:
- disableClearsOnInsertion
- clearSelection
- confirmMarkedText:
- layoutChangedByScrolling:
- willStartScrollingOverflow
- didEndScrollingOverflow
- setInGesture:
- swallowsDoubleTapWithScale:atPoint:
- textDocument
- loupeGesture
- singleTapGesture
- scrollView
- _selectionView
- updateSelectionWithPoint:
- clearGestureRecognizers:
- detach:
- containerIsBrowserView
- containerIsAtom
- containerIsPlainStyleAtom
- inGesture
- setLoupeGesture:
- setSingleTapGesture:
- setDoubleTapGesture:
- oneFingerDoubleTapRecognizer:
- oneFingerDoubleTap:
- addOneFingerDoubleTapRecognizer:toView:
- oneFingerTapRecognizer:
- oneFingerTap:
- addOneFingerTapRecognizer:toView:
- oneFingerTripleTap:
- oneFingerTripleTapRecognizer
- selectionTapRecognizer:
- addSelectionTapRecognizer:toView:
- twoFingerSingleTap:
- twoFingerSingleTapRecognizer
- tapAndAHalf:
- tapAndAHalfRecognizer
- loupeGesture:
- loupeGestureRecognizer:
- twoFingerRangedSelectGesture:
- twoFingerRangedSelectRecognizer
- smallDelayRecognizer:
- longDelayRecognizer:
- _asText
- phraseBoundaryGestureRecognizer
- canBeginDragCursor:
- addGestureRecognizersToView:
- linkInteractionView
- viewCouldBecomeEditable:
- useGesturesForEditableContent
- oneFingerTapSelectsAll:
- addPhraseBoundaryGestureRecognizerToView:
- addOneFingerTripleTapRecognizerToView:
- addOneFingerDoubleTapRecognizerToView:
- addTwoFingerSingleTapRecognizerToView:
- addTapAndAHalfRecognizerToView:
- addTwoFingerRangedSelectRecognizerToView:
- addOneFingerTapRecognizerToView:
- addLoupeGestureRecognizer:toView:
- addDragRecognizer
- addHighlightLinkRecognizerToView:
- addTapAndHoldOnLinkRecognizerToView:
- oneFingerTapInUneditable:
- doubleTapInUneditable:
- scrollSelectionToVisible
- setFirstResponderIfNecessary
- turnOffDrawsAsAtomIfPlainStyleAtom
- autoscrolled
- notifyKeyboardSelectionChanged
- updateWithMagnifierTerminalPoint:
- shouldHandleFormGestureAtLocation:
- shouldHandleOneFingerTapInUneditable:
- shouldIgnoreLinkGestures
- noCalloutBarAndTouchInSelection:
- containerChangesSelectionOnOneFingerTap
- rangeForTextReplacement:
- distanceBetweenPoint:andRange:
- selectWordWithoutShowingCommands
- containerIsTextField
- scheduleDictationReplacementsForAlternatives:range:
- scheduleReplacementsForRange:withOptions:
- tapOnLinkWithGesture:
- containerAllowsSelectionTintOnly
- selectionAnimationDidStop:finished:
- _scrollable
- setAutoscrollUntransformedExtentPoint:
- isChineseInputEnabled
- activateSelection
- deactivateSelection
- doubleTapGesture
- setLoupeGestureEndPoint:
- loupeGestureEndPoint
- externalTextInput
- containerAllowsSelection
- addSelectionTapRecognizerToView:
- removeGestureRecognizersFromView:
- rangeSelectionStarted:
- rangeSelectionEnded:
- rangeSelectionMoved:withTouchPoint:
- initWithResponder:
- clearGestureRecognizers
- textSelectionView
@end
