@interface VPNConnectionStore : NSObject
{
	BOOL _currentConnectionHasBeenSet;
	id _currentConnection;
	id _activeVPNID;
	id _connectionDict;
	BOOL _ignoreVPNChangedNotification;
	BOOL _activeVPNIDLoaded;
	unsigned int _vpnServiceCountDirty;
	unsigned int _vpnServiceCount;
	id _vpnServices;
	id _managedServices;
}

+ proxyType:
+ proxyServer:
+ proxyPort:
+ proxyUsername:
+ proxyPassword:
+ proxyPacFile:
+ setOnDemandEnabled:onService:forVPNType:
+ setDisplayName:onService:
+ setAuthorizationName:ofService:type:
+ setRemoteAddress:ofService:vpnType:
+ setSharedSecret:onService:type:
+ setRSASecurID:onService:vpnType:
+ setEncryptionLevel:onService:vpnType:
+ setGroupName:onService:vpnType:
+ setPassword:onService:
+ setSendAllTraffice:onService:usingPreferences:
+ setCertificate:onService:vpnType:
+ setProxyType:onService:
+ setProxyServer:onService:
+ setProxyPort:onService:
+ setProxyPacFile:onService:
+ setProxyAuthenticate:onService:
+ setProxyUsername:onService:
+ setProxyPassword:onService:
+ connectionTypeFromVPNType:
+ serviceAuthorizationName:vpnType:
+ serviceRemoteAddress:vpnType:
+ serviceDisplayName:
+ serviceSharedSecret:vpnType:
+ serviceUsesRSASecurID:vpnType:
+ serviceEncryptionLevel:vpnType:
+ serviceGroupName:vpnType:
+ serviceRequiresPassword:
+ servicePassword:
+ certificate:vpnType:
+ serviceSendsAllTraffic:usingPreferences:
+ proxyAuthenticate:
+ isOnDemandCapable:
+ onDemandEnabled:forVPNType:
+ saveActiveVPNIDToPreferences:
+ copyActiveVPNIDFromPrefs
+ setPassword:forServiceName:accountName:
+ _passwordForGenericAccount:service:
+ _resetConnectionLoaded
+ vpnTypeFromConnectionType:
+ _setPlistInformation:intoVPNService:vpnType:
+ passwordForServiceName:accountName:
+ removePasswordForServiceName:accountName:
+ removeConnection:
+ currentConnection
+ dealloc
+ init
+ connectionWithServiceID:
+ isOnDemandCapableForServiceID:
+ getLastConnectionCauseForServiceID:
+ servicePasswordForServiceID:
+ _connectionsChanged
+ activeVPNID
+ currentConnection:
+ setOptions:toService:withPreferences:vpnType:serviceId:
+ sslNameForServiceID:
+ optionsForServiceID:
+ vpnServicesForCurrentSet
+ vpnTypeForServiceID:
+ isUserCreatedVPN:
+ _defaultDictForType:
+ createVPNWithOptions:
+ updateVPNWithServiceID:withOptions:
+ deleteVPNWithServiceID:
+ setActiveVPNID:
+ isActiveVPNID:
+ freeResources
+ reloadVPN
+ organizationForService:
+ getPayloadDictForServiceID:
+ vpnServiceCount
+ sslTypeForServiceID:
+ vpnTypeForService:
- proxyType:
- proxyServer:
- proxyPort:
- proxyUsername:
- proxyPassword:
- proxyPacFile:
- setOnDemandEnabled:onService:forVPNType:
- setDisplayName:onService:
- setAuthorizationName:ofService:type:
- setRemoteAddress:ofService:vpnType:
- setSharedSecret:onService:type:
- setRSASecurID:onService:vpnType:
- setEncryptionLevel:onService:vpnType:
- setGroupName:onService:vpnType:
- setPassword:onService:
- setSendAllTraffice:onService:usingPreferences:
- setCertificate:onService:vpnType:
- setProxyType:onService:
- setProxyServer:onService:
- setProxyPort:onService:
- setProxyPacFile:onService:
- setProxyAuthenticate:onService:
- setProxyUsername:onService:
- setProxyPassword:onService:
- connectionTypeFromVPNType:
- serviceAuthorizationName:vpnType:
- serviceRemoteAddress:vpnType:
- serviceDisplayName:
- serviceSharedSecret:vpnType:
- serviceUsesRSASecurID:vpnType:
- serviceEncryptionLevel:vpnType:
- serviceGroupName:vpnType:
- serviceRequiresPassword:
- servicePassword:
- certificate:vpnType:
- serviceSendsAllTraffic:usingPreferences:
- proxyAuthenticate:
- isOnDemandCapable:
- onDemandEnabled:forVPNType:
- saveActiveVPNIDToPreferences:
- copyActiveVPNIDFromPrefs
- setPassword:forServiceName:accountName:
- _passwordForGenericAccount:service:
- _resetConnectionLoaded
- vpnTypeFromConnectionType:
- _setPlistInformation:intoVPNService:vpnType:
- passwordForServiceName:accountName:
- removePasswordForServiceName:accountName:
- removeConnection:
- currentConnection
- dealloc
- init
- connectionWithServiceID:
- isOnDemandCapableForServiceID:
- getLastConnectionCauseForServiceID:
- servicePasswordForServiceID:
- _connectionsChanged
- activeVPNID
- currentConnection:
- setOptions:toService:withPreferences:vpnType:serviceId:
- sslNameForServiceID:
- optionsForServiceID:
- vpnServicesForCurrentSet
- vpnTypeForServiceID:
- isUserCreatedVPN:
- _defaultDictForType:
- createVPNWithOptions:
- updateVPNWithServiceID:withOptions:
- deleteVPNWithServiceID:
- setActiveVPNID:
- isActiveVPNID:
- freeResources
- reloadVPN
- organizationForService:
- getPayloadDictForServiceID:
- vpnServiceCount
- sslTypeForServiceID:
- vpnTypeForService:
@end
