@interface WAKView : WAKResponder
{
	struct viewContext;
	pointer viewRef;
	id subviewReferences;
	BOOL _isHidden;
	BOOL _drawsOwnDescendants;
}

+ _frame
+ _webView
+ _web_parentWebFrameView
+ _web_superviewOfClass:
+ _web_firstResponderIsSelfOrDescendantView
+ _web_convertRect:toView:
+ _web_addDescendantWebHTMLViewsToArray:
+ accessibilityIsIgnored
+ initWithFrame:
+ setAutoresizingMask:
+ dealloc
+ bounds
+ drawRect:
+ convertPoint:fromView:
+ window
+ setHidden:
+ init
+ setFrame:
+ addSubview:
+ removeFromSuperview
+ frame
+ description
+ subviews
+ nextResponder
+ scale
+ superview
+ handleEvent:
+ convertRect:toView:
+ isHiddenOrHasHiddenAncestor
+ layoutIfNeeded
+ convertRect:fromView:
+ convertPoint:toView:
+ autoresizingMask
+ setFrameOrigin:
+ convertSize:toView:
+ willRemoveSubview:
+ setNeedsDisplayInRect:
+ needsDisplay
+ displayIfNeeded
+ setScale:
+ visibleRect
+ layout
+ setFrameSize:
+ viewDidMoveToWindow
+ invalidateGState
+ setNeedsLayout:
+ setNeedsDisplay:
+ viewWillDraw
+ displayRect:
+ _viewRef
+ hitTest:
+ lastScrollableAncestor
+ displayRectIgnoringOpacity:inContext:
+ .cxx_construct
+ _appendDescriptionToString:atLevel:
+ display
+ needsPanelToBecomeKey
+ setBoundsSize:
+ scrollPoint:
+ _initWithViewRef:
+ setBoundsOrigin:
+ _selfHandleEvent:
+ _subviewReferences
+ _lockFocusViewInContext:
+ _drawRect:context:lockFocus:
+ _unlockFocusViewInContext:
+ isDescendantOf:
+ _handleResponderCall:
+ frameSizeChanged
+ displayRectIgnoringOpacity:
+ lockFocus
+ unlockFocus
+ mouse:inRect:
+ setNextKeyView:
+ previousValidKeyView
+ nextKeyView
+ nextValidKeyView
+ previousKeyView
+ releaseGState
+ inLiveResize
+ scrollRectToVisible:
+ _setDrawsOwnDescendants:
- _frame
- _webView
- _web_parentWebFrameView
- _web_superviewOfClass:
- _web_firstResponderIsSelfOrDescendantView
- _web_convertRect:toView:
- _web_addDescendantWebHTMLViewsToArray:
- accessibilityIsIgnored
- initWithFrame:
- setAutoresizingMask:
- dealloc
- bounds
- drawRect:
- convertPoint:fromView:
- window
- setHidden:
- init
- setFrame:
- addSubview:
- removeFromSuperview
- frame
- description
- subviews
- nextResponder
- scale
- superview
- handleEvent:
- convertRect:toView:
- isHiddenOrHasHiddenAncestor
- layoutIfNeeded
- convertRect:fromView:
- convertPoint:toView:
- autoresizingMask
- setFrameOrigin:
- convertSize:toView:
- willRemoveSubview:
- setNeedsDisplayInRect:
- needsDisplay
- displayIfNeeded
- setScale:
- visibleRect
- layout
- setFrameSize:
- viewDidMoveToWindow
- invalidateGState
- setNeedsLayout:
- setNeedsDisplay:
- viewWillDraw
- displayRect:
- _viewRef
- hitTest:
- lastScrollableAncestor
- displayRectIgnoringOpacity:inContext:
- .cxx_construct
- _appendDescriptionToString:atLevel:
- display
- needsPanelToBecomeKey
- setBoundsSize:
- scrollPoint:
- _initWithViewRef:
- setBoundsOrigin:
- _selfHandleEvent:
- _subviewReferences
- _lockFocusViewInContext:
- _drawRect:context:lockFocus:
- _unlockFocusViewInContext:
- isDescendantOf:
- _handleResponderCall:
- frameSizeChanged
- displayRectIgnoringOpacity:
- lockFocus
- unlockFocus
- mouse:inRect:
- setNextKeyView:
- previousValidKeyView
- nextKeyView
- nextValidKeyView
- previousKeyView
- releaseGState
- inLiveResize
- scrollRectToVisible:
- _setDrawsOwnDescendants:
@end
