@interface WebDefaultUIKitDelegate : NSObject
{

}

+ supportedPasteboardTypesForCurrentSelection
+ addInputString:withFlags:
+ addInputString:fromVariantKey:
+ deleteFromInput
+ hasRichlyEditableSelection
+ webViewDidDrawTiles:
+ webView:didReceiveViewportArguments:
+ webView:needsScrollNotifications:forFrame:
+ webView:didFinishLoadForFrame:
+ webViewDidStartOverflowScroll:
+ webViewDidEndOverflowScroll:
+ webView:runOpenPanelForFileButtonWithResultListener:allowMultipleFiles:acceptMIMETypes:
+ webViewDidRestoreFromPageCache:
+ webView:didFirstVisuallyNonEmptyLayoutInFrame:
+ webView:didFailLoadWithError:forFrame:
+ webView:didChangeLocationWithinPageForFrame:
+ webView:didCommitLoadForFrame:
+ webView:didReceiveDocTypeForFrame:
+ webView:saveStateToHistoryItem:forFrame:
+ webView:restoreStateFromHistoryItem:forFrame:force:
+ webView:shouldScrollToPoint:forFrame:
+ writeDataToPasteboard:
+ getPasteboardItemsCount
+ performsTwoStepPaste:
+ readDataFromPasteboard:withIndex:
+ getPasteboardChangeCount
+ isUnperturbedDictationResultMarker:
+ revealedSelectionByScrollingWebFrame:
+ _webthread_webView:attachRootLayer:
+ webViewDidCommitCompositingLayerChanges:
+ checkSpellingOfString:
+ webView:plugInViewWithArguments:fromPlugInPackage:
+ webView:willShowFullScreenForPlugInView:
+ webView:didHideFullScreenForPlugInView:
+ webView:willAddPlugInView:
+ webView:didObserveDeferredContentChange:forFrame:
+ webViewDidPreventDefaultForEvent:
+ webView:didStartProvisionalLoadForFrame:
+ webView:didFirstLayoutInFrame:
+ webView:willCloseFrame:
+ webView:elementDidFocusNode:
+ webView:elementDidBlurNode:
+ webView:addMessageToConsole:withSource:
+ webView:didCreateOrUpdateScrollingLayer:withContentsLayer:scrollSize:forNode:allowHorizontalScrollbar:allowVerticalScrollbar:
+ webView:willRemoveScrollingLayer:withContentsLayer:forNode:
+ webView:didFinishDocumentLoadForFrame:
+ contentsPointForWebView:
+ documentVisibleRectForWebView:
+ webView:didReceiveMessage:
+ webViewDidLayout:
- supportedPasteboardTypesForCurrentSelection
- addInputString:withFlags:
- addInputString:fromVariantKey:
- deleteFromInput
- hasRichlyEditableSelection
- webViewDidDrawTiles:
- webView:didReceiveViewportArguments:
- webView:needsScrollNotifications:forFrame:
- webView:didFinishLoadForFrame:
- webViewDidStartOverflowScroll:
- webViewDidEndOverflowScroll:
- webView:runOpenPanelForFileButtonWithResultListener:allowMultipleFiles:acceptMIMETypes:
- webViewDidRestoreFromPageCache:
- webView:didFirstVisuallyNonEmptyLayoutInFrame:
- webView:didFailLoadWithError:forFrame:
- webView:didChangeLocationWithinPageForFrame:
- webView:didCommitLoadForFrame:
- webView:didReceiveDocTypeForFrame:
- webView:saveStateToHistoryItem:forFrame:
- webView:restoreStateFromHistoryItem:forFrame:force:
- webView:shouldScrollToPoint:forFrame:
- writeDataToPasteboard:
- getPasteboardItemsCount
- performsTwoStepPaste:
- readDataFromPasteboard:withIndex:
- getPasteboardChangeCount
- isUnperturbedDictationResultMarker:
- revealedSelectionByScrollingWebFrame:
- _webthread_webView:attachRootLayer:
- webViewDidCommitCompositingLayerChanges:
- checkSpellingOfString:
- webView:plugInViewWithArguments:fromPlugInPackage:
- webView:willShowFullScreenForPlugInView:
- webView:didHideFullScreenForPlugInView:
- webView:willAddPlugInView:
- webView:didObserveDeferredContentChange:forFrame:
- webViewDidPreventDefaultForEvent:
- webView:didStartProvisionalLoadForFrame:
- webView:didFirstLayoutInFrame:
- webView:willCloseFrame:
- webView:elementDidFocusNode:
- webView:elementDidBlurNode:
- webView:addMessageToConsole:withSource:
- webView:didCreateOrUpdateScrollingLayer:withContentsLayer:scrollSize:forNode:allowHorizontalScrollbar:allowVerticalScrollbar:
- webView:willRemoveScrollingLayer:withContentsLayer:forNode:
- webView:didFinishDocumentLoadForFrame:
- contentsPointForWebView:
- documentVisibleRectForWebView:
- webView:didReceiveMessage:
- webViewDidLayout:
@end
