@interface WebFrameView : WAKView
{
	id _private;
}

+ frameSizeChanged
+ _contentView
+ _isScrollable
+ _largestScrollableChild
+ _hasScrollBars
+ _area
+ _largestChildWithScrollBars
+ _customScrollViewClass
+ _scrollView
+ _setDocumentView:
+ _setWebFrame:
+ _viewClassForMIMEType:
+ _makeDocumentViewForDataSource:
+ _install
+ _verticalPageScrollDistance
+ _frameSizeChanged
+ _webView
+ _web_frame
+ _verticalKeyboardScrollDistance
+ allowsScrolling
+ initWithFrame:
+ dealloc
+ drawRect:
+ becomeFirstResponder
+ isOpaque
+ visibleRect
+ setAllowsScrolling:
+ documentView
+ setFrameSize:
+ viewDidMoveToWindow
+ mouseDown:
+ mouseUp:
+ webFrame
+ acceptsFirstResponder
+ finalize
+ keyDown:
+ scrollView:shouldScrollToPoint:
+ setNextKeyView:
+ _scrollOverflowInDirection:granularity:
+ _isVerticalDocument
+ _isFlippedDocument
+ _scrollToBeginningOfDocument
+ scrollToBeginningOfDocument:
+ _scrollToEndOfDocument
+ scrollToEndOfDocument:
+ _pageVertically:
+ _scrollVerticallyBy:
+ _pageHorizontally:
+ _horizontalPageScrollDistance
+ _scrollHorizontallyBy:
+ _scrollLineVertically:
+ _scrollLineHorizontally:
+ _horizontalKeyboardScrollDistance
+ _pageInBlockProgressionDirection:
+ scrollPageUp:
+ scrollPageDown:
+ scrollLineUp:
+ scrollLineDown:
+ _forwardMouseEvent:
+ _goForward
+ _goBack
+ _firstResponderIsFormControl
+ _webcore_effectiveFirstResponder
+ documentViewShouldHandlePrint
+ printDocumentView
- frameSizeChanged
- _contentView
- _isScrollable
- _largestScrollableChild
- _hasScrollBars
- _area
- _largestChildWithScrollBars
- _customScrollViewClass
- _scrollView
- _setDocumentView:
- _setWebFrame:
- _viewClassForMIMEType:
- _makeDocumentViewForDataSource:
- _install
- _verticalPageScrollDistance
- _frameSizeChanged
- _webView
- _web_frame
- _verticalKeyboardScrollDistance
- allowsScrolling
- initWithFrame:
- dealloc
- drawRect:
- becomeFirstResponder
- isOpaque
- visibleRect
- setAllowsScrolling:
- documentView
- setFrameSize:
- viewDidMoveToWindow
- mouseDown:
- mouseUp:
- webFrame
- acceptsFirstResponder
- finalize
- keyDown:
- scrollView:shouldScrollToPoint:
- setNextKeyView:
- _scrollOverflowInDirection:granularity:
- _isVerticalDocument
- _isFlippedDocument
- _scrollToBeginningOfDocument
- scrollToBeginningOfDocument:
- _scrollToEndOfDocument
- scrollToEndOfDocument:
- _pageVertically:
- _scrollVerticallyBy:
- _pageHorizontally:
- _horizontalPageScrollDistance
- _scrollHorizontallyBy:
- _scrollLineVertically:
- _scrollLineHorizontally:
- _horizontalKeyboardScrollDistance
- _pageInBlockProgressionDirection:
- scrollPageUp:
- scrollPageDown:
- scrollLineUp:
- scrollLineDown:
- _forwardMouseEvent:
- _goForward
- _goBack
- _firstResponderIsFormControl
- _webcore_effectiveFirstResponder
- documentViewShouldHandlePrint
- printDocumentView
@end
