@interface WebFrame : NSObject
{
	id _private;
}

+ dd_newOperation
+ caretRectForPosition:
+ selectionRectsForRange:
+ hasSelection
+ startPosition
+ setSelectionGranularity:
+ collapseSelection
+ clearSelection
+ nextUnperturbedDictationResultBoundaryFromPosition:
+ selectionState
+ toggleBaseWritingDirection
+ selectionBaseWritingDirection
+ endPosition
+ webVisiblePositionForPoint:
+ setBaseWritingDirection:
+ moveSelectionToPoint:
+ selectionRects
+ setRangedSelectionBaseToCurrentSelection
+ clearRangedSelectionInitialExtent
+ setRangedSelectionWithExtentPoint:
+ setSelectionWithFirstPoint:secondPoint:
+ setRangedSelectionBaseToCurrentSelectionStart
+ setRangedSelectionInitialExtentToCurrentSelectionEnd
+ setRangedSelectionBaseToCurrentSelectionEnd
+ setRangedSelectionInitialExtentToCurrentSelectionStart
+ aggressivelyExpandSelectionToWordContainingCaretSelection
+ closestCaretRectInMarkedTextRangeForPoint:
+ setRangedSelectionExtentPoint:baseIsStart:allowFlipping:
+ wordAtPoint:
+ smartExtendRangedSelection:
+ moveSelectionToEnd
+ moveSelectionToStart
+ isSingleLine
+ coreFrame
+ visiblePositionForPoint:
+ selectionRectsForCoreRange:
+ setSelectionWithBasePoint:extentPoint:baseIsStart:allowFlipping:
+ closestWordBoundary:
+ setIsSingleLine:
+ extendSelection:
+ setSelectionWithBasePoint:extentPoint:baseIsStart:
+ ensureRangedSelectionContainsInitialStartPoint:initialEndPoint:
+ expandSelectionToSentence
+ renderedCharactersExceed:
+ imageForNode:allowDownsampling:drawContentBehindTransparentNodes:
+ previousUnperturbedDictationResultBoundaryFromPosition:
+ _selectNSRange:
+ setNeedsLayout
+ _handleKeyEvent:
+ needsLayout
+ setMarkedText:selectedRange:
+ characterRangeAtPoint:
+ selectionAffinity
+ selectedDOMRange
+ _setSelectionFromNone
+ preferredHeight
+ updateLayout
+ setSelectionChangeCallbacksDisabled:
+ setDictationPhrases:metadata:asChildOfElement:
+ rectForScrollToVisible
+ documentView
+ convertNSRangeToDOMRange:
+ caretRectAtNode:offset:affinity:
+ setText:asChildOfElement:
+ _selectedNSRange
+ setSelectedDOMRange:affinity:closeTyping:
+ setIsActive:
+ firstRectForDOMRange:
+ caretRect
+ _selectAll
+ confirmMarkedText:
+ characterInRelationToCaretSelection:
+ characterBeforeCaretSelection
+ characterAfterCaretSelection
+ wordOffsetInRange:
+ selectionAtDocumentStart
+ selectionAtWordStart
+ rangeByMovingCurrentSelection:
+ rangeByExtendingCurrentSelection:
+ hasEditableSelection
+ _setLoadsSynchronously:
+ resetTextAutosizingBeforeLayout
+ sendScrollEvent
+ _userScrolled
+ _bodyBackgroundColor
+ _isVisuallyNonEmpty
+ _loadType
+ hasRichlyEditableSelection
+ _replaceSelectionWithFragment:selectReplacement:smartReplace:matchStyle:
+ removeUnchangeableStyles
+ sendOrientationChangeEvent:
+ getDictationResultRanges:andMetadatas:
+ stringForRange:
+ dictationResultMetadataForRange:
+ forceLayoutAdjustingViewSize:
+ interpretationsForCurrentRoot
+ selectWithoutClosingTypingNSRange:
+ expandSelectionToWordContainingCaretSelection
+ fontForSelection:
+ _replaceSelectionWithWebArchive:selectReplacement:smartReplace:
+ expandSelectionToElementContainingCaretSelection
+ focusedNodeHasContent
+ prepareForPause
+ setTimeoutsPaused:
+ setPluginsPaused:
+ resumeFromPause
+ markedTextDOMRange
+ renderRectForPoint:isReplaced:fontSize:
+ _setProhibitsScrolling:
+ elementRangeContainingCaretSelection
+ revealSelectionAtExtent:
+ innerLineHeight:
+ approximateNodeAtViewportLocation:
+ deepestNodeAtViewportLocation:
+ scrollableNodeAtViewportLocation:
+ _setVisibleSize:
+ elementAtPoint:
+ convertDOMRangeToNSRange:
+ resetSelection
+ _isDescendantOfFrame:
+ recursiveSetUpdateAppearanceEnabled:
+ _rectsForRange:
+ _setTextAutosizingWidth:
+ _setShouldCreateRenderers:
+ _isFrameSet
+ _firstLayoutDone
+ _loadsSynchronously
+ _selectionRangeForFirstPoint:secondPoint:
+ _selectionRangeForPoint:
+ _pendingFrameUnloadEventCount
+ formElementsCharacterCount
+ selectNSRange:
+ selectedNSRange
+ _restoreViewState
+ _saveViewState
+ renderedSizeOfNode:constrainedToWidth:
+ createDefaultFieldEditorDocumentStructure
+ setCaretColor:
+ layoutCount
+ isTelephoneNumberParsingAllowed
+ isTelephoneNumberParsingEnabled
+ mediaDataLoadsAutomatically
+ setMediaDataLoadsAutomatically:
+ expandSelectionToStartOfWordContainingCaretSelection
+ wordRangeContainingCaretSelection
+ wordInRange:
+ spaceFollowsWordInRange:
+ wordsInCurrentParagraph
+ selectionAtSentenceStart
+ selectNSRange:onElement:
+ setMarkedText:forCandidates:
+ _replaceSelectionWithText:selectReplacement:smartReplace:matchStyle:
+ _replaceSelectionWithText:selectReplacement:smartReplace:
+ _replaceSelectionWithMarkupString:baseURLString:selectReplacement:smartReplace:
+ _cacheabilityDictionary
+ _allowsFollowingLink:
+ _stringByEvaluatingJavaScriptFromString:withGlobalObject:inScriptWorld:
+ _javaScriptContextForScriptWorld:
+ setAccessibleName:
+ _layerTreeAsText
+ accessibilityRoot
+ _clearOpener
+ _computePageRectsWithPrintScaleFactor:pageSize:
+ _documentFragmentForText:
+ _documentFragmentForWebArchive:
+ _documentFragmentForImageData:withRelativeURLPart:andMIMEType:
+ _dispatchDidReceiveTitle:
+ _unreachableURL
+ _isDisplayingStandaloneImage
+ stringByEvaluatingJavaScriptFromString:forceUserGesture:
+ _globalContextForScriptWorld:
+ jsWrapperForNode:inScriptWorld:
+ _convertToNSRange:
+ _convertToDOMRange:
+ _documentFragmentWithMarkupString:baseURLString:
+ _isIncludedInWebKitStatistics
+ _initWithWebFrameView:webView:
+ _hasSelection
+ _findFrameWithSelection
+ _clearSelection
+ _nodesFromList:
+ _stringWithDocumentTypeStringAndMarkupString:
+ _shouldFlattenCompositingLayers:
+ _stringByEvaluatingJavaScriptFromString:forceUserGesture:
+ _firstRectForDOMRange:
+ _canProvideDocumentSource
+ _attachScriptDebugger
+ _detachScriptDebugger
+ _clearCoreFrame
+ _updateBackgroundAndUpdatesWhileOffscreen
+ _setInternalLoadDelegate:
+ _internalLoadDelegate
+ _unmarkAllBadGrammar
+ _unmarkAllMisspellings
+ _clearSelectionInOtherFrames
+ _dataSource
+ _isCommitting
+ _setIsCommitting:
+ _markupStringFromRange:nodes:
+ _selectedString
+ _stringForRange:
+ _drawRect:contentsOnly:
+ _getVisibleRect:
+ _stringByEvaluatingJavaScriptFromString:
+ _caretRectAtPosition:affinity:
+ _scrollDOMRangeToVisible:
+ _scrollDOMRangeToVisible:withInset:
+ _needsLayout
+ _selectionGranularity
+ _convertNSRangeToDOMRange:
+ _convertDOMRangeToNSRange:
+ _markDOMRange
+ _smartDeleteRangeForProposedRange:
+ _documentFragmentWithNodesAsParagraphs:
+ _replaceSelectionWithNode:selectReplacement:smartReplace:matchStyle:
+ _insertParagraphSeparatorInQuotedContent
+ _visiblePositionForPoint:
+ _characterRangeAtPoint:
+ _typingStyle
+ _setTypingStyle:withUndoAction:
+ _canSaveAsWebArchive
+ _commitData:
+ renderTreeAsExternalRepresentationForPrinting:
+ numberOfPagesWithPageWidth:pageHeight:
+ printToCGContext:pageWidth:pageHeight:
+ containsOnlySelectableElements
+ isTexty
+ isMainFrame
+ dealloc
+ init
+ reload
+ dataSource
+ name
+ webView
+ frameView
+ DOMDocument
+ loadRequest:
+ loadHTMLString:baseURL:
+ loadData:MIMEType:textEncodingName:baseURL:
+ childFrames
+ stopLoading
+ finalize
+ _loadData:MIMEType:textEncodingName:baseURL:unreachableURL:
+ _loadHTMLString:baseURL:unreachableURL:
+ initWithName:webFrameView:webView:
+ frameElement
+ loadAlternateHTMLString:baseURL:forUnreachableURL:
+ reloadFromOrigin
+ findFrameNamed:
+ javaScriptContext
+ provisionalDataSource
+ globalContext
+ windowObject
+ loadArchive:
+ parentFrame
- dd_newOperation
- caretRectForPosition:
- selectionRectsForRange:
- hasSelection
- startPosition
- setSelectionGranularity:
- collapseSelection
- clearSelection
- nextUnperturbedDictationResultBoundaryFromPosition:
- selectionState
- toggleBaseWritingDirection
- selectionBaseWritingDirection
- endPosition
- webVisiblePositionForPoint:
- setBaseWritingDirection:
- moveSelectionToPoint:
- selectionRects
- setRangedSelectionBaseToCurrentSelection
- clearRangedSelectionInitialExtent
- setRangedSelectionWithExtentPoint:
- setSelectionWithFirstPoint:secondPoint:
- setRangedSelectionBaseToCurrentSelectionStart
- setRangedSelectionInitialExtentToCurrentSelectionEnd
- setRangedSelectionBaseToCurrentSelectionEnd
- setRangedSelectionInitialExtentToCurrentSelectionStart
- aggressivelyExpandSelectionToWordContainingCaretSelection
- closestCaretRectInMarkedTextRangeForPoint:
- setRangedSelectionExtentPoint:baseIsStart:allowFlipping:
- wordAtPoint:
- smartExtendRangedSelection:
- moveSelectionToEnd
- moveSelectionToStart
- isSingleLine
- coreFrame
- visiblePositionForPoint:
- selectionRectsForCoreRange:
- setSelectionWithBasePoint:extentPoint:baseIsStart:allowFlipping:
- closestWordBoundary:
- setIsSingleLine:
- extendSelection:
- setSelectionWithBasePoint:extentPoint:baseIsStart:
- ensureRangedSelectionContainsInitialStartPoint:initialEndPoint:
- expandSelectionToSentence
- renderedCharactersExceed:
- imageForNode:allowDownsampling:drawContentBehindTransparentNodes:
- previousUnperturbedDictationResultBoundaryFromPosition:
- _selectNSRange:
- setNeedsLayout
- _handleKeyEvent:
- needsLayout
- setMarkedText:selectedRange:
- characterRangeAtPoint:
- selectionAffinity
- selectedDOMRange
- _setSelectionFromNone
- preferredHeight
- updateLayout
- setSelectionChangeCallbacksDisabled:
- setDictationPhrases:metadata:asChildOfElement:
- rectForScrollToVisible
- documentView
- convertNSRangeToDOMRange:
- caretRectAtNode:offset:affinity:
- setText:asChildOfElement:
- _selectedNSRange
- setSelectedDOMRange:affinity:closeTyping:
- setIsActive:
- firstRectForDOMRange:
- caretRect
- _selectAll
- confirmMarkedText:
- characterInRelationToCaretSelection:
- characterBeforeCaretSelection
- characterAfterCaretSelection
- wordOffsetInRange:
- selectionAtDocumentStart
- selectionAtWordStart
- rangeByMovingCurrentSelection:
- rangeByExtendingCurrentSelection:
- hasEditableSelection
- _setLoadsSynchronously:
- resetTextAutosizingBeforeLayout
- sendScrollEvent
- _userScrolled
- _bodyBackgroundColor
- _isVisuallyNonEmpty
- _loadType
- hasRichlyEditableSelection
- _replaceSelectionWithFragment:selectReplacement:smartReplace:matchStyle:
- removeUnchangeableStyles
- sendOrientationChangeEvent:
- getDictationResultRanges:andMetadatas:
- stringForRange:
- dictationResultMetadataForRange:
- forceLayoutAdjustingViewSize:
- interpretationsForCurrentRoot
- selectWithoutClosingTypingNSRange:
- expandSelectionToWordContainingCaretSelection
- fontForSelection:
- _replaceSelectionWithWebArchive:selectReplacement:smartReplace:
- expandSelectionToElementContainingCaretSelection
- focusedNodeHasContent
- prepareForPause
- setTimeoutsPaused:
- setPluginsPaused:
- resumeFromPause
- markedTextDOMRange
- renderRectForPoint:isReplaced:fontSize:
- _setProhibitsScrolling:
- elementRangeContainingCaretSelection
- revealSelectionAtExtent:
- innerLineHeight:
- approximateNodeAtViewportLocation:
- deepestNodeAtViewportLocation:
- scrollableNodeAtViewportLocation:
- _setVisibleSize:
- elementAtPoint:
- convertDOMRangeToNSRange:
- resetSelection
- _isDescendantOfFrame:
- recursiveSetUpdateAppearanceEnabled:
- _rectsForRange:
- _setTextAutosizingWidth:
- _setShouldCreateRenderers:
- _isFrameSet
- _firstLayoutDone
- _loadsSynchronously
- _selectionRangeForFirstPoint:secondPoint:
- _selectionRangeForPoint:
- _pendingFrameUnloadEventCount
- formElementsCharacterCount
- selectNSRange:
- selectedNSRange
- _restoreViewState
- _saveViewState
- renderedSizeOfNode:constrainedToWidth:
- createDefaultFieldEditorDocumentStructure
- setCaretColor:
- layoutCount
- isTelephoneNumberParsingAllowed
- isTelephoneNumberParsingEnabled
- mediaDataLoadsAutomatically
- setMediaDataLoadsAutomatically:
- expandSelectionToStartOfWordContainingCaretSelection
- wordRangeContainingCaretSelection
- wordInRange:
- spaceFollowsWordInRange:
- wordsInCurrentParagraph
- selectionAtSentenceStart
- selectNSRange:onElement:
- setMarkedText:forCandidates:
- _replaceSelectionWithText:selectReplacement:smartReplace:matchStyle:
- _replaceSelectionWithText:selectReplacement:smartReplace:
- _replaceSelectionWithMarkupString:baseURLString:selectReplacement:smartReplace:
- _cacheabilityDictionary
- _allowsFollowingLink:
- _stringByEvaluatingJavaScriptFromString:withGlobalObject:inScriptWorld:
- _javaScriptContextForScriptWorld:
- setAccessibleName:
- _layerTreeAsText
- accessibilityRoot
- _clearOpener
- _computePageRectsWithPrintScaleFactor:pageSize:
- _documentFragmentForText:
- _documentFragmentForWebArchive:
- _documentFragmentForImageData:withRelativeURLPart:andMIMEType:
- _dispatchDidReceiveTitle:
- _unreachableURL
- _isDisplayingStandaloneImage
- stringByEvaluatingJavaScriptFromString:forceUserGesture:
- _globalContextForScriptWorld:
- jsWrapperForNode:inScriptWorld:
- _convertToNSRange:
- _convertToDOMRange:
- _documentFragmentWithMarkupString:baseURLString:
- _isIncludedInWebKitStatistics
- _initWithWebFrameView:webView:
- _hasSelection
- _findFrameWithSelection
- _clearSelection
- _nodesFromList:
- _stringWithDocumentTypeStringAndMarkupString:
- _shouldFlattenCompositingLayers:
- _stringByEvaluatingJavaScriptFromString:forceUserGesture:
- _firstRectForDOMRange:
- _canProvideDocumentSource
- _attachScriptDebugger
- _detachScriptDebugger
- _clearCoreFrame
- _updateBackgroundAndUpdatesWhileOffscreen
- _setInternalLoadDelegate:
- _internalLoadDelegate
- _unmarkAllBadGrammar
- _unmarkAllMisspellings
- _clearSelectionInOtherFrames
- _dataSource
- _isCommitting
- _setIsCommitting:
- _markupStringFromRange:nodes:
- _selectedString
- _stringForRange:
- _drawRect:contentsOnly:
- _getVisibleRect:
- _stringByEvaluatingJavaScriptFromString:
- _caretRectAtPosition:affinity:
- _scrollDOMRangeToVisible:
- _scrollDOMRangeToVisible:withInset:
- _needsLayout
- _selectionGranularity
- _convertNSRangeToDOMRange:
- _convertDOMRangeToNSRange:
- _markDOMRange
- _smartDeleteRangeForProposedRange:
- _documentFragmentWithNodesAsParagraphs:
- _replaceSelectionWithNode:selectReplacement:smartReplace:matchStyle:
- _insertParagraphSeparatorInQuotedContent
- _visiblePositionForPoint:
- _characterRangeAtPoint:
- _typingStyle
- _setTypingStyle:withUndoAction:
- _canSaveAsWebArchive
- _commitData:
- renderTreeAsExternalRepresentationForPrinting:
- numberOfPagesWithPageWidth:pageHeight:
- printToCGContext:pageWidth:pageHeight:
- containsOnlySelectableElements
- isTexty
- isMainFrame
- dealloc
- init
- reload
- dataSource
- name
- webView
- frameView
- DOMDocument
- loadRequest:
- loadHTMLString:baseURL:
- loadData:MIMEType:textEncodingName:baseURL:
- childFrames
- stopLoading
- finalize
- _loadData:MIMEType:textEncodingName:baseURL:unreachableURL:
- _loadHTMLString:baseURL:unreachableURL:
- initWithName:webFrameView:webView:
- frameElement
- loadAlternateHTMLString:baseURL:forUnreachableURL:
- reloadFromOrigin
- findFrameNamed:
- javaScriptContext
- provisionalDataSource
- globalContext
- windowObject
- loadArchive:
- parentFrame
@end
